### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by Phalanxia** [equinusocio/material-theme#1]
Please!

**Comment by equinusocio** [comment]
First i have to release the stable version of this :)

**Comment by larsenwork** [comment]
@equinusocio I'd like to help if you're interested

**Comment by equinusocio** [comment]
Hi @larsenwork, if you want to make the Atom porting tou can do it :) But remember that is a beta version and something can change in the next days. If you start the project i will follow and help you after this.

Remember the referece :)

**Comment by larsenwork** [comment]
Currently busy with other projects - there are some syntax themes for atom with material colors but no UI. 
Syntax: https://github.com/paradox41/material-color-scheme

One light/dark could be a good starting place for a UI theme

**Comment by danielbayerlein** [comment]
<3 Atom

**Comment by paradox41** [comment]
It is trivial to port Sublime -> Atom. They provide a CLI [for it](https://github.com/paradox41/material-color-scheme/blob/master/build.sh#L15)

**Comment by wldcordeiro** [comment]
@paradox41 It's trivial to port a color scheme, not a theme though.

**Comment by adiultra** [comment]
I need a material theme for atom too.

**Comment by THPubs** [comment]
1+ for Atom theme!

**Comment by Fequois** [comment]
I'm joining the choir; please, make an Atom port! This is too epic to miss out on.

**Comment by larsenwork** [comment]
...all these +1 posts - if you want it then help make it happen :suspect:

**Comment by equinusocio** [comment]
The atom support will come (maybe) after the fixes on the ST version. Don't forget that is a open-source theme :) you can edit or make your own.

**Comment by Fequois** [comment]
@larsenwork I would definitely help if 1) I knew how to do it, or 2) I had the time to learn.

Someday I will be able to, but most likely not before this has already been done. :)

**Comment by larsenwork** [comment]
@Fequois I'm just pointing out that "joining the choir" is moot when a dev has already said he wants to do it and I don't know @equinusocio skill set but he probably has to figure out 1) too and time is always limited. +1 on social media and star on github helps a dev - anything else is just annoying really. Issues are for helping/asking/contributing.

**Comment by Fequois** [comment]
@larsenwork That depends entirely on the author in question. From that perspective this entire issue is moot.

Some people appreciate encouragement, or knowing there's demand or merely support. Others don't. It's not like we're dissecting a bug here…

If it bothers anybody, feel free to remove my comment. Didn't mean to disrupt.

**Comment by OmgImAlexis** [comment]
I'm going to back @Fequois up, I know a LOT of devs that won't even look at a issue like this unless there's 20 or more "1+" comments. Either way, there's no point in arguing over this. Either the dev will add support for Atom.io or someone else will come along and do it and it'll get merged with a PR.

**Comment by nemonweb** [comment]
1+ for Atom theme! Thanks

**Comment by NelsonBrandao** [comment]
+1

**Comment by adiultra** [comment]
Well this theme is amazing still as itis not supported in atom i found a few others which are flat ENOUGH https://atom.io/themes/rain-ui https://github.com/cannikin/spacegray-dark-ui https://atom.io/themes/oceans16-atomui Hope others choose any one

**Comment by equinusocio** [comment]
Flat != Material Design. Meanwhile you can use those themes :)

**Comment by apertureless** [comment]
Theres this one, which is pretty close https://github.com/silvestreh/atom-material-ui

**Comment by equinusocio** [comment]
@apertureless yes this is similar.

**Comment by matthewhirsch** [comment]
anyone know of this? https://atom.io/themes/material-syntax

**Comment by equinusocio** [comment]
I'm working now on the Material Atom theme... this will require a bit of time.
