### ISSUE TITLE
Highlight current line

### ISSUE THREAD

**Issue by HendrikPetertje** [equinusocio/material-theme#10]
Sorry for complaining.. seriously you have an awesome theme and I'm feeling like a baws while using your material develop theme!

I have Highlight current line enabled in sublime settings (it highlights the current line so you can find your code back fast and if you are working with code from a spaghetticode programmer it makes the whole line more readable) . The small design problem here is that the contrast and tint between the background and the line-highlighter is just to big. can you if you have time and feel the same about it make a more subtle color-contrast on the highlighted line?

example here:
![screen shot 2015-06-03 at 19 50 01](https://cloud.githubusercontent.com/assets/3583395/7967406/29a95030-0a2a-11e5-8c1d-3b22cdcd41ec.png)

thanks!

**Comment by equinusocio** [comment]
Hi @HendrikPetertje. Thanks for the suggest. The syntax highlight aren't yet implemented, sorry. When the UI (the most complicated part) is finished i will set the syntax color. Be patient and remember that this is a beta version for testing :)
