### ISSUE TITLE
Strange window color when opening ST3 with multiple columns

### ISSUE THREAD

**Issue by brianyuen** [equinusocio/material-theme#1003]
### Summary
Strange background window color when opening ST3 with two or more column layout

### Expected behavior
Window color should match set theme

### Actual behavior
Active window (left side) is correct background color. Inactive background (right side) window color is gray. (see attached)

### Steps to reproduce

1. Open ST3
2. Set View to two or more columns or rows
3. Quit ST3
4. Reopen ST3

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [X] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * Not sure where this is found, but downloaded from PackageControl and configured 1.5 weeks ago.

![st3-material-weird-window-color](https://cloud.githubusercontent.com/assets/476859/19697821/d35aa35a-9aa1-11e6-8a7d-9cc50ff870e1.png)

### My user setting if it matters
```
{
	"auto_complete_commit_on_tab": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"drag_text": false,
	"findreplace_small": true,
	"folder_exclude_patterns":
	[
		"bin",
		".git",
		".sass-cache"
	],
	"font_size": 10,
	"highlight_line": false,
	"hot_exit": false,
	"ignored_packages":
	[
		"Vintage"
	],
	"material_theme_accent_sky": true,
	"material_theme_bold_tab": true,
	"material_theme_compact_sidebar": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": false,
	"open_files_in_new_window": false,
	"remember_open_files": false,
	"scroll_past_end": true,
	"show_definitions": false,
	"show_full_path": true,
	"sidebar_small": true,
	"spell_check": false,
	"tabs_small": true,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}
```

**Comment by equinusocio** [comment]
I can't reproduce this issue. I think is a problem related to your project workspace. Try to:

- Close all opened tabs in all ST windows
- In you current project go to `Project > New Workspace for project`
- Restart ST

**Comment by oivva** [comment]
This is ST bug. See [this](https://forum.sublimetext.com/t/dev-build-3112/19778/20).

**Comment by equinusocio** [comment]
Thanks @oivva
