### ISSUE TITLE
can't see the icon from mac

### ISSUE THREAD

**Issue by Timson020** [equinusocio/material-theme#1005]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. my computer is macOS,sublime text version is 3103,i sea the beautiful pic in package control , so i install material theme , but i can't see the icon . such as .gitignore .vue .balbelrc

---

When submitting a bug report, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ * ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3103
* Material Theme release:
  * v3.2.2

**Comment by equinusocio** [comment]
Full the issue templare, thanks.
