### ISSUE TITLE
Appbar for pale night theme not displaying

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#1007]
### Summary
Appbar for pale night theme not displaying but is displayed for other themes

### Expected behavior
App bar should be displayed for pale night theme

### Actual behavior
App bar not displayed for pale night theme only

### Steps to reproduce

1. Install latest version of sublime
2. restart and observe that the app bar is not there for pale night theme

### Environment
<img width="1223" alt="screen shot 2016-10-29 at 3 03 35 pm" src="https://cloud.githubusercontent.com/assets/6380855/19832418/ecae4a6a-9de8-11e6-8681-3dfab445caf1.png">

* Operating system and version:
  * [ X] Mac OS ...

* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4

**Comment by equinusocio** [comment]
The app bar packge as not be release yet.

**Comment by equinusocio** [comment]
@imoby Released, you have to wait Package Control.
