### ISSUE TITLE
[BUG] Rename background color and text color are the same

### ISSUE THREAD

**Issue by pattulus** [equinusocio/material-theme#1009]
### Summary/Expected behavior/Actual behavior

When trying to rename a file the text color seems to be the same as the background color, hence one can't see the path or file name.

### Steps to reproduce

![](https://cl.ly/hwMR/material-rename.gif)

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [X] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3125
* Material Theme release:
  * v4.0.0 _(and the one before)_

**Comment by equinusocio** [comment]
Check the readme. Thanks.
