### ISSUE TITLE
C++ Icons is not show

### ISSUE THREAD

**Issue by vCaesar** [equinusocio/material-theme#1011]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3...
* Material Theme release:
  * v3...

**Comment by SebastianS90** [comment]
Have you seen the changelog?

> From this release Material Theme use the `st-file-icons` package to display file type icons. Please install it and restart Sublime Text.

Hint: You can find that package listed as `zz File Icons` in package control

**Comment by vCaesar** [comment]
Ok,I well try it.
