### ISSUE TITLE
Distracting black border around scrollbars on Mac.

### ISSUE THREAD

**Issue by eli-crow** [equinusocio/material-theme#1012]
### Summary

Distracting black border around scrollbars on mac.
![image](https://cloud.githubusercontent.com/assets/19712894/19836777/64d73388-9e81-11e6-9982-ef30359be75e.png)
### Expected behavior

Scrollbars were probably intended to be a slightly darker rectangles without a significant difference in lightness from the layout.
### Actual behavior

Scrollbars currently have an obnoxious 2px black border around them in all color schemes.  This doesn't appear to be intentional. Not sure if anyone else is having this problem.
### Steps to reproduce
1. Happened after the most recent upgrade.
### Environment
- Operating system and version:
  - Mac OS 10.12
- Sublime Text:
  - Build 3126
- Material Theme release:
  - v4.0.0

**Comment by equinusocio** [comment]
This is what you should see. 
<img width="1060" alt="screen shot 2016-10-30 at 20 06 59" src="https://cloud.githubusercontent.com/assets/10454741/19839096/742ff94a-9edc-11e6-894f-dc0ab6d7e884.png">


Please try to build a nre project workspace `Project > New Workspace for project`

**Comment by equinusocio** [comment]
@eli-crow paste your preferences

**Comment by eli-crow** [comment]
The update fixed it. Sublime is the sexiest app on my machine again! Thanks so much for the quick response.
