### ISSUE TITLE
Show file icons for elements from opened items section

### ISSUE THREAD

**Issue by rosolko** [equinusocio/material-theme#1015]
### Summary

Can you please think about showing file icons for items from opened items section not only for items from folders section?

### Environment

* Operating system and version:
  * Windows
  * Mac OS
  * Linux
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.0

**Comment by equinusocio** [comment]
This is a sublime text behavior and It doesn't show icons for opened files. This theme provide only file icons Image.
