### ISSUE TITLE
Scrollbars barely visible

### ISSUE THREAD

**Issue by freMea** [equinusocio/material-theme#1016]
### Summary

Puck control color is too similar to the scrollbar background color. While it is not problematic with vertical scrollbar that can be replaced by the minimap, it makes horizontal scrollbar barely visible and it is just unusable to me as it is now.

### Expected behavior

I would expect that puck control take the **"material_theme_accent_$color"** user setting. It would make it usable and consistent with user choice.

### Actual behavior

Here is a [screenshot](https://snag.gy/rUfKM1.jpg) of the darker variant theme but the issue is the same for any variant.

### Steps to reproduce

1. Choose any material variant theme
2. Playing with settings **"overlay_scroll_bars": "disabled"** or **"overlay_scroll_bars": "enabled"** don't help to make it better.

### Environment

* Operating system and version:
  * Windows 10 x64 pro build 14393
* Sublime Text:
  * Build 3126
* Material Theme release:
  *  4.0.0

**Comment by dangsonbk** [comment]
+1, it's very annoying that I always have to scroll up and down so that the scrollbar appears, then I can drag it without accidentally click through and drag the text.
There should be an option to always show that scrollbar.

**Comment by freMea** [comment]
In fact, Material could be inspired by the way Boxy customizes the scrollbars.

**Comment by equinusocio** [comment]
@dangsonbk You have to just enable `"overlay_scroll_bars": "disabled"`.
@freMea Just use Boxy.

**Comment by freMea** [comment]
I do use Boxy now but it seemed to me fair played to report the issue I found in Material because it is an issue as you may admit by viewing my screenshot.

**Comment by equinusocio** [comment]
Yes, but why i should style scrollbars like Boxy? This is a different theme.
