### ISSUE TITLE
icon showing not correct after update

### ISSUE THREAD

**Issue by hubuki** [equinusocio/material-theme#1017]
### Summary

php and blade icon no show, showing icon "*" instead.

### Expected behavior

show php and blade icon

### Actual behavior

for php showing icon "*"  and blade file icon showing yellow lines align to left.

### Steps to reproduce

after auto update via sublime text

### Environment

* Operating system and version:
  
  * [v] Mac OS Sierra
  
* Sublime Text:
  * Build 3126

* Material Theme release:
  * v4.0

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/blob/develop/CHANGELOG.md

Install zz File Icons

**Comment by hubuki** [comment]
It works, thank you very much!!!
