### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by DRP96** [equinusocio/material-theme#1019]
I know this isn't a real issue about the package itself, but for some reason it's not listed in Package Controls default repository anymore. A week ago it worked just fine, but now (on my other computer) the Material Theme isn't shown when searching with Package Control.

Edit: Got it by adding the github repo to package control :) but still I'm wondering why it worked without any different repo before.

**Comment by equinusocio** [comment]
What ST version are you using?

**Comment by DRP96** [comment]
Sublime Text 3, latest Version. I completely deleted all package folders and downloaded sublime text again, now it works and your theme was shown :)
I don't know what the issue was, but now it works. Thanks for the great theme btw :)
