### ISSUE TITLE
"Find in Files..." view gets cut off

### ISSUE THREAD

**Issue by j-potts** [equinusocio/material-theme#102]
The `Find in Files...` view only fully displays the `Find` box, and the rest is cutoff.

![screen shot 2015-06-15 at 10 14 59 am](https://cloud.githubusercontent.com/assets/6355081/8161816/68b4cbbc-1347-11e5-87b1-eaf6cd89e4ad.png)

**Comment by erwanjegouzo** [comment]
:+1: same here!
![screen shot 2015-06-15 at 10 34 26 am](https://cloud.githubusercontent.com/assets/366909/8162271/2d9ea4e6-134a-11e5-977b-8554d8cc9627.png)

**Comment by Revod** [comment]
See the Issue #18

**Comment by equinusocio** [comment]
and #67
