### ISSUE TITLE
File icons issue using zz File Icons package

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/material-theme#1021]
### Summary

Today I install `Material Theme`, `Material Theme Appbar`, `Material Theme White Panels` and package for view new icons `zz File Icons`. New icons is really seen but after restart Sublime Text theme again using old icons

Gif

![ISSUE_GIF](http://i.imgur.com/mG3N9zV.gif)

### Environment

Windows 10 Latest Build 14395.351
Sublime Text 3 Build 3126
Material Theme release v4.0.1

**Comment by equinusocio** [comment]
Try to remove White Panels Package, ATM isnt'compatible with Material Theme 4.

**Comment by oivva** [comment]
@equinusocio `Material Theme White Panels` should contain `.st-file-icons` too. Also please see message on ST Forum I have some news :wink:

**Comment by equinusocio** [comment]
> @equinusocio Material Theme White Panels should contain .st-file-icons too

Yes yes i know! :) I'm working on another fix, i will release it in 1 hr.

> Also please see message on ST Forum I have some news 

I have seen :) I will reply in the evening.

**Comment by Zx-EvM** [comment]
@equinusocio I removed `Material Theme White Panels` and now new icons from `zz File Icons` package do not appear, only old icons. Or that should be?

**Comment by equinusocio** [comment]
It's correct. Material Theme now use zz File Icons to show file icons, but since MT provide his icons you will see the same file icons. You will see a zz File Icons package icon if Material Theme doesn't have the relative one.

**Comment by Zx-EvM** [comment]
@equinusocio I have a question. Here, in readme to zz File Icons, written:

I'm happy to announce that Boxy Theme and Material Theme will support this package in their next releases. **So you'll be able to choose what icons you want to use – provided by the theme or provided by the package.**

Are you sure you plan it?

**Comment by faergeek** [comment]
@Zx-EvM I'm not sure. But if your question is how to disable material theme icons and use icons from package itself, you need to set `force_override` option to `true` in zz File Icons settings

**Comment by oivva** [comment]
@Zx-EvM That's already implemented. `zz File Icons` uses theme icons by default if theme supports it. Material Theme supports it. So if you want to use icons provided by `zz File Icons` just use `"force_override": true`. See: https://youtu.be/bTIOL-5SxHY.
