### ISSUE TITLE
Showing same icons for different file types.

### ISSUE THREAD

**Issue by vajahath** [equinusocio/material-theme#1022]
### Summary
Showing same icons for different file types.

### Expected behavior
Previously it was OK.
There was an html5 icon for .html files
JS icon for .js files
and so on.

### Actual behavior
Now it looks like similar/same icons for a verity of file formats.
![alt tag](https://lh3.googleusercontent.com/SDvQsvvbJLvIabcIckJ7KmeZ-cp65mc_WPelY3PpAfvZJbk4ANQzNwbaNh4ChuuWA1Bfxjz0jXXLOvD7CFJlMu_cvEDwL53ll8hzpBMNQuv9oD0hJBZZ89l46fDisA3c8CGM-htWYv0rchXKHmXEkg-11lJkE7QU7S4fTFcOHLwwYmGUSQ8aGF7FH66zLMrdb8cxW-lJc1FSKk4sJMFVcq4ViQsdq0P-ckAU0ci2mtuVtJHQGf31R_3bgttn39Ls3GmBe30fgCUCxPPgpgtOeIJMifv4cXuqS6BObF9WqCcQ5G0zmn_XBbaCO_oaivP_g0ThlGf535BVYKeLZV8uiQis25uhQpje3sDhrcmMbaOaLMvJ6mC50n1uOZ5xpL8a42ocZwhOL_zWelfmu67mxWUcYzkz11wMjb4dLBXaXfX8qDnrkjFA726uAwolRtE_lq3uSCVKd2IgXMKs5hmjPyGWXllcqvpRCT_Jafyed_Ihod0RlG2HIdCpFjv0Jt4XgCz515axK4yzCvZ4-vDrZiVhA3VZh6A4yPOS3hkkKynio9cPSekRMep3VSAaAt2_takRDgPUFZe-VFJ0q1PCuvLiU6AgAgZ1_BtlhuX8O7AtwOnrlQ=w231-h678-no)

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [x] Linux ...

- Sublime Text:   3126
- Platform:   linux
- Arch:   x64
- Material Theme release:   4.0.1
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by thgfrzm** [comment]
install zz File Icons from Package Control

**Comment by equinusocio** [comment]
Check the readme and the changelog

**Comment by vajahath** [comment]
Thanks. It works.
