### ISSUE TITLE
Scrollbar not showing up in 4.0.0

### ISSUE THREAD

**Issue by ninebelowzero** [equinusocio/material-theme#1023]
### Summary

The sliders on side and bottom scrollbars are no longer visible since upgrading to 4.0.0 - see below:

![sublime_theme_screenshot](https://cloud.githubusercontent.com/assets/13942896/19887952/8e715cb6-a023-11e6-9144-5beffaf0fb92.png)

### Expected behavior

Should be clearly visible.

### Actual behavior

The bar is still there, but the slider is not visible.

### Steps to reproduce

Open a file large enough to need a scrollbar on the right hand side and/or below. This is an issue in all color schemes with Material Theme.

### Environment

* Operating system and version:
  * Mac OS El Capitan

* Sublime Text:
  * Build 3126

* Material Theme release:
  * v4.0.0

**Comment by diego1araujo** [comment]
this was fixed in latest release [v4.0.1](https://github.com/equinusocio/material-theme/releases/tag/v4.0.1)

**Comment by ninebelowzero** [comment]
Just upgraded. The slider is there, but barely visible - black on an almost black background.

**Comment by equinusocio** [comment]
Duplicated of #1016, check `material_theme_bright_scrollbars` and `material_theme_accent_scrollbars`

**Comment by ninebelowzero** [comment]
`"material_theme_bright_scrollbars": true` fixed this.

Thanks.
