### ISSUE TITLE
Change size of sublime linter circle marks

### ISSUE THREAD

**Issue by kiddick** [equinusocio/material-theme#1024]
![photo_2016-11-01_18-42-24](https://cloud.githubusercontent.com/assets/9250239/19895740/5bec57d0-a06b-11e6-8615-768666c394e5.jpg)

How it is possible to set it to how it was before? (with default theme)

**Comment by equinusocio** [comment]
<img width="534" alt="screen shot 2016-11-01 at 18 32 11" src="https://cloud.githubusercontent.com/assets/10454741/19899764/894ac2c0-a061-11e6-9e7f-74857d8214b1.png">
<img width="381" alt="screen shot 2016-11-01 at 18 32 18" src="https://cloud.githubusercontent.com/assets/10454741/19899763/8935bb3c-a061-11e6-8af3-cb657872fea5.png">

**Comment by kiddick** [comment]
Sweet!
Thank you
