### ISSUE TITLE
Bug: Definition-mouseover causes UI to freeze

### ISSUE THREAD

**Issue by Puffton** [equinusocio/material-theme#1025]
The definition-mouseover is triggered on OS X Sierra even when the window is in the background (for example when the active window is Google Chrome, somehow the mouseover event is triggered in Sublime causing the definitions-popup corresponding to my mouse position to show up on top of Chrome).

This usually causes the Sublime UI to freeze (can't close the window, but can open/close tabs, can't edit text). I have to shut it off in the dock and re-start it. Happens several times daily.

Material theme v4.0.1 running on Sublime 3 build 3126. Not sure if it's a bug in the theme, in Sublime or in some underlying OS libraries. The bug occurred in v4.0.0 as well, but I'm unsure if I had it before then. Recently started using the material theme.

**Comment by equinusocio** [comment]
Have you tried to build a new project worskace (`Project > New Workspace for project`)? I don't think that this issue could be releated to the theme.
