### ISSUE TITLE
Accent color not changing according to the User Setting

### ISSUE THREAD

**Issue by Microflash** [equinusocio/material-theme#1029]
### Summary

When I try to change the accent color to anything other than the default, no change is being reflected.

### Expected behavior

The accent color should change based on the settings.

### Actual behavior

The accent color remains set to the default no matter the settings.

### Environment

* Operating system and version: Windows 10
* Sublime Text: Build 3126
* Material Theme release: v4.0.1

**Comment by equinusocio** [comment]
This is the first time that i get this issue. I think you have a messy preferences or some other issue. Please try this:

- Make a new project worskace (`Project > New Workspace for project`)
- Close all opened tabs in all workspace, then restart ST
- Fresh install Sublime Text

**Comment by akatechis** [comment]
Might be related to an issue I've noticed when selecting multiple accent colors:

Steps to reproduce:
1. Open command palette.
2. Type "Material Theme: Configuration" and select it.
3. From the UI that appears, use mouse to click on "Accent"
4. From the next list that appears, select a few different accents.
5. Notice, that each time you select a new accent color, the previously selected accent colors are not deselected.

It almost looks like it goes through a list of colors that it knows about, and uses the first one it finds that is set to `true`.

**Comment by equinusocio** [comment]
Yes, at the moment you have to activate only one accent at time. I will fix this and make it a "radio button"
