### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Verhaeg** [equinusocio/material-theme#103]
Just installed this theme, fitted perfectly well with the Material Theme (Using Material Color Scheme package) but my only complaint is related to the font sizes.. 
they are HUGE!! if I'm using only on the notebook, 14-15" when I'm doing a find-replace it consumes a lot of the screen
I'm a big fan of small fonts, and I know that not everyone is like me, but would be nice to see an option to be able to set sublime font size to be used by the theme in panels and such

Great work any way ;)

**Comment by B-iggy** [comment]
Option 1: hold the CTRL key pressed and zoom with the mousewheel out to reduce font size
Option 2: in user preferences set ```"font_size": your-value```
Option 3: use your own favorite font with ```"font_face": "your-font"```

Hope it helps.

**Comment by Verhaeg** [comment]
Oh sorry.. I meant the font used by the theme.. not in Sublime..
for instance the font of the find-replace text inputs ;)

thanks

**Comment by equinusocio** [comment]
The font size of the inputs is fixed, i can make it an option. In the other UI i will make an option, but now it's 12px... very small on my 27" iMac

**Comment by Verhaeg** [comment]
Using a 23" screen, but see the difference between these texts:
"Find what" and "verifyAccountWithCertificate"
even the "Find" button has a different font size..

if this can become an option  in the future, great ;) I'll appreciate a lot!

![sublime](https://cloud.githubusercontent.com/assets/205890/8164137/977acc7e-135d-11e5-9693-23fdb65ede4c.png)

**Comment by cdymond** [comment]
I believe it's actually set at 14 right now. It is incredibly large on non-Retina monitors. I might be wrong, but I think it's a little more than just the font size that's at fault here.

![Surblerm](http://i.imgur.com/5yr048K.png)

**Comment by equinusocio** [comment]
The font-size of the inputs will inherit your code font-size. I cant make a settings for everythings
