### ISSUE TITLE
Add a High Contrast Light Theme

### ISSUE THREAD

**Issue by Microflash** [equinusocio/material-theme#1030]
The contrast between text color and the background color in the current Light theme is very low. This makes it very uncomfortable to work with for someone who is too photosensitive (like me). A flag to increase the contrast or a theme with a starker contrast would be great.

**Comment by yangmillstheory** [comment]
I modified my theme file [here](https://github.com/yangmillstheory/dotfiles/blob/master/sublime-themes/Material-Theme-Lighter.tmTheme). [Preferences](https://github.com/yangmillstheory/dotfiles/blob/master/Preferences.sublime-settings) are in the same repo.
