### ISSUE TITLE
UI Issue for Popup Definitions

### ISSUE THREAD

**Issue by agrawal-yatin** [equinusocio/material-theme#1032]
### Summary

Foreground & Background Popup UI for JavaScript Definition , CSS Classes blends together.

### Expected behavior

There must be some sort of separation - in the form of shadow or whatever you think is best

### Steps to reproduce

1. Hover over class name in any HTML file 
2. Hover over variable name / function in Js file

![31a6d1fd0dd548ba80078ccd084ae954](https://cloud.githubusercontent.com/assets/10454741/20144752/eb226f88-a69d-11e6-8565-8987c3ef0e60.png)

### Environment

* Operating system and version:
  * [x] Windows 10
* Sublime Text:
  * Build 3126
* Material Theme release:
  * Latest Build

**Comment by equinusocio** [comment]
Unfortunately this shadow is handled by the OS. Check this on macOS

<img width="570" alt="screen shot 2016-11-09 at 16 57 29" src="https://cloud.githubusercontent.com/assets/10454741/20144718/c230aaa4-a69d-11e6-8ecd-55f4a300ce3b.png">

**Comment by ilicmarko** [comment]
I can confirm that this problem is Windows based.
I tested on macOS Sierra.

**Comment by equinusocio** [comment]
As @ilicmarko pointed out, I can't directly handle the shadow by the theme.
