### ISSUE TITLE
Old color scheme

### ISSUE THREAD

**Issue by nickforddesign** [equinusocio/material-theme#1033]
Sorry if you have explained this elsewhere, but can I ask why you removed the old color schemes? The old default color scheme was my go-to scheme, and I'm very sad to see it go...

**Comment by abtink** [comment]
Thanks for the nicely designed color schemes. The old default scheme was my go-to scheme as well.

**Comment by equinusocio** [comment]
The old color schemes were not more supported and updated for a long time. This means that they were not fully compatible and that they had some bugs. I have given a few months to start using the new ones, I'm sorry for this inconvenience but now the official color schemes are only those of the theme.

**Comment by huyvohcmc** [comment]
I missed the old schemes too, I really like those red colors...
