### ISSUE TITLE
Fix issue with missing sidebar icons

### ISSUE THREAD

**Issue by jayqui** [equinusocio/material-theme#1034]
### Summary

After the latest update, the sidebar icons have disappeared for me.

### Expected behavior

show colorful icons in the side bar
 
### Actual behavior

all icons (except for .md files) are a bluish icon that looks like `</>`

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ X ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3.
* Material Theme release:
  * v4.0.1

**Comment by equinusocio** [comment]
Please check the changelog. You have to install zz File Icons package
