### ISSUE TITLE
Option/Setting to change/adjust gutter line number foreground color for contrast

### ISSUE THREAD

**Issue by ryexley** [equinusocio/material-theme#1037]
This is by far my favorite theme for ST...I love it. Thank you for all of the work you've put into it.

One issue I've noticed with it is that when I do a screenshare for remote pair programming, others always seem to have a hard time reading the line numbers in sublime, because the default foreground color of the line numbers is so close to the background. I would LOVE to see an option to either explicitly set the foreground color for line numbers in the gutter, or perhaps if it would be simpler, to just have an option to render the line numbers with greater contrast for readability.

Thanks so much for the fantastic theme!

**Comment by equinusocio** [comment]
You can override the gutter foreground by yourself.

**Comment by ryexley** [comment]
How?

**Comment by equinusocio** [comment]
#1018 just make a `.tmTheme` file instead.

**Comment by ryexley** [comment]
And what class/property/ies do I need to add to it to override that setting?

**Comment by equinusocio** [comment]
Check scheme files inside 'schemes/'. You can find out all the properties you can override. The gutter foreground is under the settings block.
