### ISSUE TITLE
New theme and color scheme with bunker bg color - attached

### ISSUE THREAD

**Issue by sldobri** [equinusocio/material-theme#1038]
New theme and color scheme with bunker bg color: 
hex: #0B1015
rgb: [11, 16, 21]

files:
Material-Theme-Bunker.sublime-theme
Material-Theme-Bunker.tmTheme

zipped:
[Archive.zip](https://github.com/equinusocio/material-theme/files/590235/Archive.zip)

**Comment by equinusocio** [comment]
Thanks @sldobri but at the moment i have no plan to add another theme.
