### ISSUE TITLE
Modified tabs

### ISSUE THREAD

**Issue by Verhaeg** [equinusocio/material-theme#104]
This is one feature I miss from a long time.. I used once a theme (Nexus Theme) and it had this little feature that helped a lot:
modified tabs (even saved ones) had different style... So I could walk through my tabs and see which ones had changes even after save..

Is this still do-able? not sure if Sublime dropped support for this or not.. but having an option to have different color under the tab if it was changed would be really nice

**Comment by equinusocio** [comment]
At the momenti the modified tabs show a little pencil icon instead a X. This is the only visual feedback for this,

**Comment by Verhaeg** [comment]
Yeah, noticed that, my idead was a little extra:
open file (highlight tab) -> edit (pencil icon) -> save (highlight tab different color)

this is not an urgent feature, but very handy when working with multiple tabs and specially with any repository ;)

example from Nexus theme: https://github.com/EleazarCrusader/nexus-theme
![nexus](https://cloud.githubusercontent.com/assets/205890/8164225/1190187a-135e-11e5-98b5-0bb1d617361a.png)

**Comment by equinusocio** [comment]
Personally i don't like this UI pattern. So much distracting colors and this is a bit "outiside" from the pattern of this theme. I can only work with the pencil icon, maybe changing the color.
