### ISSUE TITLE
Theme reset after package update.

### ISSUE THREAD

**Issue by parusel** [equinusocio/material-theme#1041]
### Summary

Everytime the package gets an update, the theme settings is overwritten by this default value:

`"theme": "Default.sublime-theme"`

Because of this, the sidebar is always in its default color.

### Expected behavior

Change the theme settings back to `"theme": "Material-Theme.sublime-theme"` after package update.

### Actual behavior

Settings are changed to this, after a package update:

`"theme": "Default.sublime-theme"`

### Steps to reproduce

1. Update package

### Environment

* Operating system and version:
  * [ ] Windows 10 Pro

* Sublime Text:
  * Build 3126

* Material Theme release:
  * v4.0.2

**Comment by equinusocio** [comment]
there are a lot of similar closed issue. Please search.

**Comment by parusel** [comment]
I did search but didn't find the right one.

Only another one like this, where it was also mentioned that similar issues have already been answered:

https://github.com/equinusocio/material-theme/issues/949

**Comment by equinusocio** [comment]
#832 #422 #283 #598 #945 and many more..

https://github.com/equinusocio/material-theme/issues/945#issuecomment-238794249
