### ISSUE TITLE
BUG 菜单栏图标现在不正确的问题

### ISSUE THREAD

**Issue by yexk** [equinusocio/material-theme#1043]
你好，可以修复下左边菜单栏的文件图标吗？？？

### Environment

* Operating system and version:
  * [v] Windows 10
* Sublime Text:
  * Build 3126
* Material Theme release:
  * Version 4.0.2.

**Comment by equinusocio** [comment]
English please

**Comment by yexk** [comment]
Hello, found a bug, the menu bar icon corresponding to the file does not...

**Comment by yexk** [comment]
![image](https://cloud.githubusercontent.com/assets/19749521/20353413/b481529c-ac55-11e6-81b1-f20a4358f638.png)

**Comment by equinusocio** [comment]
Just check the 4.0.0 changelog. You have to install zz File Icons package.
