### ISSUE TITLE
File format icons not showing

### ISSUE THREAD

**Issue by alannaidon** [equinusocio/material-theme#1046]
File format are not being show on sublime text sidebar.  Only starts to every type of file.
I'm using ST 3126 but didn't work with previous version neither.

![icons](https://cloud.githubusercontent.com/assets/13774879/20465318/3603901c-af41-11e6-90c9-9ed4dac3c6ba.JPG)

### Environment

* Operating system and version:
  * [X] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.2

**Comment by mrignacio1231** [comment]
i had the same problem but i can fix it. Just install zz File icon Package to display file icons. [zz File Icons](https://github.com/ihodev/sublime-file-icons)
