### ISSUE TITLE
.babelrc Doesn't have icon in the sidebar

### ISSUE THREAD

**Issue by Revod** [equinusocio/material-theme#1047]
### Summary

.babelrc doesn't have icons in the sidebar

### Expected behavior

.babelrc files must have icons

### Actual behavior

The sidebar doesn't show the icons
![screen shot 2016-11-21 at 11 36 01](https://cloud.githubusercontent.com/assets/10109689/20488820/d269028c-afde-11e6-8369-3f7facb8a70c.png)

### Steps to reproduce

- Open a Project
- Create a .gitignore file or .babelrc file

### Environment

* Operating system and version:
  * [x] MacOS Sierra 10.12.2 Beta 3
* Sublime Text:
  * Build 3 Dev Build 3125
* Material Theme release:
  * 4.0.2

**Comment by equinusocio** [comment]
You installed zz File Icons?

**Comment by Revod** [comment]
Nope, but now show the icon, so was fixed after close completely Sublime and open again

**Comment by equinusocio** [comment]
From 4.0.0 release you have to install `zz File Icons` package.
