### ISSUE TITLE
Complementing Icon

### ISSUE THREAD

**Issue by samholmes** [equinusocio/material-theme#1050]
It would be nice to have a matching icon to this theme similar to this one: https://dribbble.com/shots/1827862-Yosemite-Sublime-Text-Icon

The icon example above uses the same color scheme from the [Spacegray](https://packagecontrol.io/packages/Theme%20-%20Spacegray) theme.

What is the color palette for this theme? I wouldn't mind editing the sketch file myself.

**Comment by samholmes** [comment]
Looks like you had the color scheme on the README, my bad.

![sublime text material](https://cloud.githubusercontent.com/assets/517469/20636575/fe1c02ec-b323-11e6-81c5-9c03da5787b8.png)

Here's the design I came up with. I have the .sketch file too.

**Comment by equinusocio** [comment]
Thanks! There already is the Material Theme icon for Sublime Text 
https://github.com/equinusocio/material-theme#other-resources

You can make a PR and add this **unofficial** icon to the readme, under the official one.

**Comment by samholmes** [comment]
Could you release the source file for this icon? I'm considering contributing some adjustments to it if you're open to the idea.
