### ISSUE TITLE
Issue with Scroll Bar in Bottom after Latest Update of Material Theme - White Panels

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/material-theme#1051]
### Summary

Screen

![SCREEN](http://i.imgur.com/fivUcMO.png)

Gif

![GIF](http://i.imgur.com/UUHMyav.gif)

### Environment

Windows 10 Latest Build 14393.447
Sublime Text 3 Build 3126
Material Theme release v4.0.2
Material Theme - White Panels release v1.0.7
Material Theme - Appbar release v1.2.8

**Comment by equinusocio** [comment]
I think this issue is related to white panel package. Try to disable it.

**Comment by Zx-EvM** [comment]
@equinusocio Yes. When I disable `Material Theme - White Panels` this problem disappeared. But it will be very cool if you fix it in `Material Theme - White Panels`

Gif

![GIF_AFTER_DISABLE](http://i.imgur.com/l6C7V86.gif)

**Comment by equinusocio** [comment]
@Zx-EvM Can you move this issue to the White Panels repository?

**Comment by Zx-EvM** [comment]
@equinusocio Yes

**Comment by Zx-EvM** [comment]
@equinusocio How to transferring issue here? Or just copy and paste text with images and gifs?

**Comment by equinusocio** [comment]
Yes just copy all infos and close this issue

**Comment by Zx-EvM** [comment]
@equinusocio Done
