### ISSUE TITLE
Textbox doesn't show up

### ISSUE THREAD

**Issue by ivanbanov** [equinusocio/material-theme#1052]
### Summary

Textbox used in commands like `Rename File` only shows up using `"material_theme_compact_panel": true,`

### Expected behavior

Keep the default behaviors when using commands that need the textbox in bottom

### Actual behavior

Hide the textbox when using commands that need it

### Steps to reproduce

![material](https://cloud.githubusercontent.com/assets/2953018/20719972/b99a0d5c-b644-11e6-8167-42ad80aa3d1c.gif)

### Environment

* Operating system and version:
  * [ ] Windows
  * [x] Mac OS (Sierra 10.12.1)
  * [ ] Linux
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.2

**Comment by equinusocio** [comment]
Please check the readme
