### ISSUE TITLE
Rename text field clipped

### ISSUE THREAD

**Issue by kenemorales** [equinusocio/material-theme#1053]
Hi guys, I am not sure what's happening but why is it that when I rename a file, the text field is clipped? Please see screenshot

### Environment
Using macos sierra on Sublime Text 3126 with the most latest update of material theme

![screen shot 2016-11-30 at 8 36 37 am](https://cloud.githubusercontent.com/assets/20848105/20735065/8dd81274-b6d8-11e6-9368-cfac40973876.jpg)

**Comment by equinusocio** [comment]
Please check the readme
