### ISSUE TITLE
Change color of the scroll bar puck

### ISSUE THREAD

**Issue by TamerCC** [equinusocio/material-theme#1054]
1. I would love to edit the color of the scroll bar puck.
2.
I tried this but then I have to use one of the default themes: http://stackoverflow.com/questions/31093497/how-to-make-scroll-bar-indicator-more-clear-and-easy-to-see

Something like this or via advanced settings.

If it's already possible could you please tell me how?

---

### Environment
- Sublime Text:   3126
- Platform:   windows
- Arch:   x64
- Theme:   4.0.2
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.11.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by equinusocio** [comment]
Please check the readme

**Comment by TamerCC** [comment]
"material_theme_accent_scrollbars": true,
	"material_theme_bright_scrollbars": false,
sorry this solved it for me
