### ISSUE TITLE
New updates disable Material Theme

### ISSUE THREAD

**Issue by sebastianrb** [equinusocio/material-theme#1056]
Much of the time, after you push a new update, Material Theme becomes disabled and my Sublime shows the standard default theme. I have to go to settings and add the Material Theme  configurations back to re-enable the theme.

It's a pain in the butt. Are you aware of this issue?

**Comment by equinusocio** [comment]
There are a lot of similar (closed) issues here. This is related to Package Control, not Material Theme. After the update PC should reactivate the theme, but it fails.

If appen, just reactivate the theme from the command palette `cmd+shift+p` by searching for "Activate.."

**Comment by sebastianrb** [comment]
Ok, thanks! Good to know.
