### ISSUE TITLE
Tab label trimed after font increase

### ISSUE THREAD

**Issue by 7kemZmani** [equinusocio/material-theme#1057]
In Material-Theme-Darker.sublime-theme, I increased the font size from 11 to 12; and that trimmed the bottom half of the text in the tab label like this:

[![Screenshot from 2016-12-02 19-56-28.png](https://s14.postimg.org/j1dkozcxd/Screenshot_from_2016_12_02_19_56_28.png)](https://postimg.org/image/s95t5ojzh/)

Is it possible to modify the padding of the tab element?

**Comment by 7kemZmani** [comment]
Also, I tried changing the font size of the run/build output (above the status bar) in the file Widget - Material-Theme-Darker.sublime-settings by inserting "font_size": 12; yet nothing changes!

**Comment by equinusocio** [comment]
Wut? The `"font_size"` setting doesn't affects the UI font size, it increase only the code font-size. Material Theme doesn't provide any settings abut ui font-size. So i can't help you.

> Is it possible to modify the padding of the tab element?

You can enable `"material_theme_small_tab"` setting, or override by yourself the padding.

**Comment by 7kemZmani** [comment]
What I modified was not `"font_size"` propriety in Sublime Text settings; it was the `"font.size"` in the file I'm pointing at with the red arrow 'Material-Theme-Darker.sublime-theme'

**Comment by equinusocio** [comment]
I don't provide support for customizations. I'm sorry.
