### ISSUE TITLE
Breaks Vintageous command view

### ISSUE THREAD

**Issue by balanceiskey** [equinusocio/material-theme#106]
When you have the Vintageous plugin installed and begin typing vim commands, you typically get a little status line at the bottom to see what you're typing. But it looks like that might break here, looks like this: 

![2015-06-15 at 10 20 am](https://cloud.githubusercontent.com/assets/470240/8163616/c76a81fe-1349-11e5-952b-25d1a05d2ae5.png)

**Comment by equinusocio** [comment]
Pls see #67
