### ISSUE TITLE
Natural sorting in sidebar file tree

### ISSUE THREAD

**Issue by msankhala** [equinusocio/material-theme#1063]
I am not sure if this is a material theme issue or its a sublime issue. Sorry if i am reporting this at wrong place.

1. Currently sidebar file tree is sorted by alphanumerical sorting which is fine as far as files name start with alphabets, but if files name start with numbers then its doesn't sort it well. 

![sidebartree-sorting](https://cloud.githubusercontent.com/assets/234241/21198179/46376ac2-c264-11e6-9d65-d51e707abbf7.png)

### Environment

- Sublime Text:   3126
- Platform:   osx
- Arch:   x64
- Theme:   4.0.2

**Comment by equinusocio** [comment]
You should report this issue in the sublime text forum and issues repository
