### ISSUE TITLE
Unable to decode Packages/Material Theme/assets/accent-teal

### ISSUE THREAD

**Issue by 1-9** [equinusocio/material-theme#1064]
Thanks for this awesome theme.

After installing Material Theme from package control, I see the following errors when starting ST

Unable to decode Packages/Material Theme/assets/accent-teal/overflow_menu--hover.png
Unable to decode Packages/Material Theme/assets/accent-teal/tree_highlight.png
...
...

I removed the theme multiple times and tried manually installing it but the issue still persists.

I clearly see "accent-teal" folder missing from "assets/"

Is "accent-teal" deprecated, I see it's still being used in Darker.Theme

"layer1.texture": "Material Theme/assets/accent-teal/tree_highlight.png",

* Operating system and version:
  * [ ] Windows ...
  * [X ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3125
* Material Theme release:
  * 4.0.2

**Comment by equinusocio** [comment]
Thanks @1-9, can you try to install the develop branch now?

**Comment by 1-9** [comment]
@equinusocio develop branch fixed it, thanks.

**Comment by equinusocio** [comment]
#1065
