### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Sphinxs** [equinusocio/material-theme#1067]
It would be nice to put the language logo instead of generic icons.

Example :

![image](https://cloud.githubusercontent.com/assets/19755014/21324416/be5dfde8-c608-11e6-8558-7c54442c489d.png)

**Comment by equinusocio** [comment]
Check the readme. You have to install zz File Icons

**Comment by Sphinxs** [comment]
I saw in the read, but what I mean is to put the icons as the defaults already in the installation of your theme without having to install extra extensions.

**Comment by equinusocio** [comment]
Is not a good solution
