### ISSUE TITLE
Breaking Sidebar

### ISSUE THREAD

**Issue by wldcordeiro** [equinusocio/material-theme#107]
It appears the theme breaks the sidebar, the folders will no longer open or collapse properly.

These images show what I mean, there's a before and after interacting with the sidebar.
http://imgur.com/J4OpWEp,Xk8Wbyg

**Comment by equinusocio** [comment]
Give more details pls. Version of Sublime? Your preferences? and syntax color.

**Comment by wldcordeiro** [comment]
@equinusocio It turned out to be my .sublime-workspace files getting corrupted somehow. Thanks for the quick reply. :)
