### ISSUE TITLE
Goto Definition Command Pallette Cut Off

### ISSUE THREAD

**Issue by longitude** [equinusocio/material-theme#1070]
In a huge project with multiple folders when I use goto definition the full path is cut off making it harder to navigate, also there is an elipses in the text path, see screenshots below.

I also see this happening while navigating file (long path) using command palette (CMD + P).

Material theme
![screen shot 2016-12-22 at 9 35 37 am](https://cloud.githubusercontent.com/assets/5510191/21429071/2f1553f0-c82b-11e6-84a7-b4f4dcea6a95.png)

Same in default theme 
![screen shot 2016-12-22 at 9 37 22 am](https://cloud.githubusercontent.com/assets/5510191/21429009/eed49c2e-c82a-11e6-97ac-d5af62cdd02a.png)

While the padding looks great, it would be awesome if you provide some user customizable setting for no padding(especially for left and right padding).

Thanks.

* Operating system and version:
  * [ ] Windows ...
  * [x ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3
* Material Theme release:
  * latest

**Comment by equinusocio** [comment]
This is the same issue related to #67. Sublime Text doesn't consider paddings. And is a shit that i can't handle by the theme.

**Comment by equinusocio** [comment]
With the default style (only bg changed)
<img width="595" alt="screen shot 2016-12-22 at 16 29 10" src="https://cloud.githubusercontent.com/assets/10454741/21430536/dd32f996-c863-11e6-9b82-78a663ecbb1d.png">

**Comment by 1-9** [comment]
What if we remove all padding/spacing from command palette just to see if we can get the default behavior as in Monakai theme.

**Comment by equinusocio** [comment]
@1-9 You have to test it because i don't have this "infinites" paths :D

You extract the theme and edit `Material-Theme.sublime-theme` file. Search for:

```js
  {
    "class": "quick_panel",
    "parents": [{"class": "overlay_control"}],
    "row_padding": [32, 12],
    "layer0.tint": [<%= ui.background.primary.rgb %>, 0],
    "layer0.opacity": 1.0
  },
```

and edit `"row_padding": [32, 12],` to `"row_padding": [4, 12],`

**Comment by stoivo** [comment]
I did the above change and tested. Still cuts off some parts.
![screen shot 2017-01-23 at 20 37 34](https://cloud.githubusercontent.com/assets/3492040/22219673/fa73df3c-e1ab-11e6-8ab3-3db1f262fbb0.png)
![screen shot 2017-01-23 at 20 39 34](https://cloud.githubusercontent.com/assets/3492040/22219700/137aa420-e1ac-11e6-9017-3952cbe4a1f7.png)

**Comment by stoivo** [comment]
If you would like to see this you can install GitSavvy and open `git: blame current file`

**Comment by kiddick** [comment]
Finally fixed with https://www.sublimetext.com/blog/articles/sublime-text-3-point-0
