### ISSUE TITLE
Material-theme-appbar‘ height is too much,can we custom this height?

### ISSUE THREAD

**Issue by fallenk** [equinusocio/material-theme#1071]
hello, when I was using the sublimeText3 with material-theme, I found that  material-theme-appbar' height was  too much, but I couldn't solve it. 
<img width="471" alt="qq20161223-001459 2x" src="https://cloud.githubusercontent.com/assets/18565136/21432076/e74b22d2-c8a4-11e6-8831-85aea01f945d.png"> If you can answer, I will be greateful.

**Comment by equinusocio** [comment]
Just check the settings
