### ISSUE TITLE
Why my sidebar does not have a file icon?

### ISSUE THREAD

**Issue by clk528** [equinusocio/material-theme#1072]
hi:
This is a screenshot of my sidebar:
![image](https://cloud.githubusercontent.com/assets/6983344/21480314/b3372a3c-cb96-11e6-822d-1245e42d2f3e.png);
My version of sublime Text:

- Sublime Text:   3126
- Platform:   windows
- Arch:   x64
- Theme:   4.0.3
- Install via PC:   False
- Dependencies:
    * mdpopups:   1.13.1
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

I set the sublime:
![image](https://cloud.githubusercontent.com/assets/6983344/21480439/f0f9d0c6-cb97-11e6-8abe-6bd531823913.png)

**Comment by equinusocio** [comment]
Instal zz File Icons package
