### ISSUE TITLE
Windows UI font size issue

### ISSUE THREAD

**Issue by pavinthan** [equinusocio/material-theme#1074]
### Summary
I've updated PhpStrome Appearance and behavior > Appearance UI  default font size to 13, but after restart me PhpStrome it's will be override by default
...

* Operating system and version:
  * Windows 10
* PhpStrome, WebStrome ...:
  * v2016.3
* Material Theme release:
  * v0.2.2

**Comment by equinusocio** [comment]
This is not the official Material Theme repository for JetBrains software family. Please check
https://github.com/ChrisRM/material-theme-jetbrains
