### ISSUE TITLE
Can not customize SublimeLinter color anymore

### ISSUE THREAD

**Issue by sebastienbarre** [equinusocio/material-theme#1078]
### Summary
Love the theme, but it seems it is taking over the SublimeLinter color settings.
In `Material-Theme.tmTheme`, see [this line](https://github.com/equinusocio/material-theme/blob/master/schemes/Material-Theme.tmTheme#L901)
```
	<dict>
			<key>name</key>
			<string>SublimeLinter Error</string>
			<key>scope</key>
			<string>sublimelinter.mark.error</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#FF5370</string>
			</dict>
	<dict>
```
I can not, for the life of me, find a way to customize this color to something more friendly to color blind users like me.

SublimeLinter has its own user settings in `SublimeLinter.sublime-settings`, but no matter the changes, the Material Theme color seems to always take over `error_color`.
```
"user": {
        "debug": false,
        "delay": 2,
        "error_color": "0000a0",
```

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.4

**Comment by equinusocio** [comment]
This is not a issue. Material Theme offer a custom linter palette to match theme colors and improve UX.

**Comment by sebastienbarre** [comment]
You don't find it an issue that Material Theme is disabling the linter own `"error_color"` setting?

**Comment by ihodev** [comment]
@sebastienbarre I think this is `SublimeLinter` issue, because user settings should overwrite colors provided by the theme.
