### ISSUE TITLE
Use proper SASS icon in the sidebar

### ISSUE THREAD

**Issue by isaumya** [equinusocio/material-theme#1079]
### Summary

Currently even for .scss file the icon that shows up is CSS3. This is wrong and I hope you guys can add the proper SASS icon for the .scss file in near futur.

### Expected behavior

.SCSS file should dhow SASS icon

### Actual behavior

Now .scss file shows CSS3 Icon

![2017-01-21_18-42-11](https://cloud.githubusercontent.com/assets/2124755/22174637/5e8724a6-e009-11e6-823c-76e4051c6451.jpg)

### Steps to reproduce

1. Open a project in Sublime Text and put it in the sidebar
2. Open a SAS file and save it as .scss
3. Besides the file name you will see CSS3 icon

### Environment

* Operating system and version:
  * [X] Windows 10 1607
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * Latest relese

**Comment by equinusocio** [comment]
You have to install zz File Icons package. Please check the readme.
