### ISSUE TITLE
Find/Rename form is blocked by status bar

### ISSUE THREAD

**Issue by sambev** [equinusocio/material-theme#108]
My find/replace/rename or any other form that pops up at the bottom is partially covered by the status bar.

![screen shot 2015-06-15 at 12 20 18 pm](https://cloud.githubusercontent.com/assets/2127504/8167077/21df9aac-1359-11e5-8d82-852357b0a953.png)

SublimeText 3 Build 3083
Material v 1.0.2

**Comment by equinusocio** [comment]
Pls see #67
