### ISSUE TITLE
Bigger width on paneles 

### ISSUE THREAD

**Issue by stoivo** [equinusocio/material-theme#1080]
### Summary
GitSavvy have  pannel with sup select. I can not read the whole value.
I recorded a small video. http://recordit.co/zS3yhkysfP
...

### Expected behavior
Either bigger by default or a setting for wight
...

### Actual behavior
to small to read the name
...

### Steps to reproduce

1. Step is show in video http://recordit.co/zS3yhkysfP

### Environment

- Sublime Text:   3126
- Platform:   osx
- Arch:   x64
- Theme:   4.0.4
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.11.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

/cc @kiddick 
I am maintainer of GitSavvy and this is related to divmain/GitSavvy#592

**Comment by equinusocio** [comment]
Same as #1070.
