### ISSUE TITLE
Can't open advanced configurations

### ISSUE THREAD

**Issue by AceThaGemini** [equinusocio/material-theme#1082]
Whenever I try to open Advanced configuration this is what I get, a message saying
`The settings file "res://Packages/Material Theme/Preferences.sublime-settings" could not be opened`

Normal configuration just changed the editor space, but buttons and everything else... sigh!! :frowning_face: 

* Operating system and version:
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.4

**Comment by equinusocio** [comment]
I think you have a corrupted installation.

**Comment by AceThaGemini** [comment]
:man_facepalming: Strange.. The package from apt repository was a total corrupt. Removing it and installing `.deb` file did the trick.
Thanks @equinusocio now my Sublime is materialized!

**Comment by equinusocio** [comment]
You're welcome.
