### ISSUE TITLE
App crash after install theme : May be bug in MAC

### ISSUE THREAD

**Issue by AnilK2016** [equinusocio/material-theme#1083]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
I love using this theme always  with my sublime but i notice and issue.Some time sublime atomically  close when i tried to search items(command+f) this happens only in some time,,,

Sublime version : 3126
Mac version : 10.11

**Comment by equinusocio** [comment]
This is not theme related
