### ISSUE TITLE
Custom theme color

### ISSUE THREAD

**Issue by shawnlan** [equinusocio/material-theme#1084]
There are 4 default skins, but [this picture](https://camo.githubusercontent.com/972bd5d93779fdaf95e02cf0326b429be93adcba/687474703a2f2f692e696d6775722e636f6d2f395079784a4d4e2e676966) shows so many more colors. How can I customize the theme color?

**Comment by equinusocio** [comment]
There are 4 Theme (default, darker, palenight and lighter) skin and 15 accent colors. Check the readme https://github.com/equinusocio/material-theme#theme-options
