### ISSUE TITLE
Matching braces have different colors in some PHP code

### ISSUE THREAD

**Issue by adamwathan** [equinusocio/material-theme#1085]
Closing braces for static method calls are a different color than opening braces:

![image](https://cloud.githubusercontent.com/assets/4323180/22408796/340e829c-e64d-11e6-8aed-0564fdaaf2ce.png)

Can reproduce with this snippet:

```php
Foo::bar();
```

**Comment by equinusocio** [comment]
This is related to the PHP package scopes. I don't have this issue

<img width="197" alt="screen shot 2017-01-30 at 09 15 41" src="https://cloud.githubusercontent.com/assets/10454741/22416136/bcc266ec-e6cc-11e6-90d6-0ddbe83c2c30.png">

**Comment by adamwathan** [comment]
Ah weird! Any idea what could be different in my environment? Thanks for the quick reply.

**Comment by equinusocio** [comment]
I think it could be some of installed packages related to the PHP language. Are you using the default sublime text php syntax?

**Comment by adamwathan** [comment]
Ah you're right, I'm using this alternate PHP grammar:

https://github.com/gerardroche/sublime-php-grammar

I've opened an issue there because it seems to affect several other themes too.

Thanks for your help!
