### ISSUE TITLE
material_theme_big_fileicons does not work with "zz File Icon" option "force_override"

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/material-theme#1086]
### Summary

I use `zz File Icon` package icons instead of the Material Theme native icons using

```
{
    "force_override": true
}
```

And when I try to enable `"material_theme_big_fileicons": true` nothing happens

### Expected behavior

Since `Material Theme` has support `zz File Icons` would be great if `material_theme_big_fileicons` will work

### Environment

Windows 10 Build 14393.693
Sublime Text 3 Build 3126
Material Theme release v4.0.4
Material Theme - Appbar release v1.2.8
Material Theme - White Panels release v1.0.8
zz File Icons release v2.2.0

**Comment by ihodev** [comment]
@Zx-EvM When you use `force_override` you can just change the size to 11 in `zz File Icons` settings, do the same as `material_theme_big_fileicons`.

```
{
  "force_override": true,
  "size": 11
}
```

**Comment by Zx-EvM** [comment]
@ihodev Thanks. It works

I try to ask here also one thing.

When in Material Theme enable `"material_theme_big_fileicons": true` file names are not in the middle of file icon. Screen:

![sad9d23das](https://cloud.githubusercontent.com/assets/20873402/22478654/ac1c6968-e79f-11e6-90e4-be5401c78d7c.png)

![sad9d23das](https://cloud.githubusercontent.com/assets/20873402/22478660/b6f14b42-e79f-11e6-882a-06e0526e4cd3.png)

It is possible to fix that?

**Comment by ihodev** [comment]
@Zx-EvM  Unfortunately, this is Sublime Text issue. However you can play with `row_padding` of `sidebar_tree` class. 

Open `Packages/zz File Icons/dist/zpatches/Material*.sublime-theme` and add the following lines

```js
{
  "class": "sidebar_tree",
  "row_padding": [8, 6, 8, 5] // Try to play with this values 
},
```

**Comment by Zx-EvM** [comment]
@ihodev Thanks for your answers. I will try this

**Comment by equinusocio** [comment]
Thank you @ihodev!

**Comment by Zx-EvM** [comment]
@equinusocio are you plan it?

**Comment by equinusocio** [comment]
The fix is for `material_theme_big_fileicons` setting, not for zz File Icons `size` setting. If you the `size` setting from zz File Icons you will have the same issue.

**Comment by Zx-EvM** [comment]
@equinusocio Ok. If you create fix for native MT icons I will use native icons
