### ISSUE TITLE
how do you change color of current file

### ISSUE THREAD

**Issue by craigcosmo** [equinusocio/material-theme#1088]
<img width="355" alt="screen_shot_2017-02-03_at_4_48_05_pm" src="https://cloud.githubusercontent.com/assets/538657/22586695/c7255b14-ea30-11e6-847c-8b055ae28f7d.png">

**Comment by equinusocio** [comment]
```json
  {
    "class": "sidebar_label",
    "parents": [{"class": "tree_row", "attributes": ["selected"]}],
    "font.bold": false,
    "color": [128, 203, 196]
  }
```

But if you edit the compiled theme you have to remove all accents occurrences:

```json
     ....
    {
      "class": "sidebar_label",
      "settings": ["material_theme_accent_red"],
      "parents": [{"class": "tree_row", "attributes": ["selected"]}],
      "color": [229, 115, 115]
    },
    {
      "class": "sidebar_label",
      "settings": ["material_theme_accent_purple"],
      "parents": [{"class": "tree_row", "attributes": ["selected"]}],
      "color": [171, 71, 188]
    },
   ...
```

**Comment by craigcosmo** [comment]
sorry but where should I put this config?

**Comment by equinusocio** [comment]
Is not a config. You have to extract the theme with the Packages Source Viewer package, and the edit files.

**Comment by craigcosmo** [comment]
thanks, just find out I can change the accent color in official config. But that would the folder's text color as well :(. Would be nice to have some option like `disable highlighting opened folder`. That would be easier to notice which file in tree is being viewed.
