### ISSUE TITLE
New folder not show

### ISSUE THREAD

**Issue by adamka93** [equinusocio/material-theme#1092]
When i try create new folder with left click on any folder at side bar the input box does not appear.
At the bottom of the editor the margin increasing but nothing else.
The function working, but the input box invisibe

Using windows and ST Build 3126
![default](https://cloud.githubusercontent.com/assets/10884684/22741550/d97f03b4-ee13-11e6-96ca-ca4a7ff6b35e.PNG)
![material](https://cloud.githubusercontent.com/assets/10884684/22741553/dd18e120-ee13-11e6-8c12-14215c2c5d6a.PNG)

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme#known-issues
