### ISSUE TITLE
can't save font size for application level

### ISSUE THREAD

**Issue by born2net** [equinusocio/material-theme#1095]
### Summary
I have a high res screen so need to set fonts size to 16 px
works fine, but looses settings on restart
now, the value of 16 is KEPT in the settings, but font default back to 14 px size
...

### Expected behavior
apply correct font size on restart
...

### Actual behavior
shows 16px in settings, but really 14px
...

### Steps to reproduce

change settings and restart
### Environment

* Operating system and version:
Windows 10 64 bit
WebStorm latest EA

![ca](https://cloud.githubusercontent.com/assets/5090936/22844858/f3038558-ef94-11e6-8f85-57eb949cbd2f.PNG)

I love the theme but can't use it as I have to set the fonts on every restart :(

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by equinusocio** [comment]
Please report this issue on the official IntelliJ repository.
https://github.com/ChrisRM/material-theme-jetbrains
