### ISSUE TITLE
Tabs underline color

### ISSUE THREAD

**Issue by Bagongo** [equinusocio/material-theme#1096]
Is it possible to change the tabs underline color as per the animated gif on the read-me file? So far They're just white with every combination I tried.
Thanks!

**Comment by equinusocio** [comment]
You have to set the accent color setting:
https://github.com/equinusocio/material-theme#theme-options

**Comment by Bagongo** [comment]
Thank you, I figured that! 
The fact is that in my case I am not being able to change the accents from the drop-down menu Material Theme > Configuration > Accents. 
Flagging or deflagging the options there has no effect on the layout for what I can see... However harcoding the values in Preferences.sublime-settings - User does the trick. 
Maybe it's just meant to be configured that way only? 
Anyway great job on the theme, I really like it, and thanks for the answer!
Cheers!

**Comment by equinusocio** [comment]
@Bagongo make sure you have checked **ONLY ONE** accent color from the dropdown menu.

**Comment by Bagongo** [comment]
Makes sense. 
Grazie!
