### ISSUE TITLE
Almost invisible scroll bar

### ISSUE THREAD

**Issue by finlayb** [equinusocio/material-theme#1098]
Love this theme, I've been using it for an age. Always have one issue though. For me, the scroll bar is almost invisible against the background... Would you be able to make the main page scroll bar darker please? Or is there a way I can make my own scroll bar darker? 

![scrollbar](https://cloud.githubusercontent.com/assets/12692736/23219002/c2f0ebc8-f915-11e6-88ae-e630c0fe44dc.png)

Thanks

**Comment by equinusocio** [comment]
Check https://github.com/equinusocio/material-theme#theme-options

```json
"material_theme_accent_scrollbars"        : true , // Enable accent color for scrollbars
"material_theme_bright_scrollbars"        : true , // Bright scrollbars puck color
```
