### ISSUE TITLE
Scrollbar thumb too discreet

### ISSUE THREAD

**Issue by onirix** [equinusocio/material-theme#1099]
Maybe its cause by my custom theme but I found the thumb in the scrollbar with the Dark Theme very hard too see. The contrast with the track is very low.
https://i.imgur.com/XP8O9df.png

These adding settings in my User Preferences settings doesn’t seem to change anything…
"material_theme_accent_orange": true,
"material_theme_accent_scrollbars": true,
"material_theme_bright_scrollbars": false,
"material_theme_contrast_mode": true,

Thanks for help

**Comment by equinusocio** [comment]
Duplicated. Please check the readme under the theme options, or search for a similar issue.
