### ISSUE TITLE
Rename bar is not showing

### ISSUE THREAD

**Issue by arnars** [equinusocio/material-theme#110]
I'm missing the newfile/rename/duplicate bar in the bottom of the screen when using material-theme. I would upload an image, but it would be of little use.

**Comment by johnRivs** [comment]
Put the cursor on the top border of the rename bar and resize it.

**Comment by equinusocio** [comment]
See #67

**Comment by arnars** [comment]
Ah yes. And sorry for the inconvenience, still new at actually commenting on github.
