### ISSUE TITLE
hidpi icons

### ISSUE THREAD

**Issue by brianc118** [equinusocio/material-theme#1100]
Hi, awesome job with the theme! It is near perfection, but the one thing that bugs me are the blurry icons on my screen.

### Expected behavior

HiDPI icons

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/4782836/23296920/f2a12744-fac2-11e6-9434-a8c3a0c13daf.png)

### Environment

Affects
* Operating system and version:
  * Windows 10
  * Ubuntu GNOME 16.04
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.5

**Comment by equinusocio** [comment]
What's your screen density?

**Comment by brianc118** [comment]
Surface pro 4
2736x1824
267 ppi

**Comment by equinusocio** [comment]
At the moment my focus is the version for Visual Studio Code of Material Theme. No other updates will be released for now, but i'm open to PR's.

**Comment by Zx-EvM** [comment]
@equinusocio hello. Today I update VSCode on PC to new [February 2017 (version 1.10)](https://code.visualstudio.com/updates/v1_10) but in release notes I do not see anyone new API to customize appearance. I guess I do not understand that, and in fact there are changes. But, expected in the near future, big changes in VS Code Material Theme?

**Comment by equinusocio** [comment]
@Zx-EvM The UI api implementation was deferred. Check the last part of this issue. I think we have to wait the next month update (i hope).

When theme apis will be available i can make the first v1 release. Please next time use the official https://github.com/equinusocio/vsc-material-theme repository

**Comment by equinusocio** [comment]
This should be fixed in ST 3128

**Comment by brianc118** [comment]
confirmed fixed :)
