### ISSUE TITLE
Hi,I just ask for something.

### ISSUE THREAD

**Issue by endingman** [equinusocio/material-theme#1105]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3...
* Material Theme release:
  * v3...

**Comment by endingman** [comment]
The theme auto update in sublime but I have some settings in schemes about bracket style, And I lost them. It was from your docs from the past and i forgot to backup one. Can you give me the setting of bracket style？I like it.Thanks

Can you understand my poor english?

**Comment by equinusocio** [comment]
What do you need exactly? You can che all the theme options here
https://github.com/equinusocio/material-theme#theme-options

There isn't a setting for brackets.

**Comment by endingman** [comment]
I find a backup.Thanks.
