### ISSUE TITLE
how to change sidebar heading height

### ISSUE THREAD

**Issue by anderson916** [equinusocio/material-theme#1107]
Hi,

I changed the font size of tab from 11 to 14, and tab height from 54 to 44. But I don't know how to change the height of the heading of the sidebar. Thanks.

<img width="940" alt="screen shot 2017-03-11 at 7 26 37 pm" src="https://cloud.githubusercontent.com/assets/195719/23822873/af8de4e0-0690-11e7-880c-cbd753830c1b.png">

**Comment by equinusocio** [comment]
Don't change the font-size... just use the theme `material_theme_small_tab` setting...
