### ISSUE TITLE
Custom accent color

### ISSUE THREAD

**Issue by xsme** [equinusocio/material-theme#1109]
Hello, I'm trying to change blue accent color. I found the icons in the folder: ```/assets/accent-blue```, and one thing I still needed. Where can I find variable of the color of the text?

**Comment by equinusocio** [comment]
If you want to change the accent color you should use the theme settings.
https://github.com/equinusocio/material-theme#theme-options

If you customise the package you will lost every change next update.

You can find accents colors here
https://github.com/equinusocio/material-theme/blob/develop/sources/settings/commons.json
