### ISSUE TITLE
Left margin on .md files

### ISSUE THREAD

**Issue by samikazem** [equinusocio/material-theme#111]
If I try to make a markdown file (.md) it includes a left margin which is around a tab width long. Happens on new markdown files as well as files already made.

Looks like this:
![screen shot 2015-06-15 at 20 00 59](https://cloud.githubusercontent.com/assets/4049573/8167944/5c8622d0-1399-11e5-8282-e5ca12ffadee.png)

**Comment by equinusocio** [comment]
The .md file have draw_centered setting. See #74
