### ISSUE TITLE
Icons randomly don't appear until hover

### ISSUE THREAD

**Issue by diego898** [equinusocio/material-theme#1113]
### Summary
Icons randomly don't appear until hover

### Expected behavior
The icons show up when I start

### Actual behavior
Sometimes they show up, sometimes they dont and I have to hover over them to get them to show up. Here is a gif showing 3 restarts. It shows the randomly showing, partially showing, and no showing. 

![](https://media.giphy.com/media/3o7bu36M7CbLAqHPtC/giphy.gif)

### Steps to reproduce
I'm not sure yet - I havent been using the sidebar much, just started so I just noticed this - I am investigating. 

### Environment

* Operating system and version: Mac OS 10.12.3
* Sublime Text 3: Build 3126
* Material Theme release: latest

**Comment by equinusocio** [comment]
This is a common issue not related to material theme, you can find more details about that on the sublime text forum. If you installed "A FIle Icons" package check the readme and report the issue on his repository
