### ISSUE TITLE
julialang icons are not shown in the sidebar

### ISSUE THREAD

**Issue by montyvesselinov** [equinusocio/material-theme#1114]
* Operating system and version:
  * [ ] Windows ...
  * [x ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3125
* Material Theme release:
  * v4.0.5

**Comment by equinusocio** [comment]
This theme use [A File Icon](https://github.com/ihodev/a-file-icon), please report the issue to the correct repository and @ihodev 
https://github.com/ihodev/a-file-icon

**Comment by montyvesselinov** [comment]
The Julia Icons are defined a-file-icon. However, they do not show up here.

-monty

**Comment by equinusocio** [comment]
Have you tried with another theme that support A File Icon? Like Boxy Theme

**Comment by ihodev** [comment]
@montyvesselinov Make sure that you have installed [Julia](https://packagecontrol.io/packages/Julia) package. See [this](https://github.com/ihodev/a-file-icon/blob/develop/PACKAGES.md) for more details. In any case feel free to [open issue here](https://github.com/ihodev/a-file-icon) with your environment details.

**Comment by montyvesselinov** [comment]
now it works. there was `ZZZ A-file-icon zzz` package that i had to remove.
This was clean installation so i do not know what added this package.

-monty

**Comment by ihodev** [comment]
@montyvesselinov Thanks for details. `A File Icon` generates that package. It seems that you had some error during its installation or you've closed Sublime Text before it is completely installed. I'll fix this issue in the next release of `A File Icon`.

**Comment by montyvesselinov** [comment]
Thank you very much!


-monty

On Fri, Mar 24, 2017 at 10:00 AM, Ihor Oleksandrov <notifications@github.com
