### ISSUE TITLE
Titlebar theming

### ISSUE THREAD

**Issue by n00ge** [equinusocio/material-theme#1119]
Sublime was just updated with support for title_bar theming on OSX 10.10+. I'd love to see this added into the Material Theme carrying over the tab-bar colors into the title bar. 

Documentation for the feature is here:
http://www.sublimetext.com/docs/3/themes.html#elements-windows

Thanks!

**Comment by n00ge** [comment]
Thanks! 👍

**Comment by WillsB3** [comment]
Do we have to do something specific to enable this? I have Mac OS 10.12.4, and just got the updated version of Sublime Material but the title bar is still grey/silver. 

Is there a setting somewhere that needs to be flipped to enable this feature?

**Comment by equinusocio** [comment]
@WillsB3 You need Sublime Text 3 dev build 3128+

**Comment by WillsB3** [comment]
Great, thanks for the info :)

**Comment by MechanicalHuman** [comment]
Hey, can we get a setting to enable/disable the feature? I use the MacOs Sierra Tabs and the title bar feature disables them as it uses the `full window content` area. 

<img width="1083" alt="screen shot 2017-08-11 at 12 25 18 pm" src="https://user-images.githubusercontent.com/2084868/29222360-25bde81e-7e90-11e7-8be3-fb187b8714a2.png">

_I've been editing a local copy of the theme every time a new update is out._

**Comment by equinusocio** [comment]
Do you mean having both title bar and mac tabs themed?

**Comment by MechanicalHuman** [comment]
No, being able to disable the title bar theming. I’ll make a pull request in a bit. 


Jorge Proaño
design, media and technology

https://www.hidden-node-problem.com
jorge@hiddennodeproblem.com
+1 (646) 477 0050
