### ISSUE TITLE
Title bar color

### ISSUE THREAD

**Issue by kocoai** [equinusocio/material-theme#1121]
### Summary
I just see in the release note 4.0.6, there is a colour theme for title bar, but I have always the gray classic bar after updating

https://github.com/equinusocio/material-theme/releases/tag/v4.0.6

### Expected behavior
Colored title bar after the update

### Actual behavior
Gray classic bar

### Environment
Theme version 4.0.6

* Operating system and version:
MacOS Sierra

* Sublime Text:
 Build 3126

* Material Theme release:
 4.0.6

**Comment by iczman** [comment]
According to https://www.sublimetext.com/3dev the title bar theming feature was added in Sublime dev build 3127. Get the latest dev build from that same page and you should be good to go.

**Comment by equinusocio** [comment]
Otherwise you have to wait the public release.

**Comment by JuHwon** [comment]
Since about two or three weeks I noticed that that the colored title bar is gone :( 
Anyone else noticed this? 

I'm running Sublime Build 3153 on macOS 10.12.6

**Comment by joefedricTL** [comment]
I have this issue as well, on two different MacBook Pros, using Build 3153, on both macOS 10.12.6 and macOS 10.13.0.

**Comment by shaharyarahmad** [comment]
Having the same issue on my Macbook also. Sublime Build 3143 on macOS 10.13.1

**Comment by ivandoric** [comment]
It was removed in the newest version because of some memory problems.

**Comment by equinusocio** [comment]
you can enable it again from **v4.1.2**.

**Comment by ivandoric** [comment]
@equinusocio Great, didn't know that. Thanks 👍
