### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by bastienGranger** [equinusocio/material-theme#1123]
Hi !

I just installed the theme for sublime 3 on my new mac book (mac book pro OS:10.12.4) .
But icons displayed icons are not the good one but I dont understand why :/

<img width="158" alt="screen shot 2017-04-16 at 20 26 30" src="https://cloud.githubusercontent.com/assets/2982906/25073253/04dbcd22-22e3-11e7-91e1-3331978557ed.png">

**Comment by equinusocio** [comment]
You have to install A File Icons.
