### ISSUE TITLE
The Legend for Folders and Open Files are not showing

### ISSUE THREAD

**Issue by MartSerra** [equinusocio/material-theme#1124]
### Summary

The Legend for Folders and Open Files are not showing.
### Expected behavior

Original Theme: 
![alt text](http://i.imgur.com/6ZoWEBz.png "Example Original")

### Actual behavior

Current Theme: 
![alt text](http://i.imgur.com/vfJGpZL.png "Example Custom Theme")

### Steps to reproduce

This is my configuration
````json
{
	"always_show_minimap_viewport": true,
	"caret_extra_bottom": 1,
	"caret_extra_top": 1,
	"caret_extra_width": 2,
	"caret_style": "phase",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"draw_minimap_border": true,
	"font_size": 12,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_scrollbars": true,
	"material_theme_bright_scrollbars": true,
	"material_theme_bullet_tree_indicator": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"show_full_path": true,
	"show_line_endings": true,
	"theme": "Material-Theme.sublime-theme"
}
````
### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.6
* Material Theme Appbar:
  * v1.2.8

Thanks in advance 😄

**Comment by equinusocio** [comment]
This is not the correct repository. To enable the sidebar titles you have to add `material_theme_tree_headings: true`.

More info here https://github.com/equinusocio/material-theme-appbar#addon-options
