### ISSUE TITLE
Window jumps down when making changes in the configuration menu

### ISSUE THREAD

**Issue by alextegelid** [equinusocio/material-theme#1126]
### Summary
The window jumps down when changing anything (other than *Color Scheme*) in the configuration menu. Demo video: https://cl.ly/161c0H413f2G

### Expected behavior
Window should stay in its current position on the screen.

### Actual behavior
Window jumps down about 25 pixels. Seems to be a title bars height. Might be related to #1119.

### Steps to reproduce

1. Open the *Configuration* menu
2. Click *Accent* (or any other menu item other than *Color Theme*)
3. Change the state of any checkbox

### Environment

- Sublime Text:   3131
- Platform:   osx
- Arch:   x64
- Theme:   4.0.6
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.13.1
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by equinusocio** [comment]
This is a sublime text bug. Please report that to sublime text team
