### ISSUE TITLE
Configuration to modify the tab bar size and tab title font size

### ISSUE THREAD

**Issue by hashd** [equinusocio/material-theme#113]
Most of the other sublime themes provide similar configuration to reduce the tab bar size. It would awesome if similar provision is made for this theme. 

Issues apart, the theme is amazing!

**Comment by equinusocio** [comment]
#79

**Comment by hashd** [comment]
Ah, didn't notice that a similar issue was addressed earlier. The setting however doesn't seem to be mentioned in the readme at the moment.

Thanks for redirecting me to the right place anyways :)

**Comment by equinusocio** [comment]
..because will be available in the next minor release. At the moment is available only in the Dev branch
