### ISSUE TITLE
Shadow under title bar

### ISSUE THREAD

**Issue by sn0wyfall** [equinusocio/material-theme#1130]
Hi. I was wondering if it would be possible to add a shadow under the tab bar. This would better separate the tab and the text on screen, because it does look kind of messy when you have a lot of text on the screen. Thoughts?

**Comment by equinusocio** [comment]
Not at the moment, Sublime Text doesn't have api for that shadow. I'm sorry

**Comment by sn0wyfall** [comment]
No problem. Pity that they have a shadow for the gutter but not for the tab bar!

**Comment by equinusocio** [comment]
I'm working on the Visual Studio Code porting, because at the momento i'm using it and i think is a awesome (and fast) like sublime text.

**Comment by sn0wyfall** [comment]
Cool, I guess I'll check that out
