### ISSUE TITLE
C# syntax highlighting issue

### ISSUE THREAD

**Issue by zpreston123** [equinusocio/material-theme#1131]
### Summary
There appears to be a color mismatch on both of the class curly braces in C#. 

### Expected behavior
Both curly braces have the same color.

### Actual behavior
Both curly braces do not have the same color.  See screenshots below:

Default theme
<img width="501" alt="screen shot 2017-05-08 at 1 30 14 pm" src="https://cloud.githubusercontent.com/assets/11165740/25816618/9c645734-33f2-11e7-9383-0f6c1c84fd08.png">

Dark theme
<img width="503" alt="screen shot 2017-05-08 at 5 40 07 pm" src="https://cloud.githubusercontent.com/assets/11165740/25826721/db54e936-3415-11e7-88ef-02615039afc2.png">

Palenight theme
<img width="498" alt="screen shot 2017-05-08 at 5 40 13 pm" src="https://cloud.githubusercontent.com/assets/11165740/25826730/e30f7bd2-3415-11e7-9e7b-ae53f9a47ab3.png">

Light theme
<img width="492" alt="screen shot 2017-05-08 at 5 40 02 pm" src="https://cloud.githubusercontent.com/assets/11165740/25826736/e9508d56-3415-11e7-94bb-be403e7b93be.png">

### Steps to reproduce
1. Open Sublime Text.
2. Copy the snippet below:
```
using System;

namespace Test
{
    public class HelloWorld
    {
        public static void Main()
        {
           Console.WriteLine("Hello World!");
        }
    }
}
```
3. Paste it in Sublime Text and set the syntax to C#.

### Environment
* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS 10.12.4
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.6

**Comment by equinusocio** [comment]
Please update to Sublime Text 3131, this will be fixed.

**Comment by zpreston123** [comment]
OK thanks!  I'll wait until the next stable build is released.

**Comment by equinusocio** [comment]
I suggest you to use the 3dev build because she gets more updates and it's stable.
