### ISSUE TITLE
Indent Guide Options with draw_active not behaving correctly

### ISSUE THREAD

**Issue by jaminscript** [equinusocio/material-theme#1133]
### Summary

Indentation guide is off by one column. It highlights the parent element instead of the selected element.

### Expected behavior

Indentation line should show where the selected element begins and draw a line to where it ends.

### Actual behavior

Indentation line shows where the *parent* of the selected line begins and where the *parent* element ends. Screenshot below has line 5 selected, but it's highlighting the element from line 4.

![screen shot 2017-05-12 at 10 02 46 am](https://cloud.githubusercontent.com/assets/2616473/25974075/1be37476-36fb-11e7-8b5d-5c865367d35e.png)

### Steps to reproduce

1. Install Material Theme
2. Use suggested sublime settings from README.md
3. Observe issue.

### Environment

* Operating system and version:
  * [x] Windows 10
  * [x] Mac OS 10.12.4
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v3... The latest one through package control

**Comment by equinusocio** [comment]
This is not theme related. The theme provide only the color. Report that to Sublime Text forum
