### ISSUE TITLE
Custom change syntax color?

### ISSUE THREAD

**Issue by dingo-d** [equinusocio/material-theme#1134]
Is it possible to redefine individual syntax color? I don't like the green color that comes with the Dark theme, and was wondering is there an easy way to change that?

I'm not interested in changing colors for different languages, I'd like to do it globally (just the syntax).

**Comment by equinusocio** [comment]
You have to extract the package with [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer#commands) and change the colors references inside the themes files at root:

- Material-Theme.sublime-theme
- Material-Theme-Darker.sublime-theme
- Material-Theme-Palenight.sublime-theme
- Material-Theme-Lighter.sublime-theme

**Comment by dingo-d** [comment]
Cool, thanks!
