### ISSUE TITLE
latest 0.3.0.1 release is... well not good...

### ISSUE THREAD

**Issue by born2net** [equinusocio/material-theme#1136]
colors are off
fonts are off
white number lines
and more issues
...

on Windows 10 64bit
![image](https://cloud.githubusercontent.com/assets/5090936/26529152/d25111de-436f-11e7-9d0c-b6b65030cd09.png)

**Comment by ELD** [comment]
This repo deals with the Sublime Theme AFAIK. That's in WebStorm which is a separate project.

There are two Material UI Themes I know of in the Jetbrains plugin repos, the `Material Theme UI` and `Material Theme UI Extended` ones. As far as I know, the `Material Theme UI Extended` plugin appears to be better maintained, so maybe install that one and see what happens?
