### ISSUE TITLE
Alert error while trying to start Sublime Text 2

### ISSUE THREAD

**Issue by riotkkwok** [equinusocio/material-theme#1138]
### Summary

As titled

### Expected behavior

Start ST2 as usual

### Actual behavior

![default](https://cloud.githubusercontent.com/assets/10059303/26778379/9c62fb64-4a13-11e7-9681-bb231db84bad.png)

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [x] Windows 7
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 2
* Material Theme release:
  * v4.0.6

**Comment by riotkkwok** [comment]
Though I had fixed this issue by removing the last comma in the mentioned file, I think it should be best to fix by official.

**Comment by equinusocio** [comment]
Material Theme doesn't support Sublime Text 2.
