### ISSUE TITLE
Renaming files in sidebar

### ISSUE THREAD

**Issue by stephwongwt** [equinusocio/material-theme#1139]
### Summary
When renaming files from sidebar(with SideBarEnhancement installed) the bar that appears below for the user to rename cannot seen in full.

### Expected behavior
For the rename bar to appear in full so users can see the filename they are renaming.

### Actual behavior

The bar appears just slightly above the bottom info(line, column, tab size) bar so you can see a text box with highlighted text but cannot see the text at all.

### Steps to reproduce

1. Open side bar
2. Rename a file

### Environment

* Operating system and version:
  * [*] Windows 7
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.6

**Comment by olimortimer** [comment]
Similar issue to this - https://github.com/equinusocio/material-theme#known-issues

If you move the cursor to the rename bar, you can drag it up and back down, and it will be fixed.
