### ISSUE TITLE
.terminal companion style

### ISSUE THREAD

**Issue by mvaneijgen** [equinusocio/material-theme#114]
Hey I made a quick `.terminal` companion style, maybe you could improve up on it. 

![material-theme terminal](http://i.imgur.com/Wbhmshx.jpg "image")

Gist:
https://gist.github.com/mvaneijgen/4c56701215847dd5ddcf

**Comment by loekup** [comment]
Very nice theme @mvaneijgen , one question how dit you get the nice git status bars ?

**Comment by mvaneijgen** [comment]
@loekup I followed Wesbos his [Command line Power User playlist](https://www.youtube.com/playlist?list=PLu8EoSxDXHP7tXPJp5ZmUpuT7sFvrswzf). I don't know everything, but I thinks its a combination of [Oh my ZSH](http://ohmyz.sh) and a font with special characters. Just follow the playlist.

**Comment by equinusocio** [comment]
Nice job, i will add a link in the main README after a little revision.

**Comment by gj1118** [comment]
@loekup  its this zsh theme https://gist.github.com/agnoster/3712874 ..

**Comment by oller** [comment]
Looks great, I've been looking for an iTerm2 compatible theme, unfortunately it doesn't seem to support this format.  I don't' suppose anyone has stumbled across or created one?
