### ISSUE TITLE
Color highligth support for PHP catch multiple exceptions

### ISSUE THREAD

**Issue by stefanoruth** [equinusocio/material-theme#1141]
Hi there.

I would be nice if you would add support for color highlighting PHP multiple-catch, here is an example of how it looks :)

https://wiki.php.net/rfc/multiple-catch

![image](https://user-images.githubusercontent.com/6178983/27121135-63ea9092-50e6-11e7-9a0b-6ae76e14ce6e.png)

**Comment by equinusocio** [comment]
This is handled by the PHP package, atm it doesn't provide the correct scope for the first element:

![screen shot 2017-06-14 at 09 54 52](https://user-images.githubusercontent.com/10454741/27121413-882024e4-50e7-11e7-830b-961ccc21b26a.png)
![screen shot 2017-06-14 at 09 54 37](https://user-images.githubusercontent.com/10454741/27121414-8842bce8-50e7-11e7-8df0-621a138c3e2a.png)

The first element is not recognised as `support.class.exception`, so it doesn't get the color from the theme.
