### ISSUE TITLE
Exception thrown in plugin Material Theme UI PHPStorm.

### ISSUE THREAD

**Issue by roelmonnens** [equinusocio/material-theme#1143]
### Summary
I opened a folder that contains phtml-files.
It opens but it triggers an exception in PHPStorm. Everything keeps working. The phtml-files get the icon of the php-files.

**Error message:**

> Icon cannot be found in '/icons/plugins/fileTypes/plist.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'

**Details:**

> Icon cannot be found in '/icons/plugins/fileTypes/plist.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:144)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:112)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:132)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:122)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
> 	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
> 	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
> 	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
> 	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
> 	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
> 	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:144)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:112)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:132)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:122)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
> 	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
> 	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
> 	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
> 	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
> 	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:78)
> 	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
> 	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
> 	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:229)
> 	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
> 	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
> 	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
> 	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
> 	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:144)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:112)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:132)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:122)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
> 	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
> 	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
> 	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
> 	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
> 	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
> 	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:144)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:112)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:132)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:122)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
> 	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
> 	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
> 	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
> 	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
> 	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:78)
> 	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
> 	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
> 	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:229)
> 	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
> 	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
> 	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
> 	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
> 	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:144)
> 	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:112)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:132)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:122)
> 	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
> 	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
> 	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
> 	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
> 	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
> 	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
> 	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
> 	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

### Reproduce
Open a folder that contains phtml-files.

### Environment
* Operating system and version:
  * [x] Mac OS 10.12.5
* PHPStorm:
  * PhpStorm 2017.1.4
  * Build #PS-171.4694.2, built on May 16, 2017
  * JRE: 1.8.0_112-release-736-b21 x86_64
  * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  * Mac OS X 10.12.5

**Comment by equinusocio** [comment]
https://github.com/ChrisRM/material-theme-jetbrains
