### ISSUE TITLE
Why the .vue file's icon is blue in Webstorm?

### ISSUE THREAD

**Issue by DanielWLam** [equinusocio/material-theme#1145]
Just update the webstorm and some plugin, and some how, vue's icon gets blue, which looks pretty weired.  Is it my problem? If not, hope to change it back to the official icon.  

![image](https://user-images.githubusercontent.com/8369212/27521889-00eb8a88-5a54-11e7-8c9d-c41f2ff76932.png)

**Comment by mallowigi** [comment]
Material icons are taken from the repository "A File Icon" and are pretty much colored glyphs. If you don't like it you can still select "disable Material Icons" in the settings.

**Comment by mallowigi** [comment]
Besides you're here complaining about the sublime plugin and it has nothing to do with it.

**Comment by DanielWLam** [comment]
So, is it a problem from the 'A File Icon'? Thanks anyway!
