### ISSUE TITLE
Material theme panels (configuration, info, etc.) don't appear

### ISSUE THREAD

**Issue by sn0wyfall** [equinusocio/material-theme#1148]
### Summary

Often the configuration panel (accessible by right clicking or from the command palette) will not appear.

### Expected behavior

It should appear on the current visible screen when called.

### Actual behavior

Sometimes it fails to appear.

### Steps to reproduce

It's quite hard to reproduce this as it appears to be random as far as I can tell. It just won't show when it is activated. However, there is a "version" of this bug which can be reproduced (which isn't as bad as the actual bug, but still could be classified as an "annoyance").

1. Go to the top of a document.
2. Activate the configuration panel.
3. Scroll down the document. The panel will disappear. 
4. Try to activate it as you're in the bottom of the document. It won't appear.

You can see it again if you activate it from the top of the document, where you originally activated it from. This is where the actual bug comes in: with the steps I provided, it will appear again if you go to the original activation position. The bug I keep facing is one where it doesn't seem to show at all anywhere in the document. Perhaps these two bug are related in how they occur.

I also experience this with panels such as the info panel.

Edit: I have another way to reproduce this:

1. Scroll in your document.
2. Activate a panel while your are scrolling. This will only be possible through the command palette.
3. You won't be able to open any more panels in that document. However, if you create a new document, you'll be able to activate them there.

### Environment

- Sublime Text:   3140
- Platform:   osx
- Arch:   x64
- Theme:   4.0.7
- Install via PC:   True

**Comment by sn0wyfall** [comment]
I just realized that it appears where the text cursor is and I'm a complete idiot.

**Comment by sn0wyfall** [comment]
Would it perhaps be possible to change the behavior so that it appears on the screen irrespective of the text cursor? So that it stays in the same place even if you scroll? The current behavior is slightly confusing.

**Comment by equinusocio** [comment]
For that i need a python supporter.

**Comment by sn0wyfall** [comment]
Do you think this'll be a useful change? I mean, I feel honored you didn't close this issue yet

**Comment by equinusocio** [comment]
Yes, but i don't have any python collaborator. I'm the only supporter and i don't have such skills. I'm sorry.

**Comment by sn0wyfall** [comment]
It's fine! I really appreciate you for making what you've made now. I can't imagine living without this theme... it's _literally_ the best one, in my opinion
