### ISSUE TITLE
Add a bit more padding to the status bar text on the left

### ISSUE THREAD

**Issue by sn0wyfall** [equinusocio/material-theme#1149]
I think it would be nice to move the text on the bottom right a bit more to the left. More specifically, the hamburger menu should be in the middle under the gutter, and the line and column info text should align itself approximately with the text of the document. I know this depends on how large the document is (and thus the size of the gutter), but currently it seems like the text is squeezed a bit too much to the left.

The reason I'm asking is because the left padding seemed a bit better when I had the normal status bar, but I enabled the small status bar option and now it looks a bit too cramped to the left. I also know I'm being a bit picky and I could change it myself but I'm just wondering if you'd agree with me.

**Comment by mallowigi** [comment]
There's very unlikely that the guy will release a new version just for a few pixels. Get over it.

**Comment by sn0wyfall** [comment]
> I also know I'm being a bit picky and I could change it myself but I'm just wondering if you'd agree with me.
