### ISSUE TITLE
Color Schemes Missing

### ISSUE THREAD

**Issue by Kaelri** [equinusocio/material-theme#1150]
### Summary

It looks like the default color themes were accidentally (?) removed in a recent commit: 35cf5f80f61cfa75dba2f8ea75579f652fc19d6d

### Expected behavior

The following color scheme files should be present:
- Packages/Material Theme/schemes/Material-Theme.tmTheme
- Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme

### Actual behavior

The color scheme files are missing.  
https://github.com/equinusocio/material-theme/tree/master/schemes

**Comment by klipitkas** [comment]
I can confirm this issue. This occurs after the last update.

**Comment by goranefbl** [comment]
Same here...

**Comment by nfilzi** [comment]
Same here!

**Comment by fcarrascosa** [comment]
Same here! 
As a temporary Solution I just copied and pasted to a new file the latest version of it:

**Comment by equinusocio** [comment]
Sorry, fixed.

**Comment by TheKidCoder** [comment]
When will the next update be published?

**Comment by equinusocio** [comment]
@TheKidCoder Minutes

**Comment by tommymarshall** [comment]
Same.

**Comment by viclafouch** [comment]
Same here :(

**Comment by drewlustro** [comment]
dang :/ +1

**Comment by equinusocio** [comment]
Just update.
