### ISSUE TITLE
Material Theme Crashed after latest update

### ISSUE THREAD

**Issue by ghassanachi** [equinusocio/material-theme#1151]
### Summary
I was using sublime and I got a notification that Material theme was just upgraded, and then the theme crashed and returned to the default sublime theme

### Expected behavior

Theme upgrades -> Keep working

### Actual behavior

Theme Upgrade -> Sublime returns to the default and sends me the following error:

Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme

### Steps to reproduce

1. First step: Nothing really, package manager upgraded the package and then failed to load the new Material-Theme.tmTheme. I checked the schemes directory and the file Material-Theme.tmTheme is absent.
2. Second step: I removed and reinstalled the package  via the package manager but the same error occured.
3. Third step

### Environment

* Operating system and version:
  * [x] Mac OS: version 10.12.5 
* Sublime Text: version 3
  * Build 3126
* Material Theme release:
  * v4.0.8

**Comment by equinusocio** [comment]
#1150
