### ISSUE TITLE
Material Theme Color Schemes unavailable upon latest release

### ISSUE THREAD

**Issue by ahopkins** [equinusocio/material-theme#1152]
### Summary

I received an update to the theme today. However, it seems to have broken my styling. Seems like maybe there are some files missing.

### Expected behavior

I was hoping to use the default styling. 

### Actual behavior

It is not available.

![image](https://user-images.githubusercontent.com/166269/27872835-c92d32de-61b2-11e7-8042-a607b268e29e.png)

I only see color schemes available for Material Theme Lighter and Palenight.

### Steps to reproduce

1. Activate theme
2. Color scheme is missing ...

I even tried completely removing Material Theme and reinstalling. No luck

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [X] **Linux Ubuntu 17.04**
 Sublime Text:
  * Build 3126
* Material Theme release:
  * 4.0.7

    - Sublime Text:   3126
    - Platform:   linux
    - Arch:   x64
    - Theme:   4.0.7
    - Install via PC:   True
    - Dependencies:
        * mdpopups:   2.1.1
        * markdown:   2.6.6
        * pygments:   2.1a0
        * jinja2:   2.8

**Comment by JoahG** [comment]
I am experiencing this as well. 

macOS 10.12.4
ST 3126

**Comment by drehimself** [comment]
Same for me on MacOS Sierra 10.12.5
ST 3126

**Comment by Endymion1977** [comment]
I get the same on Windows 10 when updating to v4.0.8.

It appears that there is a v4.0.9 already whch fixes it, I tried removing the theme and reinstalling it but Package Control still offers 4.0.8 to me?

**Comment by beornlake** [comment]
Same here on Win 10. Tried uninstall/reinstall as well, but Package Control looks like it needs to be updated.

**Material Theme: Info**
- Sublime Text:   3126
- Platform:   windows
- Arch:   x64
- Theme:   4.0.8
- Install via PC:   True
- Dependencies:
    * mdpopups:   2.1.1
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by jedrekdomanski** [comment]
Same thing here.
- Sublime Text:   3126
- Platform:   linux
- Arch:   x64
- Theme:   4.0.8
- Install via PC:   True
- Dependencies:
    * mdpopups:   2.1.1
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by ahopkins** [comment]
Anxiously awaiting Package Control update. I never quite realized how much I relied upon the consistency and quality of the look and feel of my text editor. It's throwing me off today.

**Comment by alvitawa** [comment]
Same here, also tried cloning the repo, wich does have those schemes in the scheme folder, but that only increases the amount of errors.

These are the errors I get:

- Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme
- Error loading colour scheme Packages/Material Theme/widgets/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/Widget - Material-Theme.stTheme
- Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme
- Error loading colour scheme Packages/Material Theme/widgets/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/Widget - Material-Theme.stTheme
- Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme
- Error loading colour scheme Packages/Material Theme/widgets/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/Widget - Material-Theme.stTheme
- Error loading colour scheme Packages/Material Theme/widgets/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/Widget - Material-Theme.stTheme

**Comment by JoahG** [comment]
Just received the 4.0.9 update, color schemes are back! Thanks @equinusocio!

**Comment by drehimself** [comment]
Package Control has the latest version for me now. Re-installed and all is looking pretty again!

**Comment by jedrekdomanski** [comment]
It's working fine now. Preferences -> Package Settings -> Material Theme -> Activate

**Comment by ahopkins** [comment]
Nice. Confirmed. Closing now.
