### ISSUE TITLE
Hi, Can you add setting for sidebar font?

### ISSUE THREAD

**Issue by Samjin** [equinusocio/material-theme#1155]
The side bar fonts is very hard to read especially when I need to read through from top to bottom to find the file name I am looking for. Is there a way to allow user to make it slightly brighter? 
Thanks

**Comment by mallowigi** [comment]
I have planned to make all colors customizable in a future release. In the meantime, sorry but no.

**Comment by equinusocio** [comment]
Enable the contrast mode.

**Comment by Samjin** [comment]
The contrast mode was enabled and I found it really hard to read thus I post this issue. Is there an alternative way to make text brighter? 
Here's an example after contrast mode is enabled.
![image](https://user-images.githubusercontent.com/6115094/28503185-7e216e10-6fb6-11e7-9816-2d20a3514dd7.png)
