### ISSUE TITLE
Not able to see new folder input 

### ISSUE THREAD

**Issue by hemanjosko** [equinusocio/material-theme#1157]
I am using this configuration 

{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"theme": "Material-Theme.sublime-theme",
	"font_size": 12,
	"always_show_minimap_viewport" : true,
	"bold_folder_labels"           : true,
	"font_options"                 : [ "gray_antialias", "subpixel_antialias" ],    // On retina Mac & Windows
	"indent_guide_options"         : [ "draw_normal", "draw_active" ],   // Highlight active indent
	"line_padding_bottom"          : 3,
	"line_padding_top"             : 3,
	"overlay_scroll_bars"          : "enabled",
}

and i am not able to new folder input

**Comment by equinusocio** [comment]
Please check the readme file.
