### ISSUE TITLE
Sidebar not working & error on light theme

### ISSUE THREAD

**Issue by rizalio** [equinusocio/material-theme#1159]
### Summary

Well I try to installing Material Theme on fresh install sublime text, I want to install the light color scheme, The editor work like what I expected see image below.

![Work on editor](http://i.imgur.com/BWPufvl.png)

But if I try to change sidebar to light theme there's was error check image below

![Not work on sidebar](http://i.imgur.com/L5f37sr.png)  

### Expected behavior

Now I'm using Windows 10, previously on my Ubuntu is work normally.

If see the readme.md there's a screenshot showing a preview for light color scheme that make me sure the problem is on my configuration file. 

![Preview](https://camo.githubusercontent.com/972bd5d93779fdaf95e02cf0326b429be93adcba/687474703a2f2f692e696d6775722e636f6d2f395079784a4d4e2e676966)

### Environment

* Operating system and version:
  * [x] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3162
* Material Theme release:
  * v4.0.9

### Here my configuration file

```
{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Lighter.tmTheme",
	"font_face": "Operator Mono book",
	"font_size": 12,
	"hot_exit": false,
	"ignored_packages":
	[
		"Vintage"
	],
	"material_theme_big_fileicons": true,
	"material_theme_bold_tab": true,
	"material_theme_bright_scrollbars": true,
	"material_theme_bullet_tree_indicator": true,
	"material_theme_tabs_separator": true,
	"remember_open_files": false,
	"theme": "Material-Theme.Material-Theme-Lighter"
}

```

**Comment by equinusocio** [comment]
Is `"theme": "Material-Theme-Lighter.sublime-theme"`

**Comment by rizalio** [comment]
But i just following this recomended

![This](http://i.imgur.com/AsTSSYl.png)

**Comment by rizalio** [comment]
Anyway Thanks! for the awesome theme 👍
