### ISSUE TITLE
[Feature request] Make command pallete position cofigurable

### ISSUE THREAD

**Issue by carlevison** [equinusocio/material-theme#1161]
I really like the way Monokai Pro and ayu themes have their palette position, the only downside is that I would like them in the center, so a configurable option to position it would be fantastic.

![screen shot 2017-07-23 at 11 15 10](https://user-images.githubusercontent.com/6619631/28498581-a5366d3e-6f98-11e7-9ef9-47e332bffac7.png)

**Comment by equinusocio** [comment]
This is not possible. ST doesn't offer a way to do it.
