### ISSUE TITLE
Hover / Active colour overlay does not cover whole element

### ISSUE THREAD

**Issue by Nachtalb** [equinusocio/material-theme#1162]
### Summary

Hover / Active overlay does not cover the whole element even though it should
![image](https://user-images.githubusercontent.com/9467802/28559930-de5e51a4-7118-11e7-875f-5296456cce37.png)

### Expected behavior

Rounded hover / active overlay over whole element

### Actual behavior

Small round hover / active effect which does not cover the whole text

### Steps to reproduce

1. Installing latest update
2. Open find in path
3. Hover over or click on a search location

### Environment

* Operating system and version:
  * [ ] Windows: Don't know
  * [x] Mac OS: 10.12.6 (16G29) - MacBook Pro (Retina, 15-inch, Early 2013)
  * [ ] Linux: Don't know
* PyCharm 2017.2:
```
Build #PY-172.3317.86, built on July 19, 2017
Licensed to Nick E
Subscription is active until October 15, 2017
For educational use only.
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
* Material Theme release:
  * v0.7.0.1

**Comment by equinusocio** [comment]
https://github.com/ChrisRM/material-theme-jetbrains
