### ISSUE TITLE
bold font in phpStorm 2017.2

### ISSUE THREAD

**Issue by mahdiborjian** [equinusocio/material-theme#1165]
### Summary

Fonts of every element, menu, panel, etc. goes **BOLD** by updating php storm to new version.

### Environment

* Operating system and version:
  * Windows 10
* Php Storm 2017.2
* Material Theme release:
  * v 0.5.3

**Comment by equinusocio** [comment]
https://github.com/ChrisRM/material-theme-jetbrains
