### ISSUE TITLE
Even Darker Theme

### ISSUE THREAD

**Issue by Dane456** [equinusocio/material-theme#1169]
I am inches close to changing all the settings and pngs needed to get the #212121 background to #111111, but cannot find where to change the background color for the search text fields (ctrl-p, ctrl-f, etc). Can you help point me in the right direction?

I'd be happy to submit a PR as well if you're interested in expanding the portfolio of themes to add another, however all i have are the changed files, I have yet to figure out how to hook it up to the ui configuration you created, I just branched off the Darker.tmtheme as well as the Darker.sublime-theme of yours and swapped it into my user package control.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/search?utf8=%E2%9C%93&q=darker%2Finput&type=
