### ISSUE TITLE
Not all fields of "Find in Files..." are fully visible

### ISSUE THREAD

**Issue by uzyn** [equinusocio/material-theme#117]
![screen shot 2015-06-16 at 1 52 20 pm](https://cloud.githubusercontent.com/assets/280505/8176605/2326f6d6-142f-11e5-8cf5-4ef6986b5063.png)

Only 1.5 of the 3 fields are visible.

"Find in Files..." is accessible from Find > Find in Files... or the default keyboard shortcut ⇧⌘F on Mac

**Comment by msankhala** [comment]
Yes i have the same issue.

**Comment by equinusocio** [comment]
Please see #67 and read the Readme "....first search a similar issue"
