### ISSUE TITLE
Uppercase in tabs setting not being saved

### ISSUE THREAD

**Issue by sidner** [equinusocio/material-theme#1174]
### Summary
When changing "Toggle uppercase tabs" from active to not active, when I close the IDE and reopen it, the tabs are again in uppercase and the option is active. The setting is not being saved between "sessions".
...

### Expected behavior
When I reopen IntelliJ, I want the tabs to not be in uppercase.
...

### Actual behavior
Tabs are back in uppercase when I reopen IntelliJ
...

### Steps to reproduce

1. First step
Untick "Toggle uppercase tabs" option
2. Second step
Close IntelliJ
3. Third step
Re-Open IntelliJ and see that tabs are back in uppercase.

### Environment

* Operating system and version:
  * Linux Mint 17.3
* Material Theme release:
  * 0.9.0

**Comment by equinusocio** [comment]
You should report this issue here: https://github.com/ChrisRM/material-theme-jetbrains
