### ISSUE TITLE
Sublime Material Icon Pack

### ISSUE THREAD

**Issue by halacoglu** [equinusocio/material-theme#1177]
Hello. I created an icon pack for the Material Theme. You can download it here:

[Sublime Material Icon Pack](https://github.com/halacoglu/sublime-material-icon-pack)

![Sublime Material Icon Pack](https://camo.githubusercontent.com/340f76ef9fd742f95da5a6516b51346cdd64f771/687474703a2f2f692e696d6775722e636f6d2f504b53525473352e706e67)

**Comment by mallowigi** [comment]
Hi, can I use this as well?

**Comment by halacoglu** [comment]
Sure, it is free for personal use. Added the PNG's.

**Comment by mallowigi** [comment]
It's not for personal use. I want to use it for https://github.com/mallowigi/material-theme-jetbrains-eap

**Comment by halacoglu** [comment]
As long as non-commercial, why not.

**Comment by equinusocio** [comment]
@mallowigi You use the Sublime logo on JetBrains? 😲

**Comment by mallowigi** [comment]
It's not the Sublime Logo, it's a well designed logo that is better than the boring droplet :)

**Comment by equinusocio** [comment]
But this is the new sublime text app icon :)

**Comment by mallowigi** [comment]
How? 

https://www.sublimetext.com/blog/ 

I don't see anything looking like the OP's icon... 

Agreed it is one of the designs of the icon but whatever :)

**Comment by ihodev** [comment]
@mallowigi This is new ST icon, to see it install dev version or wait next stable ST3 version (latest forum messages hint that it will be available soon).

https://www.sublimetext.com/3dev

```
Build 3127
Release Date: 12 April 2017
Refreshed UI theme, including full high DPI support
New icon
```

**Comment by mallowigi** [comment]
Didn't know that. Well never mind I like the icons.

**Comment by equinusocio** [comment]
Added to the readme.
