### ISSUE TITLE
The green explorer tab

### ISSUE THREAD

**Issue by iamslimane** [equinusocio/material-theme#1178]
### The question:
> How to disable this _**green explorer tab**_ in sublime text 3 / material theme ?
>  Can i disable it ?

### Operating system and version:
> Windows 10

### Sublime Text:
> Build 3

### Material Theme release:
> v4.0.10

![sublime-material_theme-issue](https://user-images.githubusercontent.com/31626673/30034404-6abac922-91a1-11e7-962e-9126d34360c6.JPG)

**Comment by equinusocio** [comment]
Just remove Material Theme Appbar package you installed.

**Comment by iamslimane** [comment]
> How can i remove it ?
> Please give me the steps ?
>**Thanks**

**Comment by equinusocio** [comment]
https://packagecontrol.io/docs/usage

>Package Control is driven by the Command Palette. To open the palette, press ctrl+shift+p (Win, Linux) or cmd+shift+p (OS X). All Package Control commands begin with Package Control:, so start by typing Package.
> The command palette will now show a number of commands. 

Then search for `Remove package`

**Comment by iamslimane** [comment]
> **thank you !**
