### ISSUE TITLE
VS Code Theme

### ISSUE THREAD

**Issue by designMoreWeb** [equinusocio/material-theme#1179]
So i use VS code for both Windows and Mac. On the mac the darker theme colors work for this theme. However for windows it doesn't. It remains at the default theme color. 

Please help me out.

Using windows 10

**Comment by equinusocio** [comment]
Hi @designMoreWeb, next time use the vsc relative repository https://github.com/equinusocio/vsc-material-theme.

I just updated the README file. Before change the theme variant you need to activate the theme like other vsc themes. Launch the `Preferences: Color theme` command and select Material Theme, then you will able to change the theme variant.
