### ISSUE TITLE
Error loading colour scheme Packages/Material Theme/widgets/default/Widget

### ISSUE THREAD

**Issue by huglester** [equinusocio/material-theme#118]
Hello,

now I get

```bash
Error loading colour scheme Packages/Material Theme/widgets/default/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/default/Widget - Material-Theme.stTheme
```

And folders I see are like this: http://pic.webas.lt/webas.lt-0be5bba81b.png

It mainy happened after git pull... Any idea what I could be doign wrong?

**Comment by equinusocio** [comment]
What branch you pulled? You've renamed the folder as it says in the README file? You've pasted the folder in the right Package folder? **(Preferences > Browse Packages...)**

**Comment by huglester** [comment]
Sorry, did not see that install instructions did change.

Thanks!

**Comment by Mrhjx2** [comment]
i hava a same wrong"Error loading colour scheme Packages/Material Theme/widgets/default/Widget - Material-Theme.stTheme: Unable to open Packages/Material Theme/widgets/default/Widget - Material-Theme.stTheme"

**Comment by mirzavu** [comment]
Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme

Facing same issue in Sublime text 3

**Comment by equinusocio** [comment]
I really can't help you. This type of issues are related to the Package Control plugin and i can't help about that. I can suggest to search for a similar closed issue and completely purge/reinstall the theme, both through Package Control and manually.

**Comment by mirzavu** [comment]
The manual installation worked given here 
[Material Theme](https://github.com/equinusocio/material-theme)

**Comment by sunlee-newyork** [comment]
Manual install worked for me!
