### ISSUE TITLE
ST3 Build 3143 breaks active tab underline 

### ISSUE THREAD

**Issue by anchnk** [equinusocio/material-theme#1180]
### Summary

ST3 build 3143 breaks UI on my machine. Active tabs underline isn't matching the accent color used in preferences. That's the only quirk I have been able to spot migrating from 3126 to 3143.

### Config

Here's my current configuration, which didn't change between the 2 releases:

```
{
	"color_scheme": "Packages/User/SublimeLinter/Dracula (SL).tmTheme",
	"dpi_scale": 1.0,
	"drag_text": false,
	"font_face": "SauceCodePro Nerd Font",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"material_theme_accent_cyan": true,
	"material_theme_accent_scrollbars": true,
	"material_theme_appbar_charcoal": true,
	"material_theme_arrow_folders": true,
	"material_theme_bright_scrollbars": true,
	"material_theme_bullet_tree_indicator": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"overlay_scroll_bars": "enabled",
	"show_encoding": true,
	"sidebar_row_padding_medium": true,
	"sidebar_size_13": true,
	"tab_size": 2,
	"tabs_label_not_italic": true,
	"tabs_medium": false,
	"tabs_small": false,
	"theme": "Material-Theme-Palenight.sublime-theme",
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
```

### Expected behavior

![st3-material-build-3126](https://user-images.githubusercontent.com/515506/30381841-dcaef6b8-989d-11e7-80f8-d86abee57d25.png)

### Actual behavior

![st3-material-build-3143](https://user-images.githubusercontent.com/515506/30381851-e242b042-989d-11e7-82e1-7f6c9e8cb993.png)

### Steps to reproduce

1. Upgrade from 3126 to 3143
2. Restart ST3

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [x] Linux (Ubuntu 16.04 LTS)
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.0.10

**Comment by equinusocio** [comment]
Are you on a @3x pixel density device?

**Comment by anchnk** [comment]
I don't think so but I not really sure. My monitor is a LenovoThinkVision E232.

**Comment by equinusocio** [comment]
@anchnk try here:
http://dpi.lv/

**Comment by anchnk** [comment]
1. http://dpi.lv: **166 pixels per inch**
2. https://www.infobyip.com/detectmonitordpi.php: **Your monitor DPI: 96 x 96**

**Comment by equinusocio** [comment]
mm so you are on a @1x device and this is strange because this kind of issues occurs when ST load an asset with a different/lower resolution than your monitor. At the moment Material Theme provide assets for @1x and @2x.

**Comment by alanstratos** [comment]
The same thing is happening for me as well on 148 pixels per inch and 96 x 96 according to those websites.

**Comment by equinusocio** [comment]
Hi, here the release note from the dev channel:
<img width="768" alt="screen shot 2017-09-15 at 09 23 42" src="https://user-images.githubusercontent.com/10454741/30471111-bd29d4d8-99f7-11e7-9eab-4a74d3dfde90.png">

I thinks this issue can be related to the first fix

**Comment by anchnk** [comment]
I tried it but no luck, same issue

**Comment by shawjak3** [comment]
I am also experiencing this behavior since the release of Sublime Text 3 earlier this week.

**Comment by dotKev** [comment]
I have the same issue, but I end up with two different tab styles on the same screen.
![st-material-tab](https://user-images.githubusercontent.com/1915812/30654737-66a50474-9df4-11e7-8c1d-f19b09811fbe.gif)
- 96x96 dpi
- 221 ppi
- Mac OS Sierra
- Sublime Text:   3143
- Platform:   osx
- Arch:   x64
- Theme:   4.0.10
- Install via PC:   True
- Dependencies:
    * mdpopups:   2.1.1
    * markdown:   2.6.9
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by anchnk** [comment]
Is the referenced commit fixing the issue ? Has it been shipped yet ? I did upgrade my packages today but I still have the issue even though ST3 told me it updated the theme

**Comment by equinusocio** [comment]
Sorry wrong reference

**Comment by equinusocio** [comment]
This theme is now deprecated and no more under active development. I'm open to proposals and PR's. If someone want to collaborate and rewrite this theme let me know. For now, consider switching to a not-obsolete editor like Visual Studio Code with [Material Theme](https://github.com/equinusocio/vsc-material-theme)
