### ISSUE TITLE
Grey Bar in MacOS full screen mode on macOS/ST3.0

### ISSUE THREAD

**Issue by ajoy39** [equinusocio/material-theme#1181]
### Summary

When entering the MacOS full screen mode with ST3.0 I have a gray bar on the bottom of my row, roughly the same height as the MacOS Menu bar, along the bottom of my window. If, while already in fullscreen mode, you open a new window it fill the while screen, but if you toggle out of and back into full screen mode with that window it will have the gray bar again. 

Disabling the Material Theme resolves this bug

### Expected behavior

ST3 takes up the full vertical height of my monitor

### Actual behavior

The aforementioned gray bar, screenshot below

![Gray Bar](https://i.imgur.com/b6YsxYe.png)

### Steps to reproduce

1. Make a window fullscreen 

### Environment

* Operating system and version:
  * Mac OS High Sierra Beta build 17A360a
* Monitor:
  * Resolution 1920x1080
  * `dpi_scale` used in ST ...
* Sublime Text:
  * Build 3143 
  * 64 bit
  * Material Theme v 4.0.10

I have been able to confirm this bug does not happen on MacOS 10.12, at least on a fresh install of ST3. It also wasn't happening on build 3126 of Sublime Text on MacOS 10.13 Build 17A360a (the beta version I'm currently running) So You need, at a minimum, all 3 pieces to reproduce of ST3.0, MacOS High Sierra beta, and the Material Theme.

**Comment by equinusocio** [comment]
Please add some screenshots.

**Comment by ajoy39** [comment]
@equinusocio Sorry about that, there was supposed to be one in the middle there but I always mess up the image syntax in markdown. Fixed it now.

**Comment by equinusocio** [comment]
I can't replicate this issue on my mac:
<img width="1440" alt="screen shot 2017-09-13 at 17 02 00" src="https://user-images.githubusercontent.com/10454741/30384797-8f40f3ba-98a5-11e7-99ad-5375434aee43.png">

**Comment by ajoy39** [comment]
Are you running the MacOS High Sierra beta? I had a friend on Mac OS Sierra try to replicate the issue and he couldn't, I'm on High Sierra build 17A360a.

**Comment by equinusocio** [comment]
Yes, I'm on Mac OS Sierra. At the moment i cant fix an issue that could be caused by mac os beta. If after the official release this issue will persist i can try to fix it.

**Comment by ajoy39** [comment]
I actually decided to try doing a fresh installed of sublime text and re-add all the packages I usually use, including the material theme, and I'm not longer having this issue. I'm not sure why disabling the material theme is what "fixed" it before but I no longer believe this issue lies with the material theme itself.
