### ISSUE TITLE
Poor contrast on the macOS title bar with ST build 3143

### ISSUE THREAD

**Issue by alekseyg** [equinusocio/material-theme#1182]
### Summary

It's a minor issue, but it had me confused for a second when I updated my Sublime Text. With the shiny new stable release (build 3143) of Sublime Text 3 and its custom macOS title bar, the contrast between the bar and the title is rather low when using the Material Theme, giving off the impression as though the window were in the background rather than the foreground.

### Expected behavior

More contrast between the title text and title bar colors, especially if the window is currently focused.

### Actual behavior

Rather low contrast between title text and title bar colors, resulting in the impression of an unfocused window.

### Steps to reproduce

1. Open Sublime Text
2. Use Material Theme

### Environment

* Operating system and version:
  * macOS 10.12.6 Sierra
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.0.10

![screen shot 2017-09-13 at 3 50 20 pm](https://user-images.githubusercontent.com/68075/30404757-efd9700c-989c-11e7-9514-9864ea73474c.png)

**Comment by equinusocio** [comment]
Hi @alekseyg. This is a issue subjective. Many people want different colors for every part of the ui. I can't make all happy. What is low-contrasted for you can be high-contrasted for others. You can customise your local theme installation and fix colors just for you :)

**Comment by alekseyg** [comment]
For the record, before Sublime changed to the custom title bar, it used the native macOS title bar, which uses very high contrast for active windows and lower contrast (but not lower than the image in my original ticket) for inactive windows. Demonstrated below with iTerm:

![screen shot 2017-09-15 at 9 47 25 am](https://user-images.githubusercontent.com/68075/30494183-f1d22308-99fb-11e7-9306-a7a484bdba92.png)
![screen shot 2017-09-15 at 9 47 32 am](https://user-images.githubusercontent.com/68075/30494184-f1e9df8e-99fb-11e7-9a4d-995579af92b2.png)

Also, here's a screenshot of the same window as in the original ticket, but using Sublime's adaptive theme:

![screen shot 2017-09-15 at 9 48 04 am](https://user-images.githubusercontent.com/68075/30494230-23fe5c02-99fc-11e7-9b74-90afa1fc74c8.png)

Granted, there is no difference in the color when the window is active or inactive, which would lead me to believe it's more of an issue with Sublime Text rather than just the theme.

As for being subjective, I suppose you can say that, but the macOS system is designed to create a subjective feeling of difference between an active window and an inactive one. Again, this isn't a deal breaker for me, but I was confused when I first upgraded and couldn't figure out why the window wouldn't come into focus when I clicked it several times until I looked at the smaller visual cues of the title bar buttons and the current file icon and realized it was active. It's just that this particular aspect of macOS is so ingrained at this point, so subjective or not, the cognitive load here is definitely more than zero when compared to other apps which work the macOS way in this regard; it's a bit of a special case you have to keep in mind.

Speaking of the icon for the currently open file, the high contrast between it and the title bar vs the low contrast between the text and the title bar is also a bit jarring (though I'll admit, this is probably the most subjective thing so far):

![screen shot 2017-09-15 at 10 00 04 am](https://user-images.githubusercontent.com/68075/30494584-9ff968fa-99fd-11e7-8fed-138c9cac62d5.png)

All that said, I still think this is an issue, albeit a small one. I'm just a perfectionist and I doubt I'm the only one who will notice not just in subjective aesthetics here, but more importantly, the discrepancy in  active vs inactive window visual cues with this theme and Sublime Text 3.0 in general vs the rest of macOS. Sorry for the long rant. I still love this theme and will stick to it, but I just wanted to explain my reasoning. Keep up the great work!
