### ISSUE TITLE
Cannot install Material Theme on latest release of Sublime 

### ISSUE THREAD

**Issue by Gunny123** [equinusocio/material-theme#1184]
### Summary

Cannot activate package on Sublime Text's latest release... 

I may be missing something easy, sorry for the issue in advance if it's a simple thing I am overlooking.

### Expected behavior

Successful activation

### Actual behavior

Cannot activate

### Steps to reproduce

1. Install via package control
2. Attempt to activate in preferences
3. [Activate theme gives a grey out option](https://i.imgur.com/0EMS4UY.png)

### Attempted manual workaround

I downloaded the latest release and followed instructions on your readme.md and moved it to the correct directory. When I went to activate the theme it would not allow me to do so under preferences. 

### Environment

* Operating system and version:
  * [x] Windows 10 CU
  * [ ] Mac OS 
  * [ ] Linux
* Sublime Text:
  * Version 3.0 (latest release)
* Material Theme release:
  * v4.0.10

**Comment by mallowigi** [comment]
There were a lot of issues from people trying to update to build 3143, me as well. I had to delete my Sublime folder and reinstall everything from scratch.

**Comment by Gunny123** [comment]
Great 😅. I’ll just do a complete uninstall and reinstall then.

**Comment by equinusocio** [comment]
@Gunny123 let me know if you fix this issue

**Comment by Gunny123** [comment]
@equinusocio You'll be the first to know. I'll update this comment appropriately.

**Comment by Gunny123** [comment]
Sorry misclick on the close issue button. 

So I uninstalled Sublime Text 3 and deleted the folder then restarted on my PC. I reinstalled ST3 and installed through package control and still could not get it to go. I do not know what else I can do tbh.

**Comment by mallowigi** [comment]
Use command palette, write Material Theme Config, then Theme, then Default

**Comment by mallowigi** [comment]
If it works, please close this issue.
