### ISSUE TITLE
High CPU Usage Possibly Related to Material Theme

### ISSUE THREAD

**Issue by mattcdavis1** [equinusocio/material-theme#1185]
### Summary
There seems to be a CPU issue with Material Theme + Sublime Text 3 + Some other condition.  I noticed this issue a good number of builds back.  I think it started occurring sometime after ST build 3103.  
...

### Expected behavior
CPU usage same as with other themes or default theme
...

### Actual behavior
CPU climbs to 10, 20% and doesn't come back down at all or doesn't come back down to the same level as with other themes or default theme.  
...

### Steps to reproduce

I'm not 100% sure that this is a Material theme issue or how to reliably reproduce but it does seem like the CPU issues i was experiencing have gone away since switching to a different theme.  I just made this change about 30 minutes ago so will report back if this changes.  For now, though, it seems Material Theme was the reason for my high CPU usage.

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS 10.12.6
  * [ ] Linux ...
* Sublime Text:
  * Build 3143
* Material Theme release:
  * 4.0.10

**Comment by equinusocio** [comment]
#1128
