### ISSUE TITLE
Accent Scrollbars not working for my configs

### ISSUE THREAD

**Issue by stephen-silveira** [equinusocio/material-theme#1188]
### Summary
I'm trying to have the `material_theme_accent_scrollbars` to work.
Have already disabled (`overlay_scroll_bars`) and tried everything in issue #1023 and  #147

### Expected behavior

When I see the scrollbars, to have them highlighted.

### Actual behavior

My scrollbars stay just as 'normal':

![image](https://user-images.githubusercontent.com/16563148/30560359-102717c0-9c8e-11e7-9128-1257e42ec34a.png)

*my accent is blue (tried with another accents)

### Steps to reproduce

Open any file, my Sublime Text have Material Theme Enabled.

### Environment

Here's my personal config
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"ignored_words":
	[
		"php"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 10,
	"line_padding_top": 1,
	"material_theme_accent_blue": true,
	"material_theme_big_fileicons": true,
	"material_theme_bold_tab": true,
	"material_theme_bullet_tree_indicator": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "disabled",
	"tab_size": 2,
	"theme": "Material-Theme.sublime-theme",
	"material_theme_bright_scrollbars": true,
	"material_theme_accent_scrollbars": true,
}
```

I don't know if any other packages may be causing this or I'm misconfiguring something, let me know if I need to send any more information.

- Windows 10 Home Single Language 1607
-   Sublime Text Build 3 - 3143
-   Material Theme release v4.0.10

*If I do a new fresh install of ST, it works on another PC's. Haven't tried to reinstall(ST) in my current pc (Have tried to reinstall Material Theme and did not work)

**Comment by mallowigi** [comment]
The scrollbars have been broken for a long time.

**Comment by stephen-silveira** [comment]
When I install in a new PC or new Sublime Text it works, does the scrollbar breaks when interacting with another packages ?

**Comment by mallowigi** [comment]
I've found out that using bright scrollbars with accent scrollbars cancel out the accent scrollbars.

So it did work 😮

**Comment by mallowigi** [comment]
@stephen-silveira can you close this?

**Comment by stephen-silveira** [comment]
Wow. That's great! And It works. Thank you @mallowigi and @equinusocio for your support!!!
