### ISSUE TITLE
Sublime text 3 maximize window not working

### ISSUE THREAD

**Issue by cili93** [equinusocio/material-theme#1189]
After upgrading to 3143 Sublime Text it's no longer possible to maximize the window using `double click` or `Shift + double click` on Sublime text header. It works on default Sublime theme and on all the other applications

#sublimetext #maximize #double #click #material

* Operating system and version:
  * [ ] Mac OS 10.11.6
* Sublime Text:
  * Build 3143
* Material Theme release:
  * 4.0.10

**Comment by equinusocio** [comment]
Report this to the sublime text forum. This issue occur when theme style the native title bar

**Comment by cili93** [comment]
Will do, tnx
