### ISSUE TITLE
Help in designing an icon for the Material Theme for Jetbrains

### ISSUE THREAD

**Issue by mallowigi** [equinusocio/material-theme#1191]
This is not a bug but rather a request for the designers out there.

I'm currently in charge for the Jetbrains' Material Theme plugin based on this one, and I'm currently writing a documentation, but I lack a proper icon. As someone pointed out, the icon used here is relevant to Sublime Text (obviously).

So if someone is interested in helping me, I'd appreciate. Including you, @equinusocio :)

**Comment by equinusocio** [comment]
@Consider that Material Theme for sublime text is not under active development cause Sublime Text is now an obsolete software with lack of features compared to other editors.

There is a lot of issues with this software and maintaining this theme is not more affordable for me. Please follow the [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) for visual studio for more updates.

About the logo, check this sketch file:
[jetbrains.zip](https://github.com/equinusocio/material-theme/files/1326682/jetbrains.zip)

**Comment by mallowigi** [comment]
okay thanks ! I think I will start from this
