### ISSUE TITLE
Need instructions for configuring syntax colors

### ISSUE THREAD

**Issue by BoltzmannBrain** [equinusocio/material-theme#1195]
Issue: I'm using the dark theme on Ubuntu 16.04, where code comments are a light grey against a grey background. I would like to change the comments color to be more readable (something like a faded green), but it is not clear how to do so -- I do not see the .tmTheme xml file as with other color scheme packages.

Request: Please document in the README how we can manually change lower-level specifics, e.g. syntax colors.

**Comment by mallowigi** [comment]
They are in the schemes directory

**Comment by BoltzmannBrain** [comment]
And where is the schemes dir?

**Comment by mallowigi** [comment]
How do you modify other themes?

**Comment by BoltzmannBrain** [comment]
Okay I found it: Package Manager --> PackageResourceViewer: Open Resource --> Material Theme --> /schemes
Thank you :)
