### ISSUE TITLE
[Question] Running from User directory?

### ISSUE THREAD

**Issue by snwflake** [equinusocio/material-theme#1199]
### Summary
Wanted to copy the theme to my `Packages/User` dir, since I want to include it in my dotfiles repo and customized  the theme to my needs
...

### Expected behavior
Runs properly with the following settings pair:
```json
{
    "theme": "Packages/User/Material Theme/Material-Theme-Darker.sublime-theme"
}
```
...

### Actual behavior
Theme doesn't load. Neither the edited one, nor the defaults.
...

### Steps to reproduce

1. extract package content with `package resource viewer`
2. edit to my liking and shove into the User dir
3. edit config key, save and restart ST3

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS Sierra 10.12.6
  * [ ] Linux ...
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.0.10

I would be happy to provide anything that could help :)

**Comment by equinusocio** [comment]
Hi report this issue to the sublime forum.
