### ISSUE TITLE
UI issue for collapsed JSON blocks

### ISSUE THREAD

**Issue by Kureev** [equinusocio/material-theme#120]
Hi all!
After installation got this issue when collapsing JSON block:
![image](https://cloud.githubusercontent.com/assets/2273613/8178827/1715c51a-1412-11e5-8aef-c3cec0ecfdb1.png)

Any ideas how to fix it?

**Comment by equinusocio** [comment]
You restarded Sublime ?

**Comment by Kureev** [comment]
Sure, few times. Here it is my config:
```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/User/SublimeLinter/Material-Theme (SL).tmTheme",
	"ensure_newline_at_eof_on_save": true,
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 13,
	"highlight_line": true,
	"ignored_packages":
	[
		"RestructuredText",
		"JSHint Gutter",
		"Vintage",
		"AngularJS",
		"Theme - Default",
		"Seti_UI",
		"Oceanic Next Color Scheme",
		"Color Scheme - Default",
		"Color Scheme - Frontend Delight",
		"Textile",
		"TCL"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"overlay_scroll_bars": "enabled",
	"tab_size": 2,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true
}
```

**Comment by equinusocio** [comment]
This happen only in json file?

**Comment by Kureev** [comment]
Nope, it seems for every collapsed block (checked only in JS and JSON). Maybe, it's because before I had a Seti theme, but I've removed their package and installed yours.

**Comment by equinusocio** [comment]
Try to disable Sublime Linter and reapply the theme (theme and color_scheme) preferences

**Comment by Kureev** [comment]
Hm, doesn't work. It may be that I f*cked up my Sublime with a lot of different plugins, let me try to clean it up and come back with a feedback :)

**Comment by equinusocio** [comment]
ok. Let me know.

**Comment by equinusocio** [comment]
I can test this, this issue doesn't appear on my ST.

**Comment by Kureev** [comment]
Ok, I found an issue. It occurs when you disable standard theme (Theme - Default). Seems material-theme package doesn't include custom icon for collapsed state for code blocks.

**Comment by equinusocio** [comment]
Yes, it's included.
https://github.com/equinusocio/material-theme/blob/master/assets/commons/fold.png

**Comment by Kureev** [comment]
That's strange: if I disable default theme - I have an issue I've mentioned before, otherwise - it's fine. Maybe it's good to keep in mind.

**Comment by equinusocio** [comment]
Ok, if i disable the Default theme i see the same issue. I will check, thanks

**Comment by Kureev** [comment]
Glad I could help. Thanks for the theme, it's awesome :+1:

**Comment by equinusocio** [comment]
This doesn't occur on my macbook, even disabling the default theme...

**Comment by Kureev** [comment]
Strange, on my Mac it does. I don't think it's major issue, but I'd like to figure out why :)

**Comment by equinusocio** [comment]
me too..

**Comment by equinusocio** [comment]
@Kureev i've tried with other themes and this happen when we disable the Default - Theme. I thinks is a sublime text bug. For now keep the default theme enabled :+1:
