### ISSUE TITLE
Add visible separator between explorer and extensions panes?

### ISSUE THREAD

**Issue by fredrikaverpil** [equinusocio/material-theme#1200]
I'm adding a visible separator line to more clearly show the border of explorer/code/terminal, which makes it easier for me to grab these handles and resize the panes:

```javascript
{
    "workbench.colorCustomizations": {
        "panel.border": "#1d262a",
        "sideBar.border": "#1d262a"
    }
}
```

Do you know if it also is possible to add such a separators between the explorer and extension panes?
I went to the [vscode theme color reference docs](https://code.visualstudio.com/docs/getstarted/theme-color-reference) but I can't figure out if this is at all possible at this time.

![screen shot 2017-10-18 at 11 20 47](https://user-images.githubusercontent.com/994357/31711128-757bc32a-b3f7-11e7-8032-e1fe9e127f05.png)

Again, thanks so much for your incredible work on this theme. I work with it full time all week long. ❤️

**Comment by Zx-EvM** [comment]
This repository for Sublime Text Material Theme not for VSCode. You can reopen this issue in https://github.com/equinusocio/vsc-material-theme

**Comment by fredrikaverpil** [comment]
Oops!
