### ISSUE TITLE
Color Schemes Missing

### ISSUE THREAD

**Issue by mdgmichael** [equinusocio/material-theme#1201]
### Summary

It looks like the default color schemes were accidentally removed in a recent commit: ddc77039422b8b3acc1bd3f8c2603c17aa3f46d4 A similar issue occurred during a previous release earlier this year: #1150

### Expected behavior

The `Material Theme/schemes` folder should be present, containing the four default color scheme files.

### Actual behavior

The "schemes" folder is missing.
https://github.com/equinusocio/material-theme/tree/master

**Comment by daliborgogic** [comment]
From console `error: Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme`

**Comment by Ekown** [comment]
why did this happen again? let's just wait for another commit.

**Comment by equinusocio** [comment]
Patch released.

**Comment by nickhstr** [comment]
Thanks for the patch, @equinusocio!
However, it looks like the title bar (on macOS) has reverted to the old default style (gray), rather than using a colored one.

**Comment by rgwsk65** [comment]
Hmm I can't update to the version with color schemes included

**Comment by equinusocio** [comment]
@nickhstr Check the changelog https://github.com/equinusocio/material-theme/releases/tag/v4.1.0

**Comment by nickhstr** [comment]
Ah, ok that's a fair trade-off.

**Comment by rgwsk65** [comment]
Is there a way to force Package Control to update this package?

**Comment by maloneya** [comment]
@rgwsk65 manually dropping the folder in you package dir does the trick. 

@equinusocio any way we could make the themed title bar an option? never had any cpu issues for me

**Comment by rgwsk65** [comment]
@maloneya Thanks, it's working now, I can painless continue my work :)

**Comment by Pavelas** [comment]
Hello guys,

A few minutes ago I had exactly the same problem with Sublime Text 3.

**Solution:**

- Remove Material theme

- Install Material theme

- Update your config file, "color_scheme" property to:
`"color_scheme": "Packages/User/Color Highlighter/themes/Material-Theme.tmTheme",`

Old property (does not work personally for me):
`"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",`

**Comment by diego898** [comment]
@Pavelas hm I tried that and it still doesnt work for me

**Comment by Pavelas** [comment]
@diego898 I am sorry, forgot to mention that personally for me, this problem was caused by Color Highlighter package conflict with Material theme package.

Try solution above, download the whole folder and drop it to your packages directory.

**Comment by Anthodpnt** [comment]
Hi @equinusocio,

Juste remove and reinstall the Material Theme on ST 3 and the issue persists...

<img width="532" alt="screen shot 2017-10-19 at 23 15 23" src="https://user-images.githubusercontent.com/6245705/31794697-763347e8-b523-11e7-830b-edba73ea50be.png">

**Comment by Anthodpnt** [comment]
Problem solved on my side with the release #4.1.1.
Thanks @equinusocio
