### ISSUE TITLE
Title Bar color is broken 

### ISSUE THREAD

**Issue by philipamour** [equinusocio/material-theme#1202]
Material Theme just autoupdated and broke the dark Title Bar that was introduced in latest Sublime Text release - now is default white and doesn't blend in with the text editor.

**Comment by philipamour** [comment]
<img width="1213" alt="screen shot 2017-10-20 at 11 19 38 am" src="https://user-images.githubusercontent.com/4676105/31816522-923996c6-b588-11e7-88bd-ee341de14120.png">
-- used to be same color as the material theme background color

**Comment by equinusocio** [comment]
Read the changelog please.

**Comment by philipamour** [comment]
@equinusocio after some digging (wish your changelog was easier to find), I have found a mention about high CPU usage; however, I have not experienced that myself and can't find it mentioned anywhere in any of the issues that the latest commit mentioned. 🤷🏻‍♂️

**Comment by nusu** [comment]
It bothers me as well, please describe how we fix this, it become so ugly now

**Comment by nusu** [comment]
@philipamour It bothered me as well, I deleted the last version and installed (v4.0.10)[https://github.com/equinusocio/material-theme/releases/tag/v4.0.10] manually

**Comment by pzduniak** [comment]
Maybe we could get this back as an option?

**Comment by equinusocio** [comment]
PR are welcome
