### ISSUE TITLE
Can't change title bar to material theme

### ISSUE THREAD

**Issue by abovethecloud** [equinusocio/material-theme#1205]
### Summary

Can't change the title bar to material theme. It remains the macOS default.
I tried to manually set the "material_theme_titlebar": true option.

### Expected behavior

The title bar should change to material theme. 

### Actual behavior

This version it doesn't.

### Steps to reproduce

1. Use macOS, version 10.13 (17A405)
2. Install latest version of material-theme on sublime text 3 (tried both automatically and manually)
3. Try to set the "material_theme_titlebar": true option
4. Restart Sublime

### Environment

* Operating system and version:
  * [ ] macOS 10.13 (17A405)
* Sublime Text:
  * Build 3143
* Material Theme release:
  * commit: 8cb4a43959461e1d410dd27a05cc1b818c048b77

**Comment by abovethecloud** [comment]
Can you explain why you closed the issue? Did I compile it wrong?

**Comment by equinusocio** [comment]
There is a closed issue for that. 

https://github.com/equinusocio/material-theme/issues/1202

We made a fix and will be activable with a setting. Check this PR

https://github.com/equinusocio/material-theme/pull/1204

**Comment by abovethecloud** [comment]
Thank you. I searched, but was unable to find it.
So you are going to include the fix in a future version?

**Comment by equinusocio** [comment]
Yes. We will release a patch next days.
