### ISSUE TITLE
Latex math preview problem with material theme color scheme

### ISSUE THREAD

**Issue by guoyiteng** [equinusocio/material-theme#1209]
### Summary
I wrote latex in sublime using latextool. After the latest update, 4.1.0 or 4.1.1, the math preview is rendered incorrectly. The background color of the math preview is white instead of the background color of the editor. I am not a developer of latextool but I have read several math preview rendering issues in latextool before. It seems that latextool will render the math equation using latex and then convert it to a png image with transparent background. The background color could be set by user. If user leaves it as default, it will use colors in the css of the current theme. I believe this problem might be related to the css file in the latest version. It works fine if I change the color scheme (not the theme) to Monokai or other schemes.

### Expected behavior

With color scheme Monokai
![image](https://user-images.githubusercontent.com/6828666/32023738-32786c84-b9a8-11e7-9a21-b7e85673460a.png)

### Actual behavior

With color scheme material theme darker
![image](https://user-images.githubusercontent.com/6828666/32023756-47c70a5a-b9a8-11e7-8349-2942a6263065.png)

### Steps to reproduce

1. Install latex and latextool
2. Write some math equations in a tex file
3. Move your cursor to the math equation and then you will see the preview math image.

### Environment

* Operating system and version:
  * [mbp late2016 15'] Mac OS high sierra
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.1.1

**Comment by guoyiteng** [comment]
Temporary solutions: Manually change the background color of the math preview in latextool to "#212121" which is the background color of material theme darker.

**Comment by equinusocio** [comment]
@zpreston123 Can you check this? This is the last issue, after this i will block issues on this repo.

**Comment by zpreston123** [comment]
@equinusocio Sure, will see what I can do and let you know what happens.

**Comment by zpreston123** [comment]
Does anyone know a scope to set the background color of the live math preview?

**Comment by guoyiteng** [comment]
"preview_math_background_color": ""

**Comment by zpreston123** [comment]
Unfortunately, I could not find a scope for the live math preview after doing some research.  I tried using "text.tex.latex meta.environment.math.block" and setting the background color to the default scheme background in the scheme YAML file, but no luck. =\

**Comment by guoyiteng** [comment]
I don't know if this is gonna help.
`
def _wrap_html(html_content, color=None, background_color=None):
    if color or background_color:
        style = "<style>"
        style += "body {"
        if color:
            style += "color: {0};".format(color)
        if background_color:
            style += "background-color: {0};".format(background_color)
        style += "}"
        style += "</style>"
    else:
        style = ""
    html_content = (
        '<body id="latextools-preview-math-phantom">'
        '{style}'
        '{html_content}'
        '</body>'
        .format(**locals())
    )
    return html_content
`
I think this part of code might be related to the rendering of math preview in LaTeXTool.

**Comment by zpreston123** [comment]
Thanks that helped a bit.  So I can conclude that both LaTeXTools and this theme use PhantomCSS, which styles the live math preview.  However, this is a bug coming from the scheme files.

@equinusocio I looked at the escape:schemes task, and it seems the &lt; and &gt; encodings at the beginning and end of the PhantomCSS styles are not replaced with < and > respectively when compiled and converted to tmTheme files.  The live math preview will work when you replace those encodings manually.  Hope that makes sense.

**Comment by equinusocio** [comment]
> @equinusocio In the scheme files, it looks like the tag encodings at the beginning and end of the PhantomCSS styles are not replaced with < and > respectively when compiled and converted to tmTheme files. The live math preview will work when you replace those encodings manually. Hope that makes sense.
@zpreston123 Yes, this is the cause.

**Comment by zpreston123** [comment]
@equinusocio I think there's something odd with the gulp "escape:schemes" task.  When you add the tag encodings in the scheme YAML file and run gulp, they're not replaced with < and > in the compiled files.  When you convert those files to .tmTheme, PackageDev parses the YAML but does not convert the encodings to < and > either.  So, you'd have to change them manually in each .tmTheme file.

**Comment by equinusocio** [comment]
@zpreston123 Try to replace this:

```yml 
    html {
      background-color: <%= scheme.background %>;
      color: <%= scheme.foreground %>;
      padding: 16px;
    }
    a {
      color: <%= scheme.base.paleblue %>;
      line-height: 16px;
    }
    .error, .deleted {
      color: <%= scheme.base.red %>;
    }
    .success, .inserted {
      color: <%= scheme.base.green %>;
    }
    .warning, .modified {
      color: <%= scheme.base.yellow %>;
    }
    .type {
      color: <%= scheme.base.cyan %>;
      font-style: italic;
    }
    .param {
      color: <%= scheme.base.orange %>;
    }
    .current {
      text-decoration: underline;
    }
```

whit this

```yml
popupCss: |

    html {
      background-color: <%= scheme.background %>;
      color: <%= scheme.foreground %>;
      padding: 16px;
    }
    a {
      color: <%= scheme.base.paleblue %>;
      line-height: 16px;
    }
    .error, .deleted {
      color: <%= scheme.base.red %>;
    }
    .success, .inserted {
      color: <%= scheme.base.green %>;
    }
    .warning, .modified {
      color: <%= scheme.base.yellow %>;
    }
    .type {
      color: <%= scheme.base.cyan %>;
      font-style: italic;
    }
    .param {
      color: <%= scheme.base.orange %>;
    }
    .current {
      text-decoration: underline;
    }
```

**Comment by zpreston123** [comment]
@equinusocio I added the following setting in the scheme YAML file:

popupCss: '<![CDATA[
      html {
        background-color: <%= scheme.background %>;
        color: <%= scheme.foreground %>;
        padding: 16px;
      }
      a {
        color: <%= scheme.base.paleblue %>;
        line-height: 16px;
      }
      .error, .deleted {
        color: <%= scheme.base.red %>;
      }
      .success, .inserted {
        color: <%= scheme.base.green %>;
      }
      .warning, .modified {
        color: <%= scheme.base.yellow %>;
      }
      .type {
        color: <%= scheme.base.cyan %>;
        font-style: italic;
      }
      .param {
        color: <%= scheme.base.orange %>;
      }
      .current {
        text-decoration: underline;
      }
      ]]>'

Still no luck.  The angle brackets were converted to their encodings after using PackageDev.

**Comment by equinusocio** [comment]
Wait, read again my previous comment :)
The new code doesn't have the brackets. Replace all the popupCss key with this:

```yml
popupCss: |

    html {
      background-color: <%= scheme.background %>;
      color: <%= scheme.foreground %>;
      padding: 16px;
    }
    a {
      color: <%= scheme.base.paleblue %>;
      line-height: 16px;
    }
    .error, .deleted {
      color: <%= scheme.base.red %>;
    }
    .success, .inserted {
      color: <%= scheme.base.green %>;
    }
    .warning, .modified {
      color: <%= scheme.base.yellow %>;
    }
    .type {
      color: <%= scheme.base.cyan %>;
      font-style: italic;
    }
    .param {
      color: <%= scheme.base.orange %>;
    }
    .current {
      text-decoration: underline;
    }
```

**Comment by zpreston123** [comment]
Great, that did the trick!  The live math preview worked as expected!  I noticed this reflected the link fg text colors on the other popups (i.e. configurator, code definitions), but I think it matches well with the theme.  Thank you @equinusocio and @guoyiteng for the help!  Will send a PR with the latest scheme files shortly.
