### ISSUE TITLE
Huge font size in find/replace and console

### ISSUE THREAD

**Issue by limenet** [equinusocio/material-theme#121]
I really love the theme, thanks!

Two things I noticed are the find/replace bar and the console not adjusting their font size to the `font_size` setting (which in my case is font size 9 for Source Code Pro) in `Preferences.sublime-settings`. While the find/replace bar is "usable", the console is just huge and unreadable.

Is there a way to adjust the font size?

Find/replace bar:
![2015-06-16 10_35_00-new issue equinusocio_material-theme](https://cloud.githubusercontent.com/assets/474329/8178982/7419a7a8-1413-11e5-83bb-f68997bf6cf6.png)

Console:
![2015-06-16 10_35_32-new issue equinusocio_material-theme](https://cloud.githubusercontent.com/assets/474329/8178987/7cb72110-1413-11e5-9cd3-50e1e298a9ab.png)

Windows 8.1 x64, Sublime Text 3 Build 3092, 1920x1080 23" monitor (non-retina)

**Comment by equinusocio** [comment]
Pls... before open a new issue search for a similar one. See #103

**Comment by limenet** [comment]
I used the search form first (incl. closed issues) but somehow didn't find it... my bad!
