### ISSUE TITLE
titlebar text fuzzy

### ISSUE THREAD

**Issue by pdfun** [equinusocio/material-theme#1210]
When select Dark theme, titleBar text become fuzzy.
And the lighter theme is ok.
![d829be8b-bfd8-4286-b683-5da60aea08cd](https://user-images.githubusercontent.com/8196592/32411380-121fd5ca-c214-11e7-98ff-ad09945796dc.jpg)

### Environment

* Operating system and version:
  * Mac OS High Sierra 10.13
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.1.2

**Comment by mallowigi** [comment]
#1202 #1121

**Comment by rikiless** [comment]
So this is not fixed if I use `"material_theme_titlebar": true`?
