### ISSUE TITLE
ST3 Build 3154 breaks command palette 

### ISSUE THREAD

**Issue by zaynali53** [equinusocio/material-theme#1212]
### Summary

Sublime text (dev build 3154) introduces a wider command palette which breaks the package style.

### Preview

![capture](https://user-images.githubusercontent.com/8646770/32692522-1093f4b2-c73b-11e7-91fb-50c433cdd9ea.JPG)

### Environment

* Operating system and version:
  * [x] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3154
* Material Theme release:
  * v4.1.2

**Comment by kud** [comment]
Same here on macOS.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/655838/32835755-a437783c-ca07-11e7-94e4-5f3f12c1d1c7.png">

**Comment by equinusocio** [comment]
Please read the readme. This theme is deprecated.

**Comment by equinusocio** [comment]
Fixed in latest builds

**Comment by equinusocio** [comment]
<img width="688" alt="screen shot 2018-02-19 at 22 43 10" src="https://user-images.githubusercontent.com/10454741/36398229-542e39ce-15c6-11e8-8794-98bb4777a71b.png">
