### ISSUE TITLE
Problems with underline in Windows and ST3

### ISSUE THREAD

**Issue by pwsandoval** [equinusocio/material-theme#1213]
The underlining of the active tab is blurred, as indicated in this issue ([#1180](https://github.com/equinusocio/material-theme/issues/1180)), I have the same characteristics.

So, how can I deactivate this underline?

* Operating system and version:
  * [x] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3143.
* Material Theme release:
  * v4.1.2

**Comment by equinusocio** [comment]
This theme is deprecated and not under active development. Please check the readme and consider to switch to a not obsolete editor like Visual Studio Code.
