### ISSUE TITLE
Create lighter icons for symlink folders - current ones are too dark

### ISSUE THREAD

**Issue by sunpietro** [equinusocio/material-theme#122]
![too dark symlink icons](https://cloud.githubusercontent.com/assets/1736658/8179318/27575976-1416-11e5-8cd7-c76b1dfcea4a.png)

I would like to symlink folder icons lighter than current ones. It's very difficult to recognize them correctly on a dark background.

**Comment by equinusocio** [comment]
Thanks man

**Comment by stickyhands** [comment]
+1

**Comment by KrisOlszewski** [comment]
Could you please update terminal (shell) icon as well? It's rather tough to see. Thanks!

![screen shot 2015-06-16 at 11 10 09 am](https://cloud.githubusercontent.com/assets/2780894/8187943/704c97fc-1418-11e5-902a-75d6fa830295.png)
