### ISSUE TITLE
Color display problem

### ISSUE THREAD

**Issue by JunFreeman** [equinusocio/material-theme#1227]
Hello, I found a problem, I updated the Material Theme UI 1.6.1 in the version of Android studio 3.0.1 When I open the Android studio, after the cursor moves to the list of items to scroll the list of items, the list display will be confused , Just like the screenshot below

![uc 20180304000529](https://user-images.githubusercontent.com/14955364/36936415-1d8e0ef2-1f40-11e8-9d58-88cd5fa41d15.png)

* Operating system and version:
  Windows 10

* Material Theme release:
  *1.6.1

**Comment by equinusocio** [comment]
Hi. This repo is for the original material theme for sublime text. We don’t give support for portings
