### ISSUE TITLE
No 'New Folder' dialog

### ISSUE THREAD

**Issue by OliverJEvans** [equinusocio/material-theme#123]
When right clicking in the project folders menu, and selecting 'New Folder' no dialog appears. Although blindly typing the new folder name and pressing the enter key still creates the folder. So the functionality is there, just no dialog.

**Comment by moofyme** [comment]
The dialog appears for me, however it has trouble displaying properly:

![Wrong Offset](https://i.imgur.com/Jo8Nr14.png)

**Comment by limenet** [comment]
Have you tried applying [the fix from #119](https://github.com/equinusocio/material-theme/issues/119#issuecomment-112334303)? While not ideal, it should do the trick.

**Comment by moofyme** [comment]
#119 solves my problem :+1:

**Comment by equinusocio** [comment]
See #67
