### ISSUE TITLE
Blur color in short tab width 

### ISSUE THREAD

**Issue by khaclam** [equinusocio/material-theme#1234]
### Summary

I got a issue when active Material theme (all Color Scheme), on the short tab width, the color under tab is blur like as below:
[![Screenshot from Gyazo](https://gyazo.com/46b645b8205cf968d81945546e97153d/raw)](https://gyazo.com/46b645b8205cf968d81945546e97153d)
Please help me fix it, thanks!

### Environment

* Operating system and version:
  * [ ] Windows
  * [x] Mac OS 10.2.6 (non-retina display)
  * [ ] Linux
* Sublime Text:
  * Build 31xx
* Material Theme release:
  * v4.1.5

**Comment by eypsum** [comment]
I have been getting this problem on more earlier than 4.1.5  under Ubuntu Gnome 16.04.

**Comment by equinusocio** [comment]
This theme is deprecated, you can read the deprecation note in the README. Please consider to switch to another editor like VS Code or Atom.
