### ISSUE TITLE
Phantoms with LAYOUT_INLINE shows below the line.

### ISSUE THREAD

**Issue by oyyq99999** [equinusocio/material-theme#1236]
### Summary

phantoms added with `sublime.LAYOUT_INLINE` doesn't position correctly

### Expected behavior

the phantoms are inline

### Actual behavior

the phantoms are showing below the line

### Steps to reproduce

1. use any(or most?) material colorscheme, `Taterial-Theme-Darker` for example
2. add some phantom with `sublime.LAYOUT_INLINE` as layout.

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3143
* Material Theme release:
  * v4.1.5

**Comment by equinusocio** [comment]
This theme ha been deprecated time ago.
