### ISSUE TITLE
how to change tab font color

### ISSUE THREAD

**Issue by huangcan5421** [equinusocio/material-theme#1237]
hello, i have a problem, 

how can i change my material theme tab （which one is ont active 、picked、checked）font color？its too dim for me.

i dont like dark theme i used  `Material-Theme.sublime-theme`   so i want change this font color

`"material_theme_accent_pink": true,`  its only change  tab for active  

//im so sorry my english is too bad  :( 

![qq 20180416154040](https://user-images.githubusercontent.com/13963286/38795963-8a93dedc-418c-11e8-9d8d-0f7341994921.png)

**Comment by equinusocio** [comment]
You can't on sublime text. Since this theme was ported to VSC and this one is deprecated i suggest you to switch to vs code or atom, you will find material theme waiting for you.
