### ISSUE TITLE
Feature Request:  Ocean Theme Variant

### ISSUE THREAD

**Issue by zpreston123** [equinusocio/material-theme#1238]
Hi @equinusocio,

Not an issue, just a feature request:  would it be possible to port the Ocean theme variant to Sublime?  I noticed it in the VSCode version, would be a really cool addition to this version.

**Comment by mallowigi** [comment]
You should probably ask the Materialize plugin instead.

**Comment by equinusocio** [comment]
@zpreston123 As you know, this project is no more under active development. I'm sorry about that but my focus is now the vsc version. This theme should be rewritten from scratch and right now it does not allow new features. I will be happy if someone will want to make a new Material Theme for ST from scratch.
