### ISSUE TITLE
Rename file textfiled not visible

### ISSUE THREAD

**Issue by heavybeard** [equinusocio/material-theme#124]
Hi Mattia,
first of all, great theme!

I tried to rename a file: the textfield doesn't appear
![image](https://cloud.githubusercontent.com/assets/12038447/8180655/be0f49ec-141f-11e5-8108-44fbff9b3208.png)

Andrea

**Comment by limenet** [comment]
I just tried [the fix from #119](https://github.com/equinusocio/material-theme/issues/119#issuecomment-112334303) with this issue and it works. The drag handle is at the very bottom of the window (but not visible, just slowly move your mouse down).

**Comment by heavybeard** [comment]
Thanks a lot! The suggestion works!

That's a little bug from Sublime?

**Comment by limenet** [comment]
@heavybeard You're very welcome!

I don't know whether it's due to this theme or the editor itself. I haven't written any theme whatsoever for ST2/3 so I don't have any experience/knowledge. However, I've never seen this bug/behavior with any other theme in the ~4 years I've been using ST2/3.

**Comment by equinusocio** [comment]
@heavybeard Because no one themes change so much the original panel margins. Anyway, pls read the README before open a issue.
