### ISSUE TITLE
Can't install the theme.

### ISSUE THREAD

**Issue by Markmaster** [equinusocio/material-theme#125]
Hi.
I tried to install Material Theme but I got this http://d.pr/i/16cMG
I tried to use Package Control to install this but there is no such http://d.pr/i/10XzW Material Theme there.
I use Sublime 3 Build 3083 and I am on OS X 10.10

**Comment by jermainecraig** [comment]
I'm having the same issue, can't find it on on Package Control. I installed it manually, but only managing to use the color scheme. 

Sidebar etc is broken when I try to use the theme.

**Comment by HendrikPetertje** [comment]
Please remove the theme package folder from your computer and if neccesairy remove the lines of code setting the theme and colorscheme.. having a fresh env again make sure to 
- remove material theme from package control (ctrl + shift + p the  type remove package and then material-theme)
- make a fresh install of the theme by reinstalling it in package control.

Is this working for you guys?

if not:
what system are you on?
what sublime version are you using?

**Comment by Markmaster** [comment]
>>> import urllib.request,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
174110
reloading plugin Package Control.bootstrap
Package Control: Settings change detected, clearing cache
reloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency bz2
Package Control: No updated packages
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.


This is log from the console. http://d.pr/i/1do5x The Package Control installed successfully I suppose.

I think the instructions is corrupted.

First, after installing the Package Control you need to go to Preferences and in the Package Control windows first is to http://d.pr/i/12TCM "Install Package". After than you select this you can search for "Material Theme" http://d.pr/i/13D6O
And you good http://d.pr/i/1jfCF

Thanks!

**Comment by jermainecraig** [comment]
I've done the above, haven't tried to manually install ... but still doesn't show up in the package manager.
https://www.dropbox.com/s/hp4mzep1s5kpzj9/Screenshot%202015-06-16%2014.22.54.png?dl=0

**Comment by christill** [comment]
I can't see it in the package manager either. When I try the manual install. It appears broken with the side menu not showing any folders etc.

**Comment by Markmaster** [comment]
@jermainecraig I think you got exactly what you need. Choose "Material Theme" and it will download and install the Theme.

**Comment by christill** [comment]
@Markmaster I think that's his point. 'Material Theme' is not in that list. Same for me.

**Comment by Markmaster** [comment]
@christill @jermainecraig got a little video for you https://db.tt/VJh7Kmw9 tell me if it's helped.

**Comment by equinusocio** [comment]
You manually intalled the package before?
Try:
1. Quit Sublime Text
2. Remove the package from **Packages folder** (Preferences > Browser package...)
3. Remove any Material Theme.package file (if exist) from **Installed Packages folder**
4. Restart Sublime and search for **Material Theme** in package control

**Comment by christill** [comment]
Does this only work on Sublime 3? I'm still on version 2. That could be my issue.

**Comment by Markmaster** [comment]
@christill Package Control available and for version 2. Did you see my video?

**Comment by christill** [comment]
@Markmaster Yeah, That is what I did and the theme is not in Package Control for me.

**Comment by jermainecraig** [comment]
@Markmaster @christill Yeah also tried this with no luck, didn't work in the console, error given - ImportError: No module named request

So I added it to installed packages, but still not showing up in the package manager installer. That's on sublime text 3

**Comment by equinusocio** [comment]
This theme is available only for ST 3. He doesn't show up in ST 2 control package .

**Comment by christill** [comment]
@equinusocio Ok that worked in Sublime 3. Thanks :)

**Comment by Markmaster** [comment]
@equinusocio ok. Thanks.

@jermainecraig do you try to restart Sublime, after that again go to the Preferences-Package Control start typing install and choose install packages, and next start to type mater - and here you go!

**Comment by jermainecraig** [comment]
Sorry, yeah I'm on Sublime 2 also, typo. @Markmaster

**Comment by equinusocio** [comment]
This theme is called "Material Theme **for Sublime Text 3**"
