### ISSUE TITLE
small SASS flex fixes

### ISSUE THREAD

**Issue by B-iggy** [equinusocio/material-theme#126]
Hey,

some flex properties in a sass file should be same colored like the rest, I guess?! See screenshots please.
![sass-flex-1](https://cloud.githubusercontent.com/assets/7815434/8184214/82893ffe-143d-11e5-9075-23ab01eac58d.PNG)
![sass-flex-2](https://cloud.githubusercontent.com/assets/7815434/8184213/8286d746-143d-11e5-8bbc-e70331905cb0.PNG)

**Comment by omgmog** [comment]
Looks like an issue with your Sass/SCSS language syntax, rather than an issue with the color scheme.

Try installing and using https://github.com/p233/Syntax-highlighting-for-Sass/ instead.

**Comment by B-iggy** [comment]
thank you @omgmog. That did the trick.
