### ISSUE TITLE
Rename bar missing text field

### ISSUE THREAD

**Issue by idreyn** [equinusocio/material-theme#127]
Love the theme, but for me it's not displaying the text field near the bottom of the window when right click a file and choose "Rename...". The bar appears but it doesn't contain a text field. I can post an image if necessary but it's difficult to see since the bar is the same color as the rest of the interface! :P 

I'm using Sublime build 3083 on OS X 10.10.1. Thanks!

**Comment by omgmog** [comment]
Also experiencing this issue, here's a screenshot:

![](http://i.imgur.com/JIFekCl.png)

Effects anything that spawns the field at the bottom of the window.

**Comment by omgmog** [comment]
Further to my last comment, and after reading #119, you can mouse over just above where the bar should be and your cursor will change to a ![](http://i.imgur.com/KYLwtxh.png) resize cursor. Then you can drag up to increase the size of the bar:

![](http://i.imgur.com/RXZ73iB.png)

**Comment by LookOnTheBrightSide** [comment]
same here, bar also seems huge!(height)

**Comment by equinusocio** [comment]
See #67

**Comment by graphitivity** [comment]
Aahhh this was an easy fix! I just had to drag it up...
