### ISSUE TITLE
new file text input is hidden

### ISSUE THREAD

**Issue by myurtsev** [equinusocio/material-theme#128]
Hi! Loving the theme, awesome! just a minor problem; when i try to make a new file the input field is not visible.
![schermafbeelding 2015-06-16 om 16 30 36](https://cloud.githubusercontent.com/assets/10652725/8185638/cd731988-1445-11e5-8376-83d0bc7d983a.png)

**Comment by equinusocio** [comment]
Pls read the README.. Search for a similar issue before open new one. See #67
