### ISSUE TITLE
Search/command palette collapsed in Vintageous

### ISSUE THREAD

**Issue by jrolfs** [equinusocio/material-theme#129]
[Vintageous](http://guillermooo.bitbucket.org/Vintageous/)

Hopefully I have time to open a PR and investigate this, but for now just documenting it:
![Screenshot](http://d.pr/i/16cGd+)

This is where commands like `:w` and `%s/thing/other/g` show up.

**Comment by gj1118** [comment]
please see #18

**Comment by jrolfs** [comment]
Haha, welp that was easy. It might be worth adding a blurb about this to the install instructions. Thanks!

**Comment by jrolfs** [comment]
However, the background needs to be fixed (just for commands not search): ![Screenshot](http://d.pr/i/1aR3q+)

**Comment by equinusocio** [comment]
You have to use the Darker version. The some packages (like emmet) use a code field for their functionality. The code field inherit the background color from the color scheme, that have a dark background.

In the darker version the background color has the same color of the inputs and you don't see the differences. I hope to find a fix for this.

**Comment by jrolfs** [comment]
I worked on a Solarized version of [Soda](https://github.com/buymeasoda/soda-theme). Ian, the original author, did some stuff I didn't fully understand the mechanism behind with a "[widget theme](https://github.com/buymeasoda/soda-theme/blob/master/Soda%20Dark/Widget%20-%20Soda%20Dark.stTheme)." Perhaps that will help you?

**Comment by equinusocio** [comment]
in Soda Theme you have a white background for the code and inputs field. Easy :)

**Comment by equinusocio** [comment]
Mmm i will check the dark version. Thanks

**Comment by jrolfs** [comment]
Yeah, sorry I didn't actually check I was just wondering if you can accomplish any of the tricky things with the widget theme.
