### ISSUE TITLE
Find in all files isn't fully visible on mac

### ISSUE THREAD

**Issue by jordan314** [equinusocio/material-theme#13]
Thanks for this theme!
The fields in the "find in all files" function are too big so not all three of them are visible, on mac yosemite.
http://i.imgur.com/6yG1Bsu.png

**Comment by equinusocio** [comment]
Hi @jordan314 this is a sublime text bug. You have to manual resize once the find/replace panel by dragging the top edge (when you see the arrow up)

**Comment by jordan314** [comment]
Oh, thanks!
