### ISSUE TITLE
Find In File panel unusuable

### ISSUE THREAD

**Issue by mseeley** [equinusocio/material-theme#130]
STR:
* OSX: 10.10.3
* Sublime Text 3 Build 3083
* Open Find in Files

Expected: All text boxes should display fully.
Actual: See screenshot

![screen shot 2015-06-16 at 7 50 00 am](https://cloud.githubusercontent.com/assets/30019/8190107/60313362-13fc-11e5-9bf5-bdda59a18c54.png)

Any idea?

**Comment by equinusocio** [comment]
Yes, find for a similar issue, or oread #67

**Comment by jrolfs** [comment]
#18 just resize it.

**Comment by mseeley** [comment]
I looked through the open issues; didn't see one so I filed.

Like this user I couldn't see the panel border: https://github.com/equinusocio/material-theme/issues/67#issuecomment-112318322

Based on the huge number of times https://github.com/equinusocio/material-theme/issues/67 is referenced maybe there's a way to make it easier to find.

Thanks for the them, looking forward to trying it out.
