### ISSUE TITLE
Rename bar is invisible

### ISSUE THREAD

**Issue by akwright** [equinusocio/material-theme#135]
When attempting to rename a file, the rename edit box that appears above the document information at the bottom of the window is not visible.

**Comment by Revod** [comment]
See #68

**Comment by akwright** [comment]
That did it - thank you :)

**Comment by equinusocio** [comment]
@akwright for the next time take a :eyes: to the realm file. :+1:

**Comment by akwright** [comment]
Ah can't believe I missed that! I am ashamed 😞
