### ISSUE TITLE
Sidebar bottom white-space

### ISSUE THREAD

**Issue by mrvkino** [equinusocio/material-theme#137]
At the bottom of the sidebar there is a weird blank zone that does not exist with other themes. In the image the sidebar cuts at about the line 45. There is also a fairly big buffer above and below the text in the status bar, can it be configurable or slimed?

Thanks
![untitled](https://cloud.githubusercontent.com/assets/279511/8198275/15410dde-1472-11e5-982a-e324ad4de186.jpg)

**Comment by equinusocio** [comment]
I will fix the sidebar white-space. The status bar is ok.
