### ISSUE TITLE
Problems with the plugin SidebarEnhancement

### ISSUE THREAD

**Issue by dondevi** [equinusocio/material-theme#138]
While using "rename" or "duplicate" to a file, I can see nothing on the bottom:

![image](https://cloud.githubusercontent.com/assets/4516651/8198892/b89d4f5c-14df-11e5-8cfd-4f88cd1fe427.png)

**Comment by mattgi** [comment]
+1 add folder, add file, etc. are all broken

**Comment by Revod** [comment]
See #67

**Comment by mattgi** [comment]
awesome.. thanks @Revod

**Comment by limenet** [comment]
It's also in the README under [known issues](https://github.com/equinusocio/material-theme#known-issues), including a gif.

**Comment by dondevi** [comment]
It works! Thanks!

**Comment by dondevi** [comment]
**I saw the GIF before, but only try it for "find/replace"...** :sweat_smile:
Maybe explicitly use words like _"It will also happends in some plugins such as SidebarEnhancement"_ will be the better. @equinusocio

**Comment by equinusocio** [comment]
Done :+1:
