### ISSUE TITLE
Add preview img to readme

### ISSUE THREAD

**Issue by blomdahldaniel** [equinusocio/material-theme#14]
Maybe you will wait with this intill your done? But for now i would enjoy the dribble pictures added to the readme here on GitHub. 

I am so hyped about this theme!

**Comment by equinusocio** [comment]
Hi @blomdahldaniel i will add some screenshots when all is defined. At the moment you can see some screenshots [here](https://dribbble.com/shots/2085617-Material-Theme-Sublime-Text-3)
