### ISSUE TITLE
Colors not matching?

### ISSUE THREAD

**Issue by g5400658** [equinusocio/material-theme#140]
Just installed, immediately noticed the colors don't match what's on the main readme page.

The background color of my theme is #263238, while the images on the readme page have a background color of #212f35. I'm sure there are others.

Were there color palette changes made or am I missing something?

**Comment by equinusocio** [comment]
The outputs of this colors are the same (on my calibrated iMac). I think In the PNG files there is a profile color.

**Comment by g5400658** [comment]
Profile colors meaning what?

**Comment by equinusocio** [comment]
When you save an image for the web you can include the profile color..
