### ISSUE TITLE
Bottom bar not visible when trying to rename a file

### ISSUE THREAD

**Issue by pratik60** [equinusocio/material-theme#142]
This is an urgent bug, as I have to go outside Sublime to rename the file

The bottom bar is super tiny in case of renames, seems fine when using find and all.

![screen shot 2015-06-17 at 12 53 32 pm](https://cloud.githubusercontent.com/assets/2249430/8201585/06ed514c-14f0-11e5-9f87-c1fa8fdaa324.png)

**Comment by conanjunn** [comment]
I have come across this bug when trying to create a file

**Comment by enygmatik** [comment]
See the issue [#67](https://github.com/equinusocio/material-theme/issues/67)

**Comment by equinusocio** [comment]
README doesn't mean IGNORME

**Comment by pratik60** [comment]
:-)

Why is it happening though, as it doesn't happen with other themes? Also didn't happen with find, replace etc...Only rename for me.

**Comment by equinusocio** [comment]
Because other themes doesn't change so much the panel size and padding. This theme add a lot of white-space and sublime doesn't refresh the new non-standard size.

Once fix this (force sublime to refresh the panel size) the issue doesn't occur anymore.
