### ISSUE TITLE
Rename box not visible

### ISSUE THREAD

**Issue by lordgiotto** [equinusocio/material-theme#143]
Hi, i've noticed an issue: if i try to rename a file within sublime text, the input box remains hidden behind the bottom bar.
I attach an image to better understand.

Thank you :)

![issue](https://cloud.githubusercontent.com/assets/5115382/8202111/2e7dabda-14d7-11e5-97da-530a4508ab36.jpg)

**Comment by equinusocio** [comment]
README doesn't mean IGNORME :)

**Comment by lordgiotto** [comment]
Ok, sorry for that! :)
