### ISSUE TITLE
Bugs in bottom bar

### ISSUE THREAD

**Issue by RoxasShadow** [equinusocio/material-theme#144]
- Windowed ST3 on the latest OSX: Cmd+Shift+F

![screen shot 2015-06-17 at 10 53 31](https://cloud.githubusercontent.com/assets/805144/8203017/217d0dc4-14df-11e5-9feb-703b8de5cc6d.png)

- Rename a file (using `Side Bar`)

A solid color block appears without inputs or anything.

![screen shot 2015-06-17 at 10 55 47](https://cloud.githubusercontent.com/assets/805144/8203060/6fd8474a-14df-11e5-86b3-62e565c2f94d.png)

**Comment by equinusocio** [comment]
REDME please ;)
