### ISSUE TITLE
Dark monochrome colour neutral variant?

### ISSUE THREAD

**Issue by JerseyMilker** [equinusocio/material-theme#146]
I already mentioned this on twitter, hopefully you're okay with me posting the idea here as well.

I'm suggesting a dark monochrome variant with dark charcoal background and colourless icons, etc.  The main point of the variant is to be colour neutral so that any dark scheme could be used with it.  This would make it easy to drop in various schemes, just by ensuring the scheme's background matches the charcoal background used in the Material variant.

For example, I'm using this modified version of your theme.  It works very well with this monkai-like scheme I'm using.  ![Image](http://puu.sh/ipG3m/0480102f55.png)

I was originally thinking of releasing my own variant, but if you are open to making such a variant, I think it'd make more sense to be part of your repo.  That said, if you want to use any of my colours or modified image assets, I've pushed them to my fork here: https://github.com/JerseyMilker/material-neutral

Anyway, thank you for considering our suggestions.  You did an incredible job on Material <3

**Comment by equinusocio** [comment]
Thanks. The darker version will become a neutral charcoal

**Comment by JerseyMilker** [comment]
Can't wait!
