### ISSUE TITLE
No horizontal scrollbar

### ISSUE THREAD

**Issue by uoziod** [equinusocio/material-theme#147]
But sometimes it's a pretty useful thing ;)

![Screenshot](https://api.monosnap.com/rpc/file/download?id=cpcQxBerVzASbBb5pyIhHdiLzx6WCN)

PS: OS Windows

**Comment by equinusocio** [comment]
Restart sublime pls..

**Comment by uoziod** [comment]
Still. http://take.ms/Hy58J

**Comment by equinusocio** [comment]
Paste your preferences

**Comment by uoziod** [comment]
You'll be laugh, but:
```
{
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "Material-Theme.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
}
```

**Comment by equinusocio** [comment]
Paste a new screenshot please.

**Comment by uoziod** [comment]
![sure](https://api.monosnap.com/rpc/file/download?id=0eOUPQ2AAgOQDknjZmSPzC7uoEJp1V)

**Comment by equinusocio** [comment]
Try this:
```json
"overlay_scroll_bars": "
```

**Comment by uoziod** [comment]
Helped. Thanks.

**Comment by SujjadAli** [comment]
and what if you can't edit the default preferences...

**Comment by equinusocio** [comment]
You can't edit the default preferences. You have to edit the you user preferences.

**Comment by SujjadAli** [comment]
helped thanks
