### ISSUE TITLE
Closing Brackets in wrong color (C++)

### ISSUE THREAD

**Issue by floxyz** [equinusocio/material-theme#148]
In C++ code closing brackets have a different color than opening brackets. This is not the case for other themes (like the default Monokai).

![bracket-error](https://cloud.githubusercontent.com/assets/1648142/8208232/cbaa311a-1506-11e5-8e36-3863257cfc59.png)

**Comment by equinusocio** [comment]
Yes. I'm working on a completely new color scheme

**Comment by bernardodsanderson** [comment]
![style_css_ _fcc-drupal-cms](https://cloud.githubusercontent.com/assets/5623786/8212286/751cf8a8-14e0-11e5-802b-22c3abe936e8.png)

Same with CSS files. But I'm sure you already knew that.

**Comment by equinusocio** [comment]
Fixed in latest release
