### ISSUE TITLE
Enter Abbreviation background input color

### ISSUE THREAD

**Issue by gpessia** [equinusocio/material-theme#151]
![schermata 2015-06-17 alle 19 43 52](https://cloud.githubusercontent.com/assets/68612/8214450/a172eedc-1529-11e5-9c66-76377c09704f.png)
c'è qualche problema qui o sono io che ho sbagliato qualche cosa? 
Cmq è veramente meraviglioso questo tema!

**Comment by equinusocio** [comment]
Me lo hanno segnalato, il fatto è che succede solo con gli altri pacchetti, probabilmente usano un campo personalizzato per le loro funzioni ed ridato lo stile del codice invece che quello degli input normali.

Ho cercato un modo ma non ho trovato nulla, e non sono sicuro possa risolverlo io. L'unica soluzione sarebbe quello di cambiare gli input e lasciarli come nella versione darker, il che comporta a sua volta a non avere i pannelli bianchi.

**Comment by equinusocio** [comment]
@gpessia Come non ho detto. Ho trovato il modo per correggere questo problema. L'unico inconveniente è che devo risolverlo per ogni pacchetto che mi viene segnalato. Nella prossima release sistemo Emmet
