### ISSUE TITLE
Replace inputs aren’t fully visible

### ISSUE THREAD

**Issue by jlmakes** [equinusocio/material-theme#153]
Hey @equinusocio, great work!

Check this out. I pressed `cmd shift F` for search and replace and…

![screen shot 2015-06-17 at 2 41 31 pm](https://cloud.githubusercontent.com/assets/2044842/8219497/4fcb5f44-14ff-11e5-9ea8-7def66c57066.png)

Also, the only package I use that alters the UI is GitGutter. Not sure if that’s important.

:beers:

**Comment by Revod** [comment]
Read the README. Or see #18 , resize the rename panel once by dragging the top edge and then restart twice sublime text

**Comment by equinusocio** [comment]
Thanks @Revod ...

**Comment by jlmakes** [comment]
:+1:
