### ISSUE TITLE
Lack of color distinctions / saturation

### ISSUE THREAD

**Issue by mvaivre** [equinusocio/material-theme#163]
Hey man,

Awesome theme you did here, thanks a lot!
I'm currently working on a project involving React + CJSX (coffescript) and I have some problems with the syntax highlighting : some elements are not very visible (wrong color distinction, some lack of saturation).

Some examples:
![materialtheme1](https://cloud.githubusercontent.com/assets/6715943/8227940/54ea3728-15ab-11e5-8811-260c626c505b.png)

VS.

![hopscoth1](https://cloud.githubusercontent.com/assets/6715943/8227942/583899f6-15ab-11e5-8cea-7ea37e8254e6.png)

OR

![material2](https://cloud.githubusercontent.com/assets/6715943/8228045/191fe764-15ac-11e5-9399-836b2648428e.png)

VS.

![hopscotch2](https://cloud.githubusercontent.com/assets/6715943/8228048/1d73a6ca-15ac-11e5-90a6-8fb29cd6a8c4.png)

I heard you are working on a whole new color scheme: if your able to create more specific highlighting + colors a bit more "flashy", you'll have one of the best theme I've ever seen!

Cheers!

**Comment by jerrykelih** [comment]
Thumbs up for better ReactJS support :+1:

**Comment by equinusocio** [comment]
Thanks for the suggestion. Making a new color scheme is a bit longer, but i want to make it the most complete (scopes)

**Comment by jrappen** [comment]
As a reference, https://github.com/bathos/Ecmascript-Sublime has a list of scopes for JS.

/cc @equinusocio

**Comment by dduupp** [comment]
![Comments](https://cloud.githubusercontent.com/assets/10728938/8239677/a87702a2-15fd-11e5-838c-bda8545a42ad.png) bother me the most, the contrast with the background is horrible.

**Comment by idreyn** [comment]
I think the line numbers could stand to have more contrast against the background as well.

**Comment by darenju** [comment]
I totally agree with @dduupp. Comments are like the most important parts of our code, and it seems not to be readable at all. A very visible colour such as #2980b9 or #e67e22 could do the trick.

**Comment by mvaivre** [comment]
@darenju : I think @equinusocio we'll do a great job at finding correct tones (I mean, you chose this theme because of its style.. ;)).

IMHO, comments shouldn't use colors as visible as your propositions... 'cause they shouldn't be the most important parts of your code! A lighter grey should be enough.

Can't wait to try the next update.

**Comment by equinusocio** [comment]
In the latest release i've highlight a bit the comments color. If you don't see any changes delete the color_scheme cache (SublimeLinter, ColorHighlighter...)
