### ISSUE TITLE
Base 16 color schemes

### ISSUE THREAD

**Issue by kristijanhusak** [equinusocio/material-theme#167]
Hi,

First of all, great theme! It's really beautiful.

I would like to check if you are planning to add some more color schemes? The ones that are currently available are not fitting me 100%.

I can suggest https://github.com/chriskempson/base16-textmate , which are really great, and I think many people are using it.

I also tested it out. Changed only background to fit the theme, and it looks pretty good. Here's the screenshot of the JS file with **base16-tomorrow-dark**:

![base-16-dark-material](https://cloud.githubusercontent.com/assets/1782860/8231763/091329d4-15cb-11e5-8bd4-e0cfc8d6a0d8.png)

If you like it, i can create PR and add this one in.

**Comment by equinusocio** [comment]
Hi, thanks for suggestion. Can you post more screenshot from different languages?

**Comment by kristijanhusak** [comment]
Sure, here are some screenshots:

**PHP**

![base-16-php](https://cloud.githubusercontent.com/assets/1782860/8248583/21587602-1661-11e5-8726-cd932fcea357.png)

**HTML**

![base-16-html](https://cloud.githubusercontent.com/assets/1782860/8248585/2952f7c4-1661-11e5-83f9-87eee6ef89b7.png)

**CSS**

![bse16-css](https://cloud.githubusercontent.com/assets/1782860/8248589/2f6f666a-1661-11e5-89e8-33f8e925ad6c.png)

**SCSS(Sass Compass)**

![base-16-scss](https://cloud.githubusercontent.com/assets/1782860/8248592/3cdd0a3c-1661-11e5-8453-ccdd7a6a306c.png)

**RUBY**

![base-16-ruby](https://cloud.githubusercontent.com/assets/1782860/8248607/454282ba-1661-11e5-9301-31ddd53de298.png)

**Comment by equinusocio** [comment]
Added in the latest release

**Comment by kristijanhusak** [comment]
@equinusocio 
I cannot find it, checked master and develop branch. Where did you put it?

**Comment by loweoj** [comment]
Bump/+1
