### ISSUE TITLE
Rename file menu is not visible

### ISSUE THREAD

**Issue by egcastro** [equinusocio/material-theme#168]
If you try to rename a file/folder the menu is not visible, neither the label or the input text to type the new name.

**Comment by equinusocio** [comment]
... See the README please

**Comment by greaterweb** [comment]
I'm experiencing the same thing, any reason this was closed?

**Comment by equinusocio** [comment]
Because there are a lot of duplicated issues. People you have to read the README before open an issue. Regards.
