### ISSUE TITLE
Color scheme updates for babel/ES6

### ISSUE THREAD

**Issue by balanceiskey** [equinusocio/material-theme#17]
Would be awesome to update the scheme to better handle ES6/Babel-flavored Javascript. Oceanic Next seems to be one of the few that does this properly: https://github.com/voronianski/oceanic-next-theme

**Comment by balanceiskey** [comment]
Also, might tackle this myself, just wanted to make sure it got logged ;)

**Comment by equinusocio** [comment]
Hi @balanceiskey pls download the latest beta release and test the highlighter for ES6/Babel-flavored.
The syntax highlighter is now based on Oceanic scheme.
