### ISSUE TITLE
Minimap doesn't show highlight

### ISSUE THREAD

**Issue by Misiur** [equinusocio/material-theme#170]
Hello. In most themes, you have this neat highlight:
![highlight](http://i.imgur.com/V7FlgvS.png)

However in this theme it's gone
![no light](http://i.imgur.com/3VyN17a.png)

**Comment by equinusocio** [comment]
Post your preferences

**Comment by Misiur** [comment]
{
		"color_scheme": "Packages/Material-theme/schemes/Material-Theme.tmTheme",
		"font_size": 11,
		"ignored_packages":
		[
			"Vintage"
		],
		"theme": "Material-Theme.sublime-theme"
	}

**Comment by equinusocio** [comment]
This is a sublime settings. Add:

```json
	"always_show_minimap_viewport": true,
```

**Comment by Misiur** [comment]
I did that. no change.
I added `"draw_minimap_border": true,` as well, however the highlight itself doesn't have any colour still

![bordered](http://i.imgur.com/huNiaet.png)

**Comment by equinusocio** [comment]
You restarted sublime after apply the theme?

**Comment by Misiur** [comment]
Oh, didn't notice new version from package manager! Works as intended now, thank you for help.
