### ISSUE TITLE
Dialogs at the bottom of the editor are covered behind the status/messages 

### ISSUE THREAD

**Issue by spirosikmd** [equinusocio/material-theme#171]
I tried **find & replace** and **add new file** dialogs and they are both hidden behind the status/messages line at the bottom of the editor.

![screen shot 2015-06-17 at 16 21 19](https://cloud.githubusercontent.com/assets/1057324/8242578/9bb3158e-1610-11e5-812b-33bc157837be.png)

Duplicate sorry!

**Comment by equinusocio** [comment]
:+1:
