### ISSUE TITLE
Find and Replace forms don't show correctly?

### ISSUE THREAD

**Issue by felixangell** [equinusocio/material-theme#172]
I think this is an issue with the theme, rather than sublime since other themes seem to work fine with this.
As you can see in the screen shot, the find and replace menu only shows the two forms, and not 3.
![screen shot 2015-06-18 at 22 37 46](https://cloud.githubusercontent.com/assets/6254332/8242953/f4850088-160a-11e5-9141-f79d770417a1.png)
I'm using Mac OS X Yosemite, and Sublime Text 3083. Here's a [pastie of my sublime settings](http://pastie.org/private/4rzlqdb0rhwzrdrfrxe6g).

**Comment by equinusocio** [comment]
READ the README please ;)

**Comment by felixangell** [comment]
@equinusocio oooo thanks :+1:
