### ISSUE TITLE
Inverted line highlight color?

### ISSUE THREAD

**Issue by scottwhudson** [equinusocio/material-theme#173]
Any idea what's causing the line highlight to be darker instead of the other way around?  I noticed it's not standard behavior in your screenshots, but the lack of contrast makes comments harder to read.  Maybe there's a config somewhere that I'm missing?

![screen shot 2015-06-18 at 12 02 58 pm](https://cloud.githubusercontent.com/assets/6406203/8237035/12c6c1a2-15b2-11e5-9911-1f5f3090f57d.png)

**Comment by equinusocio** [comment]
I've update the comments contrast in the latest release (1.0.7) i will update the screenshots today.

The line highlight is darker to make the line number visible. I can't set a color for highlighter line number.

**Comment by scottwhudson** [comment]
Ah, thanks!
