### ISSUE TITLE
Suggestion to change background color to a darker shade

### ISSUE THREAD

**Issue by MrBenjiHao** [equinusocio/material-theme#175]
A darker shade allows for more contrast against the text.

Suggested Color #182226
![darker](https://cloud.githubusercontent.com/assets/4434285/8246307/6d276338-160a-11e5-83aa-9401e3cf873c.PNG)

Original Color  #263238
![lighter](https://cloud.githubusercontent.com/assets/4434285/8246312/879fb490-160a-11e5-8cca-019508fded87.PNG)

**Comment by equinusocio** [comment]
Sorry, this theme is called Material Theme.  The main color palette is base on the Material Design Colors. Anyway more contrast = more eyes stress
