### ISSUE TITLE
Don't see the active indent guide highligh

### ISSUE THREAD

**Issue by arpitnj** [equinusocio/material-theme#178]
https://github.com/equinusocio/material-theme/commit/c0e64a7a28d38b0caf63e562ce9e2fe647dc3b24

the following commit I made doesn't seem to be reflecting on my system, I can see that the latest version of the material theme got updated today but the code is not there in theme? What do you think is the issue?

**Comment by arpitnj** [comment]
in the color scheme when I switch to old material theme it works? So I am guessing the change I made was to some other theme file?

**Comment by equinusocio** [comment]
You use ColorHighlighter or SublimeLinter?

**Comment by arpitnj** [comment]
I use ColorHighlighter.

**Comment by arpitnj** [comment]
Line 33-38 contains the code I had committed 

https://github.com/equinusocio/material-theme/blob/master/schemes/Old-Material-Theme.tmTheme#L33-L38

the default color scheme is missing that 

Line 33-36
https://github.com/equinusocio/material-theme/blob/master/schemes/Material-Theme.tmTheme#L33-L36

**Comment by equinusocio** [comment]
![screen shot 2015-06-19 at 11 03 42](https://cloud.githubusercontent.com/assets/10454741/8250327/e0f35c32-1672-11e5-9144-1799293f8dba.png)
