### ISSUE TITLE
Message box can't be seen

### ISSUE THREAD

**Issue by explodecomputer** [equinusocio/material-theme#18]
Great theme. Just one thing I've noticed - 

The gist plugin https://github.com/condemil/Gist allows you to create a gist from the file you are working on, e.g. "cmd+shif+p -> gist: create public gist" will bring up a text box at the bottom of the screen. However with this theme that text box is not visible.

**Comment by equinusocio** [comment]
Can you post a screenshot?

**Comment by explodecomputer** [comment]
this is what the box should look like with the previous colour scheme that i was using

![gist1](https://cloud.githubusercontent.com/assets/1924940/8012738/9db29f44-0bbb-11e5-956b-3be936ea305a.png)

and basically it doesn't show up when i try with the new theme. however, if i type and press enter it is registered and it performs the operation, i just can't see it

![g2](https://cloud.githubusercontent.com/assets/1924940/8012772/d1b2669e-0bbb-11e5-9f15-6ef3d85876be.png)

**Comment by equinusocio** [comment]
...You restarted sublime after activating the theme?

**Comment by explodecomputer** [comment]
Yeah. I just tried uninstalling and reinstalling the theme and the gist plugin too but same behaviour.

**Comment by equinusocio** [comment]
Paste your preferences

**Comment by explodecomputer** [comment]
{
	"theme": "Material-Theme.sublime-theme",
	"color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",
	"ignored_packages":
	[
		"Markdown",
		"roxygen",
		"Markdown Extended",
		"Vintage"
	],
	"scroll_past_end": true,
	"word_wrap": true
}

**Comment by rigor789** [comment]
Hey, I have a similar issue with AdvancedNewFile (on Linux)

Here's a screenshot:

![Sublime Issue](http://i.imgur.com/wenQbg0.png)

**Comment by gj1118** [comment]
@rigor789 I was facing the same issue as yourself. Please see this ticket : https://github.com/equinusocio/material-theme/issues/19 for more information. At the end of it , you might have to restart sublime text

**Comment by rigor789** [comment]
Thanks @gj1118 That fixed it. Awesome! :+1:

**Comment by explodecomputer** [comment]
AH! I see what this means now - I tried it and it fixed it. Thanks =]
@equinusocio - thanks again for a really nice theme.
