### ISSUE TITLE
Overlay scrollbars not shown on hover

### ISSUE THREAD

**Issue by vonchristian** [equinusocio/material-theme#180]
The overlay scroll bars when enabled does not show on hover until you press the up or down arrow keys.

**Comment by Strap1** [comment]
:+1:

**Comment by Oxicode** [comment]
:+1:

**Comment by equinusocio** [comment]
Sublime Text, even the Default - Theme, doesn't allow to overlay the scrollbars when you set "overlay" or "system" (on OS X). If you want to see the scrollbars, use ```"overlay_scroll_bars": "enabled"``` in your preferences
