### ISSUE TITLE
File rename / move bar doesn't show any text

### ISSUE THREAD

**Issue by adamtomat** [equinusocio/material-theme#182]
When renaming or moving a file / folder, sublime normally adds a bar to the bottom of the window with the filename. With this theme, you can visibly see the bar being added above `Line x, Column x` because it sits over any code, but there's no text or anything within the bar; it appears to have just punched out the space for it without filling it.

Here's a screenshot as an example. The 1st and 2nd screens are showing the process of renaming the file (to add context to the last). The 3rd screenshot shows the bar (inside the red box) has been added as it now covers up a line of code.

![screenshot](https://cloud.githubusercontent.com/assets/2631499/8254211/835eae20-168e-11e5-9130-971bf39e9d05.jpg)

And here's my current settings, incase it's any of these causing the issue:

```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_face": "Fira Code",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 15,
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme",
}
```

**Comment by existentialmutt** [comment]
@equinusocio -- thanks for making such a great looking theme!  I'm seeing this under OS X and would love to see it fixed.

**Comment by rrosen** [comment]
Whoops!  I guess they call it README for a reason! https://github.com/equinusocio/material-theme#user-content-known-issues

**Comment by adamtomat** [comment]
:+1: Thanks!
