### ISSUE TITLE
Color Scheme in PHP

### ISSUE THREAD

**Issue by patryk0605** [equinusocio/material-theme#183]
Would it be possible to make **echo** and other functions such as **date**, **isset**, **array**, **str_pad**, and so on... a different color? Currently they just blend in with plain text and it's a bit hard to quickly identify. Other than that, keep up the good work!

**Comment by equinusocio** [comment]
yes, post me a screenshots (and snippet if you want) of your code

**Comment by patryk0605** [comment]
Here's a quick example:

![material_php_echo](https://cloud.githubusercontent.com/assets/7227636/8256850/c8003fec-1677-11e5-8930-a3cb86ccd74c.png)

As you can see, it's pretty difficult to tell that **echo** and **implode** are within the line. I do like how the variable names stand out though. Not sure what color combination would work best.

**Comment by equinusocio** [comment]
Thanks

**Comment by patryk0605** [comment]
I downloaded the latest release and there is no change. Can this issue please be reopened?

**Comment by equinusocio** [comment]
You use SublimeLinter o Codehighlighter?

**Comment by patryk0605** [comment]
I use neither.

**Comment by patryk0605** [comment]
Following are my installed packages: 

"installed_packages":
	[
		"BracketHighlighter",
		"Color Highlighter",
		"DocBlockr",
		"GitGutter",
		"JavaScriptNext - ES6 Syntax",
		"jQuery",
		"LESS",
		"Material Theme",
		"Package Control",
		"SFTP"
	]

**Comment by equinusocio** [comment]
Restore the color scheme from Code Highlighter.

**Comment by patryk0605** [comment]
That did the trick, thanks!
