### ISSUE TITLE
Make smaller status bar in Sublime

### ISSUE THREAD

**Issue by cmoon2000** [equinusocio/material-theme#184]
I think that status bar is a little big. How can I make it small the same as a option for tab's size?

**Comment by equinusocio** [comment]
you can't at the moment.

**Comment by cmoon2000** [comment]
thanks for reply. And I hope you'll make it in future.

**Comment by equinusocio** [comment]
Maybe. Sincerely i don't want to make a lot of confusing settings

**Comment by sasindumendis** [comment]
I also this it would be nice to reduce the status bar size a bit either by exposing a setting or as baked-in default. The current size of it is eating up bit of extra space unnecessarily.

**Comment by equinusocio** [comment]
White space is unnecessarily until you leave it.
