### ISSUE TITLE
Better coloring for rulers

### ISSUE THREAD

**Issue by bcherny** [equinusocio/material-theme#189]
Ie. `view > rulers> 80`

Currently it's a lighter ruler that is pretty distracting. I would instead make it a smidgen darker than the background, so it's there but doesn't distract from the code.

![screen shot 2015-06-19 at 1 03 43 pm](https://cloud.githubusercontent.com/assets/1761758/8261972/a9513996-1683-11e5-83eb-2c2bc7d7ab72.png)

**Comment by mrliptontea** [comment]
Just passing by, wanted to say it's doable.

The trick is to set ruler's colour by settings default foreground's colour, and text colour by appropriate scope.
Example:

```xml
<dict>
    <array>
        <dict>
            <key>settings</key>
            <dict>
                <key>background</key>
                <string>#1a2226</string>
                <key>foreground</key>
                <string>#37474F</string> <!-- rulers colour -->
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>Text and Source Base Colors</string>
            <key>scope</key>
            <string>text, source</string>
            <key>settings</key>
            <dict>
                <key>foreground</key>
                <string>#cdd3de</string> <!-- text colour -->
            </dict>
        </dict>
    </array>
</dict>
```

**Comment by equinusocio** [comment]
Thanks @mrliptontea for the help

**Comment by plakhin** [comment]
Currently rulers in Material-Theme-Darker are too annoying, it would be nice to have them the same color as inactive indent guide.
