### ISSUE TITLE
New Folder textbox is not visible

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#19]
I am on windows 7 and using SideBarEnhancements plugin for sublime text3 
When I select the new folder menu item, the input box does appear but its not entirely visible. 

![image](https://cloud.githubusercontent.com/assets/473101/8011982/b3940be8-0b8b-11e5-9636-ccb127118c97.png)

**Comment by equinusocio** [comment]
#13

**Comment by gj1118** [comment]
Hi ,
I have tried resizing it , but it does not work as well. I have as well tried resizing sublime text window, it does not work either. Is there something else that I am missing please . 

thanks 

with regards
gagan

**Comment by equinusocio** [comment]
So you've tried to resize (by dragging the top edge) the bottom panel?

**Comment by gj1118** [comment]
yes, please..

**Comment by equinusocio** [comment]
Open find/replace (<kbd>ctrl</kbd> + <kbd>F</kbd>), you see the cutted panel?

**Comment by gj1118** [comment]
I really dont know why , but restarting Sublime Text seems to have resolved that issue. Perhaps it was cached? I dont know. I really apologize for that sir. 

![image](https://cloud.githubusercontent.com/assets/473101/8012921/fbeeec30-0b92-11e5-89bf-039174b849a0.png)

**Comment by Mr-Zer0** [comment]
Can't see any labels like the attached image.
![untitled](https://user-images.githubusercontent.com/2142972/30799372-a667cf58-a202-11e7-9138-6913aa0c6777.png)

**Comment by equinusocio** [comment]
@Mr-Zer0 ????? report it to the sublime community if you find one.
