### ISSUE TITLE
Inactive color is way too dark

### ISSUE THREAD

**Issue by justinfx** [equinusocio/material-theme#191]
I think the style is overall great... but I don't understand why the inactive color is so dark that you can almost not read the tabs for anything but the active one. It would be great to be able to easily read what the other tabs (open files) say so that I can be sure of what I want to switch to. Basically...more contrast.

**Comment by justinfx** [comment]
Maybe an increase in contrast like this?

```
From cbdcd16884ac89363d2eb225a6fff1af69a02739 Mon Sep 17 00:00:00 2001
From: Justin Israel <justinisrael@gmail.com>
Date: Sat, 20 Jun 2015 23:58:44 +1200
Subject: [PATCH] Fixes #191 - Increase contrast on sidebar and tab inactive
 label color

---
 Material-Theme-Darker.sublime-theme | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Material-Theme-Darker.sublime-theme b/Material-Theme-Darker.sublime-theme
index 840bbfd..37d74c9 100644
--- a/Material-Theme-Darker.sublime-theme
+++ b/Material-Theme-Darker.sublime-theme
@@ -317,7 +317,7 @@

                {
                        "class": "tab_label",
-                       "fg": [84, 110, 122, 255],
+                       "fg": [150, 170, 182, 255],
                        "shadow_color": [255, 255, 255, 0],
                        "shadow_offset": [0, 0],
                        "font.size": 11,
@@ -521,7 +521,7 @@

                {
                        "class": "sidebar_label",
-                       "color": [96, 125, 139],
+                       "color": [146, 175, 189],
                        "font.bold": false,
                        "font.italic": false,
                        "shadow_color": [0, 0, 0, 0],
--
1.9.5 (Apple Git-50.3)
```

**Comment by equinusocio** [comment]
please fix your monitor settings

**Comment by justinfx** [comment]
Apparently I have a different monitor than every other Apple laptop owner,
and am the only one that finds the contrast of the inactive text to
background to be quite low. Are you sure your own monitor doesn't have high
contrast?

I will just continue using local modifications to the color palette.

**Comment by equinusocio** [comment]
I use a macbook retina and iMac both with calibrated monitor (Spyder). Yew, the contrast is low (not so low) and you eyes will be grateful :)

**Comment by okonomiyaki3000** [comment]
I also find the contrast on inactive tabs to be a bit too low. What if you were to make the background of the tab a little darker but keep the text color the same? That might look good and make things more readable.

**Comment by TimOetting** [comment]
+1 for better contrast in tabs. It is not only about monitor calibrations but also about the surrounding lights in your real life workspace.
