### ISSUE TITLE
Annoying misalignment in the console

### ISSUE THREAD

**Issue by mrliptontea** [equinusocio/material-theme#194]
This is the least bothersome thing, but still.

The console's output and command bar are differently aligned and the output is rectangular while command bar has rounded corners.

![st-console](https://cloud.githubusercontent.com/assets/3495587/8272447/2864ccbe-1843-11e5-8c98-d0c5e243baa8.png)

**Comment by equinusocio** [comment]
I'm redesigning the inputs field for the default theme. Please be patient.

**Comment by mrliptontea** [comment]
Great to hear (read) :+1:
