### ISSUE TITLE
AdvancedNewFile field not visible

### ISSUE THREAD

**Issue by paulmist** [equinusocio/material-theme#195]
I'm using the common [AdvancedNewField](https://github.com/skuroda/Sublime-AdvancedNewFile) plugin.

The expected input field would look like this (default theme):

![Input](http://take.ms/WlbD5)

However, when using the Material Theme you get:

![Broken input](http://take.ms/I51yV)

**Comment by Revod** [comment]
Are u try to read the README? or see #68

**Comment by paulmist** [comment]
Thanks.

Wasn't having the issue with any other bottom panel inputs.
