### ISSUE TITLE
SideBarEnhancements Compatibility

### ISSUE THREAD

**Issue by paparts** [equinusocio/material-theme#196]
Doesn't work well with ```SideBarEnhancements``` plugin.  The bottom options doesn't show on creating new folder or creating new files.

**Comment by Revod** [comment]
Again this issue... Read The README: 
Please see the issue #67 if you can't see the bottom panel (find/replace, rename, move, can't see the box inputs in SidebarEnhancement, etc..). here the quick fix:
![a0dd09c0-1412-11e5-8ecf-f7f9ade439ae](https://cloud.githubusercontent.com/assets/10109689/8275684/b69f2ab6-1874-11e5-984c-b93819c85bfc.gif)

**Comment by paparts** [comment]
Sorry man. My bad.
