### ISSUE TITLE
Markdown files text alignment

### ISSUE THREAD

**Issue by hdtv1104** [equinusocio/material-theme#197]
Markdown files appear to not be properly aligned. The issue does not occur with other themes, or other files types which I've used (.rb, .js, .yml, .sh to name some)

![fo4_k4ox](https://cloud.githubusercontent.com/assets/6278528/8276962/eab857bc-1871-11e5-8cd3-860edad07cc5.png)

**Comment by skmlcd** [comment]
I have the same issue. My markdown file is aligned to center.

**Comment by jrappen** [comment]
This is cause by [prefs/Ext/Markdown.sublime-settings](https://github.com/equinusocio/material-theme/blob/master/prefs/Ext/Markdown.sublime-settings).

@equinusocio please remove all settings other than the one for `extensions`.

**Comment by equinusocio** [comment]
@jrappen This is the theme :) It's like to ask Apple to remove the windows transparency in OSX Yosemite. If you want to remove the center drawing you have the solution to do it :+1:

**Comment by skmlcd** [comment]
OK, thanks for explanation, there were quite a few issues about this so far. Better have final answer then people asking the same question over and over.

**Comment by equinusocio** [comment]
If more ppl will ask to remove this i will consider it
