### ISSUE TITLE
Close button for Find/Replace panel

### ISSUE THREAD

**Issue by asolfre** [equinusocio/material-theme#200]
Tried resizing the panel, but the icon didn't show up. It's supposed to remain hidden on the theme?

**Comment by equinusocio** [comment]
Read the README please :+1:

**Comment by asolfre** [comment]
Sorry but can't find any reference to the close button (X) of the panel on the README. I'm missing something?

**Comment by secu2** [comment]
Same there, no close button on search panel, and I don't see anything about this in the readme.

**Comment by equinusocio** [comment]
The close button is not displayed. If you want to close the panel press <kbd>esc</kbd>

**Comment by secu2** [comment]
Ok, thanks for your answer, your solution worked.
Actually, I can't believe I didn't manage to fid it alone...

**Comment by asolfre** [comment]
Ok, so it's intentionally not displayed, thanks for your reply. Should this issue be closed then?

**Comment by equinusocio** [comment]
@asolfre i''ve removed all distracting and useless elements from UI. This is one of the basics in this theme.

**Comment by asolfre** [comment]
@equinusocio understood. Congrats on the theme, you are doing a really good job.
