### ISSUE TITLE
Darker goto window

### ISSUE THREAD

**Issue by itsdan** [equinusocio/material-theme#202]
Goto windows stands out strongly. A bit irritating when working at night.
![screen shot 2015-06-22 at 8 55 02 pm](https://cloud.githubusercontent.com/assets/6442492/8288809/0cb62d8a-1921-11e5-9eaa-96366c21ea7a.png)

**Comment by okonomiyaki3000** [comment]
Well, actually, the "darker" option takes care of this but it makes everything much darker. Maybe I like the original colors I just don't want to be blinded by some white fields. I think there should at least be an option to keep the original colors but also use a dark background with the goto window, search box and other fields.

**Comment by equinusocio** [comment]
@okonomiyaki3000 see #210
