### ISSUE TITLE
Bottom text-input-bar has no contrast for text. Happens with Rename File, etc. 

### ISSUE THREAD

**Issue by drduggan** [equinusocio/material-theme#203]
If I do a rename file from menu or with CMD+SHIFT+P => rename file, there is no contrast in the input bar. 

Before
![screen shot 2015-06-22 at 1 01 27 pm](https://cloud.githubusercontent.com/assets/3515525/8290246/f2fae4cc-18de-11e5-8a1c-10671b94b32a.png)

After 
![screen shot 2015-06-22 at 1 01 33 pm](https://cloud.githubusercontent.com/assets/3515525/8290252/fbb670f4-18de-11e5-9629-23ecba562902.png)

**Comment by equinusocio** [comment]
See the README file :+1:

**Comment by drduggan** [comment]
You rock, thanks.
