### ISSUE TITLE
Empty bar when renaming file

### ISSUE THREAD

**Issue by NanchoKibo** [equinusocio/material-theme#204]
I love your theme, is awesome! but I have an issue when I try to rename a file. I can rename the file but I cannot see anything.

This is fine.
![screen shot 2015-06-22 at 22 44 11](https://cloud.githubusercontent.com/assets/9048149/8292519/682f75c2-1930-11e5-89fa-6c8ec6d15076.png)

This is when I click on rename file.
![screen shot 2015-06-22 at 22 43 53](https://cloud.githubusercontent.com/assets/9048149/8292508/5b28d65c-1930-11e5-9221-9f8ba5b5f2b9.png)

Thanks!

**Comment by equinusocio** [comment]
See the README please
