### ISSUE TITLE
Can't see rename box

### ISSUE THREAD

**Issue by mholt** [equinusocio/material-theme#205]
When I right-click a folder/file in the sidebar and choose Rename, I can't see the whole textbox. Just the top of the cursor:

![screen shot 2015-06-22 at 4 19 21 pm](https://cloud.githubusercontent.com/assets/1128849/8294578/99bf62a4-18fa-11e5-87fe-79d4f47ed231.png)

Really loving this theme otherwise - thanks for making it and improving it!

**Comment by knilob** [comment]
Yep, I just noticed this as well. Otherwise, everything is looking good so far.

**Comment by Revod** [comment]
Read the README, the common issues or see #67

**Comment by mholt** [comment]
Wow, you're right, this is common!

I don't know much about hacking at Sublime (never done it), but is this really hard to fix? Seems odd to me that the bug has been reported in dozens of closed issues but it is still unresolved.

**Comment by equinusocio** [comment]
This is not a theme bug. Sublime doesn't recalculate the new panel size when is much bigger than default one

**Comment by mholt** [comment]
Ah, I see. Thanks for the clarification.

**Comment by atilkan** [comment]
should report this to sublime then.

**Comment by iugo** [comment]
How to fix it: just drag to adjust the input box high.

**Comment by konsumer** [comment]
@iugo perfect, thanks!
