### ISSUE TITLE
The unsaved file icon should be highlighted

### ISSUE THREAD

**Issue by farzher** [equinusocio/material-theme#207]
![image](https://cloud.githubusercontent.com/assets/1005136/8295961/23b892e2-1918-11e5-93a7-ca6ac9b374e6.png)

At a glance, I can't tell if there's any unsaved files.
I was using soda theme before which had a bright orange circle for unsaved files.

![image](https://cloud.githubusercontent.com/assets/1005136/8296009/d424e7c0-1918-11e5-9278-afac2642cfb0.png)

It was really useful. I think you should highlight the pencil icon.

**Comment by equinusocio** [comment]
In the soda theme the tabset bar is very confuse and you can't see the difference between active tab and others.

**Comment by gpessia** [comment]
@equinusocio altri mi dicono lo stesso, ad ogni modo è vero, la sola matita si perder un pochino e non si distingue bene quale file sia stato modificato, sulla barra laterale funziona meglio, la cosa vale sia per Material che per Dark … io una prova ad impostare come colore per le icone dei file in modifica Accent Teal 200 la farei…

**Comment by claudioc** [comment]
:+1: I like orange! :)
