### ISSUE TITLE
Setting for sidebar font size

### ISSUE THREAD

**Issue by djmtype** [equinusocio/material-theme#208]
Is there a setting to resize the font label in the sidebar?

**Comment by LespiletteMaxime** [comment]
+1

I got a little issue on debian, sidebar font is different from my user settings (I use Roboto) 

![Screenshot](http://i.imgur.com/wH1S0mJ.png)

**Comment by feryardiant** [comment]
Have you try [this solution](http://stackoverflow.com/a/25694790/881743)? I found it works for me. Simply create file `[your-theme-name].sublime-theme` inside your `User` dir with content from the link above.
**afaik** you can only change your font.size, but not font.family.

**Comment by djmtype** [comment]
Awesome, thanks. I saw that thread before posting here, but misread it. 
@LespiletteMaxime you can change the font family by adding this line, `"font.face": "Roboto Mono"`

Just to recap, from the top menu, goto Sublime Text > Preferences > Browse Packages…
Create a plain text file inside that directory (with extension **sublime-theme**, *not* **txt**), called **Material-Theme.sublime-theme** (or **Material-Theme-Darker.sublime-theme**). 

Inside declare these rules: 

```
[
{
"class": "sidebar_label",
"font.size": 13,
"font.face": "Roboto Mono"
},
]
```

**Comment by LespiletteMaxime** [comment]
@feryardiant , @djmtype Thanks a lots guys it's works like a charm.

**Comment by gj1118** [comment]
I know I can do it as discussed above, but it would be nice , if it was exposed via theme settings.

**Comment by equinusocio** [comment]
it would be nice, but i can't make a setting for every user request :) Changing the font size of the sidebar label mean resize all padding and tree indentation. I don't want a theme with 192874 "stupid" settings made for a few people. Maybe in the future.

**Comment by feryardiant** [comment]
@djmtype actualy he just update his answer right after I posted here.

**Comment by sundarv85** [comment]
+1 to expose configuration settings for sidebar in theme settings (one more from the few people :) )

**Comment by 181** [comment]
From the top menu, goto Sublime Text > Preferences > Browse Packages... > Material Theme > Material-Theme.sublime-theme , then search for "sidebar_label", add this rule under the class:sidebar_label declaration: "font.size":14" , save it. ah, such a relief for your eyes.

**Comment by equinusocio** [comment]
from the next release it will be a setting for this.

**Comment by sundarv85** [comment]
@equinusocio Was this setting part of 2.0.0 or did you mean 2.0.1

**Comment by equinusocio** [comment]
2.0.0. check the README file
