### ISSUE TITLE
Can't clarify the edge between the output window and the code area

### ISSUE THREAD

**Issue by hjkcai** [equinusocio/material-theme#209]
As you can see in the attached image, there is no separate line or something on the edge between the output window and the code area. I installed this theme, version 1.2.0, through Package Control. Could you please add an option to show a separate line there? I love this theme very very much! Thanks for your great work.
![screen shot 2015-06-23 at 1 16 56 pm](https://cloud.githubusercontent.com/assets/731326/8299399/7ad53a02-19aa-11e5-859e-57776205d6f1.png)

**Comment by equinusocio** [comment]
This is the essential of this theme. Less border = Less distraction. But i will keep in mind in the future
