### ISSUE TITLE
The background of search bar could be transparent

### ISSUE THREAD

**Issue by matthewga0** [equinusocio/material-theme#210]
@equinusocio Could you remove the `white background` to make the search panel unified?

*Light Theme*
![screen shot 2015-06-23 at 13 48 04](https://cloud.githubusercontent.com/assets/133230/8299685/84fe2684-19ae-11e5-85cc-1f9d58ddb21f.png)
*Dark Theme*
![screen shot 2015-06-23 at 13 46 41](https://cloud.githubusercontent.com/assets/133230/8299668/52470814-19ae-11e5-91fe-a13699cc0b66.png)

**Comment by equinusocio** [comment]
If i remove the white bar i have to remove the white panels (cmd+p etc...) because sublime Text allow only one style for input fields.

**Comment by okonomiyaki3000** [comment]
Changing those panels' backgrounds to something darker also gets my vote.

**Comment by matthewga0** [comment]
I agree with @okonomiyaki3000, it's better to reduce the contrast of dark and light.
