### ISSUE TITLE
about Darker theme

### ISSUE THREAD

**Issue by LucianKaltz** [equinusocio/material-theme#211]
Hi, again. Good to see the material theme is rapidly evolving.

It's the darker theme. After the 1.2.0 release the darker theme turns into something with black background. I use it first only to replace the white panel in the normal theme because the white is quiet dazzling in the blue grey background(see the pic below). But now the darker theme has a black background, which is totally another thing. I hope at least there is a setting I could set to have both blue grey background theme and darker panel, etc.

Thanks!

![screen shot 2015-06-23 at 17 58 05](https://cloud.githubusercontent.com/assets/9962217/8303585/7211b8ec-19d1-11e5-917b-ff49a66f7c74.png)

**Comment by equinusocio** [comment]
I will remove the white panel and input in the next release.

**Comment by LucianKaltz** [comment]
@equinusocio great! thank you!
