### ISSUE TITLE
odd color blocks in latest version

### ISSUE THREAD

**Issue by rcrooks** [equinusocio/material-theme#212]
Seeing some odd color blocks - didn't happen till latest version. I'm on ST build 3092. See attached image. By the way, love the theme - best I've seen yet for ST!
![2015-06-23_08-25-11](https://cloud.githubusercontent.com/assets/619617/8305960/c46030c4-1981-11e5-9036-069f77faa427.png)

**Comment by equinusocio** [comment]
Paste your preferences

**Comment by gvinson** [comment]
I believe this error is because the theme is looking for a "Material Theme" folder but the folder is name "material-theme-1.0.2". I duplicated the folder and changed its name to "Material Theme" and it worked.

**Comment by equinusocio** [comment]
You're using an old version... the latest release is 1.2.0. Install the package through the Package Control

**Comment by rcrooks** [comment]
Hi, no, that's not the issue. To be sure, I uninstalled and reinstalled using Package Manager. Also discovered that when I mouse over the odd color blocks, I see the icon that should be there instead. Here are my settings:
{
	"added_words":
	[
		"param",
		"programmatically",
		"transcoding"
	],
	"auto_complete_commit_on_tab": false,
	"color_scheme": "Packages/User/SublimeLinter/Oceanic - Eighties (SL).tmTheme",
	"font_size": 17,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
	"spell_check": true,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_separators": "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
}

**Comment by equinusocio** [comment]
Mmmm you're the only one with this issue. Try to disabling other packages one by one.

**Comment by rcrooks** [comment]
ok
