### ISSUE TITLE
Darker color scheme doesn't match dark theme

### ISSUE THREAD

**Issue by imdevin567** [equinusocio/material-theme#214]
After the most recent update, the new dark color scheme doesn't seem to be matching the dark theme.
![screen shot 2015-06-23 at 9 40 59 am](https://cloud.githubusercontent.com/assets/3077341/8307418/58d72cb2-198c-11e5-9693-317e226533be.png)
It almost looks like the dark color scheme isn't being registered at all. I am running ST3 Build 3083 on a 2013 MacBook Pro Retina.

**Comment by equinusocio** [comment]
You use SublimeLinter or ColorHighlighter?

**Comment by imdevin567** [comment]
@equinusocio I use SublimeLinter

**Comment by equinusocio** [comment]
- Close and reopen all opened file in all ST windows
- Empty Sublime Linter color_scheme cache. (Apply default scheme, restart sublime, reapply Material scheme)

**Comment by imdevin567** [comment]
@equinusocio That did the trick. Thanks!
