### ISSUE TITLE
After upgrading I'm getting Markdown related errors

### ISSUE THREAD

**Issue by thelinuxlich** [equinusocio/material-theme#216]
Getting a lot of "Error loading colour scheme Packages/Material Theme/schemes/Material-Theme-Markdown.tmTheme: Unable to open Packages/Material Theme/schemes/Material-Theme-Markdown.tmTheme"

**Comment by equinusocio** [comment]
You're using the syntax specific markdown preference?

Paste your global preferences and markdown syntax specific preferences.

**Comment by thelinuxlich** [comment]
I don't have any markdown specific syntax preferences, this is my user settings:

https://gist.github.com/thelinuxlich/0e98bd4504e279819a00

**Comment by equinusocio** [comment]
What version are of Material Theme are you using? Have you tried to remove markdown from ignored package?

**Comment by thelinuxlich** [comment]
Enabling the Markdown package did the trick. thanks!
