### ISSUE TITLE
Markdown Editor && Rollover Preferences

### ISSUE THREAD

**Issue by samuelcouch** [equinusocio/material-theme#220]
When I first installed this theme, I thought there was some kind of conflict between material-theme and another package that was causing my markdown files to be bumped to the center of my editor, but this screenshot ![](http://equinusocio.github.io/material-theme/assets/materialtheme3.png)
seems to imply that's intentional. Is there a way to disable this?

Is there also a way to disable the hover-hilighting in the sidebar?

**Comment by equinusocio** [comment]
See #74 for the markdown

**Comment by samuelcouch** [comment]
Thanks!

**Comment by jrappen** [comment]
compare #78, #100, #111, #197 

@equinusocio maybe you could reconsider changing  [prefs/Ext/Markdown.sublime-settings](https://github.com/equinusocio/material-theme/blob/master/prefs/Ext/Markdown.sublime-settings) to only have that single settings for `extensions`?
