### ISSUE TITLE
Quick panel has a weird look after updated to 1.2.1

### ISSUE THREAD

**Issue by whatifhappen** [equinusocio/material-theme#221]
It's appear on darker theme
![image](https://cloud.githubusercontent.com/assets/4222249/8322111/cd00cc84-1a62-11e5-8cf0-ab2b07b3508e.png)

**Comment by seanwash** [comment]
Just a quick thought, have you tried restarting sublime? I know that things always looked jacked after a fresh update for me until I restart it.

**Comment by felixhao28** [comment]
@seanwash It is still jacked after a restart.

**Comment by jensscherbl** [comment]
> It is still jacked after a restart.

Same here.

**Comment by equinusocio** [comment]
lol sorry guys... i will fix this as soon as possible :+1:

**Comment by feryardiant** [comment]
Same here,
This issue seems only appear on **Darker** version.

**Comment by equinusocio** [comment]
I've accidentally deleted some assets
