### ISSUE TITLE
Add option to disable folder animation

### ISSUE THREAD

**Issue by RickLancee** [equinusocio/material-theme#222]
Is it possible to add a setting to disable the folder animation? Something like `"material_theme_disable_folder_animation": true`

**Comment by equinusocio** [comment]
Yes, i will do it.

**Comment by RickLancee** [comment]
Great thanks! i think the new animation looks nice but is slightly distracting

**Comment by equinusocio** [comment]
Yes, but you doesn't hover the folder everytime :)
