### ISSUE TITLE
Rename and new folder panel not seen

### ISSUE THREAD

**Issue by bajzarpa** [equinusocio/material-theme#224]
Sublime 3 (build 3083)
Theme version: 1.2.1 
OS: OSX Yosemite. 
the panels at the bottom are not visible. 
I attached some screens
Of course i tried to restart the sublime
![rename-panel](https://cloud.githubusercontent.com/assets/943893/8324984/e502955e-1a55-11e5-8594-c9eb02010484.gif)

**Comment by jdwillemse** [comment]
same issue and I have Side Bar installed

**Comment by equinusocio** [comment]
Read the README and see #67

**Comment by jdwillemse** [comment]
Yup, fixed it.
