### ISSUE TITLE
Input field not displayed when renaming a file

### ISSUE THREAD

**Issue by atmediauk** [equinusocio/material-theme#225]
When attempting to rename a file using the command palette (```cmd+shift+p```) and (```File: Rename```) a bar does seem to appear at the bottom of the screen but their is no input to type in.

Not sure if this is because the command is specific to the Sidebar Enhancements plugin (https://github.com/titoBouzout/SideBarEnhancements).

Hopefully this can be enabled, thanks for the great theme, it looks very nice.

**Comment by timbog80** [comment]
issue #23

**Comment by atmediauk** [comment]
Ah, apologies I didn't see that.

**Comment by equinusocio** [comment]
And read the README
