### ISSUE TITLE
Rename dialog box is partially hidden

### ISSUE THREAD

**Issue by Alaneor** [equinusocio/material-theme#23]
While renaming files, the rename box seems to be for most part obscured by the status bar at the bottom. Typing blindly works, but I cannot see any of the typed text. See screenshot below (the white strip is the rename dialog box).

Using latest develop branch and the standard theme (not the darker one). Thanks!

![rename box](https://cloud.githubusercontent.com/assets/3058150/8020694/080ccd8e-0c83-11e5-81db-cdfadfa45b3b.png)

**Comment by UsainBloot** [comment]
I believe this is a Sublime Text bug referenced in issue #13

**Comment by Alaneor** [comment]
Ah, indeed resizing works... Okay, I guess we can close this now since the author is aware of it.:) Thanks for help!

**Comment by UsainBloot** [comment]
Anytime, such an annoying bug!

**Comment by schnubor** [comment]
Same issue but resizing doesn't work for me. OSX Yosemite here.

**Comment by Alaneor** [comment]
The resize bar is a bit more above the white strip - have you actually found it...? It took me some time to find the resize handle, but once I moved it up, it worked.

**Comment by schnubor** [comment]
Thanks @Alaneor ! I tried resizing the whole window. Derp.

**Comment by equinusocio** [comment]
This is a sublime bug when you apply a theme with not-standard find/replace panel size. I'm sorry.

**Comment by sineld** [comment]
Resizing worked for me. Thank you.
