### ISSUE TITLE
After material-theme auto-updated itself just now, I have orange icons on OSX

### ISSUE THREAD

**Issue by bentstamnes** [equinusocio/material-theme#230]
See screenshot: 

![image](https://cloud.githubusercontent.com/assets/5342016/8338100/22e75324-1aaf-11e5-98d8-2abb3f7bc2e0.png)

**Comment by br1ckb0t** [comment]
+1, I'm getting the same orange and red bars when I open the command palette.
![screen shot 2015-06-24 at 3 47 33 pm](https://cloud.githubusercontent.com/assets/3687851/8339827/63310848-1a88-11e5-98f4-0e9b6274912b.png)

**Comment by equinusocio** [comment]
@bentstamnes Try a fresh installation
@br1ckb0t Fixed in the latest release (will be available in few minutes)

**Comment by bentstamnes** [comment]
@equinusocio Deleting the MaterialTheme-folder from */Library/Application Support/Sublime Text 3/Packages/User* actually fixed the problem (and exposed the new expanding folder animations).

**Comment by br1ckb0t** [comment]
@equinusocio yep - looks great now after the update! :+1:
