### ISSUE TITLE
PHP namespaces

### ISSUE THREAD

**Issue by vluzrmos** [equinusocio/material-theme#233]
Can you make the php namespaces color more awesome? I really don't like that:

![image](https://cloud.githubusercontent.com/assets/450848/8341256/0bc01380-1a9a-11e5-826d-c6b7b4590e75.png)

**Comment by stephenhowells** [comment]
Mine is looking ok. Maybe close all open files and restart Sublime?

![screen shot 2015-06-25 at 1 40 02 pm](https://cloud.githubusercontent.com/assets/436173/8365077/b3aaad8a-1b3f-11e5-9888-3a6d021d7256.png)

**Comment by vluzrmos** [comment]
I already made many restarts... 
I will check if some package is crashing it

**Comment by equinusocio** [comment]
@vluzrmos you use color highlighter?

**Comment by vluzrmos** [comment]
I found the package, it was "PHP Modern", it is deprecated, so I remove and now looks awesome!

![image](https://cloud.githubusercontent.com/assets/450848/8367246/be8a39ea-1b72-11e5-881c-e55de440c094.png)

Thanks, everyone!

**Comment by equinusocio** [comment]
nice
