### ISSUE TITLE
Material Theme forces re-start due to constant updating

### ISSUE THREAD

**Issue by denisinla** [equinusocio/material-theme#234]
Theres currently a glitch with the theme updating upon launch requiring a reset after a short dialog telling you to restart for Material Theme changes to reflect.

**Comment by equinusocio** [comment]
After every theme install you have to restart sublime.

**Comment by denisinla** [comment]
@equinusocio Initial theme install yes, but subsequently not(apologies if I wasn't clear). 

It seems for me each time I open a new ST3 instance I am greeted with Material Theme resetting to Monokai because of a new update. This would make sense if you were updating it every minute.

Perhaps there might be a glitch with Package Manager auto-updating each time quit ST3?

I will investigate this more when I get a chance.

**Comment by wldcordeiro** [comment]
@denisinla This is common to any theme getting updates. I've had it occur with Seti and Soda themes this issue isn't a material-theme issue but possible a Sublime Text or Package Control issue.

**Comment by sasindumendis** [comment]
Ok it doesn't happen every single time you open ST3, but currently it happens quite frequently as @equinusocio constantly push new updates to the theme :smile:. Since the theme is still relatively new this is usual, but as it get stable this will slow down. We should be thankful to this guy for his efforts to give us all a super awesome theme :+1:.

**Comment by leongaban** [comment]
I've noticed that I have to re-add `"theme": "Material-Theme.sublime-theme",` everytime I open Sublime text the next day. Are updates that frequent that it forces us to do that?

**Comment by equinusocio** [comment]
You have to restart sublime text after every update. Know your editor.. :+1:

**Comment by wldcordeiro** [comment]
@leongaban get the plugin themr you can then do `ctrl+shift+p` and run the list themes command and select Material from there.

**Comment by leongaban** [comment]
@wldcordeiro ok I just installed it and set the user settings to below, will this prevent my Sublime from breaking themes every morning?
```
{
    "theme": "Material-Theme.sublime-theme",
    "color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme"
}
```

**Comment by wldcordeiro** [comment]
@leongaban Whenever a theme updates it's likely to break. It'll just make it easier to change your theme back. Besides you just restart Sublime and all is well.

**Comment by sasindumendis** [comment]
Is it really too much work to just restart the editor?

**Comment by denisinla** [comment]
@sasindumendis It actually doesn't do that upon updating the Material Theme, it completely reverts it back to the default Monokai. You're forced to restart ST3 completely since you can't just type the theme name back into the user preferences.

**Comment by equinusocio** [comment]
@sasindumendis  When revert to monokai you have to wait until update is finished.

**Comment by denisinla** [comment]
@equinusocio No worries, Atom updated, going to try it out for a week. The never-ending love/hate relationship between ST3 and Atom.

**Comment by leongaban** [comment]
This is my problem however, every time I open Sublime Text the next day, it reverts back to the old sublime theme. I quit and restart and it's still the same, I have to manually go find this Github repo, copy the Materialize theme line and paste it into the preferences :( I feel like I have to keep Sublime Text open all the time, which isn't too bad a hack

**Comment by wldcordeiro** [comment]
@leongaban that's just weird and doesn't make much sense. I would report it to the Sublime Text development team though.

**Comment by bbokac** [comment]
Hey guys and girls. Here one solution that works for sure and I will share to all. Linux OS works but I wan't to hear others from other OS to confirm that works. And if all OS works then @equinusocio you can close all this and put solution in readme. Find that file **Preferences.sublime-settings** (~/.config/sublime-text-3/Packages/User for Linux users) and just take away write permission that is it. Be honest you are not changing that file every day so giving just ready permission and take away write permission will not harm you. When you want to make changes you will give temporary write permission till you done and you are done. Next time theme update you will be asked to restart you will restart and that is it, life goes on. No more re adjustment in user configuration file on each update. @equinusocio keep good work! Thanks for the awesome theme and that you keeping up to date.

**Comment by Revod** [comment]
@bbokac I made that change on Windows 10, hope to see a Material theme update soon and test if that work on Windows too, and I think that solution work on OS X because is similar

**Comment by citizenofearth** [comment]
the problem for me is slightly difference.  everyday, sublime updates and reverts back to "theme": "Default.sublime-theme" ... i have to manually change it back to Material theme everyday.  restarting sublime does not set the theme back to Material theme.

**Comment by Revod** [comment]
I don't have anymore the problem because I'm on macOS but you could try changing the permission to your setting file after you configured to read-only and done

**Comment by citizenofearth** [comment]
thank you, i will try that
