### ISSUE TITLE
Creating new file inside specific directory

### ISSUE THREAD

**Issue by djmtype** [equinusocio/material-theme#236]
With other themes, including the Sublime default, it's possible to create a new file by right-clicking on a specific folder inside the sidebar tree. Now, when I try to do it, nothing happens.

In other words, the File Name input with cursor is not popping up from the bottom.

**Comment by Revod** [comment]
are u read the Readme? or #177

**Comment by equinusocio** [comment]
and #67... and may others similar issue.
