### ISSUE TITLE
Missing rollbar on largest files

### ISSUE THREAD

**Issue by vluzrmos** [equinusocio/material-theme#237]
I am not using minimap, then on large files the rollbar is missing.

![image](https://cloud.githubusercontent.com/assets/450848/8346341/6fdc2fa2-1ad1-11e5-96dc-97613bd70d5c.png)

that example file have 2360 lines.

**Comment by timbog80** [comment]
i have a feeling that this might be a sublime text problem. not sure

**Comment by vluzrmos** [comment]
In default theme looks normal:

![image](https://cloud.githubusercontent.com/assets/450848/8347683/7c854c76-1adf-11e5-98bf-16408dc5f75f.png)

**Comment by timbog80** [comment]
oh yea thats a material bug them

**Comment by sasindumendis** [comment]
I can confirm this issue exists for me too.

I think the size of vertical scroll bar goes close to 0 (thus invisible) when the number of lines in the file is large. There should be a minimum height set for the vertical scroll bar to fix this.

See below (with and without the setting `"overlay_scroll_bars": "enabled"`).

![st3-large_file_with_overlay_scrollbars](https://cloud.githubusercontent.com/assets/2373211/8351626/7cdc628c-1b4c-11e5-85bb-c77f65c866d6.png)

![st3-large_file_without_overlay_scrollbars](https://cloud.githubusercontent.com/assets/2373211/8351631/7f8e20e2-1b4c-11e5-8678-d512edd31239.png)

**Comment by equinusocio** [comment]
With the default theme you see the vertical scrollbar?

**Comment by sasindumendis** [comment]
Yes it can be seen on the default theme.

![screenshot from 2015-06-25 23 24 49](https://cloud.githubusercontent.com/assets/2373211/8362035/2cb119c2-1b94-11e5-8d34-68c300241afd.png)

**Comment by vluzrmos** [comment]
Thanks!
