### ISSUE TITLE
Advanced search do not fit into GUI

### ISSUE THREAD

**Issue by albinhallden** [equinusocio/material-theme#240]
As you can see in the image below. The three search bars in the bottom is not visible due to fields being too large. 

![sublime-material-theme](https://cloud.githubusercontent.com/assets/6094750/8349374/749e6244-1b1c-11e5-86c4-0b5c041f1a5b.png)

**Comment by vluzrmos** [comment]
I think you have to resize the panel, that should work!

**Comment by equinusocio** [comment]
...and read the README

**Comment by albinhallden** [comment]
My bad. Did not think of that at all... Thanks for the help!
