### ISSUE TITLE
Theme not applying to sidebar and command fields

### ISSUE THREAD

**Issue by JonathanRe** [equinusocio/material-theme#241]
Theme was installed using package control, all recommended settings were added aswell. The theme is only applied to the editor part of Sublime, the sidebar, any inputs like the command line, package control etc. still have the default look. Running Sublime Text 3 on an x86 Win7.
![image](https://cloud.githubusercontent.com/assets/6652938/8349916/18c487c8-1b21-11e5-939c-85c0d5237a71.png)

**Comment by equinusocio** [comment]
.... restart sublime text...

**Comment by JonathanRe** [comment]
I've restarted the program several times, restarted my machine aswell, doesn't change anything.

**Comment by equinusocio** [comment]
Paste your preference

**Comment by JonathanRe** [comment]
Got it now, I was missing this line:
```
"theme": "Material-Theme.sublime-theme",
```

Thanks!

**Comment by timbog80** [comment]
omg

**Comment by Jangla** [comment]
Err....I have that line and still have un-styled side bar and command windows: http://puu.sh/iDfJy/74ea3b4dcb.png

**Comment by equinusocio** [comment]
you have set both lines?
```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

**Comment by Jangla** [comment]
Yup. You can see both in the screenshot I linked to

**Comment by equinusocio** [comment]
You used package control?

**Comment by Jangla** [comment]
Yes. Also just uninstalled, restarted and reinstalled again. No change.

**Comment by Jangla** [comment]
I've also just done an uninstall via Package Control and a manual install. Same issue: http://puu.sh/iDhof/16d389d9fa.png

**Comment by equinusocio** [comment]
Check you package folder (Preferences > Browse package folder) and check if have Material Theme inside User folder and in Installed Packages folder.

**Comment by Jangla** [comment]
Currently Package folder is: http://puu.sh/iDkqV/7bac65883a.png
And Installed Packages is: http://puu.sh/iDkqV/7bac65883a.png

So it's present in the Package folder and not in Installed Packages

Last attempt was manual install as per instructions.

**Comment by equinusocio** [comment]
Try this:
1. Close ST
2. Remove material by package control
3. Delete al Material Theme folder and files in your packages folder (even installed packages)
4. Restart ST 
5. Install this theme by package control (not manual and not extract it) and apply the theme.
6. Restart ST

**Comment by Jangla** [comment]
OK, done all that. Same problem: http://puu.sh/iDkZR/01cbce5932.png

(I assume you meant 1 and 2 the other way around?)

**Comment by Jangla** [comment]
AHA! Found it - there was a line right at the bottom that wasn't getting scrubbed when settings were changed and was resetting the theme choice!

Time for me to hit your donate button :) 86 Euro from 19k downloads is a depressingly low donation rate. Thanks for the assistance!

**Comment by equinusocio** [comment]
:+1: thanks man :)

**Comment by Jangla** [comment]
You're very welcome. The theme is great.

**Comment by irwinb** [comment]
Just in case someone comes googling here..another silly thing to look for are duplicate theme entries in your settings file. For example, I had the theme set correctly at the top of my settings file, but further down, it was being set again to the default theme 😛.

**Comment by gkumarOB** [comment]
@slashwhatever dude how di u solved it????
same issue .

**Comment by slashwhatever** [comment]
@gkumarOB my issue was the same as @irwinb

**Comment by equinusocio** [comment]
@gkumarOB Just remove these lines from your settings, and reactivate the theme from the command palette:

```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

**Comment by ShubhamGupta** [comment]
Probable issues:
1. You have multiple entries for "theme". Last one overrides others.
2. You have no entry for "theme".
3. "Theme" uses extension `.sublime-theme`. "color_scheme" uses `.tmTheme`. Be aware of this difference. Example value of theme: `Material Solarized Dark.sublime-theme`

Restarting sublime / machine / anything will not help at least on OSX. Not sure about Linux / Windows. Changes appear as soon as you save the config.

Hope this helps.
