### ISSUE TITLE
Syntax highlighting disabled when selecting

### ISSUE THREAD

**Issue by Eiskis** [equinusocio/material-theme#242]
![screen shot 2015-06-25 at 12 12 50](https://cloud.githubusercontent.com/assets/1101002/8351119/8f7a8a04-1b33-11e5-81a0-2c036333fb29.png)

Pretty self-explanatory. When using Materal Theme's color dcheme, this is what you see. Other color schemes do not have this problem. This is a bigger usability issue than you might think since Sublime has very effective and powerful multicursor support and allows users to frequently use advanced selection functionality when editing.

**Comment by sasindumendis** [comment]
I agree, whitening all selected text is a bad idea.

``` xml
<key>selectionForeground</key>
<string>#FFFFFF</string>
```

Needs to be removed.

**Comment by equinusocio** [comment]
Yes i know. But i think you will not recognize the selected text with if mantain the original color. I will check
