### ISSUE TITLE
Trying to rename a file is guesswork!

### ISSUE THREAD

**Issue by michaelsmedley** [equinusocio/material-theme#244]
Hi there

First of all, great theme!

I am having an issue when trying to rename files though.  Renaming does indeed work, however the textarea holding the filename is invisible, so I currently have to guess what I'm typing in.  I thought this may be a conflict with Sidebar Enhancements, but I tried after disabling and still am able to get the issue

To replicate:
1) Open sidebar view
2) Right click and try to rename a file
3) A textarea obviously displays at the bottom, but for me it is blank

Thanks!

**Comment by sociallymellow** [comment]
same error happening for me

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/blob/master/README.md

**Comment by michaelsmedley** [comment]
Bleurgh, my bad - apologies.  A simple read of the landing page has solved it :/
