### ISSUE TITLE
Input size a little big compared to other themes

### ISSUE THREAD

**Issue by ayong-mdsol** [equinusocio/material-theme#248]
This hides the replace input in the hide and replace unless I make my fonts super small.

__All screenshots have the same font size and same Color Scheme (which made the Flatland Theme freak out a little bit)__

Default Theme:
![screen shot 2015-06-25 at 2 33 47 pm](https://cloud.githubusercontent.com/assets/5631435/8362498/437052b0-1b47-11e5-8671-250a3981a7e1.png)

Flatland Theme:
![screen shot 2015-06-25 at 2 33 57 pm](https://cloud.githubusercontent.com/assets/5631435/8362501/4d434ae0-1b47-11e5-96b3-d15fcc701bdd.png)

Material Theme:
![screen shot 2015-06-25 at 2 34 04 pm](https://cloud.githubusercontent.com/assets/5631435/8362505/50a898f2-1b47-11e5-8753-eb00448ec28c.png)

Material Darker Theme:
![screen shot 2015-06-25 at 2 34 10 pm](https://cloud.githubusercontent.com/assets/5631435/8362513/5798f2ba-1b47-11e5-90dd-bd135b4cb927.png)

**Comment by equinusocio** [comment]
You restarted ST after install? ...paste your preferences.

**Comment by ayong-mdsol** [comment]
Oh Sorry, I just found the issue fix to drag the top. Sorry about that :S

**Comment by equinusocio** [comment]
:+1:

**Comment by ayong-mdsol** [comment]
Thanks for this theme btw. My favorite theme so far.
