### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by brooksrelyt** [equinusocio/material-theme#249]
The icons are replaced with orange blocks

**Comment by equinusocio** [comment]
Give more details.

**Comment by brooksrelyt** [comment]
Sorry first post ever. It looks like the folder icons only appear on hover and or if the folder is open. The same thing is also happening with the arrows and exit icons. All of the HTML/CSS file icons look like they are working.

I was following a post from the other day and it looked like you created an update. I tried changing themes and had the same issue with both dark and light. 

![capture](https://cloud.githubusercontent.com/assets/5075282/8363817/92ce1ae2-1b4f-11e5-8862-1ead8c81bb7a.JPG)


The theme looks great by the way, great job!

**Comment by equinusocio** [comment]
Can you paste your preferences?

**Comment by brooksrelyt** [comment]
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/material-theme-1.0.9/schemes/Old-Material-Theme.tmTheme",
	"font_options":
	[
	],
	"font_size": 13,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
		"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme",
	"material_theme_disable_folder_animation": false
}

**Comment by equinusocio** [comment]
You are using an old beta version... remove this package and install the theme with package control

**Comment by brooksrelyt** [comment]
Weird I downloaded that beta version on monday or tuesday. 

I removed and reinstalled the theme. Its working great now. Thanks equinusocio!

**Comment by ajmerainfo** [comment]
I have downloaded new version of package and using below preferences but don't see folder arrow.

{
	"font_face": "Fira Code",
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_numbers": false,
	"margin": 0,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
  	"theme": "Material-Theme.sublime-theme",
   	"overlay_scroll_bars": "enabled",
    "line_padding_top": 3,
    "line_padding_bottom": 3,
    "bold_folder_labels": true,
    "indent_guide_options": [ "draw_normal", "draw_active" ],   // Highlight active indent
}

Below is screenshot: http://prntscr.com/c8t66c
