### ISSUE TITLE
Supporting the highlight_modified_tabs option

### ISSUE THREAD

**Issue by tcaddy** [equinusocio/material-theme#250]
I have the `highlight_modified_tabs` enabled in my Sublime preferences, but it doesn't do anything when I use the Material theme.  Modified tabs appear the same as unmodified tabs.  Is there anyway something could be done to support this option?

(In the out-of-the-box theme, modified tabs appear with an orange font color in the name of tab.)

Thanks for the great theme!

**Comment by equinusocio** [comment]
This is already supported. Modified tabs have a Teal color pencil

**Comment by giovannipds** [comment]
I'd prefer a color to that... =/
