### ISSUE TITLE
Text input for renaming files does not appear

### ISSUE THREAD

**Issue by rileyjshaw** [equinusocio/material-theme#251]
Usually shows up in the bottom-left corner

**Comment by levchik** [comment]
Same issue, here is screenshot of how it looks like. Sublime Text 3, Build 3083, Mac OS X 10.10.3.
Also, it appears this way when you need to type name for a new file or folder or move the file.
Find and similar dialogs look fine though.

**Comment by llaraujo** [comment]
Hi @rileyjshaw , please read the README file. In known-issues section or see #67

**Comment by vluzrmos** [comment]
Just resize the panel

**Comment by rileyjshaw** [comment]
Ah, thanks - sorry for bothering you with this. It's hard to see since there's no border color on the input.
