### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by edonbajrami** [equinusocio/material-theme#252]
When one line of html is bigger than sublime window, horizontal scroll is not showing. Cannot find to drag.

**Comment by equinusocio** [comment]
Thanks i will fix this regression

**Comment by equinusocio** [comment]
I don't have this issue, you use overlay scrollbars?

**Comment by edonbajrami** [comment]
When you scroll horizontally and make changes, horizontal scroll disappear. On hover it doesn't show so I need to move with cursor to show the horizontal scroll bar.

**Comment by equinusocio** [comment]
you use overlay scrollbars setting? You are on OS X?

**Comment by edonbajrami** [comment]
I'm using windows, and use default settings

**Comment by equinusocio** [comment]
Can you try with ```"overlay_scroll_bars": "disabled",``` setting?

**Comment by sasindumendis** [comment]
FYI
I am using ST3 on Ubuntu 14.04 and there seems no issues with scroll bars with or without `"overlay_scroll_bars": "enabled",`

**Comment by equinusocio** [comment]
@sasindumendis because the default settings is "system" and if ubuntu use overlay scrollbars in system windows you don't see any difference between "overlay_scroll_bars": "enabled" and without this setting in your preferences. Try with "overlay_scroll_bars": "disabled",

**Comment by sasindumendis** [comment]
@equinusocio You are right. I was trying to say regardless that specific setting enabled or disabled **horizontal scroll bar** just works without an issue.
