### ISSUE TITLE
Support for alternate Accent!

### ISSUE THREAD

**Issue by Shadeslayer345** [equinusocio/material-theme#253]
Love the design of this app, especially the sidebar-icons. Not a big fan of blue though, would it be possible to change the "Accent Teal" to something a Material Red color (#FF5722)?

**Comment by equinusocio** [comment]
Yes. it's possibile and i will do. At the moment i want to be focused on the light version :)

**Comment by verpixelt** [comment]
Has this been implemented already?

**Comment by equinusocio** [comment]
Noto yet

**Comment by Havock94** [comment]
Hi, I would like to ask what the new accent feature does, because I don't seem to find any change!
Could you please post a screenshot/explain where we should see the accents? Thank you and congrats for the great theme!

**Comment by equinusocio** [comment]
@Havock94 In the readme file you can see how use alternative accent color. Right in the theme settings section

**Comment by Havock94** [comment]
@equinusocio Yes I know how to edit the settings but when I save after I've set the accent color nothing changes... Where am I supposed to see those changes?

**Comment by verpixelt** [comment]
+1
![accent-color](https://cloud.githubusercontent.com/assets/1640079/8869586/c6fea7c6-31e5-11e5-8d04-273ebfd63e72.png)

**Comment by verpixelt** [comment]
Now it works! :+1: Thanks!
