### ISSUE TITLE
Please fix rename file or folder and custom color theme

### ISSUE THREAD

**Issue by zaknight** [equinusocio/material-theme#255]
Please help me.
1. when I rename the file or folder, it does not show.
2. Please change the area into a black (# 000). It's easy to work in the daytime.
3. Similarly Part 2 may change tabs are working to black (# 000), in order to increase the contrast for easy distinction.
Thanks!!!
<img src="http://i.imgur.com/wUkcgr1.png">

**Comment by timbog80** [comment]
oh sh** that font just scared me for life!

**Comment by equinusocio** [comment]
1. Read the README for the fix.
2-3. Ask apple to change their OS X. This is the theme and this is equilibrated for eyes. More contrast =  More eyes stress
