### ISSUE TITLE
Can we add a drop shadow where the code editor meets the folder column?

### ISSUE THREAD

**Issue by kpascascio** [equinusocio/material-theme#256]
Right now it's hard to distinguish lines and boundaries. 

![screen shot 2015-06-26 at 11 53 09 am](https://cloud.githubusercontent.com/assets/7727018/8381488/f3e909cc-1bf9-11e5-93ae-17c4389c4cab.png)

Here's what it would look like with a shadow. 

![screen shot 2015-06-26 at 11 54 43 am](https://cloud.githubusercontent.com/assets/7727018/8381506/2cd538c8-1bfa-11e5-853d-84c5dc406bcb.png)

**Comment by kpascascio** [comment]
or a left border... I think a drop shadow could be conceived as too much. I trust you guys judgement.

**Comment by unlucio** [comment]
+1 for "dropshadow would be too much"
i don't even feel the need of having any separation item, afaik the line numbers are already enough as boundary.

**Comment by sasindumendis** [comment]
This is mostly a matter of individual preference. IMO a subtle indication of panel separation might not be a bad thing after all, for example, a thin border or a very slightly different background colors for each panel wouldn't hurt, but surely a drop shadow will be too much.

**Comment by kpascascio** [comment]
+1 for a slightly different background color @sasindumendis

**Comment by karolyi** [comment]
Using the Monokai-Extended theme (like here)[https://github.com/equinusocio/material-theme/issues/254#issuecomment-115768652] seems to solve this.

**Comment by equinusocio** [comment]
Less border = Less distraction. You really resize the sidebar everytimes? As said before, i will not add border, divider and similar distracting things
