### ISSUE TITLE
Theme update results in default theme

### ISSUE THREAD

**Issue by unlucio** [equinusocio/material-theme#258]
During the last couple of updates for this theme my `theme` and `color_scheme` User preferences got reset to the default monokay stuff.
Tbt I'm not really sure if the problem might be ST#, packageControl or the theme its self and the fix is rather quick so is not that big deal.
Just wondering if anyone experienced the same glitch and perhaps has any idea on what might cause it.

cheers

**Comment by sasindumendis** [comment]
Please refer #234

**Comment by unlucio** [comment]
Yes @sasindumendis @equinusocio , I know I've to restart sublime on theme updates... there's even a pop up telling it...
What I'm saying is my settings are back to the defaults AFTER restarting it.

**Comment by equinusocio** [comment]
after pop up, before restarting, wait some seconds. The theme should be reapply automatically.
