### ISSUE TITLE
The clickable area of the close button on tabs could be bigger

### ISSUE THREAD

**Issue by NicolasParada** [equinusocio/material-theme#259]
I feel that is a little difficult to click the small "x" to close a tab. It could have a bigger clickable area :)

**Comment by equinusocio** [comment]
Try <kbd>ctrl</kbd> + <kbd>W</kbd>

**Comment by NicolasParada** [comment]
Yeah, you could do that...

**Comment by equinusocio** [comment]
The icon have the active area bigger than icon, 5px left and 3px right

**Comment by timbog80** [comment]
i doubt anyone uses the X anyways

**Comment by NicolasParada** [comment]
I dont know... I miss click on it a lot of times. Or maybe a better indication on hover...
