### ISSUE TITLE
Color config for SCSS

### ISSUE THREAD

**Issue by winterwei** [equinusocio/material-theme#260]
After the new release, I had to reselect "SCSS" as the extension of my scss files in order to display the text colors correctly. Otherwise, most texts are set in purple. 

I removed and re-installed the package, but the issue remains. Attached are the screen shots showing that though the extension shows SCSS but the text colors are inconsistent.

![before reselect ext](https://cloud.githubusercontent.com/assets/4032246/8390166/70a130ca-1c54-11e5-96ba-098ee374032e.png)
![after reselect ext](https://cloud.githubusercontent.com/assets/4032246/8390165/709dde3e-1c54-11e5-9d8a-48e88d2c82d4.png)

**Comment by equinusocio** [comment]
You use SCSS package?
https://packagecontrol.io/packages/SCSS

**Comment by HendrikPetertje** [comment]
Same problem for SASS
![screen shot 2015-06-27 at 13 33 51](https://cloud.githubusercontent.com/assets/3583395/8391829/5a4a1148-1cd1-11e5-8b7e-513f40c8031f.png)

**Comment by equinusocio** [comment]
Yes ok, give me more details, @HendrikPetertje   you use SCSS package?

**Comment by baraamashaal** [comment]
+1

**Comment by winterwei** [comment]
@equinusocio Yes, I was using SCSS package, just uninstalled and reinstalled, but issue persists.

**Comment by equinusocio** [comment]
Ok, try to disable it, restart ST and reapply the syntax

**Comment by winterwei** [comment]
Did what you suggested, still the same...

**Comment by YozhEzhi** [comment]
btw. It's not only for SCSS files issue.
![cb56d87d9c](https://cloud.githubusercontent.com/assets/2706062/8402169/4caa82cc-1e41-11e5-9ade-9b22c78fcf7d.jpg)

**Comment by HendrikPetertje** [comment]
This is it:
![screen shot 2015-06-29 at 09 29 42](https://cloud.githubusercontent.com/assets/3583395/8403025/69af505a-1e41-11e5-9a20-281c37d2012a.png)

**Comment by petebarr** [comment]
I'm having exactly the same problem unfortunately, and can't resolve it so I have to uninstall the theme. Was the nicest one around but unusable until this is resolved :-(

**Comment by lukewhitehouse** [comment]
Tried using both the Sass and SCSS packages. Both very buggy. Seems when you got onto a new file it breaks styling for a second, you can go into the bottom right and select SCSS/Sass again and that partially fixes it for the time being (until you open a new file). Also seems to be some provides with the syntax highlighting in general, for example comments starting `// like this` are completely broke

**Comment by frabonomi** [comment]
Having the same problem. 
Indeed selecting again the SCSS syntax (`View -> Syntax -> SCSS` or from the bottom right corner) temporarily solves the problem, but this needs to be done every time you open a Sass or Sassy CSS file.
I'm using the [Sass package](https://packagecontrol.io/packages/Sass), but tested the [SCSS package](https://packagecontrol.io/packages/SCSS) as well and getting the same issue.

Love the theme, I hope this issue will be solved :)

**Comment by equinusocio** [comment]
Have you tried with this packages disabled and using the native syntax?

**Comment by lukewhitehouse** [comment]
@equinusocio there is no native syntax highlighting for Sass

**Comment by HendrikPetertje** [comment]
Can confirm uploaded screeny:
https://transfer.sh/1Ovnq/sass.mov

**Comment by equinusocio** [comment]
OK guys, i will improve scss and stylus color scheme. Be patient :)

**Comment by frabonomi** [comment]
Thanks :) Great work!

**Comment by HendrikPetertje** [comment]
you sir are aweome. where do I send a cup of coffee?

**Comment by equinusocio** [comment]
@HendrikPetertje I'm from itayl, but you can buy me a beer if you want :stuck_out_tongue:

**Comment by petebarr** [comment]
Lovely! Good man!

**Comment by HendrikPetertje** [comment]
will do ;)

**Comment by AntoineBoulanger** [comment]
The last version of the theme breaks the scss syntax sublime wide, in every color schemes.

**Comment by HendrikPetertje** [comment]
@equinusocio It works now and looks awesome! You are one kind of hero!
@AntoineBoulanger try uninstalling material theme and reinstalling it. then apply the theme in your user settings close all open sass files, restart sublime and you are good to go

**Comment by equinusocio** [comment]
@AntoineBoulanger  And if you use Color Highlighter restore the color scheme.

**Comment by frabonomi** [comment]
That was fast! Thanks man :)

**Comment by YozhEzhi** [comment]
Great! My eyes are satisfied so much. :+1:
