### ISSUE TITLE
Rename box do not appear

### ISSUE THREAD

**Issue by Ximore** [equinusocio/material-theme#262]
When I click to rename a file in the sidebar, there is usually a rename box in the bottom of the screen. Currently with material theme I get an empty black box. It is not a big issue, since I can rename it is Finder, but it was a minor thing for a future update.
![skaermbillede 2015-06-27 12 50 41](https://cloud.githubusercontent.com/assets/5268484/8391686/3bb313ac-1ccb-11e5-8d70-a0a442e1b82f.png)
![skaermbillede 2015-06-27 12 50 47](https://cloud.githubusercontent.com/assets/5268484/8391687/3bf4a11e-1ccb-11e5-9339-b28985ca5194.png)

**Comment by equinusocio** [comment]
Read the README.
