### ISSUE TITLE
Color bug with "&"

### ISSUE THREAD

**Issue by Adrastus** [equinusocio/material-theme#263]
Hello,
Thanks for great theme, love it. But have small color bug with &
![ampersand](https://cloud.githubusercontent.com/assets/2177717/8392040/3d841be0-1ce4-11e5-9136-9edf4c78cda5.png)

**Comment by timbog80** [comment]
do you have the right language for the syntac selected at the bottom right?

**Comment by Adrastus** [comment]
Handlebars file (*.hbs), recognized as html in Sublime. not anything special, but this "&" stands out from the general background :)

**Comment by equinusocio** [comment]
ST doesn't support handlebar syntax natively. You have to install "Handlebars" package.
https://github.com/daaain/Handlebars

**Comment by Adrastus** [comment]
Thanks, after install this addon my "&" back to right color :+1:
