### ISSUE TITLE
Add option for Smaller Status Bar

### ISSUE THREAD

**Issue by Harishwar** [equinusocio/material-theme#264]
Could you add option to have smaller status bar while using "material_theme_small_tab" setting.

The status bar looks good with normal tab size.
![screen shot 2015-06-27 at 2 35 02 pm](https://cloud.githubusercontent.com/assets/3648401/8393981/9313fcc4-1cda-11e5-8d50-5137a0ce7d98.png)

It would be nice to have an option to have small status bar while using small tab size.
![screen shot 2015-06-27 at 2 33 49 pm](https://cloud.githubusercontent.com/assets/3648401/8393980/909e578c-1cda-11e5-8972-33bbeee084a3.png)

P.S. Changed background color to show status bar size.

**Comment by equinusocio** [comment]
You should read the README file before open an issue...

**Comment by sasindumendis** [comment]
+1 for smaller status bar!

**Comment by timbog80** [comment]
+1
