### ISSUE TITLE
Color for filepath on Results page

### ISSUE THREAD

**Issue by DieByMacro** [equinusocio/material-theme#267]
Hi,

I'm just wondering if you can make this tiny update, since my work involves a lot of search in thousand of files in project. Currently the filename doesn't look different from the source code lines, they all have the grey. So, can you make the filename stand out with different color that goes along with Material color palette ?

Best,
Duc

**Comment by equinusocio** [comment]
Have you some example taken from other color scheme?

**Comment by DieByMacro** [comment]
This is how it looks like on my comp,
![bb](https://cloud.githubusercontent.com/assets/610234/8405249/4ac8061e-1e7d-11e5-9ee2-e826bf5f51b2.jpg)

Before this, I was using Soda dark theme, and it somehow works like this
![aa](https://cloud.githubusercontent.com/assets/610234/8405265/5b4047f4-1e7d-11e5-86c0-7b8156dde8e4.jpg)

**Comment by equinusocio** [comment]
Thanks, i will add this.
