### ISSUE TITLE
See no bottom panel when using Wrap selection with tag.

### ISSUE THREAD

**Issue by YozhEzhi** [equinusocio/material-theme#271]
Try to select some text in html and go to Edit -> Select - > Wrap selection with tag.
I can wrap word in tag but I see no bottom panel in witch I type tag name/class/id.

**Comment by acadet** [comment]
I have the same issue, when creating a new file. Actually the bottom panel is visible but I suspect the nested content to have the same color than the background.

**Comment by equinusocio** [comment]
Please read the README file.
