### ISSUE TITLE
Folders with stars?

### ISSUE THREAD

**Issue by augbog** [equinusocio/material-theme#274]
What does it mean when my folder has stars? I can't seem to open the folder within the project. 

![screen shot 2015-06-29 at 11 02 25 am](https://cloud.githubusercontent.com/assets/2054339/8414673/816a9ff8-1e4e-11e5-8d8e-7fb7b6bf124f.png)

**Comment by equinusocio** [comment]
These folders are a symlink (Symbolic Link) or another type of folderof another folder insider your computer.

**Comment by augbog** [comment]
Thanks!
