### ISSUE TITLE
White autocomplete menu with the default theme

### ISSUE THREAD

**Issue by kentor** [equinusocio/material-theme#276]
Using the default theme and I am getting the white autocomplete menu. Expected to be the normal background color that fits with everything else

```json
{
  "theme": "Material-Theme.sublime-theme"
}
```

![screen shot 2015-06-29 at 1 23 29 pm](https://cloud.githubusercontent.com/assets/240493/8417592/6ab04218-1e62-11e5-8f34-c67a32bfc979.png)

**Comment by sasindumendis** [comment]
Are you using the white panels add-on?

**Comment by kentor** [comment]
No, panels and inputs are the normal colors. Just autocomplete menu is white

**Comment by equinusocio** [comment]
@sasindumendis with the default theme you still see the white autocomplete menu. My mistake, i will fix this very soon.

**Comment by sasindumendis** [comment]
My bad I didn't test it myself previously before guessing @kentor might have the addon installed. I tested it now and I confirm the issue exists.
