### ISSUE TITLE
Error loading Package SCSS.tmLanguage

### ISSUE THREAD

**Issue by Flyaway87** [equinusocio/material-theme#278]
When I open Sublime Text 3 with Material Theme I get this error:

![scss](https://cloud.githubusercontent.com/assets/8334024/8426061/ba8744ee-1f0c-11e5-9bed-08a916a6a6f6.jpg)

After that, Sublime Text crashes and I'm unable to use the software.

**Comment by Tailzip** [comment]
I have the same error on OS X Yosemite, but Sublime isn't crashing, since today's (yesterday's?) update.

**Comment by Flyaway87** [comment]
Apparently, after a few crashes, ST doesn't crash anymore on my Windows 7, though the error message persists.

**Comment by benjamingrobertson** [comment]
I have the same error, but Sublime isn't crashing. I got my SCSS color syntax back by commenting out this line in my user preferences file, saving it, opening a SCSS file, uncommenting out the line, and then re-opening the SCSS file:

`"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",`

**Comment by Tailzip** [comment]
Weird... I did nothing and the error disappeared, and color syntax is back... :)

**Comment by Flyaway87** [comment]
OK, it seems that closing every tab with .SCSS files, closing ST, and reopening it, it fixes the problem.

**Comment by equinusocio** [comment]
Guys, "know your editor". Sublime Text caching the color scheme for all opened tabs. So if the color scheme get updated you see the old cached color scheme until you close and reopen all tabs.
