### ISSUE TITLE
Too large tabs

### ISSUE THREAD

**Issue by kurtextrem** [equinusocio/material-theme#279]
http://prntscr.com/7n1iwd (Fox theme)
vs
http://prntscr.com/7n1izi
Can you please add an option to make the tabs shrink? My screen isn't too wide, I don't like wasting space.

**Comment by equinusocio** [comment]
Can you please read the README file? ;)

**Comment by kurtextrem** [comment]
You mean the small tabs setting? Yeah, that is enabled, but it doesn't shrink their width.

**Comment by equinusocio** [comment]
Are you serious? :)

**Comment by kurtextrem** [comment]
Yeah. I may have something overseen, but the small tabs setting changes the height. See the screenshots. The fox theme has a dynamic width, while this one seems to have fixed no matter how short the file name is.

**Comment by vluzrmos** [comment]
That is true, but that its a "Fox theme" feature. Would be nice if it was replicated to "Material theme".

**Comment by vluzrmos** [comment]
![image](https://cloud.githubusercontent.com/assets/450848/8442541/096a2c9a-1f56-11e5-924f-7f5ec001c020.png)

**Comment by vluzrmos** [comment]
Oh, now I see, if there are many tabs the sublime text resize the tabs with small contents. That is already cool.
