### ISSUE TITLE
Missing input box for folder name

### ISSUE THREAD

**Issue by JohnHeroHD** [equinusocio/material-theme#280]
When renaming or creating a folder, there is no visible input box.
I can type, and it will save the folder, but I can not see what I am typing.

It happens on Ubuntu 14.04 on Sublime Text build 3092 - I am not sure if the issue only appears on this setup.

These are my settings:
	"theme": "Material-Theme-Darker.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"overlay_scroll_bars": "enabled",
	"line_padding_top": 1,
	"line_padding_bottom": 1,
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"indent_guide_options": [ "draw_normal", "draw_active" ], // Highlight active indent

**Comment by sasindumendis** [comment]
Please read the README (Known Issues)

**Comment by JohnHeroHD** [comment]
Ah, my bad. Dragging it up does indeed show the input, thanks.
