### ISSUE TITLE
Can't see text when renaming a file.

### ISSUE THREAD

**Issue by gib** [equinusocio/material-theme#285]
![rename](https://cloud.githubusercontent.com/assets/94830/8441606/a466f64e-1f36-11e5-918c-f84e1311592a.gif)

**Comment by vluzrmos** [comment]
see the "Know issues" on Readme.

**Comment by vluzrmos** [comment]
just resize the panel.

**Comment by gib** [comment]
I see that now. I had taken care of that with a find, but missed it here. Thank you @vluzrmos!
