### ISSUE TITLE
Renaming files via sidebar not rendering 

### ISSUE THREAD

**Issue by denisinla** [equinusocio/material-theme#287]
When renaming files in the sidebar in ST3 there is no indication window being rendered to let you change the file name, instead it renders blank.

I've attached a movie to better show what is happening:
https://www.dropbox.com/s/ozgwsn0x119hwkd/material-theme-renaming-issue.mov?dl=0

**Comment by equinusocio** [comment]
Thanks. Please read the README file.

**Comment by denisinla** [comment]
@equinusocio Awesome thanks dude!
