### ISSUE TITLE
Issue with icons on MacOs X

### ISSUE THREAD

**Issue by tiwiz** [equinusocio/material-theme#288]
With the settings (as per the screenshot), I have these yellow/red artifacts since the automatic theme update from Sublime Text... Any idea why it happened? :-S

![screen shot 2015-07-02 at 20 57 23](https://cloud.githubusercontent.com/assets/2534841/8485354/4fe81f26-20fd-11e5-9c6a-09f61c98152a.png)

**Comment by equinusocio** [comment]
Post your preferences

**Comment by tiwiz** [comment]
{
	"theme": "Material-Theme.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 13,
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"overlay_scroll_bars": "enabled",
	"indent_guide_options": [ "draw_normal", "draw_active" ]
}

**Comment by timbog80** [comment]
i get this sometimes it did that in my gutters. and i thought it was my gutter color package so i deleted it and it persisted.

**Comment by equinusocio** [comment]
Can you try removing Markdown from ignored package and restart sublime text?

**Comment by equinusocio** [comment]
What version of Material Theme are you using?

**Comment by timbog80** [comment]
I think in my case it was the gutter color package that was causing this:

http://puu.sh/iLETg/28fd2d4d6d.png

**Comment by equinusocio** [comment]
I don't thinks this is a package issue. I this is a issue with theme installation.

**Comment by timbog80** [comment]
I just updated the theme (well it updated by itself). and some icons arent working properly:
![Alt Text](http://puu.sh/iPqGr/79ccc6ce81.png)

**Comment by equinusocio** [comment]
#249 #71
