### ISSUE TITLE
Weird colors for .php files

### ISSUE THREAD

**Issue by Sheraff** [equinusocio/material-theme#29]
All files seem to use a coherent color scheme (with the exception of .js files but I'm assuming it's because of Javascript Ultimate) but .php files:

![screen shot 2015-06-07 at 12 23 38](https://cloud.githubusercontent.com/assets/1325721/8023545/7aab349c-0d10-11e5-83fb-3e76d8f83a2c.png)
![screen shot 2015-06-07 at 12 23 09](https://cloud.githubusercontent.com/assets/1325721/8023546/7aaed994-0d10-11e5-8a93-6d79dadefcba.png)
![screen shot 2015-06-07 at 12 23 29](https://cloud.githubusercontent.com/assets/1325721/8023547/7ab0cbf0-0d10-11e5-9ccc-4a8cd0211f7e.png)
![screen shot 2015-06-07 at 12 23 16](https://cloud.githubusercontent.com/assets/1325721/8023548/7ab20dd0-0d10-11e5-8c04-09f6bfacd1c9.png)

**Comment by equinusocio** [comment]
the php file now looks like this:
![schermata 2015-06-07 alle 13 45 58](https://cloud.githubusercontent.com/assets/10454741/8023804/9916b89c-0d1b-11e5-8da5-f1081a3f262d.png)

**Comment by Sheraff** [comment]
Cool, just saw your commit https://github.com/equinusocio/material-theme/commit/6d70225e94c01480bceff79dba80f397c41a3471. Looks nice.

**Comment by cve** [comment]
My colors in PHP looks different and wired:

![1](https://cloud.githubusercontent.com/assets/594384/8124566/2e489fba-10dd-11e5-90c5-abf4eaf54b70.png)
![2](https://cloud.githubusercontent.com/assets/594384/8124567/2e4ac3c6-10dd-11e5-9ed2-328aa4be0dea.png)

I'm using latest Wheezy

**Comment by johnRivs** [comment]
My php files look different as well. Sublime Text 3 build 3083 Windows 7.
http://i.imgur.com/oioq68P.png

**Comment by equinusocio** [comment]
I'm working on a new syntax scheme. I'm not a back-end developer so if you want send me some file example.

**Comment by johnRivs** [comment]
The one you showed looks awesome ![](https://cloud.githubusercontent.com/assets/10454741/8023804/9916b89c-0d1b-11e5-8da5-f1081a3f262d.png)

Here are a couple of php files: http://laravel.io/bin/GyyRk http://laravel.io/bin/bEE4J

**Comment by equinusocio** [comment]
Pls check if you have a cached color scheme by Sulbime Linter or Colorhighlighter packages.

**Comment by johnRivs** [comment]
Now that you mention it, as soon as I save the user settings file, the "color_scheme" key turns into "Packages/User/SublimeLinter/Material-Theme (SL).tmTheme". How do I prevent this?

**Comment by equinusocio** [comment]
Try to disable SublimeLinter, restart Sublime Text, and then enable the linter.

**Comment by johnRivs** [comment]
I tried downloading a zip of the master branch, installing material theme via package control.. no luck :(

I cleared the cache for sublime linter, I disabled the package throughout the process and I still see the same colors. Do I need to download the develop branch?

**Comment by equinusocio** [comment]
I'm working on develop branch. My coworkers still to see the old color (same as you), i don't know why. Pls try the develop branch (remember to remove it)

**Comment by johnRivs** [comment]
I used the Testing color theme included in the same directory. Now it looks different.

**Comment by equinusocio** [comment]
Remember that the testing color scheme aren't official and not complete. You tried to re-enable Material-Theme schema?

**Comment by johnRivs** [comment]
Doesn't work =/

**Comment by JasonLeeH** [comment]
This is still a problem.
