### ISSUE TITLE
Input for typing name in sidebar Create new file or folder  is hided

### ISSUE THREAD

**Issue by cmoon2000** [equinusocio/material-theme#291]
I cannot see clear input in Linux. Of course I still type and work with it. But it's for beauty

![1](https://cloud.githubusercontent.com/assets/6170794/8508727/eab551c8-22a5-11e5-9ea7-258bd9771d84.png)
![2](https://cloud.githubusercontent.com/assets/6170794/8508740/924a5014-22a6-11e5-8e53-d1c6bb188714.png)

**Comment by ridewn** [comment]
Please read through all of the readme before posting issues, the readme has an answer for this issue :] 

https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif

**Comment by equinusocio** [comment]
And remember to use the darker syntax with the darker theme ;)

**Comment by cmoon2000** [comment]
@ridewn easy fix. Thank you so much

**Comment by cmoon2000** [comment]
@equinusocio Yes I don't use darker syntax. When using darker, open json file. It's black of background color. Can say that I prefer lighter. So default syntax work nice in that case!
