### ISSUE TITLE
Problem with colors

### ISSUE THREAD

**Issue by brcomdiego** [equinusocio/material-theme#293]
Hey. :)

I have a prolem with one color on the Material Theme. It isn't changing the color where I'm writing the code.
![bug-materialtheme](https://cloud.githubusercontent.com/assets/8544724/8509577/b7ad39f0-2280-11e5-9f33-0fe2827302d3.png)

**Comment by equinusocio** [comment]
Close all opened tabs and reopen it. Know your editor :)
