### ISSUE TITLE
rename file

### ISSUE THREAD

**Issue by robnagel** [equinusocio/material-theme#294]
If you right-click a file and select "Rename..." you won´t be able to see the text you are writing and also if you right-click to a folder and select "New File..."

**Comment by robnagel** [comment]
ok, there is a hidden field at the bottom of the editor... if you drag the cursor there it shows the field where you can see the text. After you do it once the input field stays there. Strange behavior... but solved.

**Comment by vluzrmos** [comment]
Just resize the panel. 
Or read the section "know issues" on readme.md

**Comment by equinusocio** [comment]
thanks @vluzrmos
