### ISSUE TITLE
Disable tabs scroll arrows and selection icon

### ISSUE THREAD

**Issue by gerardroche** [equinusocio/material-theme#295]
![scroll_tabs_left_right_arrows](https://cloud.githubusercontent.com/assets/44148/8512274/c8968ede-2333-11e5-8422-c422fc2f0dde.png)

Is it possible to disable these. I don't think I've ever used these, they just steal screen real estate.

**Comment by vluzrmos** [comment]
:+1:

**Comment by equinusocio** [comment]
This is a Sublime Text question. Please know your editor :)

```json
"enable_tab_scrolling": false,
```

**Comment by vluzrmos** [comment]
Cool! Thanks! 

:smile:

**Comment by gerardroche** [comment]
@equinusocio u rock!
