### ISSUE TITLE
Only show close tab icon on hover

### ISSUE THREAD

**Issue by gerardroche** [equinusocio/material-theme#297]
![close_tab](https://cloud.githubusercontent.com/assets/44148/8512328/4ae7b0c4-2335-11e5-9f51-0b3cd79cc785.png)

Is is possible to only show the close icon on hover?

**Comment by vluzrmos** [comment]
:+1:

**Comment by equinusocio** [comment]
Non you can't. You can only hide completeley the close button, and again, know your tools ;)
```json
"show_tab_close_buttons": false,
```
