### ISSUE TITLE
Darker Theme: There is actually no high light!

### ISSUE THREAD

**Issue by PDXIII** [equinusocio/material-theme#298]
Hello!

Your theme is very beautiful, but could you please take care about they issue?

As you can see in the image below, the first paragraph is highlighted and the second is not. 

![materialtheme-hightlight](https://cloud.githubusercontent.com/assets/415557/8524906/2ac40724-23fe-11e5-8bf9-e8d2c17de1e5.png)

I would not recognize the difference if would not know about it. Could you?

Best regards,
Pete

**Comment by equinusocio** [comment]
Are you using the darker color scheme?

**Comment by equinusocio** [comment]
![screen shot 2015-07-06 at 17 05 19](https://cloud.githubusercontent.com/assets/10454741/8525446/3956268e-2401-11e5-88bc-2c0403f082d9.png)

**Comment by PDXIII** [comment]
Yes I use the ”Darker Theme“. 

![materialthemehighlight-02](https://cloud.githubusercontent.com/assets/415557/8525619/4bd10d5a-2402-11e5-998e-cd376b86ad92.png)

But honestly the highlight in the lighter theme is just slightly better.
Sorry to say that. No offense!

**Comment by equinusocio** [comment]
Can you paste your preferences?

**Comment by baraamashaal** [comment]
same issue 
my preferences - > 
 ```
{
	"afn_valid_scopes":
	[
		"string",
		"css",
		"sass",
		"less",
		"scss",
		"jade"
	],
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"font_face": "Monaco",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 8,
	"ignored_packages":
	[
		"JavaScript",
		"Vintage"
	],
	"material_theme_disable_fileicons": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_small_tab": true,
	"tab_size": 2,
	"theme": "Material-Theme-Darker.sublime-theme"
}
```

**Comment by MariusStuparu** [comment]
You can change the `Material-Theme-Darker.tmTheme` file, at line 30:
````
<key>selection</key>
<string>#61616120</string>
````
I've put `<string>#61616190</string>` and it looks better (changed the opaqueness from 20 to 90)

**Comment by equinusocio** [comment]
@MariusStuparu  No i can't. Because i see much more contrast with the actual color. I see different highlight color from my screenshot and others. So there are a color scheme issue with other ST.

Are you using Color Highlighter package?
