### ISSUE TITLE
Error after initializing theme

### ISSUE THREAD

**Issue by Kail0** [equinusocio/material-theme#3]
Hi,

I'm getting error when I'm trying to load this theme 
-"Error loading colour scheme
Packages/material-theme/schemes/Material-Theme.tmTheme: Unable toopen Packages /material-theme/schemes/Material-Theme.tmTheme"

**Comment by Kail0** [comment]
Ok, I'm sorry, my mistake - I was pasting it inside /Packages in root directory, that's the mistake. The right path is \Data\Packages

**Comment by smashkins** [comment]
it should be clear to mac users that theme folder should be move inside ~/Library/Application Support/Sublime Text 3/Packages/  folder

**Comment by equinusocio** [comment]
Preferences > Browse Packages > <kbd>cmd</kbd> + <kbd>v</kbd>
