### ISSUE TITLE
Check for update - OK button has same colour as background

### ISSUE THREAD

**Issue by Alaneor** [equinusocio/material-theme#30]
Not sure if this is by design...

The OK button on the "Check for update" dialog box is either fully transparent or has the same background colour as the rest of the dialog box, making it somewhat hard to spot. Hovering over the button highlights it, so that's ok.

![ok button](https://cloud.githubusercontent.com/assets/3058150/8023799/00104154-0d1b-11e5-8be0-e3919b212201.png)

**Comment by equinusocio** [comment]
This is designed to have the same background color. This is not a frequently action.

**Comment by Alaneor** [comment]
Okay! It's just that whenever I see some material design buttons they kind of step out with different colours and shadows etc.

**Comment by equinusocio** [comment]
Yes, i'm working on interaction and updating some assets
