### ISSUE TITLE
what about some heightlight for right side of css property 

### ISSUE THREAD

**Issue by baraamashaal** [equinusocio/material-theme#300]
can you heightlight right side off css property
![screenshot from 2015-07-07 02 08 27](https://cloud.githubusercontent.com/assets/8444762/8536114/1492fab0-244d-11e5-80b9-60dbd76ac122.png)
i'm using scss

**Comment by equinusocio** [comment]
No, i'cant. Sorry. Use another color scheme if you want some distracting things
