### ISSUE TITLE
Contextual actions panel is hidden by status bar

### ISSUE THREAD

**Issue by dharmastyle** [equinusocio/material-theme#301]
`Find all`, `Rename…` and other commands that opens the bottom panel are overlayed by status bar instead of being stacked
![Screenshot](https://cloud.githubusercontent.com/assets/327793/8541398/2190bd9c-248e-11e5-8cb3-7461ae95a341.png)

**Comment by equinusocio** [comment]
Read the README file please. ;)

**Comment by dharmastyle** [comment]
Thank you, didn't see it :|
