### ISSUE TITLE
no more classic colors

### ISSUE THREAD

**Issue by kylegoines** [equinusocio/material-theme#302]
the theme just updated and got rid of my theme colors, i really liked the older ones. i find the php next to the html tags to garrish. do you have plans to reissue old theme colors?

**Comment by equinusocio** [comment]
You mean color scheme?

**Comment by kylegoines** [comment]
Yes sorry, you've deleted the old color scheme. I really enjoyed the muted
colors and the difference between php and html tags

**Comment by equinusocio** [comment]
Sorry but the old color scheme wasn't official and is unsupported. I will no add it anymore. If you have issues (problems) with che color scheme open a dedicated issue. :wink:
