### ISSUE TITLE
Page rename input too low to see

### ISSUE THREAD

**Issue by bernardodsanderson** [equinusocio/material-theme#303]
When right clicking on a file and renaming it, the input is mostly hidden in the bottom, and you can't see what you're typing.

<img width="737" alt="page--tv_tpl_php_ _fcc-drupal-cms" src="https://cloud.githubusercontent.com/assets/5623786/8557599/fb787f38-24c3-11e5-8ba2-99ccf930810e.png">

**Comment by vluzrmos** [comment]
Just resize the panel once.

That is on "know issues" on readme.md

**Comment by vluzrmos** [comment]
![](https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif)

**Comment by bernardodsanderson** [comment]
That fixed it, thanks!
