### ISSUE TITLE
No icon for Gulpfile.js

### ISSUE THREAD

**Issue by sotojuan** [equinusocio/material-theme#304]
First of all, thanks for the theme. It's great!

Some time ago, the icon for a Gulpfile stopped working—it's now just a regular JavaScript icon. I've tried reinstalling the theme (to fix a missing `.gitignore` icon) and it did not work. It's not a big deal, but I could swear it worked a few weeks ago.

I have tried it with both `Gulpfile.js` and `gulpfile.js` as the names.

![screen shot 2015-07-08 at 5 51 07 pm](https://cloud.githubusercontent.com/assets/8217766/8584211/052afebc-259a-11e5-9fcf-92db2938c8f8.png)

**Comment by equinusocio** [comment]
Thanks i will check :+1:

**Comment by Gerst20051** [comment]
what about gulpfile.coffee files?
