### ISSUE TITLE
Brighter colour for inactive tabs

### ISSUE THREAD

**Issue by maxifick** [equinusocio/material-theme#305]
First: this theme is just epic, thanks for the great work!

Inactive tabs seem a bit too dim to me. For myself I have overridden the colour in the theme file, but this is reset on every theme update. Would it be possible to add a preference for this?

My settings are as follows:

    "class": "tab_label",
        "fg": [135, 162, 160, 255],

My display colours are possibly just all messed up, but still I thought someone else could welcome this.

**Comment by equinusocio** [comment]
Sorry, i can't make a setting only for this. But if you want to keep your edits when updating you can follow this steps:

1. Go to your ST packages folder
2. Make a folder called ```Material Theme```
3. Put inside a file called ```Material-Theme-*``` with ```.sublime-theme``` extension. (Replace * with with the style of the active theme)
4. Inside this file paste this:
```json
{
	"class": "tab_label",
	"fg": [135, 162, 160, 255],
},
```
5. Save and restart ST. This should work.

**Comment by maxifick** [comment]
Thanks for the suggestion. I did that, it indeed does change the tab colour, but also it breaks the entire theme. The sidebar is all black, current tab lost highlight, and overall everything got messed up.

Do you want me to paste in a screenshot of what happened?

**Comment by equinusocio** [comment]
Oh sorry, my mistake. Try to rename the ```Material Theme``` folder by adding some suffix like ```-mod```. If you use the same name folder ST will load it instead of the packed version... so he will find only a rule inside.

**Comment by maxifick** [comment]
Woohoo, that did it. Big thanks!

**Comment by equinusocio** [comment]
you're welcome!
