### ISSUE TITLE
Bug with Gutter Color package (incorrect colors)

### ISSUE THREAD

**Issue by xeroxoid** [equinusocio/material-theme#306]
Hi,  it seems that some overlay of the theme is causing the colors of the gutter (via the [Gutter color package](https://packagecontrol.io/packages/Gutter%20Color)) to be incorrect.

As seen here:

![screen shot 2015-07-10 at 16 44 09](https://cloud.githubusercontent.com/assets/1199451/8620002/5c94ac7a-2725-11e5-8c98-67af358b8e57.png)

Excellent them by the way! Thanks!

**Comment by equinusocio** [comment]
Please see https://github.com/ggordan/GutterColor#icon-tinting-and-light-color-schemes

You have to launch the ```GutterColor: Fix Current Color Scheme``` command.

**Comment by xeroxoid** [comment]
Thanks!
