### ISSUE TITLE
No prompt when creating new file

### ISSUE THREAD

**Issue by searsaw** [equinusocio/material-theme#307]
I noticed that when creating a new file by selecting "New file..." after right clicking on a folder in the tree menu, no prompt shows up at the bottom of the screen.  However, if I type something and then hit Enter, it creates the file.  It appears the functionality is there, I just can't see what I'm typing.

**Comment by vluzrmos** [comment]
Resize the panel once. 
That is a "know issue"  on readme.

**Comment by searsaw** [comment]
Nice.  That worked. I didn't see that part of the README. Thanks!

**Comment by equinusocio** [comment]
@vluzrmos :+1:
