### ISSUE TITLE
More from Material Design guidelines

### ISSUE THREAD

**Issue by Sheraff** [equinusocio/material-theme#31]
I believe one of the main recommendations of Google on their Material Design guidelines is to use **motion** to convey meaning and provide feedback on most actions. It'd be good to have some here. It feels kind of lacking animations when switching tab, showing & hiding the sidebar or the minimap or the search fields, popping the command palette...

Also, a little more contrast with **elevation** (basically just box shadows) could bring something. For example the command palette very well designed in this sense!

**Comment by equinusocio** [comment]
You're right. But remember that we are on a software and some things are impossible to make with a "simply" theme. I will study some interaction to implement in the next beta releases
