### ISSUE TITLE
Input for write name in new folder

### ISSUE THREAD

**Issue by Deivide** [equinusocio/material-theme#310]
When I click in new folder on my project opened in sublime, the input for write name of new folder not shown.

![folders-sublime](https://cloud.githubusercontent.com/assets/905281/8631326/e4a846fc-2749-11e5-9966-35aeb8dcd6cd.jpg)

**Comment by vluzrmos** [comment]
Just resize the panel at the bottom once.

And read the "known issues", on readme.

**Comment by Deivide** [comment]
I read, and for me not show any panel. Only for the search panel appears.

**Comment by Deivide** [comment]
Funny, I had done it for search, but in the creation of the folder just I forgot to address this way.

Sorry.
