### ISSUE TITLE
Icons in the Open Files section in the sidebar do not have icons

### ISSUE THREAD

**Issue by varkor** [equinusocio/material-theme#311]
![image](https://cloud.githubusercontent.com/assets/3943692/8633357/8dba5a20-27bb-11e5-9cdc-38c4904ee649.png)
Although files in the Folders menu look great, in simply the Open Files section there is no icon indication of the filetype. Additionally, the green dot overlaps the Close File icon and is not vertically centred (although this may be intentional?). Would it be possible to given Open Files the same appearance as files under Folders?

**Comment by equinusocio** [comment]
I can't add file type icons to the opened files. This is a ST functionality, and at the moment the icon apear only in the file tree.
