### ISSUE TITLE
Light Theme Rendering Issue

### ISSUE THREAD

**Issue by wldcordeiro** [equinusocio/material-theme#317]
The light theme seems to have some issues with the fonts in the sidebar. I'm getting results like this. Rather than what you have in your screenshot.
![snapshot6](https://cloud.githubusercontent.com/assets/580982/8636071/74ceb28c-280a-11e5-8883-f8037d415ed7.png)

**Comment by equinusocio** [comment]
Can you paste your preferences and installed packages?

**Comment by wldcordeiro** [comment]
Preferences

```json
{
	"always_show_minimap_viewport": true,
	"auto_complete_commit_on_tab": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 2,
	"caret_extra_top": 2,
	"caret_extra_width": 1,
	"color_scheme": "Packages/User/Color Highlighter/themes/material-dark.tmTheme",
	"default_line_ending": "unix",
	"detect_slow_plugins": false,
	"drag_text": false,
	"draw_minimap_border": true,
	"draw_white_space": "all",
	"findreplace_small": true,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		"__pycache__",
		".tox",
		".tx",
		"tmp",
		"node_modules",
		"bower_components",
		".sass-cache",
		".idea",
		"*.egg-info"
	],
	"font_face": "Source Code Pro",
	"font_options":
	[
	],
	"font_size": 9,
	"git_executables":
	{
		"git":
		[
			"git"
		],
		"git_flow":
		[
			"git flow"
		],
		"gitk":
		[
			"gitk"
		],
		"legit":
		[
			"legit"
		]
	},
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Makefile",
		"Vintage",
		"RestructuredText"
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"material_theme_small_tab": true,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"rulers":
	[
		80,
		100
	],
	"scroll_past_end": false,
	"show_line_endings": true,
	"sidebar_large": true,
	"tab_completion": true,
	"tabs_medium": true,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"vintageous_use_ctrl_keys": true,
	"word_separators": "./\\()\"'-_:,.;<>~!@#$%^&*|+=[]{}`~?",
	"word_wrap": "false"
}
```
Do you know of a way to get a list out of Package Manager? I have quite a few.

**Comment by gj1118** [comment]
have you restarted ST after changing the theme ?

**Comment by equinusocio** [comment]
You preferences are a bit messy. You have some preference from other theme. You are using the Darker color scheme, but your in screenshot your scheme is white.

**Comment by wldcordeiro** [comment]
What preference is from another theme? I had taken the screenshot before I changed back to the dark because of the weird drop shadow on the folder names. @equinusocio

**Comment by equinusocio** [comment]
@wldcordeiro So changing the color scheme fixing this?

**Comment by wldcordeiro** [comment]
@equinusocio No, it's only the sidebar that seems to be affected by this. I'm not sure what's causing the drop shadows.

**Comment by equinusocio** [comment]
@wldcordeiro With other theme darker and default you sede the dame issue?

**Comment by equinusocio** [comment]
Please post your ST build and try to update it

**Comment by wldcordeiro** [comment]
I'm on build 3095 on Kubuntu 15.04.

**Comment by equinusocio** [comment]
This appen only with the lighter style and not with default and darker?

**Comment by wldcordeiro** [comment]
Yeah only the light style is affected.

**Comment by equinusocio** [comment]
MM i can't reproduce this issue. It's hard for me to fix this now. Try to disable color highlighter package and check if you don't have any material folder inside packages directory
