### ISSUE TITLE
Issue with sidebar enhancement plugin

### ISSUE THREAD

**Issue by AminulBD** [equinusocio/material-theme#318]
Thank you for the awesome theme. This theme has some issue when i use sidebar enhancement plugin of sublime.

When i try to create new folder or file it the input field doesn't show. also has some problem with searching features.

Thanks!

**Comment by limenet** [comment]
@AminulBD 
> When i try to create new folder or file it the input field doesn't show.

Please see the [known issues](https://github.com/equinusocio/material-theme#known-issues) or #67. This bug has been around for quite some time and that's the way you can fix it (it also applies to find/replace, rename etc.). I hope that helps!
