### ISSUE TITLE
Black and white files icons

### ISSUE THREAD

**Issue by gerardroche** [equinusocio/material-theme#324]
An option to have to have black and white (grey-scale) file icons rather than current colour ones.

Also, atom editor icons appears much sharper: 

![96e416e8-da24-11e4-995c-00dcd84c276d](https://cloud.githubusercontent.com/assets/44148/8639658/e73daf8e-28d8-11e5-82eb-e89e7bf56358.png)

See Atom One Dark UI https://github.com/atom/one-dark-ui
See Icons used by Atom One Dark UI https://atom.io/packages/file-icons
See Github Octicons https://octicons.github.com/

**Comment by vluzrmos** [comment]
:+1:

**Comment by equinusocio** [comment]
Sorry, i can't make this on ST. I can use only one set of icons and i can't control it with an option. This is a ST limitation.

**Comment by ctf0** [comment]
@equinusocio for doing so we will need to use something like `SublimeSyncedSidebarBg` which saturate the sidebar icons like https://github.com/aziz/SublimeSyncedSidebarBg/issues/4, check https://github.com/aziz/SublimeSyncedSidebarBg/blob/master/SyncedSidebarBg.py on line @53

**Comment by equinusocio** [comment]
sublime text read automatically the icons by their name. i don't have any path to set. i don't know pyton so if someone want to help i'm open to PR and project rebuild with some python logic

**Comment by ctf0** [comment]
there no path to set, its basically some python logic that saturate the color of files and their icons, anyway i will try something with it once the issue is resolved by aziz.
