### ISSUE TITLE
No comment color for .scss 

### ISSUE THREAD

**Issue by enygmatik** [equinusocio/material-theme#325]
No comment color for .scss files and ``` :after ``` pseudo-element look strange in default color scheme.
<img width="534" alt="screenshot 2015-07-12 22 45 53" src="https://cloud.githubusercontent.com/assets/5849018/8639682/75f2baec-28ea-11e5-910e-d6aac98e4b1a.png">

**Comment by Revod** [comment]
I change the syntax from scss to sass and work 100%, i don't know what happen with scss

**Comment by equinusocio** [comment]
@enygmatik can you use the Sass package until i will fix this.

**Comment by equinusocio** [comment]
@enygmatik  The SCSS package latest update is **1 year ago**. I will no fix this, use [SASS](https://packagecontrol.io/packages/Sass) package instead.
