### ISSUE TITLE
Vertical Tab Separators

### ISSUE THREAD

**Issue by joezimjs** [equinusocio/material-theme#329]
When you have a lot of tabs open and have `"enable_tab_scrolling": true` setting, then tabs are cut off and hidden without any indication there is something there:

![material-theme-issue](https://cloud.githubusercontent.com/assets/1313898/8653529/66d5062c-294a-11e5-805e-b77f1b39e6eb.png)

Behind the tab that is simply showing "pa" as the label, there is another tab, but it's impossible to see. If there was a border to the left and right of the tabs, you would be able to see there are more files over there, just like you can with the default theme:

![material-theme-issue-default-theme](https://cloud.githubusercontent.com/assets/1313898/8653638/077b73ae-294b-11e5-9bee-6d7d6655814c.png)

This might be the one issue preventing me from making the switch to this otherwise beautiful theme.

**Comment by equinusocio** [comment]
Material Theme doesn't have tab separators. However you can personalize your theme by following this steps:

https://github.com/equinusocio/material-theme/issues/305#issuecomment-120479395

**Comment by joezimjs** [comment]
It'd be wonderful to have as an option, though I can see why you might exclude it, since the Material Design guidelines don't use separators, but they also recommend implementing the scrolling of tabs differently than ST does, so it might be a good idea to add an exception to make up for ST's lack of compliance with the guidelines. Let me know.

**Comment by equinusocio** [comment]
I will consider it

**Comment by joezimjs** [comment]
Thanks
