### ISSUE TITLE
Sidebar files and folders labels on Lighter Theme

### ISSUE THREAD

**Issue by vluzrmos** [equinusocio/material-theme#330]
I actually use the default theme, I just choose to test the Lighter theme and then...
I think that is not the correct colors / style for files and folders name:

![image](https://cloud.githubusercontent.com/assets/450848/8655474/a569c68a-2967-11e5-8021-ace102681703.png)

**Comment by vluzrmos** [comment]
Darker and Default theme looks awesome.

**Comment by vluzrmos** [comment]
SO: Ubuntu 15.04
ST 3 Build 3083

**Comment by equinusocio** [comment]
Duplicate of #317.
