### ISSUE TITLE
emmet and create file folder name input overlay

### ISSUE THREAD

**Issue by yashdeeph709** [equinusocio/material-theme#331]
Hey guys I am using material-theme for sublime text I am using st3 here and  we have a problem when  ever I create a file or folder or use the emmet plugin the name input is overlayed by something I can't figure out anything about it but really you guys should see this.
![bugmaterial](https://cloud.githubusercontent.com/assets/6427291/8657838/9f73a718-29bd-11e5-8d79-7e93fdcc5687.png)

**Comment by yashdeeph709** [comment]
I am talking about the white line you can see on bottom

**Comment by krange** [comment]
I see a similar issue except I see no interface when attempting either option (create file or folder).

<img width="1440" alt="screen shot 2015-07-13 at 12 27 24 pm" src="https://cloud.githubusercontent.com/assets/189278/8658755/a31c6ca0-295a-11e5-8668-917506456e05.png">

**Comment by equinusocio** [comment]
Please, read the README file :+1: Known issue
