### ISSUE TITLE
Overlay scrollbar White background

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#332]
Hi, 

I use Overlay Scrollbars : enabled along with the light theme. The sidebar scrollbar control when hovered changes the background color to white and stays white. If you look very closely (where the scrollbar actually starts its white). 

Please let me know if you would like me to post more screenshots to further demonstrate the issue. 

![image](https://cloud.githubusercontent.com/assets/473101/8657934/92da4f9c-296e-11e5-840e-f68da453d782.png)

thanks

**Comment by equinusocio** [comment]
After a bit the white background should be disappear. I could totally disable it when using overlay scrollbbars

**Comment by mikerockett** [comment]
It seems that if you enter the folder pane and scroll with the wheel, the white background doesn't appear. The second you move the mouse over the bar, the white panel appears...

**Comment by equinusocio** [comment]
Yes, this is correct. Is a hover effect

**Comment by gj1118** [comment]
Can this be turned into an option, please ? The option would enable the users to revert to transparent background color. 

Thanks

**Comment by equinusocio** [comment]
Astatus bar background option isn't necessary...

**Comment by gj1118** [comment]
that white color is a distraction, however.. :(
