### ISSUE TITLE
sidebar color

### ISSUE THREAD

**Issue by liamcoded** [equinusocio/material-theme#333]
I might have missed something but I don't see how to change sidebar color. It's still the same color before your theme. How do I make it dark the way you have in your first top screenshot?

I did:
Preferences > Color Scheme > Material Theme > schemes > Material Theme

Everything except sidebar changed. Thank you for any help you can give me.

OS X Maverick and Sublime Text 3

**Comment by liamcoded** [comment]
Never mind, I figured it out.

**Comment by Soullighter** [comment]
How you change it?

**Comment by equinusocio** [comment]
ask to @liamcocode

**Comment by liamcoded** [comment]
Heh, I honestly don't even remember posting this. This was back in July. Sorry… It was probably still something you have to change in preferences, I just don't remember what it was.
Also, during my last project, about a month ago Sublime crapped out on me, I switched back to Espresso.

**Comment by Soullighter** [comment]
Hello @liamcoded

I was able to manage problem. Truly it was in settings. Theme was completly different after auto-update, and because of that i was confused.
Anyway thank you for your respond.
