### ISSUE TITLE
No close button (close icon) on the find bar on pressing CTRL + F.

### ISSUE THREAD

**Issue by srahulprdxn** [equinusocio/material-theme#335]
There used to be a close button on Find as well as Find & Replace bar on pressing the shortcut keys, which I can't find now. To hide, I now press CTRL + ` twice to hide it. Can we please have that button back?

**Comment by equinusocio** [comment]
@srahulprdxn You can simply press esc to close the panel. This theme remove some useless and distracting ui elements

**Comment by srahulprdxn** [comment]
Oh awesome. Thanks for the update.
