### ISSUE TITLE
'Rename' input not visible

### ISSUE THREAD

**Issue by bloomingbridges** [equinusocio/material-theme#336]
When I right click on an item in the sidebar and go rename, an input field normally pops up at the bottom edge of the editor which prompts for a new name for the file. Not to say it doesn't work as expected, when I confirm by pressing return the file is renamed, only problem is I can't see what I'm typing.
This is on ST3 on Mac OS X Yosemite.

![screen shot 2015-07-14 at 10 41 22](https://cloud.githubusercontent.com/assets/1463168/8669485/6ab60dba-2a15-11e5-9ac0-fb868d7757f1.png)

Cheers!

**Comment by vluzrmos** [comment]
just resize the panel once.

that is "known issue" on readme.

**Comment by bloomingbridges** [comment]
Oh, sorry for wasting your time then.

**Comment by vluzrmos** [comment]
I hope it worked, if did not work you can reopen that issue.

**Comment by equinusocio** [comment]
@vluzrmos This worked for all 166383 similar issues 😊

**Comment by bloomingbridges** [comment]
Yeah it worked.. didn't know you could resize that little bugger ^^

**Comment by bloomingbridges** [comment]
Yeah it worked.. didn't know you could resize that little bugger ^^
