### ISSUE TITLE
How to change the indent_guide_options color

### ISSUE THREAD

**Issue by juanpscotto** [equinusocio/material-theme#337]
Hi, how I change the color of the indent highlighted because when the Theme-Darker is used The lines are almost not visible

The darker theme:

![image](https://cloud.githubusercontent.com/assets/1307866/8682752/a5f17dd4-2a3c-11e5-9a51-1cb7a5fcde5e.png)

The default Theme:

![image](https://cloud.githubusercontent.com/assets/1307866/8682777/c659457a-2a3c-11e5-9f29-080e56448aef.png)

**Comment by timbog80** [comment]
looks pretty visible to me.

**Comment by juanpscotto** [comment]
In the The darker theme it's not visible. How Can I change that??
![image](https://cloud.githubusercontent.com/assets/1307866/8698647/d5947a46-2acd-11e5-928d-26d357ed7ea7.png)

**Comment by equinusocio** [comment]
You have to extract the theme package and edit the specific rulers inside the darker color_scheme:

```xml
	<key>guide</key>
	<string>#42424260</string>
	<key>activeGuide</key>
	<string>#424242</string>
	<key>stackGuide</key>
	<string>#42424280</string>
```
