### ISSUE TITLE
Folders in sidebar are broken

### ISSUE THREAD

**Issue by danherd** [equinusocio/material-theme#338]
This has always been flaky since I started using this theme, but the latest update has hosed it completely.

Here's a screencast illustrating the problem: http://monosnap.com/file/od0WpsvjMFpmW1tIqEFjVz8ZEbMIdf

OSX 10.10.4
ST 3 Build 3083

Let me know if you need any more info.

Cheers,

Dan

**Comment by timbog80** [comment]
i have a feeling that it has something to do with your editor settings or the version. what version of st is that?

**Comment by danherd** [comment]
It's in my post above: Sublime Text 3 Build 3083

Packages installed (apart from Package Control and Material Theme):

ApplySyntax
ExpressionEngine
Laravel Blade Highlighter
phpfmt
Sass
SublimeLinter
SublimeLinter-csshint
SublimeLinter-jshint
SublimeLinter-phpcs
TrailingSpaces

The thing is, it all worked fine before the latest update.

**Comment by danherd** [comment]
Aha! I appear to have fixed this by creating a new workspace for the project (Project -> New Workspace for Project).
