### ISSUE TITLE
Duplicate bar is broken

### ISSUE THREAD

**Issue by marcosrjjunior** [equinusocio/material-theme#34]
![dupl](https://cloud.githubusercontent.com/assets/5287262/8040840/17e1c51c-0dea-11e5-84cf-a6d595d73f5b.png)

**Comment by mathewhany** [comment]
:+1:

**Comment by gj1118** [comment]
I would like to think that this is the same issue i was facing and it was a sublime thingy for me.. please see this bug https://github.com/equinusocio/material-theme/issues/19 for more information..

thanks

**Comment by equinusocio** [comment]
Read #19

**Comment by mathewhany** [comment]
I have restarted sublime, but this didn't work!

**Comment by mathewhany** [comment]
I tried again and it worked, thanks!
