### ISSUE TITLE
Dark theme find in files issue

### ISSUE THREAD

**Issue by maggiben** [equinusocio/material-theme#340]
I'm using windows version of Sublime 3 (build 3083)
The find in files widgets doesn't render correctly:
![image](https://cloud.githubusercontent.com/assets/2845947/8699946/6f50c58e-2adf-11e5-9d41-4331ea256379.png)

**Comment by vluzrmos** [comment]
resize the panel once.

**Comment by equinusocio** [comment]
You can find the fix inside the README file
