### ISSUE TITLE
editor background color

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#344]
Hi, 

Can the background of 1 be a transparent color, please ?
![image](https://cloud.githubusercontent.com/assets/473101/8708847/8c7b9dc8-2b0c-11e5-9777-4d94d749185a.png)

**Comment by equinusocio** [comment]
This isn't related to the theme. The "1" notification is provided by some other package. What package is?

**Comment by gj1118** [comment]
the "1" is just an annotation that I used in my screen capturing tool to point to the place where the background color should be transparent or of the same color as the background of the highlighted text. Sorry for the confusion..

**Comment by equinusocio** [comment]
You're using White Panels Package?

**Comment by equinusocio** [comment]
@gj1118 are you usi white panels package?
