### ISSUE TITLE
open folder animation - remove for hover

### ISSUE THREAD

**Issue by oisinlavery** [equinusocio/material-theme#346]
This animation looks great when I click to open a folder but it is really distracting when on hover.

**Comment by equinusocio** [comment]
You can disable it. Check the README file

**Comment by oisinlavery** [comment]
I think it is an appropriate animation for folder expansion, just not hover. Glad it can be disabled anyway.

**Comment by equinusocio** [comment]
I cant remove it on hover. The animation is applied when hover the expandable folder, then the expanded folder must have the "empty" teal icon folder.
