### ISSUE TITLE
New Light Theme looks washed out, hard to read, needs more contrast

### ISSUE THREAD

**Issue by arpitnj** [equinusocio/material-theme#347]
Hey there I am designer, I convinced myself to switch to sublime text after using it with the SODA Sublime theme as it made sublime less ugly i.e. before I made the switch to your theme. 
http://buymeasoda.github.io/soda-theme/
![SODA Theme](http://buymeasoda.github.io/soda-theme/images/soda-light-screenshot.png)

I just saw today that there was new lighter scheme, I prefer the lighter scheme, but I feel everything looks  very washed out. The colors for the text/icons/labels need more contrast to make it easier to read. 

Espresso Code Editors default theme is superb so is Coda Default theme. 
![Espresso](http://macrabbit.com/espresso/images/screenshots-2.0/Main-PreviewAndCSS.jpg)

You could use the SODA color scheme as your base.

**Comment by equinusocio** [comment]
If you're a designer you can affirm that the SODA theme and ESPRESSO use a very distracting (and old) UI.

You can simple use another color scheme, from soda light or espresso. :+1:
