### ISSUE TITLE
The rename field is hidden below the number of lines.

### ISSUE THREAD

**Issue by juanpscotto** [equinusocio/material-theme#349]
Hi. In sublime, when I click rename on an object, the field gets hidden below the number of lines. Please see the picture bellow:

![image](https://cloud.githubusercontent.com/assets/1307866/8739216/f13f8292-2c06-11e5-9a64-50910d380d0c.png)

**Comment by vluzrmos** [comment]
Just resize the panel once.

**Comment by bytelovers** [comment]
I have the same problem. I try to resize the panel, the window, all... and I've got the same, nothing :(
