### ISSUE TITLE
Material Theme Suddenly Stop Working

### ISSUE THREAD

**Issue by espellcaste** [equinusocio/material-theme#350]
I'm not sure if it is a problem on Sublime Text, Windows or my computer. But the problem only happens so far when using Material Theme.

It suddenly stops working and is removed, so now and then I have to apply the theme info on settings -> user.

**Comment by jpsear** [comment]
Same happened to me today on Mac... Latest version.

**Comment by tadurham** [comment]
Is this occurring even after closing and re-opening sublime Text?

**Comment by jpsear** [comment]
Afraid so. That is the first thing I tried.

On Fri, Jul 17, 2015 at 8:28 pm, Taylor Durham < notifications@github.com [notifications@github.com] > wrote:
Is this occurring even after closing and re-opening sublime Text?

—
Reply to this email directly or view it on GitHub
[https://github.com/equinusocio/material-theme/issues/350#issuecomment-122385171] .[https://github.com/notifications/beacon/AC2DOM-TkdCjh1vEbTZ-fz9318Lmpd0Kks5oeU7JgaJpZM4Fas1i.gif]

**Comment by espellcaste** [comment]
Yes, that's how I noticed this problem. It suddenly stopped working and returned to the default theme. I closed Sublime and reopened it normally.

Then after a while, it happens again. Again, I'm not sure if it is something in my computer or other package.

**Comment by equinusocio** [comment]
After every update you have to wait until the theme is automatically setted

**Comment by espellcaste** [comment]
@equinusocio All right! But the error happens even when there is no update. :(

**Comment by equinusocio** [comment]
Ok, so this isn't a theme issue...

**Comment by espellcaste** [comment]
I'm not sure yet! I changed for the basic theme for a week. I'm gonna install Material Theme again next week and try for a while to make sure it is the culprit. That's the only way I came up to testing.

**Comment by equinusocio** [comment]
You use dropbox sync?

**Comment by espellcaste** [comment]
Not on my computer.

**Comment by equinusocio** [comment]
Try to use another theme (not default) for a bit

**Comment by espellcaste** [comment]
Good idea! Gonna try it!

**Comment by petebarr** [comment]
Same thing happened to me :-( Just completely gone and can't install it again. Even when installing manually it doesn't work.

**Comment by equinusocio** [comment]
Please paste some screenshots..

**Comment by petebarr** [comment]
What would you like screenshots of exactly?

**Comment by equinusocio** [comment]
@petebarr A screenshot (or somethings) that explain what do you mean with (stop working). 

Errors? Glitch? ST Doesn't start?

**Comment by petebarr** [comment]
It just went back to the ST3 default theme, and the theme deleted itself from the packages directory. If you try to install it through package manager, restart ST3, browse packages and select Material Theme, it says Material Theme not found.

**Comment by equinusocio** [comment]
Try this:
1.  Download  the master branch and rename the extracted folder to "Material Theme"
2. Move it to the Packages folder (Preferences > Browser package)
3. Go to ST, and type "Remove package" in the command panel, remove the package and restart ST
4. Reopen ST, search for "Material Theme" in the command panel and install it. 
5. Apply the theme

**Comment by YozhEzhi** [comment]
@equinusocio 
I've did all of that. I see this after installation:
![Image]
(http://dl2.joxi.net/drive/0001/1889/128865/150723/c96a856426.jpg)

Than I've applied the theme. And no luck...
![Image]
(http://dl2.joxi.net/drive/0001/1889/128865/150723/eca269f0e4.jpg)

Console:
```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/YozhEzhi/Library/Application Support/Sublime Text 3/Packages
state path: /Users/YozhEzhi/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/YozhEzhi/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.337601
first paint time: 0.413043
startup time: 0.429406
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorPicker.sublimecp
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin EasyMotion.easy_motion
reloading plugin Emmet.emmet-plugin
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin Hayaku - tools for writing CSS faster.__init__
reloading plugin Hayaku - tools for writing CSS faster.hayaku_dict_driver
reloading plugin Hayaku - tools for writing CSS faster.hayaku_get_merged_dict
reloading plugin Hayaku - tools for writing CSS faster.hayaku_probe
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_contexts
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_cycling
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_get_options
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_navigation_commands
reloading plugin Hayaku - tools for writing CSS faster.hayaku_templates
reloading plugin LESS.less_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS Expander.__init__
reloading plugin SCSS Expander.scss_expander
reloading plugin Stylus.Stylus
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-07-23 08:57:59, next run at 2015-07-23 09:57:59 or after
```

**Comment by magicstickuk** [comment]
Removing Material Theme from package explorer and re adding it worked for me.

**Comment by tatygrassini** [comment]
Same as @magicstickuk: removed all "Material" packages. Download the latest ZIP, installed manually, activated, restarted and voilà!

**Comment by equinusocio** [comment]
I think there was a problem with PC. I close this issue for now.

**Comment by YozhEzhi** [comment]
@tatygrassini But not for me...

**Comment by espellcaste** [comment]
By the way, I've come to understand the error happen when I load Sublime. I work on sublime, close it and gonna do something else, I come back to work, open sublime and the theme crashes. :(

**Comment by equinusocio** [comment]
Try to disable your packages one by one

**Comment by petebarr** [comment]
Hazaaaaa! Works again.

**Comment by YozhEzhi** [comment]
@petebarr 
What I should to do to say "Hazaaaaa" to?

**Comment by petebarr** [comment]
I just installed in manually and it worked perfectly this time round.
