### ISSUE TITLE
Request: material-theme for oh-my-zsh/iTerm2

### ISSUE THREAD

**Issue by blomdahldaniel** [equinusocio/material-theme#351]
Hi @equinusocio 

I love what you have done with this sublime theme. 
Are you interested in making a material-theme for iTerm2/oh-my-zsh? 

I ask because I think that you would do a great job on that and I would LOVE to have that good feel in my terminal as well. :)

**Comment by equinusocio** [comment]
This isn't compatible?
https://gist.github.com/mvaneijgen/4c56701215847dd5ddcf

**Comment by blomdahldaniel** [comment]
Wow! Whats that? How do I use it?

**Comment by equinusocio** [comment]
I don't know if you can use this with iTerm, but in terminal, you have to select it in the theme preferences.

**Comment by blomdahldaniel** [comment]
it does work for Terminal, but the fonts are broken. I have tried with Powerline fonts. I dont get it to work in iTerm2. I have commented the gist for further info on why it doesn't work. Thanks for your work!

**Comment by equinusocio** [comment]
:+1:

**Comment by xinan** [comment]
I have created a iTerm2 port for it. :smile: Check it out here: https://gist.github.com/xinan/ca2b82fef6aaa0d1e099

**Comment by equinusocio** [comment]
@xinan can you post some screenshots?

**Comment by xinan** [comment]
Sure!

<img width="570" alt="screen shot 2015-08-02 at 1 19 37 am" src="https://cloud.githubusercontent.com/assets/2834397/9022761/9956b3e2-38b4-11e5-835c-271936c9c8a4.png">

**Comment by equinusocio** [comment]
Nice work, i will add this to the README file ok?

**Comment by xinan** [comment]
Sure! :smile: Thanks!

**Comment by blomdahldaniel** [comment]
Sweet @xinan !! :smile:

**Comment by equinusocio** [comment]
Mmmm i've installed this theme but i don't see text colors

**Comment by xinan** [comment]
Text color is called "Foreground color" in iTerm2 I think.

**Comment by equinusocio** [comment]
@xinan i don't see the themes color:
![screen shot 2015-08-03 at 09 16 11](https://cloud.githubusercontent.com/assets/10454741/9032576/4e0d0b0e-39c0-11e5-97ea-24967875178e.png)

**Comment by xinan** [comment]
@equinusocio Did you click the `Load Preset` below and choose `material-theme`?

**Comment by xinan** [comment]
Oh bash by default has no color, has it? When I use bash in Terminal.app with the terminal port, there is also no color. Sorry I'm not familiar with bash but I guess that is the expected behaviour?

**Comment by xinan** [comment]
Hi @equinusocio 

For bash to display colors, you need to add
```
export CLICOLOR=1
export TERM=xterm-256color
``` 
into your `.bash_profile` / `.bashrc`

**Comment by joaocunha** [comment]
^^^ same applies to `.zshrc`.

**Comment by Colt** [comment]
@xinan Mind sharing how you setup your prompt with those 3 arrows?  Looks great!

**Comment by xinan** [comment]
@Colt Oh I'm using [prezto](https://github.com/sorin-ionescu/prezto). That's the default theme.

**Comment by equinusocio** [comment]
Pff I can't install prezto
