### ISSUE TITLE
Quick File Creator issue

### ISSUE THREAD

**Issue by chinghanho** [equinusocio/material-theme#352]
before:
![screen shot 2015-07-19 at 6 48 19 pm](https://cloud.githubusercontent.com/assets/1897143/8765611/c0a062f4-2e46-11e5-8bab-8ba03e10c1e5.png)

after type text in input field:
![screen shot 2015-07-19 at 6 48 54 pm](https://cloud.githubusercontent.com/assets/1897143/8765614/d714cc46-2e46-11e5-85d7-8d05a5a50dae.png)

I use [Quick File Creator](https://github.com/noklesta/SublimeQuickFileCreator) plugin create file. But the input panel doesn't show any text.

**Comment by equinusocio** [comment]
Please read the README file and see #67

**Comment by chinghanho** [comment]
Sorry about that, Now fixed! Thanks!
