### ISSUE TITLE
Tab button sometimes not working

### ISSUE THREAD

**Issue by chenghuayang** [equinusocio/material-theme#353]
Sometimes, I failed to change the page when clicking the tab. I needed to close Sublime Text or click the tab more than 5 times, or tabs in other column. 
I encountered the problem after the recent update. Also, I used Sublime Text everyday, and automatically downloaded every update version. Maybe it's a bug between the latest and the second-latest. Below are the current settings.

{
"bold_folder_labels": true,
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
"font_options":
[
"gray_antialias"
],
"font_size": 14,
"ignored_packages":
[
"Vintage"
],
"indent_guide_options":
[
"draw_normal",
"draw_active"
],
"line_padding_top": 3,
"material_theme_small_statusbar": true,
"overlay_scroll_bars": "enabled",
"theme": "Material-Theme.sublime-theme"
}

**Comment by equinusocio** [comment]
Try to make a new workspace for your project

**Comment by chenghuayang** [comment]
Thanks! Sometimes, it just need a new project.
