### ISSUE TITLE
"Open Files" icons issue

### ISSUE THREAD

**Issue by camiant** [equinusocio/material-theme#354]
In latest version (1.5.2) ,inside "Open Files", icons aren't visible anymore.
They are quite useful to instantly know which files have been modified.

1.5.1
http://d.pr/i/anxx

1.5.2
http://d.pr/i/18rpl

**Comment by equinusocio** [comment]
Yes, the close icon appear on mouse hover. This theme follow a less-distracting ui idea

**Comment by camiant** [comment]
Ok, thanks a lot for your quick reply, but... would be possible to manually
restore them using a dedicated option in user-settings or anywhere else?
I'd like to have them always on ;)
Il 20/Lug/2015 19:01, "Mattia Astorino" <notifications@github.com> ha
scritto:

**Comment by melihtas** [comment]
Many people use "Open Files" panel instead of tabs especially when working on laptop. Not seeing which files are edited is a deal breaker. Please make "edited" icon visible.

**Comment by camiant** [comment]
Congrats for the new features you've added in latest (1.8.1 at the time of this writing) upgrade:
- colored accents are great
- showing only the pencil icon (when file has been edited) in "open files" is an excellent solution

Keep up the good work, Mattia!
