### ISSUE TITLE
Dirty tabs are not distinguished

### ISSUE THREAD

**Issue by Alaneor** [equinusocio/material-theme#36]
Another "possibly by design" bug report from me.:)

With the default theme, Sublime distinguishes between opened tab and "dirty" tab (a file I single-clicked, not double-clicked) by making the tab's title italic.

This tells me that if I click on a different file in the sidebar, the file will open *in the same tab*. I think some kind of distinction should be provided here, too.

Making the text italic might be an option, another one would be to use a less bright blue variant of that tab underline. I frequently felt that just the italic text alone is a weak distinction...

What do you think?

**Comment by equinusocio** [comment]
Yes. I've disabled the preview feature (single click), I will check. Thanks!
