### ISSUE TITLE
Support for Advanced New File plugin

### ISSUE THREAD

**Issue by ncerminara** [equinusocio/material-theme#360]
Hello

Awesome theme - thanks for all your hard work.

[Advanced New File](https://github.com/skuroda/Sublime-AdvancedNewFile) is an awesome plugin. It lets you create files without the default OS prompt. Check out a demo if you're unfamiliar (image is a link to YouTube):

[![bllahhahahahahahahha](http://img.youtube.com/vi/ZXvSMeNS91Q/0.jpg)](http://www.youtube.com/watch?v=ZXvSMeNS91Q)

Here's what it looks like with this theme:

![Blahhhhhhhhh](http://i.imgur.com/0eCoRmU.png)

In case it's a settings thing, here's mine:

```javascript
{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"file_exclude_patterns":
	[
		".DS_Store"
	],
	"folder_exclude_patterns":
	[
	],
	"font_size": 18,
	"highlight_line": true,
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"scroll_past_end": true,
	"tab_size": 4,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": false
}
```

Finally, I'm on Mac. OS X Yosemite 10.10.3 using Sublime Text Build 3083.

Thanks!

**Edit:**: Per known issues https://github.com/equinusocio/material-theme/issues/67, I also can't resize the area like find/replace

**Comment by equinusocio** [comment]
You can, search for the panel top edge. You will see the arrow up

**Comment by ncerminara** [comment]
Ah, you can. THANKS!
