### ISSUE TITLE
New folder name input does not appear

### ISSUE THREAD

**Issue by ononotofu** [equinusocio/material-theme#361]
Using OSX 10.10.3 and Sublime Text 3083 with the latest Material Theme installed by Package Control.

I'm including two pictures, the view when creating the folder and the view after clicking "New Folder...". I would expect that text entered after clicking would be rendered so that it is visible on the bottom, which I am highlighting.

![screen shot 2015-07-22 at 2 02 09 pm](https://cloud.githubusercontent.com/assets/9095310/8837425/332fbabe-307b-11e5-9b6e-1902e4dace09.png)

![screen shot 2015-07-22 at 2 02 16 pm](https://cloud.githubusercontent.com/assets/9095310/8837430/3bee8694-307b-11e5-8b99-5099f0398375.png)

**Comment by equinusocio** [comment]
@ononotofu Hi, you find the solution in the README file

**Comment by ononotofu** [comment]
Hi @equinusocio -- I of course tried that and it has no effect, the problem persists.

**Comment by vluzrmos** [comment]
Are you sure that you resized the panel of the input file/folder name ?

**Comment by ononotofu** [comment]
Yes -- with a find + replace command. Is there a different command I should use to bring that up? I also tried uninstalling and installing directly from git. I'll test on another computer and if I can replicate I'll post back with steps.
