### ISSUE TITLE
Color of the open folder is wrong

### ISSUE THREAD

**Issue by marcosrjjunior** [equinusocio/material-theme#362]
##### Accent Colors - Release 1.8.0

![materialthemeaccent](https://cloud.githubusercontent.com/assets/5287262/8840572/6a250c48-30b9-11e5-87c5-38f7d739b6d4.png)

**Comment by equinusocio** [comment]
mmm this doesn't happen to me. Uou're using White Panels Addon?

**Comment by marcosrjjunior** [comment]
yep, works if set `"material_theme_disable_folder_animation": false,`

**Comment by equinusocio** [comment]
Thanks, i will fix this in the evening
