### ISSUE TITLE
Wrong tab background color when accent_lime = true on Lighter theme

### ISSUE THREAD

**Issue by guocheng** [equinusocio/material-theme#363]
Here is my config:

"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Lighter.tmTheme",
"theme": "Material-Theme-Lighter.sublime-theme",
"material_theme_accent_lime": true

When the accent color is set to lime, the background color of the active tab becomes:

![qq20150723-1 2x](https://cloud.githubusercontent.com/assets/4845980/8842545/2ffb46de-312e-11e5-866b-cab51a13bf52.png)

I have tested all the other accent colors and restarted ST3, **lime** is the only one that is causing the trouble.

**Comment by equinusocio** [comment]
Oh, thanks.
