### ISSUE TITLE
Can we make the search/status bar darker as an option?

### ISSUE THREAD

**Issue by qodo** [equinusocio/material-theme#364]
Love this theme and it's my new favourite. Thanks for regularly updating this too! :)

Can we have an option to make the search/status bar a different colour as I find it slightly hard to see when renaming/searching etc.

![bar](https://cloud.githubusercontent.com/assets/3908836/8847546/b0faa7c2-3127-11e5-89ad-811002ef371d.png)

**Comment by artisologic** [comment]
@qodo You can install the Material-theme white panel extra package that will transform all those fields and make them pop out a bit. I personally love this option.

<img width="1392" alt="screen shot 2015-07-24 at 10 08 07" src="https://cloud.githubusercontent.com/assets/1539897/8871260/e77b03a4-31eb-11e5-89e5-27aa427d6c66.png">

Hope that helps!

**Comment by arhcstolen** [comment]
@artisologic It helped me alot! Thank you :)

**Comment by qodo** [comment]
@artisologic Thanks, this is great.
