### ISSUE TITLE
Accent Colors are "wrong"

### ISSUE THREAD

**Issue by joezimjs** [equinusocio/material-theme#366]
The purple accent looks more like magenta. Can we call that one magenta and then create a different one for purple that looks more like the "deep purple" from here: http://www.google.com/design/spec/style/color.html#color-color-palette

Otherwise, maybe just a deep purple option. Or maybe just make options for all of the listed colors (at their 500 value). Idk, maybe I'm just getting picky. :p 

In any case, I think the way you have the option set up isn't optimal. It'd probably be better to have one option called "material_theme_accent" and you give list of color names that can be used as values instead of using multiple options that just represent one option with multiple values.

**Comment by equinusocio** [comment]
Thanks @joezimjs i will fix the purple accent to #9C27B0 Purple 500.

Unfortunately ST doesn't allow me set a value for an option. I can use only ```true``` or ```false``` and, being a ```json``` file i can't do if/else statement. This is the only way i found to allow you to change the accent color.
