### ISSUE TITLE
File rename input box not positioned properly

### ISSUE THREAD

**Issue by yyx990803** [equinusocio/material-theme#368]
Platform: Mac OS X 10.10.4
Sublime Text: build 3083

When trying to rename files, the input box is almost completely covered by the bottom info bar (as seen in the screenshot)

<img width="470" alt="screen shot 2015-07-23 at 10 11 01 pm" src="https://cloud.githubusercontent.com/assets/499550/8866224/dc1196cc-3187-11e5-8817-e668aa2bc40f.png">

**Comment by mykebates** [comment]
Came here looking for the same.  If you haven't seen this yet -> 
https://github.com/equinusocio/material-theme/issues/67

It's small, but there is spot to drag the bar up and make taller.

**Comment by yyx990803** [comment]
Hmm, I just think it's worth fixing within the theme if possible, since obviously too many people have run into this issue.

**Comment by equinusocio** [comment]
As I said before, this is a ST bug. There is an opened issue:
https://github.com/SublimeTextIssues/Core/issues/939
