### ISSUE TITLE
If I create a file or folder, I can't see box inputs in SidebarEnhancement.

### ISSUE THREAD

**Issue by qiuyuntao** [equinusocio/material-theme#369]
<img width="1135" alt="screen shot 2015-07-24 at 1 27 29 pm" src="https://cloud.githubusercontent.com/assets/8157476/8868222/cb1bd870-3207-11e5-91ec-dd4947e9ae20.png">
Like this.

**Comment by equinusocio** [comment]
Please red the REDME file.
https://github.com/equinusocio/material-theme#known-issues
