### ISSUE TITLE
UX: Have rename/find/other similar panels cast shadows?

### ISSUE THREAD

**Issue by Alaneor** [equinusocio/material-theme#37]
Currently it is very hard to tell where the rename, find/replace or other similar bars that appear at the bottom of the window end.

Maybe, if possible, have them cast shadows...? Or add other, distinctive border?

Doing so might also help others try to move the border up to fix #23 or #34 themselves before they submit another bug.:)

**Comment by equinusocio** [comment]
No sorry. I can't change the UI for a Sublime Text bug. The fix you mentioned must be done once.

**Comment by Alaneor** [comment]
Okay.:) But what about the idea of having a nice, visible border (either by adding shadow or something else) without thinking about it as a solution to those bugs? I still think having a visible border would be a nice visual addition...

**Comment by equinusocio** [comment]
no :) For the same reason. You don't resize the find/replace panel everytime. You don't have to see this distracting border everytime. Borderless UI are less distracting, like google says. :smile:

**Comment by Alaneor** [comment]
Very well, I give up.:) Google definitely has different tastes than I, but I am still keeping this theme.:)

**Comment by equinusocio** [comment]
In material design language only elevated elements can drop a shadow.
