### ISSUE TITLE
sidebar open file indicator colour issue

### ISSUE THREAD

**Issue by artisologic** [equinusocio/material-theme#370]
Hi,

Not sure if that's normal or not, but I think a recent change introduced some sort of open file indicator in the sidebar. However the colour seems to be not in tune with the theme at all (it's giving me  flashy green, instead of the nice turquoise colour).

Here's a screeshot:

<img width="1392" alt="screen shot 2015-07-24 at 09 50 28" src="https://cloud.githubusercontent.com/assets/1539897/8870942/bb7a8574-31e9-11e5-97c8-36e6ebe95566.png">

**Comment by equinusocio** [comment]
this isn't an issue. The tree accent color must be different from others to capture the attention
