### ISSUE TITLE
No bold tabs on default color theme

### ISSUE THREAD

**Issue by rikiless** [equinusocio/material-theme#372]
![screenshot 2015-07-24 12 25 53](https://cloud.githubusercontent.com/assets/589851/8872656/4a636e6c-31ff-11e5-9dfd-3de84dd67268.png)

Seems it works only on lighter color theme.

**Comment by equinusocio** [comment]
the setting works with all styles. Have you restarted ST?

**Comment by rikiless** [comment]
@equinusocio I had to reinstall the theme and its fine now. Maybe it was caused by using outdated theme file (Material-Theme (SL).

**Comment by equinusocio** [comment]
@rikiless Every package that work with the color scheme (like sublime lineter) generate a private cached version of it. If the color scheme get changes you have to regenerate it through the package. You don't need to reinstall all.
