### ISSUE TITLE
Line Numbers very light

### ISSUE THREAD

**Issue by msrafi** [equinusocio/material-theme#374]
The line numbers are very low in default theme. Its almost hidden.

**Comment by equinusocio** [comment]
I think you have to calibrate your monitor

**Comment by msrafi** [comment]
You mean the MacBook Pro?

**Comment by equinusocio** [comment]
@msrafi Yes. On my mbp i see with no problem the line numbers. 

I'have calibrated my monitor with spyder sensor.

**Comment by grantholle** [comment]
I'm also having difficulty seeing line numbers, and don't think I need to calibrate my screen...

It could be just a _little_ brighter is all.

**Comment by grantholle** [comment]
<img width="215" alt="screen shot 2015-07-31 at 7 19 28 am" src="https://cloud.githubusercontent.com/assets/1189456/8997856/fa7fe31c-3758-11e5-99d6-f633f00b0f23.png">

This is what I'm seeing on MacBook Pro Retina, using `"gray_antialias"`.

I still think it's really low contrast. I also don't think I should have to "calibrate" my screen...

**Comment by equinusocio** [comment]
@grantholle You really need to see the line numbers constantly while you code? Line numbers are one of the most distracting thing, and you have to see it when you need it.

You can customize the theme by overriding the rule in your local package

**Comment by grantholle** [comment]
:+1: Thanks, great theme. I appreciate the work put into it

**Comment by msrafi** [comment]
@equinusocio no problem. thank you very much for your effort and a great theme for sublime. I like every bit of it.

**Comment by RoxasShadow** [comment]
I'm writing this here as reference for someone who's interested in doing the same.

Just open the color scheme (you can take the path from Preferences) you're using and set `gutterForeground` to `#4b5960` (it's a different shade of the original one, looks pretty nice),

**Comment by msrafi** [comment]
Thank you very much

**Comment by Kwadz** [comment]
Hi,
Could you just explain how to override the rule in the local package?
I tried to follow RoxasShadow's instructions but I don't find any file to edit.
I use Sublime Text 3 on OSX.
Thanks

**Comment by equinusocio** [comment]
@Kwadz You have to extract the package with [Resource Viewer](https://github.com/skuroda/PackageResourceViewer)

**Comment by Kwadz** [comment]
@equinusocio Could you mention the path/filename of the package to edit please?
Thanks

**Comment by equinusocio** [comment]
`Material Theme/schemes/Material-Theme-*`
