### ISSUE TITLE
HTML (Djaneiro) colouring no longer working.

### ISSUE THREAD

**Issue by BrockBeldham** [equinusocio/material-theme#375]
I use Django as my backend and therefore use Djaneiro Package for colouring django files. This theme used to colour HTML (Djaneiro) files, but sometime over the past week it has stopped working for me. Is there something special I have to do for it to colour the 'HTML (Djaneiro)' files? Or am I just going to have to use 'HTML' to colour my HTML files?

**Comment by equinusocio** [comment]
Please give me more info:
- Sublime Text version and build 
- Djaneiro Package version
- Your preferences

**Comment by BrockBeldham** [comment]
Sublime Text 3, Build 3083
Djaneiro - v2015.03.04.16.04.50 - https://github.com/squ1b3r/Djaneiro
My User Preferences:
```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"font_size": 12.0,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"rulers":
	[
		0
	],
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
```

Hope that helps

**Comment by BrockBeldham** [comment]
I have restarted Sublime Text and apparently I was missing Version 1.8.0 and Version 1.8.1 of Material Theme. Seems to be working fine now. Lesson learned: don't leave ST open for days lol.
