### ISSUE TITLE
Caret Width

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#376]
Request to increase the caret width and add color to match the theme that the user is currently using.

**Comment by equinusocio** [comment]
I can't target only the caret in the scopes and i can't increase his width.

**Comment by imoby** [comment]
You can at least target the caret's color the scopes of the different tmthemes by modifying the following key:

      <key>caret</key>
      <string>#ffcc00</string>

Below stuff can be modified in the preferences if the user wants to increase the width and style. 
"caret_extra_bottom": 0,
"caret_extra_top": 0,
"caret_extra_width": 8,
"caret_style": "phase",
