### ISSUE TITLE
Bracket theme

### ISSUE THREAD

**Issue by Amstramgram** [equinusocio/material-theme#378]
Hi,
i love your theme, he is really awesome but i work with Brackets too. I made this [Bracket-theme.zip](http://julienmiclo.fr/stuff/mtrldsgn.zip) maybe you can mix your theme with this and do a awesome theme for brackets.

-Amstramgram

**Comment by equinusocio** [comment]
You have a repository for this theme?

**Comment by Amstramgram** [comment]
https://github.com/Amstramgram/brackets-mtrldsgn-lighter

**Comment by equinusocio** [comment]
Unfortunately brackets allow to style only the color scheme. So, at the moment, the porting cannot be made.
