### ISSUE TITLE
New/edit File input not shown

### ISSUE THREAD

**Issue by joelcoxokc** [equinusocio/material-theme#379]
Hello wonderful team. 

I am using the sideBar enhancements. 

When I right click a folder or file and select new/rename/move
The input at the bottom of the screen is not shown. Yet I am still able to type the value. 

Has anyone else had this issue?

**Comment by wadehammes** [comment]
Check out #67 (and read the README under Known Issues) and it should fix your problem.

**Comment by SrPatinhas** [comment]
@equinusocio this issue is still happening, at least in my pc, and i have the ST3 with this team installed on 3 PCs

**Comment by equinusocio** [comment]
@SrPatinhas The fix is in the README file and more info are in the issue #67
