### ISSUE TITLE
support more scopes

### ISSUE THREAD

**Issue by lemures-t** [equinusocio/material-theme#380]
The material theme for st3 is really awesome, which leads me to upgrade from st2. But after using it as my st3 theme, I find there is no highlight for something like ```height``` in ```$('#id').height()```. There seems no ```support.function``` color in the theme file. Have you ever considered to add more scopes like ```support.function```? Many thanks.

**Comment by equinusocio** [comment]
![screen shot 2015-07-30 at 09 14 41](https://cloud.githubusercontent.com/assets/10454741/8977668/6fc13658-369b-11e5-8bc2-f9c1bf11f3f9.png)
these are the colors for javascript. You don't see this highlight?

**Comment by lemures-t** [comment]
<img width="382" alt="2015-07-30 17 39 14" src="https://cloud.githubusercontent.com/assets/11439157/8980279/f5c07b42-36e1-11e5-90eb-757e3a5305b9.png">
But it comes to me like this. Is there any more configuration I should do?

**Comment by equinusocio** [comment]
Are you using Sublime Linter? What ST version and build are you using?

**Comment by equinusocio** [comment]
please see #299

**Comment by lemures-t** [comment]
Great! Really appreciate for your answering! I have read the #299 very very carefully. And i tried to upgrade to 3095 dev version.Now everything is OK. Thanks very much. BTW, I am using Sublime Linter. Is there any problem with this plugin which will lead to material theme quirk?

**Comment by equinusocio** [comment]
No, but almost any package that work with color scheme, like Sublime Linter, they use a cached version of the scheme and sometimes you have to rebuild the cache if the scheme get changes. Otherwise you'll not see the changes.
