### ISSUE TITLE
A option for highlighting active tab?

### ISSUE THREAD

**Issue by cmoon2000** [equinusocio/material-theme#384]
I often open 2 vertical panel. Sometimes, Sometimes, It makes me confused for a while  to relize what active tab is. Can u make it a option for highlight active tab to make thing easier?

**Comment by equinusocio** [comment]
The active tab is already highlighted...
<img width="442" alt="screen shot 2015-07-31 at 19 08 58" src="https://cloud.githubusercontent.com/assets/10454741/9012753/9d983d34-37b7-11e5-8705-36c567afb130.png">

**Comment by cmoon2000** [comment]
No that's not what I mean. 
There're 2 columns. And each file in columns have same highlight. If I do in `foo.js`, maybe It can be highlight with other color (red for example) and else.
![screenshot_2015-08-01_08-46-32](https://cloud.githubusercontent.com/assets/6170794/9020230/0f939132-382a-11e5-8c26-cfe64acdfcfc.png)

**Comment by equinusocio** [comment]
I can't set different style for the highlighted tab.
