### ISSUE TITLE
Icon for windows 10 

### ISSUE THREAD

**Issue by giltig** [equinusocio/material-theme#385]
Hi,
Could you publish a sublime icon also for windows 10?

**Comment by equinusocio** [comment]
You mean a white outlined icon?

**Comment by giltig** [comment]
I mean ico - the nice icon package that you give in win format

**Comment by equinusocio** [comment]
Ahem yes. Sorry :)

**Comment by limenet** [comment]
@giltig does this suit your needs? https://www.dropbox.com/s/7nsmd1c8ph6ypij/material_icon.ico?dl=0 (it's the icon by @equinusocio as a 256 x 256 ico file)

**Comment by NicolasParada** [comment]
Maybe a white outlined icon would be cool too...

**Comment by giltig** [comment]
@limenet yeah that's cool thanks.
