### ISSUE TITLE
can I remove the padding on treeview left

### ISSUE THREAD

**Issue by ilovezy** [equinusocio/material-theme#386]
this theme is great,I love the icons and colortheme,
a liitle wish I hope you can add this
there are about 20px padding on left
![qq 20150801093732](https://cloud.githubusercontent.com/assets/8774988/9020195/ef915c50-3830-11e5-9873-c9eba17c6534.png)
I hope you can add an option to remove this padding, my screen is a liitle small to make it looks like this
![qq 20150801094000](https://cloud.githubusercontent.com/assets/8774988/9020197/3c5dc988-3831-11e5-9047-503675cb74a8.png)

or is there any way I can change this myself

**Comment by equinusocio** [comment]
The white-space, paddings and margins are an essential things in this theme. At the moment you can remove it only by overriding the theme rules

**Comment by ilovezy** [comment]
I open your source and change this value to 10 or 15 , hope you don't mind
It look really good for me 
and the inactive tabs font color is to dark now, maybe make it look a little lighter 
I hope you can consider about these two point, just a little advise

![qq 20150802033846](https://cloud.githubusercontent.com/assets/8774988/9023292/db7c40da-38c7-11e5-92a8-0231a2dbfc0e.png)
