### ISSUE TITLE
I need some serious help !!!

### ISSUE THREAD

**Issue by DeeJaVu** [equinusocio/material-theme#388]
Hey i can't decide between
This
----------
```
"theme": "Material-Theme-Darker.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
```
And this
----------

```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

they both look sooo beautiful

**Comment by equinusocio** [comment]
Sorry, i can't help you :)

**Comment by druellan** [comment]
You can use https://github.com/facelessuser/ThemeScheduler to schedule a theme change. For example, you can use the normal version during the day, and automatically change it for "Darker" at night :)

**Comment by vluzrmos** [comment]
hahahahaha!!

**Comment by DeeJaVu** [comment]
@druellan Thanks :+1:
