### ISSUE TITLE
Suggest : Less RED in PHP files

### ISSUE THREAD

**Issue by tunecino** [equinusocio/material-theme#390]
Great theme ! is by far my preferred one !

I have only one issue, there is too much RED colors into PHP files : 

![material_theme](https://cloud.githubusercontent.com/assets/5133397/9040491/7eb18f34-39fa-11e5-83cb-ebf22a1bfe1a.png)
It would be really great if it was a little bit cleaner like JS files :

![material_theme2](https://cloud.githubusercontent.com/assets/5133397/9040772/2702154a-39fc-11e5-92db-fbc55713c705.png)

**Comment by equinusocio** [comment]
Your JS color highlight doesn't match material theme one. I think you have the "old" ST version that use the old syntax system. When you will update ST you will get the same color of PHP file
