### ISSUE TITLE
Sidebar font size

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#391]
Hi , 
This is not an isssue, but rather a new request please. Can you please add a new setting for changing the sidebar font size?

thanks 

With regards
Gagan

**Comment by equinusocio** [comment]
Duplicated of #103 #208. Hi @gj1118, you can change the sidebar font-size by following this steps:
https://github.com/equinusocio/material-theme/issues/208#issuecomment-114864396

I will not add a sidebar font-size setting, because if i do this, i have to make all font-size configurable.  Sorry.

**Comment by gj1118** [comment]
Sure .. But can you please help me understand, why if I do this in the Packages\Material-Theme.sublime-theme

```
[
{
"class": "sidebar_label",
"font.size": 13,
"font.face": "Roboto Mono"
},
]
```

it does not break the tree indentation or any other thing. it seems to me , that everything just works.. Perhaps I am missing a thing here ? 

![image](https://cloud.githubusercontent.com/assets/473101/9066421/88804518-3aa5-11e5-9171-dc5b4ab4eace.png)

**Comment by equinusocio** [comment]
Where do you put the file?

**Comment by gj1118** [comment]
![image](https://cloud.githubusercontent.com/assets/473101/9067647/ceb91206-3aac-11e5-9172-ea759c7acf81.png)


I am on Windows

**Comment by equinusocio** [comment]
Try to put the file inside a folder called ```Material Theme```
