### ISSUE TITLE
Line number color setting

### ISSUE THREAD

**Issue by franck-paul** [equinusocio/material-theme#393]
It would be nice to have the opportunity to make line number lighter or better to change his color. It may be difficult to read (not enough contrast I mean, as you can see on the screenshot joined to this issue).
![sublime text](https://cloud.githubusercontent.com/assets/307049/9069996/26944758-3aed-11e5-8328-ba3f1d048d56.jpg)

**Comment by druellan** [comment]
Hi @franck-paul. I'm currently working on a fork of the dark variation, just to increase a bit the contrast on some texts, that are a pain to read on some monitors.

![2015-08-04_20h07_22](https://cloud.githubusercontent.com/assets/6965667/9074849/7568dff0-3ae4-11e5-8748-cde5ea74364a.png)

Basically the darker text (line numbers, comments, etc) was increased from rgb 66,66,66 to rgb 88,88,88. The sidebar text was ok, but I like how the contrast is a bit higher on the original, so, I changed the rgb from 97,97,97 to 107,107,107 for a more evident edge.

Status bar text was also changed to rgb 107,107,107. I feel that 88,88,88 is better for the design, but the font is so damn small...

I didn't touch the gray icons, that are all at ~rgb 71,71,71 on the status bar and 66,66,66 on the sidebar.

Be free to check it out: https://github.com/druellan/material-theme

**Comment by equinusocio** [comment]
You can use the @franck-paul forked version.

**Comment by franck-paul** [comment]
But I have not forked your project! Anyway, I will continue to use at it is now. Thank's a lot!

**Comment by druellan** [comment]
Hi @equinusocio. I am the one forking the project ;), @franck-paul was only suggesting that perhaps some texts need more contrast, and I agree. On some monitors (*coughTNcough*) or using some settings (I work using a very low brightness setting), small texts are barely legible.
You don't need to change the design too much, just 20 rgb points, to make them ok on such environments, so, if more people complains about it, perhaps it is a change you can consider in the future.
Thanks for your work!

**Comment by winds** [comment]
Setting line numbers color?
You can now use the "gutterForeground" key in .tmTheme files
...
<key>gutterForeground</key>
<string>#a0a0a0</string>
...

**Comment by franck-paul** [comment]
Thank's for advice @winds, once package extracted (with PackageResourceViewer plugin), it's easy to do.

Reminder: to do again on Material update…
