### ISSUE TITLE
Console separator 

### ISSUE THREAD

**Issue by corndogcomputers** [equinusocio/material-theme#396]
It's very difficult to see the console border to grab it with the cursor. Can you add a light border to the top of the console so it's easier to see? Other than that, your work on this theme has been superb!

![example](https://cloud.githubusercontent.com/assets/1114421/9121991/ff0532b6-3c3a-11e5-8f46-f6aec1c76575.jpg)

**Comment by gj1118** [comment]
I think it looks better that way... I have been using this theme since its inception and i can immediately locate the handle. 

Rest -  it depends on Mattia :)

**Comment by corndogcomputers** [comment]
That's fine. A configurable option then....?

**Comment by B-iggy** [comment]
see my issue: https://github.com/equinusocio/material-theme/issues/75 
We have to do it by ourselves ;)

**Comment by equinusocio** [comment]
You can't add a separator only for console panel. They use a shared style. So all panels (find, find/replace/packages) will get a top border. I will try some trick to do this in this days, but i can't make sure that work. :+1:
