### ISSUE TITLE
No "Enter Abbreviation" panel

### ISSUE THREAD

**Issue by MaciejJanyska** [equinusocio/material-theme#399]
When I'm trying to put "enter abbreviation" (Emmet http://docs.emmet.io/actions/wrap-with-abbreviation/) the text is invisible in a field.

With standard theme it looks like this:

![sublime](https://cloud.githubusercontent.com/assets/1210486/9135309/3549efac-3d0c-11e5-8d9d-494080408552.png)

Material Theme doesn't support it now.

**Comment by equinusocio** [comment]
Y<ou can find the fix in the README file. Check also #67

**Comment by MaciejJanyska** [comment]
Resizing a panel does the trick. Thank you!
