### ISSUE TITLE
Syntax Highlight improvements

### ISSUE THREAD

**Issue by Kail0** [equinusocio/material-theme#4]
I guess, it's a matter of taste, but I would prefer more distinctive lines.. just a opinion, don't take me bad, sir.

**Comment by UsainBloot** [comment]
If any changes were added to the line highlighting, it would be nice to see these changes reflect the line number highlighting.

**Comment by equinusocio** [comment]
I remember that this theme is in beta development. No color schemes are already definited. :)

**Comment by Kail0** [comment]
Exactly, it's a beta. That's why is feedback so important, sir...

**Comment by equinusocio** [comment]
Yes, but at the moment the syntax highlight aren't yet implemented. So, i've read the suggest and thanks, i'll consider it.

**Comment by Kail0** [comment]
Naah, it's up to you, sir. I don't want to be pain in the a-hole. 
You are doing your job and I really appreciate it your effort. Really good looking theme, I'm in love.

have a nice day! (=
