### ISSUE TITLE
When renaming a file, the field is obscured by the footer. 

### ISSUE THREAD

**Issue by marchdoe** [equinusocio/material-theme#40]
![screenshot 2015-06-09 15 26 12](https://cloud.githubusercontent.com/assets/20447/8067467/e9630016-0ebb-11e5-9382-95b81c43eec7.png)

note the footer is above the input where you can rename the file

**Comment by Alaneor** [comment]
Yes, see #34, #19, #23, #18... Seems that this list will only grow.:)

**Comment by marchdoe** [comment]
@Alaneor Whoops, sorry about that I only looked at the first issue tab. A bit new to reporting, etc. Thanks for the additional links.

**Comment by Alaneor** [comment]
No problem, I did exactly that myself when I came here...

**Comment by marchdoe** [comment]
@Alaneor I am going to open up the theme and see if I can't open up a PR

**Comment by Alaneor** [comment]
In #13 @equinusocio mentions this to be a Sublime bug, but hey - don't let me stop you from trying!

**Comment by RowdyPuran** [comment]
manually resize the rename bar and hopefully the problem should solve

**Comment by equinusocio** [comment]
This ST bug was fixed in the latest builds.
