### ISSUE TITLE
Add options to change row height of sidebar tree

### ISSUE THREAD

**Issue by caeldom** [equinusocio/material-theme#400]
I love the material design. Would be great if an option to change the row height of the sidebar tree could be added to the settings.

Something like material_theme_sidebar_tree_small etc.

Examples of this setting in other popular themes:
https://github.com/kkga/spacegray#sidebar-tree-rows-height
https://github.com/thinkpixellab/flatland#optional-settings

**Comment by gj1118** [comment]
Mattia has said that he is not going to do . I remember because I requested this twice and came across the same reply both times.


:)

**Comment by caeldom** [comment]
Really? Isn't it as simple as adding the following code to sublime-theme?

```json
{
    "class": "sidebar_tree",
    "settings": ["material_theme_sidebar_tree_small"],
    "row_padding": [24, 2]
},
{
    "class": "sidebar_tree",
    "settings": ["material_theme_sidebar_tree_medium"],
    "row_padding": [24, 4]
},
etc...
```
Anyway, I manually changed the sidebar settings in the theme myself, using [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) to edit the Material Theme sublime package, and then the sublime-theme file inside. Look for ```"class":"sidebar_tree"``` and edit the row_padding value to whatever tickles your sidebar fancy.

**Comment by gj1118** [comment]
Sorry I was not specific earlier. I had requested about the sidebar font size and **not** the row height..  I sincerely apologize if that created some confusion. Here is the issue that I had created #391
