### ISSUE TITLE
Broke in sublimetext 3095 Linux

### ISSUE THREAD

**Issue by ibrahimsaqr** [equinusocio/material-theme#403]
the theme continue to crash on Sublime Text 3095 Linux version
this happen a lot

sublime automatically return to it's default theme and I have to reopen the user settings file and retype "theme, color_scheme" options again.

so any body knows why that !!!

**Comment by welkang** [comment]
I have also meet this situation on Mac and Windows platform.

**Comment by equinusocio** [comment]
please post:
- OS version
- ST build
- installed packages
- preferences
- console log

**Comment by ibrahimsaqr** [comment]
OS: Linux Mint 17.1, 17.2

ST build: 3090, 3095

installed packages: [
		"AdvancedNewFile",
		"AutoFileName",
		"Blade Snippets",
		"BracketHighlighter",
		"Color Highlighter",
		"Emmet",
		"Git",
		"jQuery",
		"Laravel Blade Highlighter",
		"Material Theme",
		"Package Control",
		"SCSS",
		"SFTP",
		"SideBarEnhancements",
		"Terminal"
	]

Theme preferences: [
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
"material_theme_small_tab": true,
"material_theme_disable_fileicons": true,
"material_theme_disable_folder_animation": true,
"material_theme_small_statusbar": true,
"material_theme_disable_tree_indicator": true,
"material_theme_bold_tab": true,
"material_theme_tabs_separator": true,
"material_theme_accent_lime": true,
"material_theme_accent_purple": true,
"material_theme_accent_red": true,
"material_theme_accent_orange": true,
"material_theme_accent_yellow": true, 
"material_theme_panel_separator": true
]

console log: not available now ... I'll add it soon

**Comment by equinusocio** [comment]
So, the console log?

**Comment by ibrahimsaqr** [comment]
I'm sorry ... the theme does not crash since my last replay ... So I can not get the console log ... because I cleared it ... I think we should close the issue until the theme crash again!!!

**Comment by ibrahimsaqr** [comment]
the theme crashed again today and this is a console log

--------------------------------------------------------------------------------------------------
DPI scale: 1
startup, version: 3095 linux x64 channel: dev
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/ibrahim/.config/sublime-text-3/Packages
state path: /home/ibrahim/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/ibrahim/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage", "Material Theme"]
pre session restore time: 0.187655
warning: mnemonic b not found in menu caption SFTP/FTP
startup time: 0.319487
first paint time: 0.327531
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.run_all_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SFTP.SFTP
SFTP: enabling custom linux ssl module
SFTP: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin Terminal.Terminal
plugins loaded
error: unable to open crawldb (~/.config/sublime-text-3/Index), indexing is unavailable
Emmet: No need to update PyV8
Package Control: The package Material Theme is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["Vintage"]
warning: mnemonic b not found in menu caption SFTP/FTP
generating meta info summary
warning: mnemonic b not found in menu caption SFTP/FTP
Package Control: Skipping automatic upgrade, last run at 2015-09-01 22:46:42, next run at 2015-09-01 23:46:42 or after
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
warning: mnemonic b not found in menu caption SFTP/FTP
-----------------------------------------------------------------------------------------------------

all other data not changed (addons, theme preferences, etc)

**Comment by equinusocio** [comment]
no issue... isn't a crash. Is the auto update. i've released two version today.

**Comment by ibrahimsaqr** [comment]
ok but the theme disabled and I have to re-open settings and re-type "theme" and "color_scheme" settings !!! if this from update I think you have to fix that.

but any way the theme is really great and I use it in my daily work.
