### ISSUE TITLE
Input doesnt show old name of file to be renamed when renaming files or folders

### ISSUE THREAD

**Issue by kn9ts** [equinusocio/material-theme#405]
When you right click to rename a file and the bottom panel input pops up to  display old name of file to be renamed. The old name is not visible at all.

See image below.

<img width="585" alt="screenshot at aug 15 10-47-12" src="https://cloud.githubusercontent.com/assets/1999708/9288012/48069ffc-433b-11e5-9172-fb46625d52ad.png">

**Comment by MoreAxes** [comment]
This appears to be an issue related specifically to the bottom panel, as it is reproducible with all packages I've used that rely on it (e.g. iOpener, ShellCommand). I haven't found a workaround.

**Comment by equinusocio** [comment]
@MoreAxes Duplicated of 404 and many other issues. Before open a issue please read the README file.
