### ISSUE TITLE
Too much red in JS

### ISSUE THREAD

**Issue by giltig** [equinusocio/material-theme#406]
Hi, 
I'm using babel js syntax in sublime (great for es6).
I really like your theme although instead of variables being in gray color they all in red color.
Can you fix this ?
Thanks Gil.
![image](https://cloud.githubusercontent.com/assets/5754742/9290865/648c1e0c-43ab-11e5-9fc3-23825de4d00b.png)

**Comment by giltig** [comment]
P.s I think oceanic next color scheme is a good example which fits well with material theme.

**Comment by equinusocio** [comment]
Sorry but this isn't an issue. The red color depends on babel package, and then, this is the color scheme that material theme use. If you don't like it try another color scheme :)
