### ISSUE TITLE
SCSS Syntax Highlighting

### ISSUE THREAD

**Issue by jhned** [equinusocio/material-theme#408]
Just this morning I starting seeing some syntax highlighting issues with SCSS files. The theme was highlighting my SCSS files properly before now. Here are a couple examples:

![screen shot 2015-08-18 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/2520143/9339088/2c51ceda-45b6-11e5-8563-5c4879097960.png)

![screen shot 2015-08-18 at 2 33 15 pm](https://cloud.githubusercontent.com/assets/2520143/9339096/397854d0-45b6-11e5-89e8-3f13d062081c.png)

**Comment by equinusocio** [comment]
@jhned What sass package are you using?

**Comment by jhned** [comment]
I'm using Syntax Highlighting for Sass, and I think I've discovered the issue: when you have Syntax Highlighting for Sass installed, you have more than one SCSS option when you're setting the syntax for the file. 

![screen shot 2015-08-18 at 2 42 31 pm](https://cloud.githubusercontent.com/assets/2520143/9339416/edd5ca2e-45b7-11e5-82d7-f1c514b0105b.png)


Using the default "Set Syntax: SCSS" option that is available with the package disabled produces the errors that I posted above. Using the other "Set Syntax: SCSS" option that is available after enabling the package fixed it.

**Comment by equinusocio** [comment]
@jhned Yes this is caused by the package. One syntax use the new sublime system, and one use the old syntax system that isn't available from the latest releases. 

I suggest you to associate the new syntax (which one that work) with the file extension.
