### ISSUE TITLE
Ugly sidebar font shadow in Linux

### ISSUE THREAD

**Issue by brielov** [equinusocio/material-theme#410]
I don't really know if this is a theme issue or if there is any configuration key I'm missing, ether way here it is. 

![screenshot from 2015-08-20 17 20 01](https://cloud.githubusercontent.com/assets/1876796/9394678/25cb0a62-4760-11e5-8119-2438e2242b7c.png)

**Comment by equinusocio** [comment]
Check in the next release.

**Comment by peduxe** [comment]
@equinusocio ![it's solved now](http://i.imgur.com/HlgkRPm.png)
