### ISSUE TITLE
Can I make the bottom panel smaller

### ISSUE THREAD

**Issue by dinhtungdu** [equinusocio/material-theme#413]
First, thank you for stunning theme. I love it so much.:+1:

But the bottom panel (search, replace panel) is too big for me. I set the option `"material_theme_small_statusbar": true` but not help. The padding is too large. can you show me how to make the button icon, the input field, and the padding smaller. And it would be better for other like me infuture if theme has an option for small bottom panel :heart_eyes: .

**Comment by phaberest** [comment]
Same problem here, had to change theme.

**Comment by equinusocio** [comment]
@dinhtungdu you have to overwrite the theme with your local customization. Follow this step and add your modified rules:
https://github.com/equinusocio/material-theme/issues/208#issuecomment-114864396
