### ISSUE TITLE
Unreadable font while renaming file

### ISSUE THREAD

**Issue by kalwyn** [equinusocio/material-theme#414]
Font color is same as the background when renaming file.

![screen shot 2015-08-26 at 2 42 43 am](https://cloud.githubusercontent.com/assets/8174087/9490390/499fa5fc-4b9c-11e5-9c77-b8ee1202e495.png)

Lighter bar is underlining the text

**Comment by equinusocio** [comment]
README file pls.

**Comment by kalwyn** [comment]
My bad. Great work!
