### ISSUE TITLE
Indicate symlinks

### ISSUE THREAD

**Issue by nalbion** [equinusocio/material-theme#415]
I find it very useful to be able to see which directories are symlinked to a development workspace and which folders have been installed by bower/npm.  IntelliJ shows a little link overlay in the top-right corner.  I have seen other Sublime themes which show an arrow within the folder, or an outlined folder

**Comment by equinusocio** [comment]
You should see the folder with 2 arrows for the symlink. You don't?

**Comment by airtonix** [comment]
nope. symlinked folders appear no differently to non symlinked folders.

![screenshot from 2015-09-15 09 35 07](https://cloud.githubusercontent.com/assets/61225/9864826/28ccad56-5b8d-11e5-9cd9-73cbaeff48b4.png)

Highlighted folder is a symlink: 
![screenshot from 2015-09-15 09 36 34](https://cloud.githubusercontent.com/assets/61225/9864867/8a28920e-5b8d-11e5-9d0a-151fd3cdf1d8.png)

**Comment by equinusocio** [comment]
Are you using the latest build of ST? This is what i see and what you should see:

**Comment by airtonix** [comment]
Yes I'm using latest.

Rather than using finder, it's more useful to show the symlink in your terminal with : `ls -al ./`

Also I don't use Windows or MacOSx.

**Comment by equinusocio** [comment]
This isn't a theme related issue. I think there is a problem with symlink on Linux.

**Comment by airtonix** [comment]
Err... No.

You can clearly see in the screenshot the symlink works.

**Comment by equinusocio** [comment]
@airtonix Not for ST. I can only change the icon, i can work on the ST symlink behavior

**Comment by Yimiprod** [comment]
i'm on a mac and i have the same problem, folders icon even for symlinks.
