### ISSUE TITLE
Text in bottom of screen cut off

### ISSUE THREAD

**Issue by hiramhibbard** [equinusocio/material-theme#416]
When creating a new file or directory from the sidebar (I'm using SideBarEnhancements), the text field for typing the file/directory name is nearly invisible.

![untitled-1](https://cloud.githubusercontent.com/assets/658679/9558307/e8f14496-4d98-11e5-9fff-cb88cac6593e.jpg)

**Comment by brunogaspar** [comment]
This if [this](https://github.com/equinusocio/material-theme#known-issues) fixes your issue.

**Comment by equinusocio** [comment]
Please read the README file and #67
