### ISSUE TITLE
Doesn't Work with Advandced new File

### ISSUE THREAD

**Issue by SteveAzz** [equinusocio/material-theme#42]
Hell I use the Plugin called "Advandced New File" where I press ctrl+alt+ n to open up a dialog box at the bottom. In Material design i looks like the following whilst in other themes it looks normal.

Other Theme :
http://imgur.com/6HVtPgc

Material Theme :
http://imgur.com/3cvNUIO

Thank you for the awesome theme.

**Comment by equinusocio** [comment]
See #18. Thit is a sublime text bug that appear sometimes when you change the UI theme.
