### ISSUE TITLE
Can't see text box when renaming files

### ISSUE THREAD

**Issue by GuruAnt** [equinusocio/material-theme#421]
In the *Folders* pane on the right, when I right-click on a file and *Rename* I don't see the text-entry box in the bottom, although I do see a horizontal line roughly corresponding to the length of the filename.
![sublimematerialrename](https://cloud.githubusercontent.com/assets/4224152/9625249/861e1580-514c-11e5-9f74-2651070eb7ae.png)

Build 3083 / Windows 7

**Comment by equinusocio** [comment]
please read the README file.

**Comment by GuruAnt** [comment]
Doh! Sorry.
