### ISSUE TITLE
Theme switches to default on update

### ISSUE THREAD

**Issue by atilkan** [equinusocio/material-theme#422]
Theme switches to default sublime theme on every update or opening. Formatted and still happening. On mac, windows and ubuntu.

**Comment by thiensubs** [comment]
Yes, What happen with it! My theme was gone! Please fix it

**Comment by thiensubs** [comment]
Any body fix it?

**Comment by equinusocio** [comment]
This isn't a theme related issue. This is the PC behavior when update packages. It disable the package and, after update, the package should be reactivated.

**Comment by thiensubs** [comment]
Are you sure about that? Because my PC is automatic update packeage. And when it update successfully, theme broken. Do you want to see my image and my config?

**Comment by NomNuggetNom** [comment]
This happened to me too.

**Comment by danqing** [comment]
+1 seeing the default theme on Mac

**Comment by atilkan** [comment]
@equinusocio I never thought i say this. Please don't update this often then. We see bugs more than features.

**Comment by equinusocio** [comment]
@atilkan What kind of bugs

**Comment by atilkan** [comment]
@equinusocio According to your word Sublime bug. Eventually it bugs users. :D

**Comment by gj1118** [comment]
guys, this happens to me as well. but I dont see this as an issue and somehow i agree with @equinusocio as well. Updating , installing a package is done by the Package control. If the Package control fails to revert it back to the theme that was already being used, pray, tell me how how @equinusocio can set it for you. I think if @equinusocio had that ability he would have forced you to use a theme of his liking. Also  I have themr package installed and if it changes to the default i take 2 seconds out to change it back. 

@atilkan I would suggest you to disable package control and then the theme will never be updated, but please let me have my updates... 

give the man some rest :)

**Comment by equinusocio** [comment]
I suggest everyone to use internet before open any issue. That's all you need, so:

- Similar to other issues:
https://github.com/equinusocio/material-theme/issues/234
https://github.com/equinusocio/material-theme/issues/283

- Related issues on package control repo:
https://github.com/wbond/package_control/issues/965
https://github.com/wbond/package_control/issues/961

I also suggest to learn to know tools you're using. Closed and locked.
