### ISSUE TITLE
Incorrect Material JavaScript colour scheme 

### ISSUE THREAD

**Issue by agreco** [equinusocio/material-theme#423]
Hey,

The recent update has created a problem for the JavaScript colour scheme.. please see screen shot below. 

![screen shot 2015-09-02 at 12 59 35](https://cloud.githubusercontent.com/assets/20005/9630484/9c221450-5172-11e5-8f27-901743035c1e.png)

I was currently using SBT3 dev build 3083, when this problem occurred. Then moved to using, SBT3 dev build 3095, and the issue is still persisting.

**Comment by equinusocio** [comment]
are you using Material Theme 1.8.6 or 1.8.5?

**Comment by agreco** [comment]
I'm using using package manager, so pm automatically updated to 1.8.6

**Comment by Paleolithic** [comment]
I'm also seeing similar JavaScript syntax highlighting. I'm not sure if the blue brackets and general text being blue is a feature or a bug? But it's new as of this update.

![screen shot 2015-09-02 at 1 10 51 pm](https://cloud.githubusercontent.com/assets/3632506/9638312/19eece5e-5174-11e5-8191-8fbf7be86ec3.png)

**Comment by equinusocio** [comment]
@Paleolithic Please post your code snippet

**Comment by Paleolithic** [comment]
```javascript
function forEach(obj, iterator, context) {
  var key, length;
  if (obj) {
    if (isFunction(obj)) {
      for (key in obj) {
        // Need to check if hasOwnProperty exists,
        // as on IE8 the result of querySelectorAll is an object without a hasOwnProperty function
        if (key != 'prototype' && key != 'length' && key != 'name' && (!obj.hasOwnProperty || obj.hasOwnProperty(key))) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    } else if (isArray(obj) || isArrayLike(obj)) {
      var isPrimitive = typeof obj !== 'object';
      for (key = 0, length = obj.length; key < length; key++) {
        if (isPrimitive || key in obj) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    } else if (obj.forEach && obj.forEach !== forEach) {
        obj.forEach(iterator, context, obj);
    } else if (isBlankObject(obj)) {
      // createMap() fast path --- Safe to avoid hasOwnProperty check because prototype chain is empty
      for (key in obj) {
        iterator.call(context, obj[key], key, obj);
      }
    } else if (typeof obj.hasOwnProperty === 'function') {
      // Slow path for objects inheriting Object.prototype, hasOwnProperty check needed
      for (key in obj) {
        if (obj.hasOwnProperty(key)) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    } else {
      // Slow path for objects which do not have a method `hasOwnProperty`
      for (key in obj) {
        if (hasOwnProperty.call(obj, key)) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    }
  }
  return obj;
}
```

**Comment by xichuanwang** [comment]
+1 @Paleolithic 

@equinusocio 
also seeing blue syntax highlighting after updating to latest via pm. definitely threw me off after restarting sublime. not sure about everyone else but I prefer the original white text.

**Comment by agreco** [comment]
My previous screenshot was using JavaScript ES6 s

**Comment by seansellek** [comment]
Really bothered by the blue syntax as well =(

<img width="811" alt="screen shot 2015-09-02 at 5 16 02 pm" src="https://cloud.githubusercontent.com/assets/1727840/9644835/4fcbf138-5196-11e5-9508-9e4c223c483e.png">

**Comment by equinusocio** [comment]
@Paleolithic what build of ST are you using? Are you using native ST javascript or package? That's what i see with native js and your snippet:

<img width="1022" alt="screen shot 2015-09-02 at 23 55 57" src="https://cloud.githubusercontent.com/assets/10454741/9645799/457bebc4-51ce-11e5-8ea2-669190dfb759.png">

**Comment by equinusocio** [comment]
@agreco paste your snippet please

**Comment by Paleolithic** [comment]
@equinusocio I'm using Sublime Text Stable Channel, Build 3083, native js on a Mac OSX Version 10.9.5 Mavericks

**Comment by equinusocio** [comment]
@Paleolithic ST 3084 beta (released April 8 2015) add a new syntax system. My theme are build on this new format, and doesn't offer a fallback for the old syntax system. Please consider to use the beta channel (stable and updated).

**Comment by Paleolithic** [comment]
@equinusocio Alright, thank you. This is likely the same problem the other people are having as well.

**Comment by equinusocio** [comment]
The issue has already been discussed in a similar one
https://github.com/equinusocio/material-theme/issues/299

**Comment by agreco** [comment]
@equinusocio read through #299, and I'm not sure I understand the outcome of the discussion. It seems that this ticket being closed implies a "won't fix" and a workaround for it is to upgrade to 3095?

**Comment by equinusocio** [comment]
This isn't a workaround. The new sublime-syntax is more powerfull and allow a more specific customization. Not only for the color scheme, but also for the UI elements like file type icons that use the new system. I think the new stable release (with the new syntax system) will be available in the next weeks.

**Comment by agreco** [comment]
Ok cool. So just to be clear, are you saying the new syntax system in the new stable release should resolve the red variable colours?

**Comment by equinusocio** [comment]
No, the red variables are correct. The problem is the blue. But i need to test your code and scopes.

**Comment by agreco** [comment]
Oh, so the latest release is changing the colours of variables to red intentionally? Won't this look a bit too strong on the eyes?

**Comment by agreco** [comment]
As requested you can grab my code from here https://github.com/agreco/spiel/blob/master/src/helpers.js

**Comment by deshiknaves** [comment]
I have the same issue with the latest version of Sublime 3095 and I just uninstalled and reinstalled the theme. The dark theme has the right JS syntax highlighting, the default (which I normally use), everything is blue (well lots of things). Not sure why this one has been closed.

**Comment by denizozger** [comment]
Red variables do look like a bug as it's quite bizarre to colour plain text in red.. I love everything about this theme but red variables make it impossible to use. Many people seem to be complaining as well.

Is there any way (setting, hack etc) to change this colour?

Thanks

**Comment by equinusocio** [comment]
Variables are red from the first color scheme beta released 3 months ago. Isn't a bug.
