### ISSUE TITLE
can't resize bottom panel.

### ISSUE THREAD

**Issue by airtonix** [equinusocio/material-theme#424]
read the README... still can't resize the bottom panel.
therefore can't: 

- rename files
- duplicate files
- move files
- find and replace
- etc

This *is* a bug with your theme. it *is* critical because i can't use sublime text with this theme.

the fix is to remove the padding so we can see the input fields.

**Comment by equinusocio** [comment]
README file :+1:

**Comment by airtonix** [comment]
first line of my comment above: {{ read the README... still can't resize }}.

**Comment by equinusocio** [comment]
This isn't a theme related bug, see #67 and many other similar issue
