### ISSUE TITLE
keyword.operator.logical.python

### ISSUE THREAD

**Issue by aldanor** [equinusocio/material-theme#425]
Can barely tell the difference of logical operators (and also arguments in function definitions) from the normal code (like variables):

![image](https://cloud.githubusercontent.com/assets/2418513/9657884/ea54169e-523c-11e5-84f0-0edc0402b2a1.png)

I can tell function arguments and logical operators are a bit different in color, greenish and brighter, but I really have to squint to discern that.

Most (if not all) color schemes I've used highlight Python operators the same way as keywords (`keyword.control.flow.python`). Here's Tomorrow Eighties:

![image](https://cloud.githubusercontent.com/assets/2418513/9657868/d300e242-523c-11e5-9cc6-d3920cfa30eb.png)

Oceanic Next:

![image](https://cloud.githubusercontent.com/assets/2418513/9657913/2d962992-523d-11e5-8fa9-42f95456989f.png)

**Comment by equinusocio** [comment]
@aldanor this should be fixed in the next release.

**Comment by aldanor** [comment]
Thanks!
