### ISSUE TITLE
support.type.python

### ISSUE THREAD

**Issue by aldanor** [equinusocio/material-theme#426]
The built-in types (`support.type.python` scope) don't seem to be highlighted at all; for example:

```python
int
float
bool
str
tuple
list
long
unicode
set
dict
```

and a few others.

**Comment by equinusocio** [comment]
Can you post a screenshot and snippet? What ST build are you using?

**Comment by aldanor** [comment]
Using ST 3 v3083, I believe that's the latest?

Here go some screenshots.

Material theme:

![image](https://cloud.githubusercontent.com/assets/2418513/9680421/c467a47a-52ee-11e5-8d8a-d654ba9b60f9.png)

Tomorrow Eighties:

![image](https://cloud.githubusercontent.com/assets/2418513/9680417/b391a2cc-52ee-11e5-817a-4909d419a576.png)

Rails Casts:

![image](https://cloud.githubusercontent.com/assets/2418513/9680435/dd5005fe-52ee-11e5-8627-1f6488ebd7cd.png)

**Comment by aldanor** [comment]
Thanks! Any chance for a release anytime soon?

**Comment by equinusocio** [comment]
I don't know. It is a minor bug. If you want to use latest changes, you can install the package manually by downloading the master branch

**Comment by raduchiriac** [comment]
I don't like the way my JS files look after this update. I cannot differentiate Function names from Objects and property names. I had to switch to the Darker version

![image](https://cloud.githubusercontent.com/assets/1213284/9791154/f339a420-57d9-11e5-8ecc-d5ac3a703332.png)
