### ISSUE TITLE
Find & Replace Dialog Display

### ISSUE THREAD

**Issue by austinstudio** [equinusocio/material-theme#427]
The find and replace box, the one that you use when you hit Command+Shift+F doesn't show all of the content.  It is too short and chops off the Where and the Replace fields.  I am on a MacBook Pro Retina.

<img width="1459" alt="screenshot 2015-09-03 09 52 52" src="https://cloud.githubusercontent.com/assets/1907053/9660040/96369b9c-5221-11e5-9c72-5724473d052b.png">

**Comment by equinusocio** [comment]
Please read the README file for the fix.
