### ISSUE TITLE
Bottom dialogue unsuable with SideBarEnhancements

### ISSUE THREAD

**Issue by matthewerskine** [equinusocio/material-theme#428]
When attempting to use a SideBarEnhancements command such as 'File: Move', the text entry dialogue at the bottom of the editor is not visible with this theme.

This is how it appears when no theme is being used:
![screen shot 2015-09-03 at 16 00 14](https://cloud.githubusercontent.com/assets/7579504/9661925/e3a5273a-5254-11e5-9af1-5d0b3b5b949c.png)

This is how it appears when using this theme:
![screen shot 2015-09-03 at 15 55 51](https://cloud.githubusercontent.com/assets/7579504/9661874/a93c7fe4-5254-11e5-9813-7b6e41470835.png)

**Comment by equinusocio** [comment]
You can find the fix in the README file.
