### ISSUE TITLE
Tab separator 

### ISSUE THREAD

**Issue by nawazdj** [equinusocio/material-theme#429]
It seems that the Tab separator indicator is TOO subtle to notice.

**Comment by tomahl** [comment]
+1

**Comment by ArmorDarks** [comment]
also, would be not bad to have optional bottom separator too

**Comment by equinusocio** [comment]
@ArmorDarks "material_theme_panel_separator"

**Comment by ArmorDarks** [comment]
@equinusocio sorry, my bad — I meant bottom separator for tabs, but just now I've noticed that they already have very-very-very subtle bottom separator

**Comment by equinusocio** [comment]
Isn't a separator. What you see is the top shadow of the editor.
