### ISSUE TITLE
Text color and panel background the same

### ISSUE THREAD

**Issue by wldcordeiro** [equinusocio/material-theme#43]
If you use something like Vintageous this is how the command panel looks.

![Sublime Text panel wrong](https://cloud.githubusercontent.com/assets/580982/8088513/2580da16-0f5f-11e5-9524-30de93523be3.jpg)

This is how it looks with another theme for comparison.

![Sublime Text panel right](https://cloud.githubusercontent.com/assets/580982/8088514/25826e9e-0f5f-11e5-8633-cc660448123e.jpg)

**Comment by equinusocio** [comment]
The Vintageous tab looks identic in the screenshots, but the second one you use a black theme and you don't see so much different. This is not a theme issue...

**Comment by wldcordeiro** [comment]
Look at the very bottom of the screenshot, right above the status bar, there's a command bar that's impossible to use with your theme currently.

**Comment by gj1118** [comment]
@wldcordeiro  see #19

**Comment by wldcordeiro** [comment]
@gj1118 Oh I see, well after resizing the background of the bar is still the color of the color scheme and not the white of other panels.

**Comment by equinusocio** [comment]
Pls upload high quality screenshot :)

**Comment by wldcordeiro** [comment]
@equinusocio It was high quality but Github's compression is way too high. :disappointed:

**Comment by equinusocio** [comment]
Ok i see. Unfortunately i think i can do much for this issue. This happen with all packages (emmet do the same) because their use a code syntax inside the input instead of the sublime text standard input.
