### ISSUE TITLE
Sidebar and tab background color

### ISSUE THREAD

**Issue by tomahl** [equinusocio/material-theme#430]
I think the UI would be even greater if it was possible to choose an alternative color for the sidebar and tab bar.

**Comment by olimorris** [comment]
Why can't you do that yourself using PackageResourceViewer and searching for the RGB color you'd like to replace?

Infact there's even a screencast here showing you how to do it:
https://laracasts.com/series/sublime-text-mastery/episodes/1

**Comment by tomahl** [comment]
Well, for an end-user like myself I think the theme would be better in total if it was possible to achieve color change with a setting instead of having to install additional packages etc. Thanks for your suggestion anyway. I'll try that in the mean-time.

**Comment by equinusocio** [comment]
Sorry but i will not add this options. There are to many variable and to many "user preferences" here. I could not find a solution that fits all. Sorry.
