### ISSUE TITLE
Add option to make tabs responsive

### ISSUE THREAD

**Issue by Stephn-R** [equinusocio/material-theme#431]
Can we have an option where the tabs width are wrapped to the width of the filename rather than a fixed width?

**Comment by equinusocio** [comment]
@Stephn-R Isn't possibile.

**Comment by Stephn-R** [comment]
Have you looked at how the Pheonix theme does this?

**Comment by Stephn-R** [comment]
In Phoenix, if you set the tab width to 0, they will auto adjust:

'''json
    // Tab set
    {
        "class": "tabset_control",
        "settings": ["phoenix_tabs_auto_width"],
        "tab_width": 0
    },
'''

**Comment by equinusocio** [comment]
@Stephn-R Mmm thanks. I will check for this. It's a trick but i can add this in the next release 👍

**Comment by Stephn-R** [comment]
I will attempt doing this sometime soon to see if it works

**Comment by Stephn-R** [comment]
Oh, awesome. I'll run a quick local test but perhaps aim for the next release! :simple-smile:
