### ISSUE TITLE
Theme didn't load properly 

### ISSUE THREAD

**Issue by wembleyhoo** [equinusocio/material-theme#432]
I can't find any solution to fix this, does anyone encounter the same problem ? I am using build 3038 , Mac OS. I have tried to restart ST. 
<img width="1102" alt="screen shot 2015-09-06 at 21 44 43" src="https://cloud.githubusercontent.com/assets/11646511/9704199/a9a2bb36-54e0-11e5-857c-573ae466a92a.png">

Thanks.

**Comment by wembleyhoo** [comment]
I have figured out. Close.

**Comment by jamland** [comment]
what caused the issue? i have similar glitches =\

**Comment by wembleyhoo** [comment]
I made a mistake on the directory. Instead of locate the Material Theme folder on Packages, I misplace it on User folder. 

Cheers : ) 
Hope this solve your issue.

**Comment by jamland** [comment]
Thanks @wembleyhoo!
I've just reinstalled it and it works smooth =)
