### ISSUE TITLE
Messy sidebar

### ISSUE THREAD

**Issue by kenmaclord** [equinusocio/material-theme#433]
Hey,

I'm facing an issue about the sidebar. No folders can be opened, and if I resize the sidebar I get a messy stuff.

![capture d ecran 2015-09-07 a 11 31 08](https://cloud.githubusercontent.com/assets/5345859/9713815/3f4b50b2-5554-11e5-82aa-3d5c2e9f1765.png)

Karl.

**Comment by equinusocio** [comment]
You preference file is broked. Have you restarted ST after applying the theme?

**Comment by kenmaclord** [comment]
Hello Mattia,

I did some workaround in my preference file and restarted ST and everything is fine now.

Thanks for your answer and for your work !!

Karl.

Le 8 sept. 2015 � 22:43, Mattia Astorino a �crit :
