### ISSUE TITLE
New file input invisible

### ISSUE THREAD

**Issue by idleberg** [equinusocio/material-theme#435]
When adding a new file to a folder from the sidebar, a dialog pops up at the bottom of Sublime Text in which I can name the file.

![screen shot 2015-09-10 at 11 53 43](https://cloud.githubusercontent.com/assets/1504938/9785446/d624c256-57b2-11e5-90bc-1cab33b4fc71.png)

When using Material Theme, the dialog is unusable, since it's not readable at all. When using a different color scheme (with a different background color that Material), one can notice the bar at the bottom extends. Also, the font color matches the background, so it's impossible to tell what one is typing.

![screen shot 2015-09-10 at 11 54 11](https://cloud.githubusercontent.com/assets/1504938/9785511/35970aa0-57b3-11e5-8243-a3f8196c4e08.png)

**Comment by aldanor** [comment]
https://github.com/equinusocio/material-theme/issues/67?
