### ISSUE TITLE
Color scheme JavaScript change with latest update?

### ISSUE THREAD

**Issue by kalms** [equinusocio/material-theme#437]
It seems like there was a change in the latest material theme design with JavaScript, causing objects and function to be all colored green(ish)?

![screen shot 2015-09-11 at 10 40 21](https://cloud.githubusercontent.com/assets/867757/9810503/93ee5eb4-5871-11e5-9947-3a4bdcca73b4.png)

Sadly I don't have a screenshot of what it looked like before the update. But it seems off to me.

**Comment by m19** [comment]
I have this too. I don't think this is supposed to happen?

**Comment by aldanor** [comment]
I think it's related to #426, #436 and https://github.com/equinusocio/material-theme/commit/185cdd31e3d03f66d01e85c2498fb4b0310a07f6

**Comment by kalms** [comment]
It is, which is why I closed it. Sorry!

**Comment by raduchiriac** [comment]
@kalms I liked the way it was before. I had to switch to `Material-Theme-Darker` because as you said, in JS everything was green(ish). Hope it will get better in the future.

**Comment by equinusocio** [comment]
@raduchiriac what ST build are you using?

**Comment by raduchiriac** [comment]
@equinusocio 3083

**Comment by equinusocio** [comment]
From 3084 ST use a new syntax system

**Comment by astanciu** [comment]
So what's going to be the eventual resolution to this?

**Comment by equinusocio** [comment]
Use a latest beta build or wait until it will be released as a stable.
