### ISSUE TITLE
Changing the comments color - very hard to see

### ISSUE THREAD

**Issue by noctivityinc** [equinusocio/material-theme#439]
How do we change the comments color?  It's almost impossible to see and causing eye strain.

<img width="1070" alt="screen shot 2015-09-15 at 1 22 14 pm" src="https://cloud.githubusercontent.com/assets/78850/9884341/329d2cbe-5bad-11e5-89a9-603a207abadf.png">

**Comment by ValentinTrinque** [comment]
I do agree. The comments are very hard to read. This is the only thing which annoys with this theme.

**Comment by equinusocio** [comment]
You can customise the theme by following this:
https://github.com/equinusocio/material-theme/issues/305#issuecomment-120479395
