### ISSUE TITLE
When the plug-in uses the lower input box, for example Emmet (сtrl + g), the letters you type is not visible.

### ISSUE THREAD

**Issue by borovik96** [equinusocio/material-theme#440]
![-projects-camers-cart php camers - sublime text unregistered _001](https://cloud.githubusercontent.com/assets/9018702/9907908/f4e2731e-5c99-11e5-84da-052988ef2fbd.png)
The picture highlighted entered characters.

**Comment by erlingur** [comment]
Check this: https://github.com/equinusocio/material-theme/issues/67#issuecomment-111689361
