### ISSUE TITLE
Material Theme on Windows

### ISSUE THREAD

**Issue by Vahn84** [equinusocio/material-theme#441]
Hi, thanks for this great theme. Don't know if it's really an issue or not (i see that all of your screenshots refer to the OsX platform), but on windows 7 installing the Material Theme doesn't change the appearance of the sidebar and the bottom bar

I've also installed the white panels addon but didn't help

**Comment by equinusocio** [comment]
@Vahn84 Have you restarted ST?

**Comment by Vahn84** [comment]
Yep! Multiple times :(

(Ciao! :D )

**Comment by equinusocio** [comment]
@Vahn84 Incollano le tue preferenze

**Comment by Vahn84** [comment]
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 11,
	"ignored_packages":
	[
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_lime": true,
	"material_theme_accent_orange": true,
	"material_theme_accent_purple": true,
	"material_theme_accent_red": true,
	"material_theme_accent_yellow": true,
	"material_theme_bold_tab": true,
	"material_theme_disable_fileicons": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_disable_tree_indicator": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": true,
	"material_theme_tabs_separator": true,
	"overlay_scroll_bars": "enabled"
}

**Comment by rajasiman** [comment]
@Vahn84 you also need to add this to the preferences file.

"theme": "Material-Theme.sublime-theme",

**Comment by Vahn84** [comment]
thanks!

love ya all guys!!!!! xD

Sorry for my inattention. I'm closing the issue
