### ISSUE TITLE
White Panels Issues

### ISSUE THREAD

**Issue by scott-joe** [equinusocio/material-theme#446]
I dunno if it's a real issue or just a common issue in Subl, but when I installed White Panels and decided I didn't like it, it did not uninstall well... it persisted and the only solution was to uninstall the Soda theme, the Spacegray theme, and all aspects of the Material Theme, then re-install the Material Theme and add the 2 baseline config options back to the Settings file.

There's no better space to pose these comments so I just wanted to make the statement.

**Comment by equinusocio** [comment]
When you uninstall white-panels package you have to wait until finished and then set again `"theme": "Material-Theme.sublime-theme"`.

I suggest you instead to uninstall white panels add it to the ignored packages and restart ST
