### ISSUE TITLE
TypeScript-Sublime Plugin Compatibility 

### ISSUE THREAD

**Issue by joshtoo** [equinusocio/material-theme#448]
@equinusocio 

First. Epic Sublime theme, best by far.

That being said, there are compatibility issues that exist between https://github.com/Microsoft/TypeScript-Sublime-Plugin and this theme. I have not worked out what is breaking and why as of yet but intend to.

Placeholder until I can finish my investigation and make the changes necessary to make full use of the tooling that the Microsoft TypeScript plugin brings to the table.

**Comment by equinusocio** [comment]
Wat kind of issues you encountered?

**Comment by joshtoo** [comment]
IntelliSense window stops functioning. 
Build window no longer displays results / errors.

I'll get a few screen grabs and see if I can find some meaningful logging. Just need to setup a VM where I can have a fresh install of Sublime, Your Theme and the Microsoft TypeScript plugin to properly test.

**Comment by equinusocio** [comment]
@joshtoo Are you sure that this is related to material theme?

**Comment by joshtoo** [comment]
@equinusocio Running the TypeScript plugin without it works fine. I am "Sure" they don't play well together. I will determine if it is the TypeScript plugin or the Theme that is causing issues. 

At the very least this issue can serve is an information hub for people that want to use the Mater theme & the TypeScript plugin. Given the popularity of the two, i'm pretty sure I won't be the only one having an issue. If it is a problem with their implementation, i'll create an issue over there and reference it here so people don't bug you about it constantly.

**Comment by joshtoo** [comment]
@equinusocio - Pretty much what I expected. After a fresh install + theme + typescript the problem was determined to be an issue with the Intelisense implementation for their sublime plugin. Tweaked it and it works like a charm.

<img width="1332" alt="screen shot 2015-09-30 at 10 04 56 am" src="https://cloud.githubusercontent.com/assets/8420490/10196948/05b5f028-675b-11e5-8213-b925532c015c.png">

**Comment by equinusocio** [comment]
:+1:
