### ISSUE TITLE
Renaming dialog?

### ISSUE THREAD

**Issue by eexit** [equinusocio/material-theme#450]
Hello,

First off, thank you so much for this great theme, it's really neat!

The first issue I'm encountering with it is when renaming files: I can't see any dialog nor cursor in the filename... I end up blind typing and hopping the new file name will be right as a result.

I didn't see this in current issues, maybe nobody ever renames a file with ST?

ST v3083
Theme v1.8.7

Thanks,

**Comment by astanciu** [comment]
If you have the same symptoms for all bottom panels, like Find, etc..., it may be this: #427. It was for me. Just drag the edge up

**Comment by eexit** [comment]
Thanks @astanciu, that was it.

:+1:
