### ISSUE TITLE
Issue with New File Relative to Current View dialog

### ISSUE THREAD

**Issue by tschwartz** [equinusocio/material-theme#451]
When creating a new file relative to the current view using the command pallet, the dialog that extends upwards from the bottom does not visibly show.

1. Open Sublime Text with the Material Design Theme and Scheme enabled
2. Press `command` + `ctrl` + `p`
3. Type `New File Relative to Current View`
4. Hit `return`
5. Observe that a dialog extends from the bottom but you can not see a prompt
6. Type `file.js`
7. Hit `return`
8. Observe that a file was actually created and is now open

**Comment by gj1118** [comment]
please see #67
