### ISSUE TITLE
text field at find panel is too narrow

### ISSUE THREAD

**Issue by helloheesu** [equinusocio/material-theme#453]
At find panel, text input field is too narrow.
![find result](https://cloud.githubusercontent.com/assets/5011544/10266446/0b5702a2-6a9d-11e5-8bdc-a6bc75ada88e.png)

I suppose giving option for smaller icons or less margin between them.
Or changing layout of buttons, as 'find in files' panel look better.
![find in files result](https://cloud.githubusercontent.com/assets/5011544/10266447/0c172da2-6a9d-11e5-8a5f-f66f35e1205d.png)

Anyways, really thanks for amazing theme :)

**Comment by equinusocio** [comment]
I can't change the layout, this is only a style. You have to use bigger window.
