### ISSUE TITLE
Sidebar icons no show

### ISSUE THREAD

**Issue by milohuang** [equinusocio/material-theme#455]
I recently upgraded to El Capitan and installed Sublime Text 3 (3088) as usual. I install the theme and it turns out no icons on the sidebar.

![screen shot 2015-10-04 at 9 45 31 pm](https://cloud.githubusercontent.com/assets/919712/10268142/31a04f14-6ae2-11e5-937d-dc76f0fddb2b.jpg)

Here's the setting:

// Theme Settings
	"theme": "Material-Theme.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
    "material_theme_disable_fileicons": false,                   // Hide siderbar file type icons
	"material_theme_small_tab": true,			// Set small tabs
	"material_theme_small_statusbar": true,		// Set small status bar
	"material_theme_bold_tab": true,			// Make the tab labels bolder
	"material_theme_tabs_separator": true,		// Show tabs separator
	"material_theme_panel_separator": true,		// show bottom panel separator
	"material_theme_tabs_autowidth": true,		// Enable autowidth for tabs
	"material_theme_accent_yellow": true,		// set orange accent color

**Comment by milohuang** [comment]
Guess I was wrong. It works when I create a project.

**Comment by tunnckoCore** [comment]
@milohuang mm nope.
@equinusocio still not works for me. Before few days it works perfectly. Now just installed sublime and only material theme with it's defaults.
