### ISSUE TITLE
File icons 

### ISSUE THREAD

**Issue by enygmatik** [equinusocio/material-theme#456]
Hi! I use material theme, but icons for gulp and package.json not showed,you can help me?

<img width="929" alt="screenshot 2015-10-07 01 09 28" src="https://cloud.githubusercontent.com/assets/5849018/10324267/f7ae8d74-6c90-11e5-93cb-3b709c0fb079.png">

**Comment by equinusocio** [comment]
what build are you using?

**Comment by enygmatik** [comment]
This is latest build 1.8.7

**Comment by equinusocio** [comment]
@enygmatik Sublime text build

**Comment by enygmatik** [comment]
@equinusocio, aa sorry, build 3083.

**Comment by equinusocio** [comment]
Can you try with the latest build 3095?
