### ISSUE TITLE
color of variable sign ($)

### ISSUE THREAD

**Issue by Macsch15** [equinusocio/material-theme#459]
hi, i want to change (in the darker theme) color of the variable sign ($) to be the same as variable name how can i do that?

![2015-10-11_03-45-06](https://cloud.githubusercontent.com/assets/1592053/10414254/b4e472e6-6fca-11e5-97b8-c02c9d1b92d8.png)

thanks for help

**Comment by equinusocio** [comment]
```embedding.php text.html.basic meta.embedded.block.php source.php variable.other.php punctuation.definition.variable.php```
