### ISSUE TITLE
Сolor distortion (packages Gutter Color)

### ISSUE THREAD

**Issue by Borodin** [equinusocio/material-theme#461]
[Gutter Color packages](https://packagecontrol.io/packages/Gutter%20Color)

![default](https://cloud.githubusercontent.com/assets/645491/10417112/f222cbf8-7038-11e5-8f16-c033f078fb71.PNG)
white no white

**Comment by equinusocio** [comment]
https://github.com/ggordan/GutterColor#icon-tinting-and-light-color-schemes
