### ISSUE TITLE
.md files

### ISSUE THREAD

**Issue by Disgeae** [equinusocio/material-theme#463]
When trying to open .md files it gives this error, using standard theme:
Error loading colour scheme Packages/Predawn/predawn-markdown.tmTheme: Unable to open Packages/Predawn/predawn-markdown.tmTheme

**Comment by equinusocio** [comment]
@Disgeae Predawn?? O.o

**Comment by Disgeae** [comment]
Yeah, it's asking for another theme like the markup doesn't exist for material, this is my config:
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_face": "Roboto mono",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 12,
	"ignored_packages":
	[
		"SublimeLinter-jshint",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"material_theme_disable_folder_animation": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"tabs_small": true,
	"theme": "Material-Theme.sublime-theme"
}

**Comment by equinusocio** [comment]
Open a MD file and then open the syntax specific preferences:
![screen shot 2015-10-12 at 18 04 42](https://cloud.githubusercontent.com/assets/10454741/10432512/ca8ec924-710b-11e5-8dac-fb2e04119a80.png)

You shouldn't have any predawn reference. This is my settings:

{
	"draw_centered": true, // Centers the column in the window
	"draw_indent_guides": false,
	"trim_trailing_white_space_on_save": false,
	"word_wrap": true,
	"wrap_width": 80  // Sets the # of characters per line
}

**Comment by Disgeae** [comment]
That fixed it! Thanks!
