### ISSUE TITLE
Support ES2015 template strings

### ISSUE THREAD

**Issue by voischev** [equinusocio/material-theme#465]
<img width="500" alt="2015-10-12 17 41 22" src="https://cloud.githubusercontent.com/assets/1510217/10430648/fb5820c6-7108-11e5-8fb8-35ffb446948f.png">

**Comment by equinusocio** [comment]
Are you using Babel package?

**Comment by voischev** [comment]
in Babel package. Thx!
<img width="456" alt="2015-10-13 10 55 11" src="https://cloud.githubusercontent.com/assets/1510217/10448940/f99e9dec-7198-11e5-90b2-9188b2d84005.png">
