### ISSUE TITLE
Different colours for variables and variable functions?

### ISSUE THREAD

**Issue by chlab** [equinusocio/material-theme#466]
Hey

Is it possible to get slightly different colours for variables and functions that are variables?
I've been using this theme for a while and maybe it's just me but it seems that this changed at some point. 

Here `require` is a function in a variable:
![screen shot 2015-10-13 at 08 38 13](https://cloud.githubusercontent.com/assets/1931446/10447583/f75ef012-7185-11e5-8cb0-e4d12ab5760e.png)

But the syntax highlighting isn't really helping much when everything is the same colour :)

Here `d` is a variable and it's methods are being coloured as variables too:
![screen shot 2015-10-13 at 08 38 37](https://cloud.githubusercontent.com/assets/1931446/10447586/faf3c9b4-7185-11e5-8a5e-c51adf60ba6d.png)

What do you think?

Thanks a lot for this theme, I love it!

**Comment by equinusocio** [comment]
I'm sorry but this theme support only the new syntax-system released with the 3085+ build
