### ISSUE TITLE
Problem when apply color schema

### ISSUE THREAD

**Issue by huglester** [equinusocio/material-theme#47]
Hello,

when I try to change color schema to:
"color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",

The colors of Settings - User are chaged (after I click save), but then they are reverted right aray, and after few moments, the schema is back to previous...

Any ideas?

**Comment by equinusocio** [comment]
Make sure you have only one ```"color_scheme"``` in your preferences.

**Comment by huglester** [comment]
@equinusocio that is the problem, I am really sure it is one in the list. I replace the current one `"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",` with new one.

 click save,
I see the colors are changed but it then reverts back.. (like undo),

Theme is saved, and folders are nicely colored..
I tried git pulling the fresh version - but still the same :(

**Comment by Alaneor** [comment]
Did you restart Sublime...? You need to.

**Comment by huglester** [comment]
@Alaneor well, I edit User config, click save, 
alt tab somewhere, alt tab - to get back to sublime, and config is beeing automaticly reverted :/

**Comment by Alaneor** [comment]
Yes, well... did you restart Sublime after editing user config?:)

**Comment by Alaneor** [comment]
On second thought... Are you per any chance syncing your config via Dropbox? You might also want to check your permissions - perhaps you have only read access or something, although I would expect that would not even allow you to save the file...

**Comment by huglester** [comment]
Yeah I tried restarting. But problem is that config is somehow reverted.

For example config is:
```json
	"theme": "Material-Theme.sublime-theme",
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
```

I change to:
```json
    "theme": "Material-Theme.sublime-theme",
    "color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",
```

I click SAVE - I see imediate change of the UI.
But when I try openning other files, I see that it has 'Monokai theme', and when I return to the settings tab, it also has old styling.

And 'theme' parameter is beeing moved to bottom of the config, and 'color_scheme' is reverted to Monokai.

I believe it should be some theme issues.

Yes I use Dropbox. But I can change the other config values just fine...

Thanks for the patience:)))

**Comment by equinusocio** [comment]
When you apply the theme you have to restart sublime. If you see the old syntax color you have to close e reopen the files. Sublime Text sometime cache the syntax color per-file.

For the settings, try to change other settings and save, but i think it's a dropbox problem.

**Comment by huglester** [comment]
Why would it be a dropbox problem, if I try to change any other config value, it is saved without problem...

Are there any easy to use linux reroding tools? I'd try to create short video:)

**Comment by Alaneor** [comment]
Dropbox regularly causes me pain when I have two computers running Sublime and syncing to the same Dropbox account. One Sublime saves the config, Dropbox syncs it, but the other Sublime somehow reverts the settings back. It's kinda crazy, and the only solution for me is to kill Sublime on one machine or manually revert to a previous version from Dopbox website.

I believe you, but I don't think this is a problem with the theme.:) You might try to uninstall it and install it again. With Sublime turned off...

**Comment by Alaneor** [comment]
Another option I would try is to quit Sublime, manually edit the configuration file, set ownership to root and limit access to group and others to read-only. So Sublime will not be allowed to modify the file.

**Comment by equinusocio** [comment]
I'm sure this is not a theme issue. Try to manually edit the preferences with other editor.

**Comment by huglester** [comment]
And tried this... really first time I have similar problem. Maybe you can cuggest me other color schemes? So I just can try it?

Other PC if offline, I know what you mean by overwriting new configs, been there!:) but this issue is really something different :(

**Comment by huglester** [comment]
What i see strange, that:
`"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",`

I can't see such folder (Color Scheme ...) in the Packages folder,
while I see the 'material-theme' folder. 

Or Monokoi is just built in, and that's why it is like that?

**Comment by huglester** [comment]
Ok, what I figured out, I can't generaly switch 'color_scheme' at all.

I select even from : Preferences > Color schemes > Default > Monokai Bright,
it switches, and then rolls back :/

Any ideas?

**Comment by gj1118** [comment]
@huglester do you have PackageControl installed?  If yes, can you try disabling that and check if you can change color_schemes ?  

thanks

**Comment by huglester** [comment]
@gj1118 yes I have it installed. I can uninstall packages. But how do I disable it?

**Comment by gj1118** [comment]
@huglester if you are on windows : Ctrl+Shift+P -> disable package -> package control. If you are on a Mac , CMD+Shift+P. 


Note: I am not sure how to enable package control back again. You might have to reinstall it again. I tried looking for Disable Packages in the Preferences , but could not find it there. But disabling and installing it again, seems to have resolved that error. It seems that package control is looking for a package.json which is not there which is why it keeps reverting the theme.

**Comment by huglester** [comment]
Hello guys again!

Thanks for you patience. And solutions. Well the package control disabling did not help.. But it just pushed me to just remove sublime all together, and install from scratch.

I pushed again all my configs from dropbox, and everything seems fine.

Thanks a log for everyone!

**Comment by equinusocio** [comment]
Nice :+1:
