### ISSUE TITLE
How to compile theme?

### ISSUE THREAD

**Issue by yairEO** [equinusocio/material-theme#470]
I would like to change the graphic of the tab and compile the theme so I will have everything the same, only with the tab color change, is that possible? is so, how? Thanks a lot! awesome theme!

I'm trying to give each file type it's own theme, so the only difference will be the Tab color, so all files of certain file type will have same tab color.

**Comment by Revod** [comment]
It's a bit hard to explain, but you can create a file with the same name as your theme in the Packages/User folder. For example, with Material dark theme, you'd create 
```sublime-theme
Packages/User/Material-Theme-Darker.sublime-theme
```
and in that file, you add only changes your want to override. example, if I want the sidebar text more bold, if you wanted to make them bold, I would put this in the file:
```JSON
[
    {
        "class": "sidebar_label",
        "font.bold": true,
    },
]
```

and save

**Comment by yairEO** [comment]
Thanks. And if I want file;s tabs to have different background?

**Comment by Revod** [comment]
You can look at the [original theme file](https://github.com/equinusocio/material-theme/blob/master/Material-Theme-Darker.sublime-theme) and all its rules to get an idea of what you can change.

**Comment by equinusocio** [comment]
If you only want to change the tabs color you have to edit the relative asset image :+1:
