### ISSUE TITLE
Visual improvement File Icons?

### ISSUE THREAD

**Issue by davesnx** [equinusocio/material-theme#472]
Hello @equinusocio,

I have a small issue with the File Icons space between the icon and the label.

![captura de pantalla 2015-10-19 a las 9 58 46](https://cloud.githubusercontent.com/assets/3763599/10572370/168f230a-7648-11e5-931e-0107c598cb98.png)

I mean, as far as I know... we can change this values of the sidebar_label, there are an option for change this space or implies the size of the icon?

```
"class": "sidebar_label",
"font.size": 13,
"color": [97, 97, 97],
"font.bold": false,
"font.italic": false,
"shadow_color": [0, 0, 0, 0],
"shadow_offset": [0, 1]
```

**Comment by equinusocio** [comment]
You mean file type icons or folders icons?

**Comment by davesnx** [comment]
Between the File type icon and the label.

I mean, the space between the Folder Icon and the label is different than the File Type icon and the label, and there are no way to change it...

**Comment by equinusocio** [comment]
> The space between icon and label is inside the icon image, is a blank space.
