### ISSUE TITLE
Javascript highlighting is pretty bad

### ISSUE THREAD

**Issue by Fossil01** [equinusocio/material-theme#475]
Compared to Monokai for example there isn't much highlighting going on which makes it very hard to read. Also there isn't any proper JSON highlighting going on.

See this comparison:

**Material:**
![Material](https://www.dropbox.com/s/tnb9pd0cc0eugdh/Schermafdruk%202015-10-20%2011.45.44.png?raw=1)

**Monokai:**
![Monokai](https://www.dropbox.com/s/h4fgxo6o12o0ed4/Schermafdruk%202015-10-20%2011.46.07.png?raw=1)

It would be nice if the JS highlighting could get some more love :+1:

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/436#issuecomment-147177698
