### ISSUE TITLE
Ugly display in the selection / allocation of tasks

### ISSUE THREAD

**Issue by antonazgarovich** [equinusocio/material-theme#477]
Ugly display in the selection / allocation of tasks in the plugin TodoReviews
Sorry for my bad english
![screenshot](https://monosnap.com/file/4bF49hO2rDuResNZFZbCfTiDTaLOQD.png)

**Comment by equinusocio** [comment]
The screenshot is broken

**Comment by antonazgarovich** [comment]
http://take.ms/DM17D

**Comment by equinusocio** [comment]
Sorry but i can't fix this. This is related to the TodoReview package, that isn't supported anymore.
