### ISSUE TITLE
Markdown highlight

### ISSUE THREAD

**Issue by leaf-hsiao** [equinusocio/material-theme#478]
It seems that it doesn't support markdown highlight

**Comment by equinusocio** [comment]
Please provide more informations or i will close this issue. The markdown is totally supported as you can see with the screenshots in readme file.

**Comment by leaf-hsiao** [comment]
It works after I reinstalled the sublimetext. Thanks.

**Comment by flekschas** [comment]
A quick question: do you have an extra plugin installed to recognize markdown? I had MarkdownEditing installed and deinstalled in as their theme is not as great as yours. Unfortunately after deinstallation of MarkdownEdit markdown files are not recognized anymore. I've reinstalled Material Theme (v2.0.5) but unfortunately that didn't help. Maybe I am missing something.
