### ISSUE TITLE
Suggestion: Schema is getting too red when HTML mixed with PHP

### ISSUE THREAD

**Issue by sucat** [equinusocio/material-theme#480]
Great theme! :+1: 
But I'd improve the color schema in case you have to mix HTML with PHP.
A code is getting too red (html tag names, php opening/closing tags and php variables use similar colors):
![material-theme-html-php](https://cloud.githubusercontent.com/assets/7252341/10757933/d1905d0a-7ca5-11e5-8259-776c1f018b78.png)

So I changed the schema colors as following:
- php opening/closing tag no longer uses red color as it's not that important tag to grab too much attention.
- html tags uses orange color instead of red one

Results:
![material-theme-html-php-altered](https://cloud.githubusercontent.com/assets/7252341/10758064/d5907a56-7ca6-11e5-871b-5ed1a0a65383.png)

![material-theme-html-altered](https://cloud.githubusercontent.com/assets/7252341/10758051/c021d610-7ca6-11e5-93ad-6504f34c6ba2.png)

What do you think about it?

Code used:
```
<table>
    <tbody>
        <?php foreach($data as $row): ?>
            <tr>
                <?php foreach($row as $key =? $val): ?>
                    <td>
                        <?php
                            $prefix = !empty($common[$key]) ? $common[$key] : null;
                            $output = $prefix.$val;

                            echo $output;
                        ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
```

HTML Tag color altered:
```
<dict>
	<key>name</key>
	<string>Tags</string>
	<key>scope</key>
	<string>entity.name.tag</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#ff8a00</string>
	</dict>
</dict>
```

PHP Opening/Closing tags color new dict:
```
<dict>
	<key>name</key>
	<string>PHP Tags</string>
	<key>scope</key>
	<string>punctuation.section.embedded.begin.php, punctuation.section.embedded.end.php</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#DDDDDD90</string>
	</dict>
</dict>
```

**Comment by equinusocio** [comment]
Ave you checked 
> <dict>
    <key>name</key>
    <string>Tags</string>
    <key>scope</key>
    <string>entity.name.tag</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#ff8a00</string>
    </dict>
</dict>

with others language?

**Comment by sucat** [comment]
I've checked it with:
- Go
- Python
- Java
- C++

I haven't noticed any issues.
It would be great if anyone else could test it just in case :)

**Comment by equinusocio** [comment]
I've changed only the html tags inside php
<img width="732" alt="screen shot 2015-11-01 at 19 59 15" src="https://cloud.githubusercontent.com/assets/10454741/10870772/311917ae-80d3-11e5-97f2-d886e3a99589.png">

**Comment by andremacola** [comment]
@equinusocio How to go back the html colors? I was adapted to the color and different html colors with .html and .php files is not the best way to resolve this.

**Comment by equinusocio** [comment]
@andremacola have you a solution?

**Comment by sucat** [comment]
@equinusocio It looks ok for me :) Personally I prefer "dark yellow/orange" for HTML tags but still better :)
