### ISSUE TITLE
Javascript Babel Syntax Support

### ISSUE THREAD

**Issue by offirgolan** [equinusocio/material-theme#481]
Any chance of getting support for [Javascript (Babel)](https://packagecontrol.io/packages/Babel) syntax? You can checkout [Oceanic Next Color Scheme](https://github.com/voronianski/oceanic-next-color-scheme)

**Comment by equinusocio** [comment]
@offirgolan Yes, install babel package.

**Comment by offirgolan** [comment]
Is this the intended color scheme?
<img width="771" alt="screen shot 2015-10-27 at 12 35 48 pm" src="https://cloud.githubusercontent.com/assets/575938/10770224/5585845e-7ca7-11e5-98bc-4880df427ad9.png">

**Comment by equinusocio** [comment]
Read #436. This theme support only the new syntax-system that comes with build 3085

**Comment by offirgolan** [comment]
Got it! Thanks for the quick replies :+1:
