### ISSUE TITLE
Find In Files is not complete/hidden

### ISSUE THREAD

**Issue by kleinfreund** [equinusocio/material-theme#483]
When you go to *Find in files…* from the *Find* menu, you can search and replace across files in a project. This (the replacing) is not possible with the theme as you can see in the screenshots below:

![search-in-files-default](https://cloud.githubusercontent.com/assets/5774638/10794333/bb0fd9c6-7d94-11e5-8c23-06d904e3a149.png)

![search-in-files](https://cloud.githubusercontent.com/assets/5774638/10794335/be335ce0-7d94-11e5-85b8-21e3d0c4fc95.png)

This happens on my machine, running Windows 8.1 and Sublime Text 3.

**Comment by equinusocio** [comment]
@kleinfreund Please read the readme file

**Comment by kleinfreund** [comment]
Sorry, just checked the open issues.
