### ISSUE TITLE
Alignment issue with Advanced New File

### ISSUE THREAD

**Issue by johnend** [equinusocio/material-theme#484]
As you can see from the screenshot below the text field that appears when creating a new file with the Advanced New File is misaligned, was more visible before the most recent update.

![sublime text - github com - - screen shot 29 oct 2015 10 24 24](https://cloud.githubusercontent.com/assets/3886057/10815962/402ff180-7e27-11e5-9667-ef877440c395.png)

**Comment by equinusocio** [comment]
You can find the fix inside the README file.

**Comment by mikeerickson** [comment]
@johnend @equinusocio As commented in other thread on the same subject, which setting "fixed" this issue?  I have applied the settings from the readme, but I still have this same issue?

**Comment by equinusocio** [comment]
Past a full screenshot and preferences
