### ISSUE TITLE
Rename function

### ISSUE THREAD

**Issue by TwinLight** [equinusocio/material-theme#489]
![image](https://cloud.githubusercontent.com/assets/9023187/10928264/f2dc3802-82e1-11e5-8931-c8f4f84ce655.png)

Hello, i'm not sure if it is my setting or something, but whenever i try to rename my file, i can't see what was typing. Below is my screenshort 
![image](https://cloud.githubusercontent.com/assets/9023187/10928202/6bb91da4-82e1-11e5-882b-5f97601350ad.png)
As shown above it just show the 1 black horizontal line.

One more thing, what is the code to make my tab can clearly distinguish between others tab. Currently "bolding" tab doesn't fits to me and the colors.
![image](https://cloud.githubusercontent.com/assets/9023187/10928255/e2d44ec2-82e1-11e5-8dca-abba9b2f0c36.png)

**Comment by Weeb** [comment]
https://github.com/equinusocio/material-theme/issues/67

**Comment by equinusocio** [comment]
For the first issue you can find the fix in the readme file, always in the readme file you can find the theme options, try to use this: ```"material_theme_tabs_separator": true,```

**Comment by TwinLight** [comment]
Sorry about opening same issues again.
Erm.. i already set "material_theme_tabs_separator": true, and nothing happen actually. And also make it to 'false' doesnt effect on anything.

![image](https://cloud.githubusercontent.com/assets/9023187/10960085/76963ff6-83bb-11e5-988e-d9b41a287a95.png)

Still find it difficult to differentiate between tabs

**Comment by AntonTrapp** [comment]
I just searched how to enable some sort of separator between the open file tabs, found this topic - can confirm, that setting the separator does nothing at all (made two screenshots and blended them in difference mode in Photoshop because I thought I have some problems with my eyes). Pixel to Pixel 1:1 - restart does not change anything. Visible separators would be great!
