### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by psddesignereu** [equinusocio/material-theme#49]
![kepernyofoto 2015-06-11 - 11 02 07](https://cloud.githubusercontent.com/assets/12843125/8103838/fa43d9a2-102b-11e5-97f9-e7a627a36d99.png)

This theme looks so pretty and cool ! Please fix this small error. After installing it i got some missing icons . Thank you !

**Comment by equinusocio** [comment]
This is strange. Past here all your prererences.

**Comment by psddesignereu** [comment]
I just started using Sublime because i saw your amazing theme. Here is how i installed the theme : 

1, Packeges - User here i dropped the folder
2. In sublime is changed the Color Scheme to material-theme 0.9.0

The user setting looks like this : 
![settings](https://cloud.githubusercontent.com/assets/12843125/8107913/4cad7a38-104d-11e5-8548-c53b51831832.png)

If this isnt enought pls tell me where i should make some screenshots. Thank you

**Comment by smashkins** [comment]
https://github.com/equinusocio/material-theme/issues/3#issuecomment-109573474

**Comment by psddesignereu** [comment]
Yes i did the same still everything is the same.

**Comment by equinusocio** [comment]
You have to paste the package here (not in the user folder):
```/Users/**********/Library/Application Support/Sublime Text 3/Packages.```

do ***Preferences > Browser Packages....***

Then apply the theme with 
```"color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",``` 

not

```"color_scheme": "Packages/User/material-theme/schemes/Material-Theme.tmTheme",```

**Comment by psddesignereu** [comment]
wow i made this once but i tried it again and works :D thank you :+1:
