### ISSUE TITLE
1.9.0 - broken?

### ISSUE THREAD

**Issue by ld0rman** [equinusocio/material-theme#493]
Since updating to 1.9.0 the theme no longer activates. I am left with ST's default theme. What information can I provide to help with debugging this issue?

**Comment by relferreira** [comment]
I'm having this problem too

**Comment by equinusocio** [comment]
This is a package control issue. Activate the theme and restart sublime.

**Comment by ld0rman** [comment]
I can assure you that this is not the solution. I have tried uninstalling and reinstalling the package as well as restarting Sublime Text - I have done this through manual installation and with Package Control and the problem persists.

**Comment by equinusocio** [comment]
1. Unistall material theme through package crontrol
2. Go to packages folder and remove any "material theme" folder
3. Restart Sublime Text
4. Reinstall Material Theme from Package Control 
5. Restart ST
