### ISSUE TITLE
New dark color not change on all page

### ISSUE THREAD

**Issue by ariefeko** [equinusocio/material-theme#494]
![screen shot 2015-11-09 at 18 44 40](https://cloud.githubusercontent.com/assets/10136140/11032948/1117c56e-8712-11e5-8ddf-0e3d9f9a8754.png)
![screen shot 2015-11-09 at 18 45 55](https://cloud.githubusercontent.com/assets/10136140/11032961/293de88a-8712-11e5-855f-d3ce10de0fab.png)
Already set this but not work for all page
![screen shot 2015-11-09 at 18 47 17](https://cloud.githubusercontent.com/assets/10136140/11032979/54a83d86-8712-11e5-8f4e-79bc45e01f4b.png)

**Comment by equinusocio** [comment]
Close all tabs e restart sublime text.
