### ISSUE TITLE
Code Folding Display Issue

### ISSUE THREAD

**Issue by saulhudson** [equinusocio/material-theme#495]
Fairly self explanatory from the screen shot but with using ""material_theme_accent_red": true, " I get a strange display glitch on the code folding arrows on the right of the editing pane.

![bug](https://cloud.githubusercontent.com/assets/789556/11059445/b42d8cfa-8791-11e5-9a65-998bcb2711c6.png)

**Comment by saulhudson** [comment]
I can further confirm it does this all material_theme_accents not just the red.

**Comment by equinusocio** [comment]
I think there is a problem with your ST or installed Material Theme. Try to purge all material theme folders and reinstall it manually.

**Comment by saulhudson** [comment]
Sorted, thanks!!

I had a version of the Material Theme in 

C:\Users\[username]\AppData\Roaming\Sublime Text 3\Packages

as a compressed .sublime-package file and another version in 

C:\Users\[username]\AppData\Roaming\Sublime Text 3\Installed Packages

which was an uncompressed folder.

Package control must have updated the compressed one but I was actually using the older one from the other folder. No idea why or how I'm using 2 folders for packages but I'm sorted. I highly doubt this is an issue with your theme and just my Sublime playing up. Close the issue if you agree.

**Comment by BridgeTheGap** [comment]
I have the same issue.
