### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by GinKoSen** [equinusocio/material-theme#496]
###### JVM : 1.8.0_60[Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)]
**When is used , i set the ui font options like this**

![mtsp1](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/mtsp1.png)

#### But , when i restart the ide , the ui font options is wrong(reset the font options, everything is ok , but  when restart, it appear again...)
![mtsp2](https://raw.githubusercontent.com/GinKoSen/ginko/master/images/mtsp2.png)

**Comment by equinusocio** [comment]
You have to report this issue to the official porting repository
https://github.com/ChrisRM/material-theme-jetbrains

**Comment by GinKoSen** [comment]
@equinusocio  Ok , thx.
