### ISSUE TITLE
Theme not applied

### ISSUE THREAD

**Issue by ianchanning** [equinusocio/material-theme#498]
I'm having a very similar issue to #341. I'm using 

- Linux Mint (i.e. Ubuntu based). 
- Sublime Text 3 (build 3083)

This is a clean installation of ST, with only the package manager and the Material Theme installed.

I installed the theme through the package manager and where as it sets the `color_scheme` property in the `User/Preferences.sublime-settings` it doesn't set the `theme` property:

```json
{
	"color_scheme": "Packages/Color Scheme - Default/Solarized (Dark).tmTheme",
	"ignored_packages":
	[
		"Vintage"
	]
}
```

**Comment by ianchanning** [comment]
Obviously the solution is to add in the `theme` property - but this doesn't follow the package installation steps which suggests that only a restart is required.

**Comment by equinusocio** [comment]
You have to activate the theme, like README say:
```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

**Comment by ianchanning** [comment]
Via package control - README states:

> You can install this awesome theme through the Package Control. Search for "Material Theme", install, restart Sublime Text and enjoy!

Only for the manual installation must you set the theme.

Not that it's a major issue - but it just doesn't do what it says.

**Comment by equinusocio** [comment]
When you use a tool is assumed to be known. To edit sublime theme you have do update your preferences, Package Control can't edit it for you.

**Comment by ianchanning** [comment]
Ah - ok. Perhaps could I suggest that you create a separate section in the README, that separates the manual installation steps 1 and 2 from step 3. The activation step applies to both the manual and the package installation route - but the current README (and package installation notes) indicates that it is only a requirement for manual installation.

e.g. the [Soda Theme README](https://github.com/buymeasoda/soda-theme) entirely separates the instructions into two separate sections 'Installation' and 'Activating the theme'.

I don't think that most people know that ST can't set the theme. It seems odd that package installation can set the `colour_scheme` but not the `theme` user preferences.

It's great that you have notes that come with the installation of the theme - which is more than most other themes do. It's only because the notes explicitly talk about activating the theme for manual installation but nothing for package installation that I got confused.
