### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by paulirish** [equinusocio/material-theme#5]
can you add some screenshots to the readme?

thxx!

**Comment by aloisdg** [comment]
Can you also add a picture of the palette?

Thank you

**Comment by aloisdg** [comment]
I just saw on [reddit](http://www.reddit.com/r/web_design/comments/38c9df/the_most_epic_material_design_theme_for_sublime/crty22t) that we can found official screenshot on [dribbble](https://dribbble.com/shots/2085617-Material-Theme-Sublime-Text-3).

**Comment by yuche** [comment]
What is the font for screenshots?

**Comment by coryshaw1** [comment]
@yuche Looks like [Fira Code](https://github.com/tonsky/FiraCode)

**Comment by yuche** [comment]
@coryshaw1 Thanks,great help.

**Comment by ojosdegris** [comment]
@equinusocio Thank you for great theme! If you need to test anything, more than happy to help.

**Comment by equinusocio** [comment]
Hi @paulirish i'm happy to see you here :) i will update the readme, but at the moment you can see the screenshots here [Material Theme Screenshots](https://dribbble.com/shots/2085617-Material-Theme-Sublime-Text-3/attachments/375409)
