### ISSUE TITLE
C++ langage bad bracket hightlighting with all color shemes

### ISSUE THREAD

**Issue by Guema** [equinusocio/material-theme#503]
![image](https://cloud.githubusercontent.com/assets/8943532/11199129/108eeeec-8ccb-11e5-9a8e-720979a014ae.png)

i would like to help you to fix that, but, in fact the file seams very HUGE and uncommented and i think you are using some kind of tool to manage color shemes.

if you tell me what you use, i will certainly try to make a pull request without messing other languages.

Thanks for this wonderfull theme anyway.

**Comment by equinusocio** [comment]
There is only one color scheme (one for Darker, default and lighter) for all languages, there isn't a color scheme for one specific language

**Comment by Guema** [comment]
Sorry, as im french i could possibly not say right what i want to say.

I just would like to report a bug that is present on every single scheme. The bug do not occure on every languages, i use it for python and colors are fine. But in fact, when using any of the material schemes in C++, and C (i suppose) calling a function make the first bracket wrongly colored, the closing one is not. Refer to my screenshot were calling triple cause the first bracket to be blue.

I will try to work on it via this link, by the way.

Thanks for your attention.

**Comment by equinusocio** [comment]
What ST build are you using?

**Comment by Guema** [comment]
I can reproduce the bug on ST3 both 3083 and 3095 (dev).

**Comment by Guema** [comment]
What snippet are you speaking about ? i does not think it's about snippets, the bug is occuring on all c++ code and on both method (local scope) and functions (global scope).
see this other exemple :

![image](https://cloud.githubusercontent.com/assets/8943532/11227742/45497bc6-8d88-11e5-8342-0c02798d4960.png)

I commented the code.

Here you can dl this text source files :

[ExempleClass_CPP_.txt](https://github.com/equinusocio/material-theme/files/37314/ExempleClass_CPP_.txt)
[ExempleClass_H_.txt](https://github.com/equinusocio/material-theme/files/37313/ExempleClass_H_.txt)
[ExempleFunction_CPP_.txt](https://github.com/equinusocio/material-theme/files/37315/ExempleFunction_CPP_.txt)

as i am unable to dumb Cpp files directly, i writed there real extentions between underscore. but it doesn't matter, you can set syntax manually on sublime text by opening Command Palette (Tools menu) and typing SSC++. it will use c++ colors (i don't know if you know this so if you actually does, ignore it ^^).

Thanks for your attention, keep asking question if you need, maybe i just didn't understand what you meen by "snippet".

**Comment by Guema** [comment]
Ok, update.

I took the time to study the problem.

Your scheme seems to be fine in facts, i cannot modify anything without destroying all other languages syntaxes... and the issue is more from original sublime text C++ langage file. i finally choosed to use "C++ starting kit" highlighting who correct the issue.

maybe i should make a ticket on sublime text project, because i really think you the problem is not yours.

you could write the tip to install a better syntax to use material theme with c++.
