### ISSUE TITLE
Problem with Material Theme OceanicNext and the Darker version

### ISSUE THREAD

**Issue by Revod** [equinusocio/material-theme#504]
Here a screen: with variables in scss or sass

![screenshot from 2015-11-16 20 43 53](https://cloud.githubusercontent.com/assets/10109689/11199754/c78591ec-8ca2-11e5-8824-30033b0b1377.png)

and with the material-theme normal scheme color:
![screenshot from 2015-11-16 20 45 56](https://cloud.githubusercontent.com/assets/10109689/11199785/0e4a5f04-8ca3-11e5-9c41-c22bfd3aa30e.png)

**Comment by equinusocio** [comment]
This is not a issue. Oceanic Next Color scheme doesn't make red variables.
