### ISSUE TITLE
Advanced New File input not displaying properly

### ISSUE THREAD

**Issue by mikefrancis** [equinusocio/material-theme#505]
I frequently use the [Advanced New File](https://github.com/skuroda/Sublime-AdvancedNewFile) and have had to stop using the Material Theme as I can't see what is in the input:

![Material Theme ANF](https://dl.dropboxusercontent.com/u/14362388/Screen%20Shot%202015-11-17%20at%2010.25.08.png)

Compare this with the default Sublime theme:

![Default Theme ANF](https://dl.dropboxusercontent.com/u/14362388/Screen%20Shot%202015-11-17%20at%2010.25.34.png)

**Comment by equinusocio** [comment]
@mikefrancis Please read the readme file

**Comment by mikefrancis** [comment]
@equinusocio Already have done, but I'll assume you're referring me to [this part](https://github.com/equinusocio/material-theme#known-issues) of the README.

These controls don't show - I've posted above exactly what I'm seeing.

**Comment by mikefrancis** [comment]
Ignore that, was like 1 pixel high or something - thanks.

**Comment by mikeerickson** [comment]
@equinusocio @mikefrancis Which of the recommended settings in the README was supposed to address this?  I have applied all the settings, but I still have this same issue?

**Comment by equinusocio** [comment]
@mikeerickson Check the known issues.
