### ISSUE TITLE
Can't see anything when renaming or creating files

### ISSUE THREAD

**Issue by hgranholm** [equinusocio/material-theme#506]
I love the theme and have used it for a long time, but there's one annoying issue: the text colour in the rename/name input box is the same as the background color. (Right-click on file & Rename or create a new file.) Would be great to see this fixed!

Edit: using Material-Theme-Darker

**Comment by equinusocio** [comment]
@hgranholm What? You can fix the input field by dragging it. Read the readme file under known issue

**Comment by hgranholm** [comment]
No need to be rude about it. It's not exactly obvious. But thanks.
