### ISSUE TITLE
New Update Color Change

### ISSUE THREAD

**Issue by outliercody** [equinusocio/material-theme#507]
The color of the tab background change to black, but I wanted to know if there was a setting I could set so revert it back to the off-grey color is was before.

I am using the Darker theme.

My preferences are sublime settings are below as well.

{
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": "/",
			"selector": "string.quoted.double.html,string.quoted.single.html, source.css"
		}
	],
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"colorize": true,
	"detect_slow_plugins": false,
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": false,
	"font_face": "Bitstream Vera Sans Mono",
	"font_size": 11,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"material_theme_disable_fileicons": false,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": false,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"scroll_past_end": true,
	"spacegray_tabs_font_normal": true,
	"spacegray_tabs_normal": true,
	"tab_size": 2,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": true
}

**Comment by equinusocio** [comment]
@outliercody Try to restart sublime

**Comment by outliercody** [comment]
I thought I did that already - I was wrong!

Thanks for helping me with such a trivial issue
