### ISSUE TITLE
Atom One Dark theme colors?

### ISSUE THREAD

**Issue by c0ppo** [equinusocio/material-theme#508]
Greetings,

I've used atom for some time, but reverted back to sublime due to atom being really slow for my needs :(
But I got used to Atom One Dark theme + One Dark Monokai scheme. Any chance you could use those colors as well?

If not, could you please guide me how to edit your theme so I can at least try to make it on my own.
Thanks in advance :)

P.S.
And ty for the material theme, no1 theme for me when using sublime :)

**Comment by equinusocio** [comment]
At the moment you can use the monokai edited by @saadq. For the UI you can use de Darker version if you don't like the default one. Check the README file to know how use it.
https://github.com/saadq/Materialize

**Comment by c0ppo** [comment]
I know. Already using dark version + Materialize monokai. Just think that those dark blue colors are way nicer then the default materialize dark. Already googled up on editing themes, so gonna try to edit your theme to match One Dark colors :)
