### ISSUE TITLE
New Oceanic Next based color schemes seem to be corrupted

### ISSUE THREAD

**Issue by Jamushroom** [equinusocio/material-theme#509]
When loading the new Oceanic Next based color schemes my Sublime seems to look corrupted. The sidebar and tapbar turn completely black.

![screen shot 2015-11-18 at 11 03 34](https://cloud.githubusercontent.com/assets/13051971/11238151/111e985c-8de4-11e5-8bc7-0b37e169f277.png)

**Comment by NicolasParada** [comment]
Because its just a scheme. Don't use it in the theme property, just in the color_scheme property.

**Comment by equinusocio** [comment]
... Ocenic Next is a color_scheme not a theme.
