### ISSUE TITLE
about file rename bug

### ISSUE THREAD

**Issue by notek** [equinusocio/material-theme#510]
Rename file/directory when the change box below cannot be displayed, modify the name seems not so easy

![sublime-modify](https://cloud.githubusercontent.com/assets/3304247/11249003/46b3e8fc-8e5f-11e5-8208-92f9b3a53b7b.gif)

**Comment by equinusocio** [comment]
@notek Also read the readme file seems hard.  👍🏻

**Comment by notek** [comment]
@equinusocio ok,i saw [#67](https://github.com/equinusocio/material-theme/issues/67)
