### ISSUE TITLE
Rename box is not visible

### ISSUE THREAD

**Issue by jdbrice** [equinusocio/material-theme#511]
I like the theme a lot. When using the material-theme the rename box in the bottom left is not visible. 
Running ST3 , OSX 10.10. Let me know if you need more info. Switching to a different theme doesn't fix until after a reboot of ST.

![screen shot 2015-11-19 at 10 43 17 am](https://cloud.githubusercontent.com/assets/6765220/11277168/f4ddbb60-8eaa-11e5-8224-3080f921fbf9.png)

**Comment by gj1118** [comment]
@jdbrice There is already a fix provided for this scenario. Please see the Readme for more info on this. 

-Cheers

**Comment by jdbrice** [comment]
Thanks, sorry for not reading first!
