### ISSUE TITLE
Python comments are a bit light on Material-Theme-Darker

### ISSUE THREAD

**Issue by njamaleddine** [equinusocio/material-theme#512]
Hello, while using `Material-Theme-Darker` it looks like comments in python are a bit light and difficult to read. Perhaps adding a bit more contrast or brightness to the default color might help. Thanks!

<img width="472" alt="screen shot 2015-11-20 at 6 52 36 pm" src="https://cloud.githubusercontent.com/assets/5332222/11314873/12fcffb2-8fb8-11e5-9a83-de94ef40ce57.png">

It's similarly the case in `Material-Theme-Darker-OceanicNext`.

Love the theme otherwise, it's probably the best theme I've used on Sublime so far. Great work :+1:

**Comment by equinusocio** [comment]
I can't make every one happy, some people like this comments and someone not. If you like you can change the color comment by yourself in your local installation. I'm sorry.

**Comment by njamaleddine** [comment]
@equinusocio Yeah that's true, I understand, thanks anyway man!

**Comment by Tronix117** [comment]
Are you sure some people like those this way ?

https://github.com/equinusocio/material-theme/issues/439
https://github.com/equinusocio/material-theme/issues/290
https://github.com/equinusocio/material-theme/issues/254
https://github.com/equinusocio/material-theme/issues/70
...

Sure it's fine when we change them manualy, but it seems those comments need to be lightened a bit, even on an highly contrasted monitor, those comments are hardly readable, and in development comments are really important.

Thanks for your awesome theme ;)

**Comment by equinusocio** [comment]
@Tronix117  #70 isn't related to this. Anyway, like with the variables color, i can't make happy all the users. Someone like this comments and someone no. Someone like the red variables someone no. 

As you said you can do it manually
https://github.com/equinusocio/material-theme/issues/305#issuecomment-120479395
