### ISSUE TITLE
Material theme just updated and now "New Folder..." strip is completely blank

### ISSUE THREAD

**Issue by kruncher** [equinusocio/material-theme#513]
I have tried restarting sublime several times; but now when the material themes are selected the "New Folder..." strip is completely blank.

If I rever to the default Sublime theme then the "New Folder..." strip works as expected.

Steps to reproduce:

1. Activate material theme.
2. Right-click folder in side-bar.
3. Select "New Folder...".
4. Observe empty strip along bottom of the Sublime window.

Aside:

If you ignore the lack of visual and just type the new folder name and hit the enter key; the new folder appears as expected. For some reason the text field is completely cloaked.

**Comment by Revod** [comment]
Is a common issue, read the [README](ohttps://github.com/equinusocio/material-theme/blob/master/README.md) in 'Known issues'

**Comment by kruncher** [comment]
Aha, thanks!
