### ISSUE TITLE
Gulp file icons not showing

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#515]
Seems like the gulpfile.js icons are still not showing even after issue 304 was fixed. 
https://github.com/equinusocio/material-theme/issues/304

<img width="301" alt="gulp file" src="https://cloud.githubusercontent.com/assets/6380855/11321753/b6523d0c-9090-11e5-8832-29e6605cd359.png">

**Comment by equinusocio** [comment]
You still miss the icon?

**Comment by imoby** [comment]
Yep still missing. Tweaked with the config file too and no luck.

**Comment by equinusocio** [comment]
Have you updated to the last rerelease 1.9.7?

**Comment by zaynali53** [comment]
@equinusocio Updated to 1.9.7 but still missing.

![capture](https://cloud.githubusercontent.com/assets/8646770/11668039/eafe1df8-9e16-11e5-9d02-fd125cc7a8be.JPG)

**Comment by equinusocio** [comment]
... no one file have the right icon @zaynali53 mmm

**Comment by zaynali53** [comment]
@equinusocio Yes and some icons like laravel is still blurry. PR #485 

![capture](https://cloud.githubusercontent.com/assets/8646770/11695894/653cde1c-9ed3-11e5-95c4-b4f7f988c85f.JPG)

**Comment by Revod** [comment]
Same problem 
![screenshot from 2015-12-09 15 38 35](https://cloud.githubusercontent.com/assets/10109689/11697262/f2fa1632-9e8a-11e5-944c-6359e8335c20.png)

**Comment by gj1118** [comment]
this could be marked as resolved because the gulp icons now are showing up.
![image](https://cloud.githubusercontent.com/assets/473101/12198317/c578a322-b5dc-11e5-85e5-0e899896764e.png)

**Comment by oivva** [comment]
Now you can use [File Icons Extended](https://packagecontrol.io/packages/File%20Icons%20Extended) package that supports Material Theme.

**Comment by equinusocio** [comment]
@oivva I tried File Icons Extended but nothing change.

**Comment by oivva** [comment]
@equinusocio And after restart too?

On fresh ST: 
![](http://i.imgur.com/MbaefjX.png)

**Comment by equinusocio** [comment]
Yes, after restart.

**Comment by oivva** [comment]
Maybe you have settings conflict with other installed ui themes, currently `File Icons Extended` supports only Material & Boxy.

**Comment by equinusocio** [comment]
Fixed by rebuilding the workspace. 👍
