### ISSUE TITLE
types like size_t in C/C++ are not highlighted

### ISSUE THREAD

**Issue by tcwalther** [equinusocio/material-theme#519]
It would be nice if standard types like size_t, uint16_t etc. were highlighted in the C/C++ themes.

And of course: thanks for your great work, I love your theme!

**Comment by equinusocio** [comment]
You can paste a snippet with this keywords?

**Comment by manoverda** [comment]
Here what I add to make this working (note that uint16_t is not recognized, but uint, ushort, size_t are):
``` xml
    <dict>
      <key>name</key>
      <string>SysTypes</string>
      <key>scope</key>
      <string>support.type.sys-types</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
```

**Comment by equinusocio** [comment]
I need a C/C++ snippet to test it :)
