### ISSUE TITLE
The input area at bottom can not be fully displayed.

### ISSUE THREAD

**Issue by larryzhao** [equinusocio/material-theme#520]
See the screenshot below (The image shows the status after I click on `rename...` on one file), the input field at bottom could not be correctly displayed.

It affects: rename file, and also affect vim users because it show the vim commands there. 

![image](https://cloud.githubusercontent.com/assets/442278/11439004/900d8a64-9533-11e5-9f90-a409a737f677.png)

Thanks for make such a beautiful theme. It's really really good.

**Comment by equinusocio** [comment]
You can find the fix in the REDME file under the known issue

**Comment by larryzhao** [comment]
@equinusocio Thank you very much. It's perfect.
