### ISSUE TITLE
Issue With Enhanced Sidebar

### ISSUE THREAD

**Issue by ChrisThompson5** [equinusocio/material-theme#523]
I have the Material Theme installed on my Sublime Text 3. I love the look of it, however I am currently having an issue with it integrating with the Enhanced Sidebar package. There is options for New File and New Folder, however, when I click them I do not get a prompt to type a name in for the folder/file. If I uninstall this theme package, that functionality work fine.

**Comment by equinusocio** [comment]
@ChrisThompson5 Hi. This is a known issue. Check the readme file.

**Comment by ChrisThompson5** [comment]
Awesome, fixed the issue! I take it the bar will now stay expanded from here on out?

**Comment by equinusocio** [comment]
@ChrisThompson5 You have to do this once. 👍🏻

**Comment by ChrisThompson5** [comment]
Awesome! Thanks a lot!
