### ISSUE TITLE
How to make this material theme compatible with AceJump plugin?

### ISSUE THREAD

**Issue by rahmatawaludin** [equinusocio/material-theme#525]
Hi, I really love this plugin. Currently, I'm using AceJump plugin https://github.com/ice9js/ace-jump-sublime. But, the contrast looks weird. Here's what I got:

![screen shot 2015-12-03 at 8 29 56 pm](https://cloud.githubusercontent.com/assets/1274849/11561875/cecb775c-99fc-11e5-80b7-bbddcb529e5e.png)

I'm really can't see the mark. For inspiration, using solarized dark, here's what I got:
![screen shot 2015-12-03 at 8 31 52 pm](https://cloud.githubusercontent.com/assets/1274849/11561886/f7a3884a-99fc-11e5-9b43-531deeb93982.png)

What should I do to fix this? Thanks..

**Comment by equinusocio** [comment]
@manoverda @rahmatawaludin Can you give me the scopes of the highlighted text? You can do it by installing ScopeHunter and enable it, the click the selected text.

**Comment by manoverda** [comment]
Sure, here what I have:
text.todo-list. Maybe you want ScopeHunter to be configured with more information?
Let me know.

**Comment by rahmatawaludin** [comment]
Guys, here some solution I've found https://github.com/ice9js/ace-jump-sublime/issues/33

**Comment by rahmatawaludin** [comment]
Still, its not really looking good

**Comment by manoverda** [comment]
I managed to have a good value for TodoReview plugin by changing the `foreground` value (the generic one) which was low contrasted with the `background` value. I changed this to a light value, so it is well contrasted with the dark background. As I don't know for what else the `foreground` generic value is used, I don't what I changed inside this theme to do this.
``` XML
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#212121</string>
        <key>caret</key>
        <string>#FFCC00</string>
        <key>foreground</key>
        <string>#D4DADEFF</string>
```
![ok](https://cloud.githubusercontent.com/assets/8159138/11718332/b673d20e-9f55-11e5-9461-47edb6e82a7a.png)

**Comment by SG-Github** [comment]
I've unsubscribed from this thread but I keep getting emails.

Is there something else that needs to be done to stop receiving emails.

**Comment by manoverda** [comment]
Maybe you're watching the whole project, so it may be more priority than the subscribe option. Not sure...

**Comment by manoverda** [comment]
PR #552

**Comment by equinusocio** [comment]
The selection color must be changed only for this plugin :+1:

**Comment by manoverda** [comment]
There is no particular scope for `TodoReview` plugin. I can't tell for `AceJump`, as I don't use it.
The only way to correct the bug for me was to change the general foreground value.
`ScopeHunter` make no difference between a selected line and any other lines.
