### ISSUE TITLE
JSON highlighting

### ISSUE THREAD

**Issue by piq9117** [equinusocio/material-theme#526]
I've been loving the material-theme! My concern is, although not an urgent problem or a real problem is that there is no highlighting for JSON files. How can I set so key and value will have different colors?

**Comment by equinusocio** [comment]
<img width="723" alt="screen shot 2015-12-08 at 13 06 20" src="https://cloud.githubusercontent.com/assets/10454741/11655254/80bf9210-9dac-11e5-8b19-0558a9a8d1ac.png">
