### ISSUE TITLE
Hidden text field when creating new folder

### ISSUE THREAD

**Issue by afrastgeek** [equinusocio/material-theme#529]
When creating a new folder in sublime with material theme, the text-field blocked by status bar.
![2015-12-05 20 03 24](https://cloud.githubusercontent.com/assets/4904057/11607893/4ce8f79c-9b8b-11e5-834a-ae82f2493228.png)

**Comment by equinusocio** [comment]
Hi @afrastgeek you can find the fix in the README file under known issues

**Comment by afrastgeek** [comment]
Thank you @equinusocio
