### ISSUE TITLE
Different Colours Seen on my Windows Machine

### ISSUE THREAD

**Issue by jishcem** [equinusocio/material-theme#53]
When I installed this theme in my personal laptop, I was not able to see the one I saw in my office laptop. Its completely different. 

![image](https://cloud.githubusercontent.com/assets/5296346/8112327/b688e046-1084-11e5-9f7a-1ecb7bb13ec9.png)
![image](https://cloud.githubusercontent.com/assets/5296346/8112342/c01007b6-1084-11e5-956d-efd3daf520cd.png)

I am almost sure this is the not the colors you meant. Do you think otherwise ? Is this a problem of my home laptop color setting or the setting of the plugin itself ?

**Comment by equinusocio** [comment]
On my screen (Macbook Retina 15") i see two identical screenshots... you have to fix the color settings :)
