### ISSUE TITLE
Autocomplete background is confusing

### ISSUE THREAD

**Issue by erosnicolau** [equinusocio/material-theme#532]
In the dark skin versions, the autocomplete drop-down list has the same background color as the page background color and no any other visual aid to help distinguish between the drop-down and the rest of the page. A slightly lighter background color for these autocomplete drop-downs would make auto-completing a lot easier on the eye.

**Comment by equinusocio** [comment]
In all schemes the autocomplete popup have the same background color. You can add more contrast by using https://github.com/equinusocio/material-theme-white-panels
