### ISSUE TITLE
Dull color in recent version 

### ISSUE THREAD

**Issue by AyushRaviRai** [equinusocio/material-theme#533]
The recent update of material theme have made the color more dull.
How can i revert back to the version before it ??

the variable name in php, function names etc have become so dull made them less readable

please look into this 
thanks

**Comment by vydn** [comment]
I have the same problem. 
I have choose PHP syntax but the status bar in the bottom always show HTML. After removed "SublimeLinter" I can choose PHP, but the color still not working.

**Comment by quietkillah** [comment]
You can download the previous version of the theme and install the "schemes/Material-Theme.tmTheme" file from there.

I've renamed it to "Material-Theme-old.tmTheme" and added it to my user Packages, this way it won't get overwritten when the theme updates.

**Comment by equinusocio** [comment]
Sublimelinter make a cache of the opened tab color scheme. You have to close all tabs and all ST istances. Then change the color scheme with another and reselect the one that you like. Sublimelinter should be have some menu option to rebuild the cache.

This issue also occur with the CodeHighlighter package.

I will make the old color highlighting available as alternative

**Comment by marcushat** [comment]
Thank so much @equinusocio. I commented about this also in #538 also.

**Comment by AyushRaviRai** [comment]
Thanks for reply @quietkillah 
Downloaded old version and it worked
