### ISSUE TITLE
Lines Highlight is not readable in Dark color scheme

### ISSUE THREAD

**Issue by manoverda** [equinusocio/material-theme#534]
Some packages select a whole line to interact with. In this case, the `Material-Theme-Darker` color scheme has a little contrast and it's not possible to read the selected line. I post here an example with _TodoReview_ package, but I've already saw that with other packages (I just don't remember them). Here is the same example with `Material-Theme-Darker` color scheme and `Monokaï` color scheme:

![linehighlight](https://cloud.githubusercontent.com/assets/8159138/11680562/5cead536-9e59-11e5-9317-33c34d7b8ce6.png "Material-Theme-Darker color scheme")
![linehighlight2](https://cloud.githubusercontent.com/assets/8159138/11681571/0e8d6c80-9e60-11e5-807f-5985799423af.png "Monokaï color scheme")

**Comment by manoverda** [comment]
I was looking for a good place to post it, but didn't find it :(
Your theme is just awesome, I can't imagine _SublimeText_ without it.
Thanks a lot for your great work! The power of _SublimeText_ with the good looking of your theme makes it a tool I can't live without.
Just some enhancement of your color scheme and it would be perfect (at least for me).
Thanks again.

**Comment by manoverda** [comment]
I thinks this issue is linked with issue #525
To confirm.

**Comment by equinusocio** [comment]
Yes is related of #525.
