### ISSUE TITLE
Markdown Strikethrough

### ISSUE THREAD

**Issue by manoverda** [equinusocio/material-theme#535]
It would be nice to have __Strikethrough__ support on _Markdown_ syntax. Here the same text displayed with `Material-Theme-Darker` color scheme and `MarkdownEditor-Dark` color scheme:

![linestrikethroughmarkdown](https://cloud.githubusercontent.com/assets/8159138/11681038/a6415bd0-9e5c-11e5-9fab-6c52c8ecb9ab.png "Material-Theme-Darker Theme")
![linestrikethroughmarkdown2](https://cloud.githubusercontent.com/assets/8159138/11681072/d6abb810-9e5c-11e5-834a-787cb30cf100.png "MarkdownEditor-Dark Theme")

**Comment by equinusocio** [comment]
At the moment i don't have plans for this. Waiting for a PR :+1:

**Comment by manoverda** [comment]
OK. I'll check if I can do that, but for the moment, I never changed a syntax...

**Comment by manoverda** [comment]
Just added this and it partially works. I don't know yet how to define priorities on scopes: when strikethrough, bold is still bold, links are still links. I saw a them where everything was strikethrough (it was the most priority scope I think):
``` XML
    <dict>
      <key>name</key>
      <string>Strikethrough</string>
      <key>scope</key>
      <string>markup.strikethrough</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#444444</string>
      </dict>
    </dict>
```
![strikethrough](https://cloud.githubusercontent.com/assets/8159138/11713744/88bc0f2c-9f35-11e5-99b6-f6c2ed9f189c.png)
![strikethrough2](https://cloud.githubusercontent.com/assets/8159138/11713773/af999a7e-9f35-11e5-9bab-9857c4a2d82d.png)

**Comment by manoverda** [comment]
PR #551
