### ISSUE TITLE
Markdown link color improvement

### ISSUE THREAD

**Issue by manoverda** [equinusocio/material-theme#537]
Not urgent, but a better looking of links in _Markdown_ could be nice.
In fact, the color used in your screenshots is far better. Why is it not what I have (I am using `Material-Theme` Theme and color scheme for my screenshots, but problem is the same for darker version)?
Here are 4 screenshots. First 3 are from my application (red/orange or orange/orange). Last is from your screenshot (red/blue). We can see that links are far more readable in your screenshot:

![markdownlinks](https://cloud.githubusercontent.com/assets/8159138/11682137/5d7bde6e-9e63-11e5-8ed0-785c49391a2e.png)
![markdownlinks2](https://cloud.githubusercontent.com/assets/8159138/11682140/5d7cca9a-9e63-11e5-874c-7dc0da4f4e43.png)
![markdownlinks3](https://cloud.githubusercontent.com/assets/8159138/11682138/5d7c0cf4-9e63-11e5-8b04-3e1b94bae8d1.png)
![markdownlinks4](https://cloud.githubusercontent.com/assets/8159138/11682139/5d7c272a-9e63-11e5-8ad9-da1731fdbe09.png)

**Comment by equinusocio** [comment]
What ST build are you using?

**Comment by manoverda** [comment]
I am using ST3 build 3083

**Comment by manoverda** [comment]
I have a start of comprehension:
Using the same links inside a list and it looks like your links (so just adding a `* ` in front of the link, and it's OK, but remove it, and the links color changed).
Here are the scope when not well rendered and when well rendered:
* Bad: `text.html.markdown meta.link.inline.markdown markup.underline.link.markdown`
* Good: `text.html.markdown meta.paragraph.list.markdown meta.link.inline.markdown markup.underline.link.markdown`

**Comment by equinusocio** [comment]
@manoverda  thanks for the help. From build 3085 Sublime Text ( 3 dev ) use a new syntax system and this theme use this new one. The new syntax system has changed some scopes and i think this is the case. Before change the color-scheme, can you try with a fresh install of ST 3 dev? I can't fix all changed scopes...

http://www.sublimetext.com/3dev

**Comment by manoverda** [comment]
I am not a registered user, so I can't use dev builds I tried, but dev buils are only for registered users.

**Comment by equinusocio** [comment]
this theme work from build 3085+ and the new syntax system.
