### ISSUE TITLE
Search and Tabs not themed anymore?

### ISSUE THREAD

**Issue by ddagz** [equinusocio/material-theme#539]
After the update, I can't seem to get sublime to use the theme on my Tabs, or the search feature. It is using the default sublime theme. I've restarted sublime many times, and tried to switch back between themes to see if it would fix itself.

**Comment by equinusocio** [comment]
Can you give more details?
- ST version and build
- Have you tried to remove and reinstall it?
- have you tried manual installation?

**Comment by ddagz** [comment]
Sublime Text 3, Build 3083
I have tried to reinstall it, but not with manual installation.

**Comment by samwlui** [comment]
I'm getting a similar issue with ST Build 3059

![image](https://cloud.githubusercontent.com/assets/2241772/11720541/502433a2-9f25-11e5-8e29-3e6524c2a87f.png)

**Comment by equinusocio** [comment]
I can't help on ST old builds. This theme is made for 3085+ build
