### ISSUE TITLE
Suggestion: Publish to PackageControl

### ISSUE THREAD

**Issue by rodrigoscna** [equinusocio/material-theme#54]
It would be nice to be able to install the theme from packagecontrol.io.

**Comment by wldcordeiro** [comment]
The guide to doing so is here. https://packagecontrol.io/docs/submitting_a_package

**Comment by wldcordeiro** [comment]
It appears @equinusocio has actually already submit it to Package Control and is awaiting the PR being merged, so this can be closed.

**Comment by Revod** [comment]
he said it before, when the stable version are ready, they upload to Package Control. Material Theme still in development

**Comment by wldcordeiro** [comment]
@Revod the stable version is ready, it's just a matter of how long it takes the Package Control dev to accept it into the list.

**Comment by equinusocio** [comment]
Yes. The firs release is ready for https://github.com/equinusocio/material-theme/releases/tag/v1.0.0.

**Comment by rodrigoscna** [comment]
Great... thank's for the feedback :+1:
