### ISSUE TITLE
Material Light "Goto" is not styled 

### ISSUE THREAD

**Issue by andersodt** [equinusocio/material-theme#540]
There are different shades of white in the light theme vs the darker themes which are uniformly colored while using the Goto dialog.

**Comment by equinusocio** [comment]
Can you add a screenshot?

**Comment by andersodt** [comment]
https://www.dropbox.com/s/y3j2web9mbbgvp6/Screenshot%202015-12-09%2013.11.05.png?dl=0

The different shades of white here vs the uniform black here:

https://www.dropbox.com/s/3us7lc67h8tlnca/Screenshot%202015-12-09%2013.12.20.png?dl=0

**Comment by equinusocio** [comment]
I will check thanks :+1:

**Comment by equinusocio** [comment]
![a0zmtseeavgym-5u_bate3bzf0zimpj7h4o4msvy5qc](https://cloud.githubusercontent.com/assets/10454741/11897034/40f9cf46-a58c-11e5-90d5-eb7948067997.png)
![nvt_7tcfd9xrvuoo0edc_3mfjv_h0f0p254gxdiomp4](https://cloud.githubusercontent.com/assets/10454741/11897035/4118b6b8-a58c-11e5-871d-36709a3fa49d.png)
