### ISSUE TITLE
Laravel icon is still blurry

### ISSUE THREAD

**Issue by zaynali53** [equinusocio/material-theme#541]
@equinusocio I think it's not resolved correctly in PR #485 

![capture](https://cloud.githubusercontent.com/assets/8646770/11696341/95d8118e-9ed5-11e5-8a96-56f27cba110e.PNG)

**Comment by equinusocio** [comment]
Thanks @zaynali53. If you have time you can make a PR :). I will check asap

**Comment by zaynali53** [comment]
Yes sure @equinusocio Check #548
