### ISSUE TITLE
SidebarEnhacement new file bottom bar not visible

### ISSUE THREAD

**Issue by ricbermo** [equinusocio/material-theme#542]
I just configured the awesome theme on my ST3 where I use SidebarEnhacement plugin to empower sidebar. Unfortunately, the new file bar, displayed at the bottom of the editor, to enter the file name is not visible. I can only see a very little with dot, which is the actual cursor. This is happening with the Dark and default themes. I have not tested yet the others.

![screen shot 2015-12-09 at 3 01 27 pm](https://cloud.githubusercontent.com/assets/2601363/11697126/29e6967a-9e86-11e5-9760-09164268b1d0.png)

**Comment by Revod** [comment]
Read the README, in Known Issues

**Comment by ricbermo** [comment]
So sorry, I jumped directly to issues. didnt see that on.
