### ISSUE TITLE
Add or rename file/folder

### ISSUE THREAD

**Issue by andrei-cacio** [equinusocio/material-theme#549]
When you want to add or rename a file or folder, the input appears but you can't see what you are typing. It's a blank input. It works but there is no preview of what the text is.

**Comment by equinusocio** [comment]
@andrei-cacio You can find the fix in the readme file. 😉

**Comment by andrei-cacio** [comment]
@equinusocio yeah, it works. But isn't there a more elegant fix?

**Comment by equinusocio** [comment]
No, this is a ST bug that doesn't recalculate the new panel size.
https://github.com/SublimeTextIssues/Core/issues/939
