### ISSUE TITLE
[Bug] Display tab bar and folder

### ISSUE THREAD

**Issue by wallish** [equinusocio/material-theme#554]
Hi,

I have a retina and this weird things is happening but it's working well on my other computer (pc)

<img width="880" alt="capture d ecran 2015-12-14 a 22 09 14" src="https://cloud.githubusercontent.com/assets/5347276/11794047/8b777698-a2af-11e5-9875-f22e955d1d87.png">

**Comment by Providex** [comment]
Same problem :(

Manjaro KDE and Elementary OS Freya
![snapshot6](https://cloud.githubusercontent.com/assets/11682837/11854035/658214f8-a452-11e5-8779-6ec5189eb02d.png)
![8p9epaoydve](https://cloud.githubusercontent.com/assets/11682837/11854044/72da73d4-a452-11e5-905e-c51dac69b50f.jpg)

**Comment by Revod** [comment]
Hey @Providex I have elementary os freya and can't reproduce that, my st with material theme work fine. Are you try reinstalling the theme?

**Comment by Providex** [comment]
@Revod Reinstalling does not change anything. I use Manjaro, Elementary OS deleted.

**Comment by equinusocio** [comment]
You used package control or the manual installation?

**Comment by wallish** [comment]
@equinusocio i dont remember how i installed, so i reinstalled with package control, and... It's working, so i think i made something wrong with manual installation.

@Providex try to install with package control
