### ISSUE TITLE
How to add material icon?

### ISSUE THREAD

**Issue by lovebdsobuj** [equinusocio/material-theme#556]
Hi, 
Can anyone tell me, How to add **Material** icons in ```material-theme``` for sidebar files and folder.

**Comment by wehrhaus** [comment]
http://apple.stackexchange.com/a/153179/162391

**Comment by equinusocio** [comment]
@lovebdsobuj ST add the sidebars icons from version 3 **build 3065+**
http://www.sublimetext.com/3

**Comment by lovebdsobuj** [comment]
Thank you sir, for your reply. 
I'm, sorry sir, Now I see folder icons but files icon not showing.
![screenshot_00085_20h29m10s](https://cloud.githubusercontent.com/assets/10352682/11932750/d627ec78-a821-11e5-8f4d-bfd6a4b7b807.png)

**Comment by lovebdsobuj** [comment]
Also I have a request to you, ST not support Unicode text, Is there have any solution you know?

Actually I face problem with Bangla Font, Like this.
![screenshot_00086_20h40m01s](https://cloud.githubusercontent.com/assets/10352682/11933164/58144cf2-a824-11e5-9f23-50a54c8bb172.png)
