### ISSUE TITLE
"New folder" naming area not shown

### ISSUE THREAD

**Issue by g105b** [equinusocio/material-theme#557]
1. Right click a folder, choose "New folder"
2. Naming area should be visible, so I can type the name of the folder
3. Instead, the area to type into is hidden.

![opt](https://cloud.githubusercontent.com/assets/358014/11914834/7670e636-a682-11e5-9f75-586fd252a2a4.gif)

**Comment by Revod** [comment]
Read the README, in known issues

**Comment by g105b** [comment]
I read it, and wobbled the find/replace bar too... not sure what I am meant to do, so asked here as an issue, seeing as this is a "known issue" but there is no issue open for it.

**Comment by equinusocio** [comment]
Because isn't related to this theme. It's a ST bug i can't fix
