### ISSUE TITLE
Lighter Theme margin-top on tabs 

### ISSUE THREAD

**Issue by guemidiborhane** [equinusocio/material-theme#558]
Hello,

have some margin on the top of tabs in lighter theme, tried to reinstall but still doesn't work 

![selection_022](https://cloud.githubusercontent.com/assets/4106935/11929003/0b0d6c8c-a7d8-11e5-8ca4-2557d03b1b6a.png)

**Comment by equinusocio** [comment]
Your theme installation seems to have some problem... this theme doesn't have a grey tab-bar..

**Comment by guemidiborhane** [comment]
Sorry,

needed to restart ST3 to get the colors fixed, Here are some screenshots of `darker` and `lighter`

![selection_024](https://cloud.githubusercontent.com/assets/4106935/11932612/05a62c6a-a7f7-11e5-9c96-b4b552543b1e.png)

![selection_025](https://cloud.githubusercontent.com/assets/4106935/11932613/05c92a1c-a7f7-11e5-8e71-b9371517fa0b.png)

**Comment by equinusocio** [comment]
:+1:
