### ISSUE TITLE
Issues with find & replace and new file panel

### ISSUE THREAD

**Issue by moon0326** [equinusocio/material-theme#56]
It might be my configuration, but I have layout issue with find & replace and new file panel as shown below.

New File
![screen shot 2015-06-11 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/4723145/8118015/74f98844-1041-11e5-997a-5968f5c633ef.jpg)

Find & Replace
![screen shot 2015-06-11 at 1 54 26 pm](https://cloud.githubusercontent.com/assets/4723145/8118016/7507ccce-1041-11e5-9602-af6c81f86407.jpg)

**Comment by equinusocio** [comment]
Please see #18

**Comment by moon0326** [comment]
Thanks!

**Comment by moon0326** [comment]
Sounds like the solution is to restart my sublime. I've done that already, but I didn't fix the issue.

**Comment by moon0326** [comment]
Actually, *resizing* worked.
