### ISSUE TITLE
Input bar is not displayed (overlap with status bar)

### ISSUE THREAD

**Issue by schmimae** [equinusocio/material-theme#560]
Hello,

first of all: Thank you for this great theme!

I noticed the following bug:

![1](https://cloud.githubusercontent.com/assets/8665053/11935265/31d86234-a807-11e5-9ea9-3716b0c69daf.PNG)

The blue line marks where the input bar would usually be. However, it seems to be overlayed or shifted to the bottom.

When using the standard theme, it looks like this:

![2](https://cloud.githubusercontent.com/assets/8665053/11935294/6287512e-a807-11e5-9238-76a4da705ab6.PNG)

If there is any way I can help to further debug this, just say so!

**Comment by equinusocio** [comment]
@schmimae Please read the readme file under known issues

**Comment by schmimae** [comment]
Thanks, that was of course the problem.
