### ISSUE TITLE
New file / New folder is not styled

### ISSUE THREAD

**Issue by anhvupham** [equinusocio/material-theme#562]

**Comment by Revod** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10109689/11970489/6af3d0e2-a8fe-11e5-8bc2-c60caba360e5.png)
![untitled2](https://cloud.githubusercontent.com/assets/10109689/11970490/6b0d7768-a8fe-11e5-839e-f9e9f559e195.png)

**Comment by equinusocio** [comment]
I don't see any issue

**Comment by anhvupham** [comment]
Did you guy install it from Package control or Manually ?

**Comment by Revod** [comment]
Both, In Windows with Package Control and linux manually

what ST Build are using?
Are you tried to remove the theme and download and install again?

**Comment by alvik48** [comment]
Have the same issue: I don't see any editing field when creating new file/folder or rename them. OS X 10.11.12, Sublime Text 3 (build 3083). Theme was installed by Package Control. Re-installation didn't help.

**Comment by equinusocio** [comment]
1. read the readme file 
2. search for a similar issue before open new one

You can find the fix in the README file under known issues :+1:
