### ISSUE TITLE
Recursive collapsing of folders in side bar

### ISSUE THREAD

**Issue by georgewaters** [equinusocio/material-theme#563]
Ctrl + Alt + Click (Linux shortcut) on a folder in the sidebar should collapse the folder and all sub-folders. Sublime Text build 3083 on Ubuntu 15.04, Material theme v1.9.7

**Comment by equinusocio** [comment]
the shortcut is <kbd>alt</kbd>+<kbd>click</kbd> and this isn't related to Material Theme

**Comment by mgmeyers** [comment]
I can confirm this issue. The shortcut in ctrl + alt + click on linux, and this issue is caused by the disclosure_button_control having `"content_margin": [0, 0, 0, 0]`.
