### ISSUE TITLE
Find and replace overlap

### ISSUE THREAD

**Issue by warreb1** [equinusocio/material-theme#568]
I have noticed the "find and replace" is not fully visible anymore. (see screenshot) Anything that can be done here? When disabling the theme it's visible again,so it's a theme related issue I presume.
![screen shot 2015-12-29 at 16 26 48](https://cloud.githubusercontent.com/assets/2844328/12036731/0ac137be-ae49-11e5-8281-1ebb0fe92890.png)

**Comment by equinusocio** [comment]
Yes. You can find the fix in the README file 😜
