### ISSUE TITLE
Separator between sidebar and editor?

### ISSUE THREAD

**Issue by huglester** [equinusocio/material-theme#57]
Hello,

on the left it's a sidebar and on the right - editor: http://pic.webas.lt/webas.lt-e00f063f3c.png

But there is no separator visible, maybe it would would be good to have one? 
Because when you want to expand sidebar, you need to 'catch' the separator:)))

**Comment by equinusocio** [comment]
The sidebar separator is exactly where begins the color of the selected line :smile:
