### ISSUE TITLE
Symbols and Strings in Ruby

### ISSUE THREAD

**Issue by Alexthelionheart** [equinusocio/material-theme#570]
I LOVE this theme. This is by far my favorite Sublime text theme but the color scheme colors both symbols (example :name) and strings (example "name") the same and this gets me confused a lot. 
Can you please fix this ? 
Merry Christmas and keep on making this theme awesome.

**Comment by equinusocio** [comment]
@Alexthelionheart can you paste an example snippet?

**Comment by Alexthelionheart** [comment]
@equinusocio Here is a screenshot 
![screen shot 2016-02-04 at 9 11 30 am](https://cloud.githubusercontent.com/assets/6015676/12817280/4f9a4176-cb1f-11e5-8c41-3aa551a0633c.png)
