### ISSUE TITLE
Can vertically scroll the sidebar to reveal sidebar  items

### ISSUE THREAD

**Issue by ofelix03** [equinusocio/material-theme#571]
Hi, 
I recently  installed this awesome theme: material design. It's been great using it, until i discovered the vertical scroll for the sidebar is missing. I can't scroll to bring into view all the sidebar items that are out of current view.
What should i do, i' might probably be misising a simple config setting?
![material-theme-missing-sidebar-scroll-bar](https://cloud.githubusercontent.com/assets/9988430/12060494/f455b57e-af68-11e5-89df-e38b2a97724d.PNG)

**Comment by equinusocio** [comment]
try disabling overlay scrollbar setting
