### ISSUE TITLE
Sass 3.3 syntax support

### ISSUE THREAD

**Issue by MitchJackson94** [equinusocio/material-theme#572]
![screen shot 2015-12-31 at 12 21 32](https://cloud.githubusercontent.com/assets/2472850/12064361/12e0f3aa-afb9-11e5-875a-015c3c3900fd.png)

**Comment by equinusocio** [comment]
where is the issue

**Comment by MitchJackson94** [comment]
When I nest using the & parent selector to use bem in my sass it gets highlighted in red I have made sure I'm using the up to date version of Syntax Highlighting for Sass

**Comment by equinusocio** [comment]
there is the same issue with other themes? because i think this issue's related to the sass package and his scope.

**Comment by equinusocio** [comment]
@MitchJackson94 this is what i see:
<img width="235" alt="screen shot 2016-01-05 at 00 11 17" src="https://cloud.githubusercontent.com/assets/10454741/12103225/e354194c-b340-11e5-98ba-9bca244e2b7e.png">

**Comment by MitchJackson94** [comment]
It must be a problem with my sublime text, Thanks for your time

**Comment by equinusocio** [comment]
what build are you using?

**Comment by MitchJackson94** [comment]
I'm using Sublime Text 3 build 3083

**Comment by equinusocio** [comment]
Ok i think this issue is related to this build cause 3083 use old syntax system and maybe sass package use the new one introduced from build 3085

**Comment by MitchJackson94** [comment]
Thanks I have updated to the dev build it still was not working then I renamed my Sublime Text 3 folder in Application Support so that I could start from scrach installed your theme and sass sytax and now its working fine, Thanks for all your help

**Comment by Revod** [comment]
I have the same problem, using the last build
![image](https://cloud.githubusercontent.com/assets/10109689/12125173/0f45bb52-b3bc-11e5-89fa-c7971fcf5dd3.png)

**Comment by equinusocio** [comment]
you see the right colors
