### ISSUE TITLE
Some icon not working

### ISSUE THREAD

**Issue by chonlatee** [equinusocio/material-theme#575]
I download and install but something wrong. 

sublime text 3 build 3083

Macbook pro retina 13 OS X 10.11.2

<img width="687" alt="screen shot 2559-01-04 at 5 48 54 pm" src="https://cloud.githubusercontent.com/assets/324432/12088174/7f2cfe32-b30b-11e5-8a84-87a0f8b8d562.png">

<img width="1276" alt="screen shot 2559-01-04 at 5 47 24 pm" src="https://cloud.githubusercontent.com/assets/324432/12088139/48c145ba-b30b-11e5-8532-9ed3f3ea6474.png">

**Comment by equinusocio** [comment]
you have to put the package inside the right folder

**Comment by chonlatee** [comment]
@equinusocio  Thank you.

I put to Library/Application Support/Sublime Text 3/Packages/User 

this is right folder?

**Comment by chonlatee** [comment]
@equinusocio Thank you it's work now.

Your theme is awesome.
