### ISSUE TITLE
New file/folder (SideBarEnhancements) line input is almost "hidden"

### ISSUE THREAD

**Issue by diogolr** [equinusocio/material-theme#578]
When I click to create a new file/folder (SideBarEnhancements plugin installed), the line line input is almost "hidden".

**Before** click to create a new file/folder:
![image](https://cloud.githubusercontent.com/assets/4297658/12117567/61a57f8e-b3a0-11e5-986c-a9fe7f5cf9a8.png)

**After** click to create a new file/folder (look at the tiny litte bar/pipe blink right above the Line/Column information):
![image](https://cloud.githubusercontent.com/assets/4297658/12117581/7384e37a-b3a0-11e5-9b45-7f7f2586bc14.png)

**Comment by equinusocio** [comment]
please read the README file

**Comment by diogolr** [comment]
Relate to https://github.com/equinusocio/material-theme/issues/67
