### ISSUE TITLE
Feedback: Increase sidebar spacing

### ISSUE THREAD

**Issue by kruncher** [equinusocio/material-theme#579]
I don't know how others feel; but I am not a fan of this new super chunky default. To me it seems that such a large change should be opt-in rather than opt-out.

I went and configured `"material_theme_compact_sidebar": true` straight away.

**Comment by cenderin** [comment]
I kind of agree with this.  I went and found that immediately as well and set it.

**Comment by equinusocio** [comment]
you can use default o small sidebar spacing. what is the issue? i can't make all happy.
