### ISSUE TITLE
sidebar has extra space at the top (image attached)

### ISSUE THREAD

**Issue by byronedwards** [equinusocio/material-theme#580]
Love the theme, thank you. Just a small area above the Open Files in the sidebar that's 'looks wrong'.
I'm using OSX 10.7.5

"theme": "Material-Theme.sublime-theme",

![screen shot 2016-01-06 at 11 16 41](https://cloud.githubusercontent.com/assets/4012796/12141416/053013fa-b467-11e5-97f3-d1e9ff6d16a2.png)

**Comment by equinusocio** [comment]
try to build a new workspace for the project

**Comment by byronedwards** [comment]
Hi, sorry that hasn't worked - the space is there even in a new blank window.
![screen shot 2016-01-06 at 12 37 43](https://cloud.githubusercontent.com/assets/4012796/12142724/5031bf9c-b472-11e5-919a-c68036d4e1f0.png)

**Comment by equinusocio** [comment]
I mean **Project > New Workspace for Project**
<img width="279" alt="screen shot 2016-01-07 at 15 05 36" src="https://cloud.githubusercontent.com/assets/10454741/12172253/20ca75f8-b550-11e5-9ac8-2841c50be565.png">

**Comment by byronedwards** [comment]
Hi, thanks for replying. Sorry that's not working either.

However if I edit Packages/User/Material-Theme-Darker.sublime-theme I can get it to disappear, however it will not 'stick', ie. it gets overwritten when I open a new file/project.

`{
        "class": "sidebar_container",
        "layer0.opacity": 1.0,
        "layer0.tint": [
            33,
            33,
            33
        ]
    },
`

![screen shot 2016-01-07 at 14 32 53](https://cloud.githubusercontent.com/assets/4012796/12172924/bd740d7e-b54b-11e5-9f0b-ab37aaa644be.png)

**Comment by equinusocio** [comment]
This is strange... because the `sidebar_container` actually already have `[33,33,33]` as a tint. Have you Material Theme through Package Control or manually?

**Comment by byronedwards** [comment]
Yes through Package Control - I'm going to get rid of my other themes and start from scratch to see if that fixes it - Thanks for helping :)

**Comment by byronedwards** [comment]
Hi, after getting rid of various old themes and a fresh install of Material Theme, everything is working properly. Thanks for your time, and the theme :)

**Comment by equinusocio** [comment]
Nice :+1: Now i'm making addon to add tinted tabbar. If you wanna try check the repository https://github.com/equinusocio/material-theme-appbar

**Comment by byronedwards** [comment]
I'll check it out :) (note: typo 'abb' in the readme).

PS. I think the problem I was having was a conflict with the theme here: A fork of Material Theme.
https://packagecontrol.io/packages/Theme%20-%20Dark%20Material

**Comment by equinusocio** [comment]
so isn't closed?

**Comment by byronedwards** [comment]
Sorry, yes - All good now, I'll close this :)
