### ISSUE TITLE
OLD-* themes still trying to load

### ISSUE THREAD

**Issue by skoch** [equinusocio/material-theme#581]
Update yesterday seemed fine. Today I am getting the error about not being able to load the old theme:
```
"color_scheme": "Packages/Material Theme/schemes/OLD-Material-Theme.tmTheme",
```
No biggie; I changed to normal theme, and saved the Prefs file:
```
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```
However continually getting the error message:

![image](https://cloud.githubusercontent.com/assets/112034/12145684/ab4bb8f2-b45d-11e5-9911-8641a6bc72a0.png)

A few files seem to be OK (the Prefs file, some SCSS/JS/CSS/Twig files) but others seem to revert to the original white theme from Sublime Text.

Is there a caching issue? I've restarted ST twice to no avail.

**Comment by skoch** [comment]
Seems when I click on an open tab that is displaying/using the default style, close said file I get the error message from above however when I reopen the same file all is good. 

Seems to be using the correct theme.

**Comment by equinusocio** [comment]
yes. isn't a bug related to this theme. Sublime cache all opened tab, even the color scheme. you have to close and reopen alla files.

**Comment by equinusocio** [comment]
ps the OLD theme now is under the OLD folder. Check the README file how to use it.

**Comment by skoch** [comment]
Thanks for clarifying the cache issue.

Yep, saw that in the README the 1st time I read it.
