### ISSUE TITLE
Sidebar Enhancements

### ISSUE THREAD

**Issue by ccbragg** [equinusocio/material-theme#582]
First off, love your theme!

I'm having trouble with Sidebar Enhancements plugin. If I use a command that requires typing (create new file/folder, rename, etc.), the text box pops up, but I cannot see anything that I am typing. Any ideas why this is happening? Let me know if you need more info.

<img width="954" alt="screen shot 2016-01-06 at 3 27 52 pm" src="https://cloud.githubusercontent.com/assets/1943615/12156889/ddb5ebbe-b48a-11e5-812c-005cbd307c9d.png">

<img width="953" alt="screen_shot_2016-01-06_at_3_28_02_pm" src="https://cloud.githubusercontent.com/assets/1943615/12156886/d76304d6-b48a-11e5-80a2-50f6655a6a9f.png">

**Comment by equinusocio** [comment]
you can find the fix in the README file

**Comment by ccbragg** [comment]
That worked, sorry didn't see that sooner. Thanks!
