### ISSUE TITLE
High-definition icons not working

### ISSUE THREAD

**Issue by finncatling** [equinusocio/material-theme#583]
Hi, great theme! Just a tiny issue: I'm running Windows 10 with an HD screen but the icons are displaying in standard definition (see pic). Am I missing something? Thanks.

![image](https://cloud.githubusercontent.com/assets/11691520/12171730/14f76684-b544-11e5-9b57-1145bc22bce0.png)

**Comment by equinusocio** [comment]
I think there is a problem with ST HD screen recognition. On my MacBook Retina i see the right icon. I have to try with @3x icon... but it's ridiculous using raster icons. SVG isn't supported.

**Comment by finncatling** [comment]
OK, thanks for your efforts :)

**Comment by equinusocio** [comment]
Sublime Text now can support @3x retina images so i can make relative assets

**Comment by finncatling** [comment]
That's great,  thanks
