### ISSUE TITLE
theme reset

### ISSUE THREAD

**Issue by prempalsingh** [equinusocio/material-theme#584]
Hi

Thanks for the awesome theme. I am, however, facing one issue. My theme resets to default Monokai after every reboot. Not sure if this is an issue with the theme or Sublime Text. Would really appreciate your help on this. Thanks!

**Comment by equinusocio** [comment]
Duplicated of #258 #327 #387 #234

**Comment by prempalsingh** [comment]
Oh, sorry. I should have searched for this in the closed issues. Thanks!
