### ISSUE TITLE
Does not work with SideBar Enhancements

### ISSUE THREAD

**Issue by luco** [equinusocio/material-theme#585]
Whenever I try to create a File or Folder, the bottom name prompt never shows. It seems to be related with Sidebar Enhancements since it shows for find & replace.

Anybody else with this issue?

Also, congrats for this beautiful theme. I love it.

Thanks

**Comment by equinusocio** [comment]
yes this is under known issue's in the README file. You can find the fix there.

**Comment by luco** [comment]
@equinusocio Oh sorry, didn't see. Thanks!
