### ISSUE TITLE
minimalistic

### ISSUE THREAD

**Issue by dcrystalj** [equinusocio/material-theme#587]
Is there a way to to make it minimalistic? 
I want to decrease status bar height and tab height as well as search bar. It is not mentioned in reccomended UI or theme options section

**Comment by keksas** [comment]
+1. Tabs are way over sized and file list items waste vertical space.

**Comment by equinusocio** [comment]
You haven't read well the README file ;)

```
"material_theme_small_tab": true,
"material_theme_small_statusbar": true,
```

For the search bar you can't do anything with settings. You have to manually override the theme.

**Comment by dcrystalj** [comment]
i was thinking about custom height but. its better for now. Thank you

**Comment by equinusocio** [comment]
Sublime allow only boolean settings. I'm sorry.
