### ISSUE TITLE
Problem with Emmet plugin

### ISSUE THREAD

**Issue by adibhanna** [equinusocio/material-theme#59]
when using emmet plugin (say i'm clicking cmd+w) the open a box to write the tags is not completely showing, part of it is still missing.

**Comment by equinusocio** [comment]
Sede #18 forma this.

**Comment by thegregthomp** [comment]
I tried reading through these and nothing, using CTRL+W to wrap tags, the message box doesn't show up. My CMD+F find box shows up. I restarted etc. nothing.

**Comment by equinusocio** [comment]
Readh the README file @thegregthomp :wink:

**Comment by thegregthomp** [comment]
Oh duh, just grabbing the bottom bar and pulling it up worked great. Sorry for not seeing that and thanks for the response.
