### ISSUE TITLE
I can't get appbar to work

### ISSUE THREAD

**Issue by Droyk** [equinusocio/material-theme#590]
You are about too read some bad english. and i am really sorry about it i am not a native english speaker

Hey guys i am new to sublime and just try some thems and i cant get Material theme appbar to work properly 

So guys i want your help 
This what i want but cant get no matter how many times i try 
![screenshot_20160108133619](https://cloud.githubusercontent.com/assets/15848350/12193333/502b4b66-b60d-11e5-86a3-7ed5d272522e.png)

These are my settings 

```JSON
{
	"ignored_packages":
	[
		"Vintage"
	],
    "theme": "Material-Theme-Darker.sublime-theme",
    "color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
    "overlay_scroll_bars": "enabled",
    "line_padding_top": 3,
    "line_padding_bottom": 3,
    "always_show_minimap_viewport": true,
    "bold_folder_labels": true,
    "indent_guide_options": [ "draw_normal", "draw_active" ],   // Highlight active indent
    "font_options": [ "gray_antialias" ],                       // For retina Mac
    "material_theme_small_tab"                : true , // Set small tabs
	"material_theme_small_statusbar"          : true , // Set small status bar
	"material_theme_compact_sidebar"          : true , // Set small status bar
	"material_theme_disable_tree_indicator"   : true , // Disable sidebar file indicator
	"material_theme_bold_tab"                 : true , // Make the tab labels bolder
	"material_theme_accent_lime"              : true , // set green lime accent color
	"material_theme_accent_yellow"            : true , // set yellow accent color
	"material_theme_accent_red"               : true , // set pale red accent color
	"material_theme_panel_separator"          : true , // show bottom panel separator
	"material_theme_tabs_autowidth"           : true , // Enable autowidth for tabs
	"material_theme_contrast_mode"            : true , // Enable sidebar and panels contrast mode
    "material_theme_tree_headings"            : true , // Show siderbar headings
}
```

**Comment by Droyk** [comment]
fixed it by manually installing Material Theme - Appbar

my only request is fix this issue if we install this via package control this happens ![](https://cloud.githubusercontent.com/assets/4065569/12187363/7b29b23a-b568-11e5-97ca-765fd0d4c1d9.png)

But if we install this manually via github link https://github.com/equinusocio/material-theme-appbar/releases/tag/v1.0.0 it fix automatically. so plz fix this issue

**Comment by equinusocio** [comment]
Please report this issue in in the relative repository

https://github.com/equinusocio/material-theme-appbar
