### ISSUE TITLE
Frustrating colour change since theme update

### ISSUE THREAD

**Issue by evenicoulddoit** [equinusocio/material-theme#591]
In e130a741eb03d3d2920629f7b1cdafcbbdacdff4 the foreground colour for the darker themes was fixed to be an actual hex colour, however this made my default colour for everything `#80cbc4` which is an annoying light blue which contrasts far less with the other theme colours. For now I have manually changed the `foreground` colour to `#EAEAEA` (not knowing how the default is generated as it was when the bug was present). Hopefully you'll agree that:

![image](https://cloud.githubusercontent.com/assets/3514018/12194745/12594f04-b5ea-11e5-8a0e-fae2d3c37ae3.png)

Is better than:

![image](https://cloud.githubusercontent.com/assets/3514018/12194733/fd4c47b0-b5e9-11e5-80f1-f44409968295.png)

Thanks!

**Comment by equinusocio** [comment]
Can you tell me what language is?

**Comment by evenicoulddoit** [comment]
@equinusocio Python, though it's the same for all languages - its the `foreground` colour change made within the `tmTheme` files

**Comment by evenicoulddoit** [comment]
Aside from not liking the blue as much as the white, it makes operators (above `is` and `and`) much more difficult to spot

**Comment by equinusocio** [comment]
Can you paste this snippet? What Sublime Text Build are you using?

**Comment by equinusocio** [comment]
This is what i see with ST 3095
<img width="602" alt="screen shot 2016-01-08 at 11 57 52" src="https://cloud.githubusercontent.com/assets/10454741/12196474/1fdc62fa-b5ff-11e5-9757-78132d22aefc.png">

**Comment by manoverda** [comment]
Here what I get from build __3083__, so without issue:
![python_dark](https://cloud.githubusercontent.com/assets/8159138/12196573/da30d5fa-b5ff-11e5-9461-5cc87b5a67c2.png)

**Comment by evenicoulddoit** [comment]
I'm on `3095`. Strange - my ST seems a bit borked anyway because the theme files seem to be within `SublimeLinter` for reasons completely unknown. I'll try a clean install when I can stomach it and see if its repeatable. What *should* the `foreground` property set?

**Comment by rileyjshaw** [comment]
I'm also seeing this since updating, for what it's worth.

**Comment by equinusocio** [comment]
Sometime package controllo fail to restore theme after update

**Comment by evenicoulddoit** [comment]
I had the same issue as @rileyjshaw, I had to re-apply the theme

**Comment by mupkoo** [comment]
I kinda have similar problem. First whenever I change my theme in Sublime, it gets copied over `SublimeLinter` folder or to be more specific, to `"color_scheme": "Packages/User/SublimeLinter/Material-Theme-OceanicNext (SL).tmTheme",`. But I think that this is not related to the theme.

As you can see I am using OceanicNext color scheme and I get the blueish foreground as well. 
Replacing the value [here](https://github.com/equinusocio/material-theme/blob/master/schemes/Material-Theme-OceanicNext.tmTheme#L35) to `#cdd3de` is fixing it for me.

**Comment by evenicoulddoit** [comment]
^ Exactly the same issues as me. @mupkoo you using Linux?

**Comment by mupkoo** [comment]
I forgot to add this information - I am using Sublime Text Build 3100, running on Mac OSX

**Comment by equinusocio** [comment]
@mupkoo You have to empty Sublime Linter scheme cache. You're still using the old one.

**Comment by mupkoo** [comment]
I did this by hitting `Cmd + P -> SublimeLinter: Clear Cache` and `Cmd + P -> SublimeLinter: Clear Color Scheme Folder`, but its not helping.

**Comment by equinusocio** [comment]
Try to purge Sublime Linter package, close al opened tabs, set color scheme again and reinstall sublime linter.

**Comment by radum** [comment]
In case anyone doesn't know why is this happening http://www.sublimelinter.com/en/latest/usage.html#choosing-color-schemes here is why.
