### ISSUE TITLE
Accent not taken into account in completion dropdown

### ISSUE THREAD

**Issue by MrWaz** [equinusocio/material-theme#592]
Hi

First I'd like to thank you for this wonderful piece of art. The appbar add-on rocks!
Using any color accent, I notice that the suggestions ' drop-down list is still using the default teal color.
Will keep me using the default accent just to stay consistent while I was so deeply in need for some purple.. :'(

**Comment by equinusocio** [comment]
Fixed. If you want now the fix you have to use the master branch until i will release the v2.0.2.

**Comment by MrWaz** [comment]
Nice thank you for the quick fix
