### ISSUE TITLE
Color Highlighter is not working

### ISSUE THREAD

**Issue by Webess** [equinusocio/material-theme#593]
Hello! Your theme is beautiful, but I have a problem. Color Highlighter Package doesn't work when I use your theme (any color). I also tried other themes and it worked.

My preferences:
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_bold_tab": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": true,
	"material_theme_tabs_separator": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"show_encoding": true,
	"theme": "Material-Theme-Darker.sublime-theme"
}
```
It can be used at the same time? Any solution?

Best regards, Webess

**Comment by equinusocio** [comment]
what di you mean with "doesn't work"? can you post a screenshot?

By the way i use it with no problem. Maybe you have to rebuild the cache from the color scheme under Packages > Color highlighter

**Comment by Revod** [comment]
example:
![image](https://cloud.githubusercontent.com/assets/10109689/12216917/1364bb8e-b6c3-11e5-87a7-4f7f2ec2b5c5.png)
![image](https://cloud.githubusercontent.com/assets/10109689/12216920/1e848d82-b6c3-11e5-9910-1c99ec40813f.png)

Is that your problem with Color Highlighter @Webess?

**Comment by Webess** [comment]
![2016-01-09_15-18-00](https://cloud.githubusercontent.com/assets/11719946/12217025/2d168842-b6f4-11e5-96df-913ba1d9f7f2.png)

@Revod nope. It's like it was disabled.

But I'm solved it with reinstal ST3 (with delete ST3 folder in appdata) and clear install theme and then packages.
Thank you for your response.

...and sorry for my bad english.
