### ISSUE TITLE
Sublime 3 reverts to default theme and color_scheme 

### ISSUE THREAD

**Issue by fredrikbonander** [equinusocio/material-theme#598]
Since mid-december Sublime, seemingly at random, sometimes reverts back to it's default `theme` and `color_scheme` in user settings when the application starts.

Don't know if this is problem with Sublime or the Material-theme. Sublime hasn't been updated, it's the same build (3083) as before this started to happen.

No errors appear in the console when starting Sublime.

Any ideas?

**Comment by equinusocio** [comment]
This happen when Package control update your packages... You have to wait until finish. By the way this issue is related to Package Control. You can ask on his repository.

**Comment by fredrikbonander** [comment]
@equinusocio thanks!
