### ISSUE TITLE
HTML attribute highlighting inconsistency

### ISSUE THREAD

**Issue by joeserg** [equinusocio/material-theme#599]
Hi there,

Attributes on HTML5 elements (such as `nav`, `article`, etc.) are now being coloured red in 4b74db9, where they were previously yellow (and still are on other elements, such as `div`, `li`, etc.).

<img width="505" alt="screen shot 2016-01-11 at 11 36 05" src="https://cloud.githubusercontent.com/assets/1327888/12232560/8ed39d90-b857-11e5-8112-06c5bb0508ba.png">

If this was an intentional change, could there be an option to revert back to the previous behaviour where all attributes are coloured the same?

I'm using the following settings:

    "theme": "Material-Theme-Darker.sublime-theme",
    "color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
    "material_theme_accent_indigo": true,
    "material_theme_contrast_mode": true,
    "material_theme_small_statusbar": true,
    "material_theme_compact_sidebar": true,

**Comment by equinusocio** [comment]
This is what i see:
<img width="528" alt="screen shot 2016-01-14 at 23 12 14" src="https://cloud.githubusercontent.com/assets/10454741/12339254/4be2fc82-bb14-11e5-9863-102fd748413b.png">
What build are you using?

**Comment by joeserg** [comment]
So I replicated your example and achieved the same result. However, when I inserted content inside the `nav` element I experienced my original issue:

<img width="603" alt="screen shot 2016-01-18 at 10 06 32" src="https://cloud.githubusercontent.com/assets/1327888/12388531/4fd7d2c2-bdcb-11e5-9202-e96cde897126.png">

I'm using release 2.0.1.

**Comment by equinusocio** [comment]
I think you have some issue with you packages like color highlight or SublimeLinter
![screen shot 2016-01-18 at 12 23 14](https://cloud.githubusercontent.com/assets/10454741/12390211/516db6c0-bdde-11e5-828c-8de7a5765bb9.png)
