### ISSUE TITLE
Please change the go to anything menu (ctrl+p) to be less bright

### ISSUE THREAD

**Issue by G4MR** [equinusocio/material-theme#6]
I haven't tried the latest version, but I hope [this](https://d13yacurqjgara.cloudfront.net/users/44860/screenshots/2085617/attachments/375511/Command_Panel_2.jpg) doesn't stay this bright.  Destroys the eyes.

**Comment by equinusocio** [comment]
@G4MR Unfortunately the original interface was not so, was one of the technical choices that I had to take. 

Sublime Text allows you to assign one style to the input field (hex solid background), so if i make this:

![field](https://cloud.githubusercontent.com/assets/10454741/7969178/5241a212-0a35-11e5-8961-a92f3a3da659.jpg)

I have to do this, and i don't like the overlay panel with the same background color.

![panel dark](https://cloud.githubusercontent.com/assets/10454741/7969187/5dc8be36-0a35-11e5-8866-edd0cd4d4b3b.png)

**Comment by Far0s** [comment]
Hi,

Actually, I think it doesn't look bad at all. It is maybe a little less evident to the eye, but it integrates more with the general theme.
Maybe keep it as an option or an idea for an alternative theme ? :-)

Great work Mattia !

**Comment by equinusocio** [comment]
@G4MR new darker (above screenshots) in the next beta release

**Comment by G4MR** [comment]
Awesome work.

**Comment by equinusocio** [comment]
@G4MR you can download the latest release and activate the darker version with:
```json
"theme": "Material-Theme-Darker.sublime-theme",
```
