### ISSUE TITLE
Issue with CSS icon

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#600]
Not sure if you would be able to replicate this issue, but I am getting the less icon whenever I create a CSS file. 

![image](https://cloud.githubusercontent.com/assets/473101/12238220/f400c410-b850-11e5-8ec8-e9dc345005cd.png)

**Comment by Revod** [comment]
Yeah, Is a little issue with the theme..
![image](https://cloud.githubusercontent.com/assets/10109689/12241663/a0dcb706-b866-11e5-81b5-9dd49823aea7.png)

**Comment by equinusocio** [comment]
sorry for this stupid issue. I will fix it soon.

**Comment by equinusocio** [comment]
@Revod are you using indigo accent? You should see indigo folders and label in treeview.

**Comment by Revod** [comment]
@equinusocio Yep. But done, I close the project and reopen again and worked
![image](https://cloud.githubusercontent.com/assets/10109689/12330448/67002830-bab7-11e5-9299-fa7ea550f608.png)
