### ISSUE TITLE
p_thread types have no highlighting

### ISSUE THREAD

**Issue by JohnBehnke** [equinusocio/material-theme#602]
Adding these to the highlighting would give calls like "pthread_mutex_t" some highlighting and would be super appreciated:

support.type, support.class

**Comment by equinusocio** [comment]
P_thread is?

**Comment by JohnBehnke** [comment]
Standard POSIX threads.

**Comment by equinusocio** [comment]
@JohnBehnke  I can't try it. Which color you want as highlight?

**Comment by JohnBehnke** [comment]
I've tried a yellow (FFF176) and it look good in my opinion. Then again, its your theme, so you can change it up if you want.

**Comment by equinusocio** [comment]
How do you highlight posix syntax? Can you paste a snippet?

**Comment by JohnBehnke** [comment]
```
<dict>
			<key>name</key>
			<string>Library class;type</string>
			<key>scope</key>
			<string>support.type, support.class</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#FFF176</string>
			</dict>
		</dict>
```

**Comment by equinusocio** [comment]
You use some package to highlight syntax?

**Comment by JohnBehnke** [comment]
How do you mean? I added that snippet of code to "Material-Theme.tmTheme" to get the highlighting.
