### ISSUE TITLE
Matlab/C++ Icons

### ISSUE THREAD

**Issue by Theolean** [equinusocio/material-theme#603]
There is a little problem with one icon. I don´t know if material theme has a specific icon for matlab files (*.m ), but it choose the c++ icon. 
If I remember correctly you would normally use .cc or .cpp for c++ files. So I thing it may be a bug.

![unbenannt](https://cloud.githubusercontent.com/assets/16598642/12327235/98b89286-bad5-11e5-8989-1f7c6181466c.PNG)

**Comment by equinusocio** [comment]
What sublime Text build are you using?

**Comment by equinusocio** [comment]
This is what i see:
<img width="268" alt="screen shot 2016-01-14 at 23 21 30" src="https://cloud.githubusercontent.com/assets/10454741/12339478/9283b716-bb15-11e5-8329-4192e637777a.png">

**Comment by Theolean** [comment]
I use Sublime Text 3 build 3083 with latexing

**Comment by Theolean** [comment]
if I change the name of the file from .m to .matlab, I habe the correct icon.
But corresponding with this site http://de.mathworks.com/help/matlab/matlab_env/mathworks-file-extensions.html?s_tid=gn_loc_drop .matlab is not a comman file extension

**Comment by vikjam** [comment]
Hi @Theolean, I see the correct icon in Material Theme with both ```.m``` and ```.matlab```.

![screen shot 2016-01-23 at 1 57 53 pm](https://cloud.githubusercontent.com/assets/1154799/12532121/b1028c74-c1d9-11e5-9179-9eda0f5e6aac.png)

I don't think this is a problem with the theme. Note that Object-C uses the same extension as Matlab/Octave. As a result, you need to set the syntax of ```.m```. The [solution](http://stackoverflow.com/questions/12081256/m-files-as-matlab-octave-for-sublime-text) is simply to set the syntax using the menu as follows (make sure you have a .m file opened).

``` View -> Syntax -> Open all with current extension as... ->```

Note that you maybe need to reload the folder/project for the icon to change.

**Comment by Theolean** [comment]
Hey, thx for your help and this explanation. 

After changing the syntax and restart sublime the icon is the right one!
