### ISSUE TITLE
Current tab indicator not extending to the far left

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#604]
![cyqvs2nuaaa5nat](https://cloud.githubusercontent.com/assets/6380855/12330539/4b6c1130-baab-11e5-8fd7-3eb72269d6f9.jpg)

**Comment by equinusocio** [comment]
Thanks man

**Comment by equinusocio** [comment]
@imoby are you using `"enable_tab_scrolling": false,`?

**Comment by equinusocio** [comment]
Fixed from the next release https://github.com/equinusocio/material-theme-appbar/commit/5d934bb3687833467e6b1d5a1b8ad1c27629df9d
