### ISSUE TITLE
Highlight TODOs in coments

### ISSUE THREAD

**Issue by chalmagean** [equinusocio/material-theme#605]
I would be nice to have `TODO` keywords pop out in comments so that they are easier to spot and harder to ignore.

**Comment by equinusocio** [comment]
I will check if i can grab the scope

**Comment by equinusocio** [comment]
I can't grab todo scope. You have to try some Packages.

**Comment by heavybeard** [comment]
May I suggest to support the plugin TodoReview (here https://packagecontrol.io/packages/TodoReview)

Now the colors do not help reading.
![image](https://cloud.githubusercontent.com/assets/12038447/14736109/314f9e80-0875-11e6-843d-b05dc29b754b.png)

But with the Makefile Highlight color (with some fixes) should work
![image](https://cloud.githubusercontent.com/assets/12038447/14736009/ad4e5a72-0874-11e6-810d-3b3ce38ac5c5.png)

Numerical order - path to file - the TODO line number - the TODO text

@equinusocio Do you think is possible to implement it?

**Comment by equinusocio** [comment]
@heavybeard please open a new issue. 👍
