### ISSUE TITLE
Does material-theme supports GitGutter?

### ISSUE THREAD

**Issue by learawesome** [equinusocio/material-theme#606]
@equinusocio thing that I want to ask just as same as the title.

**Comment by equinusocio** [comment]
Already supporto gitgutter..

**Comment by jonesj** [comment]
I get an email every time someone does an update or email response and I don't know how to stop it or unsubscribe.

**Comment by jonesj** [comment]
I'm not following nor watching anything.

**Comment by jonesj** [comment]
I think following is what's causing me to get emails:

Participating
When you participate in a conversation or someone brings you in with an @mention.
x Email  x Web

I have both Email and Web checked.  So I suspect that whenever I make a comment like this, then that's considered participating in a conversation and I get a notification email sent.  Is there a way to unsubscribe from a conversation?

**Comment by learawesome** [comment]
Thanks a lot, by the way material-theme is awesome.
