### ISSUE TITLE
Future Request: Syntax Highlighting for tabular/table

### ISSUE THREAD

**Issue by Theolean** [equinusocio/material-theme#607]
I have a feature request. would it be possible to add syntax highlighting für tabular / table environment in Latex? It would be really nice if de "&" sign could be highlighted. This sign is placed between 2 cells. 

![unbenannt](https://cloud.githubusercontent.com/assets/16598642/12373381/8bb797d2-bc77-11e5-8c66-b3ed0b089a98.PNG)

**Comment by equinusocio** [comment]
Sorry i can't. The Latex plugin doesn't provide a specific scope for &
