### ISSUE TITLE
Yellow accent 

### ISSUE THREAD

**Issue by giltig** [equinusocio/material-theme#608]
Hi,
when you use the command pallete in sublime the color of search matches is red instead of yellow.
![image](https://cloud.githubusercontent.com/assets/5754742/12377274/88fc9d22-bd20-11e5-906d-91136e5d583a.png)

**Comment by equinusocio** [comment]
Thanks. I will renew the yellow accent to match the appbar add-on so i will fix this also..

**Comment by jonesj** [comment]
How do I stop receiving emails from material-theme?

I'm not subscribed to this thread?
I'm not watching this thread?
Please advise...

**Comment by jonesj** [comment]
How do I stop receiving emails from this thread?

I'm not subscribed to this thread?
I'm not watching this thread?

I've looked at notifications, email and help; however, I don't see any setting that is causing me to receive emails from this thread...

@equinusocio
