### ISSUE TITLE
Changing the color scheme for HTML

### ISSUE THREAD

**Issue by axelf** [equinusocio/material-theme#609]
Hi,

can i change the colors for the HTML? For me it looks to colorful. The theme is very nice but the HTML-View is a pain for my eyes.

**Comment by equinusocio** [comment]
You can do what you want with your color scheme.. There is a lot of schemes around  and materiale theme have  alternative schemes. Check the readme

**Comment by axelf** [comment]
Thank you. Nice work.

**Comment by jonesj** [comment]
How do I stop receiving emails from this thread?

I'm not subscribed to this thread?
I'm not watching this thread?

I've looked at notifications, email and help; however, I don't see any setting that is causing me to receive emails from this thread...

@equinusocio

**Comment by equinusocio** [comment]
Are you watching le starring the repo?

**Comment by jonesj** [comment]
Apologize for being naive, but how do I check and confirm whether I'm watching or staring repository?

Everything I've checked and looked at says I'm not watching nor stared, nor subscribed.

**Comment by jonesj** [comment]
I just unstared myself.  I'll see if that fixes it.
