### ISSUE TITLE
Can't install properly via Package Control

### ISSUE THREAD

**Issue by bloomingbridges** [equinusocio/material-theme#61]
Hey,

I found out about this theme via the twitter account of the [package control repository](https://packagecontrol.io/packages/Material%20Theme) so naturally I first installed it using Package Control. The colour scheme installed fine, though even after a restart certain assets seemed to be amiss, such as the X graphic for the close button on tabs. Instead I saw bright orange gradients in a couple of places. Also a popup dialog, which informed me about missing *widgets*.

Manual installation worked fine. This was on OS X w/ Sublime Text 3.

**Comment by nerdExpo** [comment]
I've just submitted a pull request here #60 

Hope it'll be fixed soon ^ ^

**Comment by equinusocio** [comment]
Sorry guys. I've merged your fix (thanks!) and fix the widgets path. The new package release will be available in about half hour.

**Comment by bloomingbridges** [comment]
Hey, that was quick. Works like a charm now :3
