### ISSUE TITLE
Couldn't use toggle comment on syntax 'Gulpfile JS'

### ISSUE THREAD

**Issue by opjlmi** [equinusocio/material-theme#611]
Hi

When I use the syntax 'Gulpfile JS',
I want to toogle the <del>command</del> comment, but there's nothing happened.

**Comment by equinusocio** [comment]
@opjlmi  Can you be more specific?

**Comment by opjlmi** [comment]
okay,

If I set the syntax 'Javascript',
toogle comment should be
```
    var test;

    // when I click 'toogle comment'
    // var test;
```

But I set the syntax to 'Gulpfile JS',
it couldn't work.

**Comment by opjlmi** [comment]
Oh, I'm sorry.....
I made a typo ......

**Comment by equinusocio** [comment]
I have the same issue using Default theme... isn't related to it. I think we use some package that breaks this.

You can try with Default theme and confirm?

**Comment by opjlmi** [comment]
@equinusocio It still not working ...
I think the problem is from the syntax file (Gulpfile JS).
but I don't know where can setting like [THIS](http://docs.sublimetext.info/en/latest/reference/comments.html).

**Comment by opjlmi** [comment]
![2016-01-23 5 48 34](https://cloud.githubusercontent.com/assets/6351593/12529635/8f4b483a-c1f9-11e5-8026-f0e637536f92.png)

**Comment by opjlmi** [comment]
This? [Gulpfile JS](https://github.com/equinusocio/material-theme/blob/master/langs/Gulpfile%20JS.tmLanguage)
