### ISSUE TITLE
Per project accent config

### ISSUE THREAD

**Issue by Misiur** [equinusocio/material-theme#614]
I'd like to set accent color on per-project basis. [I know theme setting cannot be changed in project](https://forum.sublimetext.com/t/theme-setting-is-ignored-in-project-specific-settings/14765/4), however would it be possible to set the `material_theme_accent_lime` in my `*.sublime-project` files?

**Comment by equinusocio** [comment]
You could ask to Sublime Text developers.. I really don't know this

**Comment by equinusocio** [comment]
@Misiur Inside your project file you can paste this:

```
"folders": [...], 
"settings": {
		"rulers": [120],
		"tab_size": 2,
		"translate_tabs_to_spaces": true,
		"trim_trailing_white_space_on_save": false,
	}
```
