### ISSUE TITLE
support for sidebar enhancements

### ISSUE THREAD

**Issue by DenJohX** [equinusocio/material-theme#615]
I really like the theme, just looks amazing!

However, I'm having some trouble with the plugin sidebarEnhancements https://github.com/titoBouzout/SideBarEnhancements , when you want to do an action which requires user input, say create or move a file, it doesn't show the prompt (it think it shows but in the same color as the background), thus making those options unusable.

Please check it.

I'm using it in a Debian GNU/Linux machine, if it helps.

Thanks

**Comment by equinusocio** [comment]
Check the known issue section in README file
