### ISSUE TITLE
material_theme_tabs_separator does (almost) nothing?

### ISSUE THREAD

**Issue by AntonTrapp** [equinusocio/material-theme#616]
Hi!

First: best theme ever! LOVE it!

Second: The tabs of the open files do not have any horizontal separators. Sometimes it makes it hard to spot which text is belonging to which tab... tried material_theme_tabs_separator (which sounded like a solution) - did nothing at all for me (even after a restart).

Was as second question in the #489 bug (which is closed - I think because the real question is answered in the readme and not a material-theme bug). So I open a new one here. OS is 10.10.3. Theme is Material-Theme-Darker!

UPDATE:
Removed all themes (including material), reinstalled only material, getting "separators" - problem: in dark theme the seperators are so dark that you need to turn up the contrast to maximum so you can see them ;) - any way of "more visible" separators?

**Comment by equinusocio** [comment]
i have to work on separators with appbar addon. So i can add also a bit of contrast for the dark theme.

**Comment by AntonTrapp** [comment]
That would be f... awesome! Btw. - where is the donate button? ;)

**Comment by equinusocio** [comment]
@AntonTrapp In the readme file! :+1: :smile:

**Comment by AntonTrapp** [comment]
Done :) - I should try to look at the beginning of the web pages :D
