### ISSUE TITLE
Support Origami

### ISSUE THREAD

**Issue by RoxasShadow** [equinusocio/material-theme#62]
Since I use Origami for splitting the tabs, highlighting the tab separator would be really useful.

Just to clarify: it's just on the left of highlighted line
![untitled](https://cloud.githubusercontent.com/assets/805144/8137426/a3d84594-1143-11e5-9567-c3e9a8209716.png)

Thanks and kudos!

**Comment by equinusocio** [comment]
@This is a general theme issue. I will add a little line between the 2 columns layout.
