### ISSUE TITLE
Tab scrolling disabled makes tab height bigger

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#620]
Tab scrolling disabled makes tab height bigger
<img width="560" alt="enabled tab scrolling" src="https://cloud.githubusercontent.com/assets/6380855/12571326/96f86f6a-c3a5-11e5-9e38-3f81e4292916.png">

**Comment by equinusocio** [comment]
Mmm i haven't this issue. You update to the last 2.0.4?
<img width="711" alt="screen shot 2016-01-26 at 07 35 51" src="https://cloud.githubusercontent.com/assets/10454741/12573966/a76508d6-c3ff-11e5-829d-d15415f28a40.png">

**Comment by equinusocio** [comment]
OK, this happen when you use ```material_theme_small_tab``` with `enable_tab_scrolling: false`

**Comment by imoby** [comment]
Yep you got it. Sorry I should have sent that info as well in my original post.

**Comment by equinusocio** [comment]
@imoby Master branch is now fixed. For package control you have to wait the next release.
