### ISSUE TITLE
Add back the yellow color

### ISSUE THREAD

**Issue by marcosrjjunior** [equinusocio/material-theme#621]
- This match yellow is like orange, or replace this with orange color

**Comment by equinusocio** [comment]
I'm sorry but this isn't a real issue, you can customize your local installation.. It's like to say to Apple "Yellow tag is like orange tag"
![screen shot 2016-01-26 at 14 08 04](https://cloud.githubusercontent.com/assets/10454741/12581364/681629a8-c436-11e5-8c8c-35b2acf40fcd.png)

**Comment by marcosrjjunior** [comment]
![rsz_screenn](https://cloud.githubusercontent.com/assets/5287262/12587013/b449160c-c439-11e5-9694-7961d8fd1454.png)
i'ts seems orange to mee, but ok

**Comment by equinusocio** [comment]
I can rename yellow to orange and orage to dark orange..

**Comment by marcosrjjunior** [comment]
I think we can add a old yellow color again ;p, 
I know you don't like yellow, but you can add another name like 'gold' i'ts pretty nice

**Comment by RichardPinheiro** [comment]
:+1:

**Comment by RichardPinheiro** [comment]
I think we can add a old yellow color again too.

**Comment by equinusocio** [comment]
It's about usability and contrast. Old yellow accent was unusable with lighter theme.
