### ISSUE TITLE
Change separator color

### ISSUE THREAD

**Issue by marcosignacio** [equinusocio/material-theme#622]
Hi, 

First of all: Excellent work and beatiful theme my friend. Thank you.

Just a question, there's a chance to customize the panel's separator color? This one: http://imgur.com/xGDsMBE

Thank you, Iamar.

**Comment by equinusocio** [comment]
`json
 // Status bar panel
  {
    "class": "panel_control",
    "settings": ["material_theme_panel_separator"],
    "layer1.texture": "Material Theme/assets/commons/panel_separator.png",
    "layer1.opacity": 0.2,
    "layer1.inner_margin": [2, 2, 2, 2],
  },
`

**Comment by marcosignacio** [comment]
Mattia, 

Thank you! where exactly I should change that? what file? user settings?

Thank you, Iamar.
