### ISSUE TITLE
tree view padding as a variable

### ISSUE THREAD

**Issue by christophe-g** [equinusocio/material-theme#624]
Thanks a lot for this theme - looks really nice.

I tend to override paddings for the folder treeview ( for my use case with plenty of files per folder, I prefer to squeeze the view and see more information ) - but this gets overridden when new release of the theme are emitted. 
Would it be possible to have tree view row paddings as a variable we can play with in user preferences ?

similar concerns were expressed here https://github.com/equinusocio/material-theme/issues/386
C.

**Comment by equinusocio** [comment]
I can't make "padding" variable. I can only accept boolean value. You can customize your theme without lose anything when theme get update. Search in closed issue's.

**Comment by christophe-g** [comment]
ok. , thanks a lot for this rapid answer !
Cheers,
C.

**Comment by jfcartier** [comment]
Then maybe we should reduce the padding by default, because imho, it's a bit too much. It's really beautiful, but not really convenient.

**Comment by equinusocio** [comment]
@jfcartier 
```
"material_theme_small_statusbar"          : true , // Set small status bar
"material_theme_compact_sidebar"          : true , // Set compact side bar
"material_theme_compact_panel"            : true , // Set minimal padding for the search panel
```
