### ISSUE TITLE
<video> tag color problem

### ISSUE THREAD

**Issue by heavybeard** [equinusocio/material-theme#625]
Hi Mattia,
there's a problem with the video tag: the attributes color switch to red from the standard yellow when other char(s) are between the start and the end tag.

Here some screenshot
![video no char](https://cloud.githubusercontent.com/assets/12038447/12595382/340e07bc-c47b-11e5-9ef8-5c35b8b3c4a5.PNG)
![video with char](https://cloud.githubusercontent.com/assets/12038447/12595381/340c5246-c47b-11e5-847a-a266744ec89d.PNG)
![video with source tag](https://cloud.githubusercontent.com/assets/12038447/12595380/3409d250-c47b-11e5-9938-7ed321477430.PNG)

This is my User Settings:
```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"ensure_newline_at_eof_on_save": true,
	"font_size": 8,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"material_theme_accent_indigo": true,
	"material_theme_contrast_mode": true,
	"tab_size": 4,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true
}
```

**Comment by DarylPinto** [comment]
This seems to happen with all HTML5 tags' attributes whenever there is a newline between the opening and closing tags. See here:

[Image](http://i.imgur.com/p22hP8A.png)

**Comment by heavybeard** [comment]
@DarylPinto Maybe the problem is with html HTML syntax?

**Comment by heavybeard** [comment]
this is not fixed, yet. After the update too.

![image](https://cloud.githubusercontent.com/assets/12038447/13007872/4a9958ea-d193-11e5-9e42-c366d9b7f577.png)

Is this fixed to someone?
