### ISSUE TITLE
Uninstaling this shit!

### ISSUE THREAD

**Issue by gabrieldepaula** [equinusocio/material-theme#626]
I'm the type of person who is excited! then when I open the sublime, i like to go direct in the files that i want to see and edit and have nothing more annoying than these f*ck1ng updates!

**Comment by gabrieldepaula** [comment]
great theme by the way =P

**Comment by imoby** [comment]
@gabrieldepaula wow, cant believe you are giving the developer shit for actually working on this awesome theme! Instead of ranting out why not instead ask if there was a way to prevent getting these updates, such as possibly installing it manually.

**Comment by gj1118** [comment]
wow... that was some language. Learn to be polite please sir. The author has been kind enough to share his art (yes, its art) with us( who could not have created it in the first place). If you didn't like it enough , you could have uninstalled it, without the brouhaha and the github world would not have noticed. Now they have done that, and realize that you are one piece who is good for nothing. 

Adios!!

**Comment by equinusocio** [comment]
@gabrieldepaula I'm a person who want to fix the bugs instead of annoy other people with useless issues. No one is forcing you to use this theme.

**Comment by mupkoo** [comment]
@equinusocio the theme is awesome and I am grateful for all your efforts. Thank you

**Comment by christoga** [comment]
Just because you think the theme is _shitty_, doesn't mean other people think the theme is _shitty_, If you didnt like this theme, you can easily uninstall it without sending a useless issue @gabrieldepaula
