### ISSUE TITLE
Replace-bar hidden

### ISSUE THREAD

**Issue by mathiasmadsen** [equinusocio/material-theme#627]
Hi,

I recently installed this package - and I love it! However, one small issue has appeared:

When using 'Find and replace', the replace-bar does not show.

Below are my user settings and a screenshot.
<img width="1263" alt="screen shot 2016-01-27 at 12 53 49" src="https://cloud.githubusercontent.com/assets/3418529/12612718/14f6847e-c4f5-11e5-8460-e094c046d93c.png">
<img width="571" alt="screen shot 2016-01-27 at 12 54 02" src="https://cloud.githubusercontent.com/assets/3418529/12612719/14f6fc74-c4f5-11e5-9ac0-2b671c6a7685.png">

Let me know if you can fix this :)

**Comment by equinusocio** [comment]
You can find the fix in the readme file under known issues section :+1:

**Comment by mathiasmadsen** [comment]
Thanks :+1:
