### ISSUE TITLE
Can't adding or renaming file and folder

### ISSUE THREAD

**Issue by incleaf** [equinusocio/material-theme#628]
<img width="1680" alt="screen shot 2016-01-28 at 12 51 57 am" src="https://cloud.githubusercontent.com/assets/7221609/12619061/c6139aee-c559-11e5-8eb0-c00edb9f25a3.png">

It's not certain that this problem is occurred from material-theme but there is no problem in default theme so I want to ask about this problem.

In the left side of screenshot, I clicked rename button in sidebar so the rename bar is appeared but it's covered 80% by file status bar.

Thank you :blush:

**Comment by equinusocio** [comment]
Inside readme file, under known issues, you can find the fix.

**Comment by incleaf** [comment]
Oh okay thanks!
