### ISSUE TITLE
Eats up tons of CPU the moment it's installed

### ISSUE THREAD

**Issue by bsleighb** [equinusocio/material-theme#63]
![screen shot 2015-06-12 at 3 44 07 pm](https://cloud.githubusercontent.com/assets/3516166/8139013/2a56efe2-111e-11e5-9c87-2f49c71c97e6.png)

Quitting/Restarting etc doesn't help. I had to remove via package install, quit sublime, start sublime, and then kill one of those processes for it to stop taking up 100% of my CPU.

Other info:
* Installed via package control.
* Version: Sublime Text Build 3083

**Comment by equinusocio** [comment]
have you checked the CPU with other themes? ....

**Comment by bsleighb** [comment]
[This one](https://packagecontrol.io/packages/Theme%20-%20Brogrammer) works fine.
