### ISSUE TITLE
Reload Theme info

### ISSUE THREAD

**Issue by Timson020** [equinusocio/material-theme#632]
It is a great theme ,
but I has a problem. Sometime I restart sublime-text.
I have to write 

"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme”,

this json file again

**Comment by jpmurray** [comment]
I have that for every theme update.

**Comment by equinusocio** [comment]
This is related to Package Control.
