### ISSUE TITLE
Twig Comment Bracket Color

### ISSUE THREAD

**Issue by besimhu** [equinusocio/material-theme#634]
I love the theme, and appreciate the hard work put into it.

That being said, my only comment, would be to turn twig comments the same color as the text inside. See attached screenshot of what I am referring to. http://i.imgur.com/JUq5wEr.png

Or if there is a way for me to do it by myself, that would be nice too.

**Comment by besimhu** [comment]
Actually, it looks like this is related to the Craft Twig syntax sublime plugin.

**Comment by equinusocio** [comment]
I think yes. I will close this for now.
