### ISSUE TITLE
Sidebar Highlight Defaults to Purple

### ISSUE THREAD

**Issue by MattAds** [equinusocio/material-theme#637]
After changing the highlight colour in the settings from default to purple and then changing back to something else or removing the option entirely the colour of the selected file indicator in the sidebar remains purple forever!

![screenshot 2016-02-01 12 01 31](https://cloud.githubusercontent.com/assets/1252329/12716907/ea5d908c-c8db-11e5-86af-ca7665256fd6.png)

**Comment by christoga** [comment]
Have you try to press ` cmd + s ` and then reopen your sublime text? @MattAds

**Comment by MattAds** [comment]
Yep, file is definitely saved and numerous restarts since the glitch occurred have not made any difference.
