### ISSUE TITLE
Style of the rows used for navigating between tabs and tabs background color is bugged.

### ISSUE THREAD

**Issue by Pablocgdev** [equinusocio/material-theme#638]
![tab](https://cloud.githubusercontent.com/assets/9206972/12724854/285c6fb4-c910-11e5-80d7-57782f29d507.png)

I've tried swapping between different versions of the theme and still bugged, it's always that color. I'm on Linux Mint if that helps.

**Comment by diegonc** [comment]
Same here (on Windows 10).
![bar-bg](https://cloud.githubusercontent.com/assets/261458/12737763/0f018732-c93a-11e5-84a0-4330202cb085.png)

**Comment by Pablocgdev** [comment]
Issue persist however sometimes color scheme works properly, but after rebooting same happens again.

**Comment by equinusocio** [comment]
Please restart Sublime Text...
