### ISSUE TITLE
Panel Switcher Button

### ISSUE THREAD

**Issue by mohamadnorouzi20** [equinusocio/material-theme#642]
It doesn't show the panel switcher button in the new Sublime Build 3101

**Comment by jrappen** [comment]
> Dev Build 3101 is out now at https://www.sublimetext.com/3dev
> There's now a button on the status bar to switch between panels. If you have a custom theme, the relevant class name is panel_button_control.
> Also changed is the way Sublime Text detects changes to open files. Sublime Text 2 would simply poll the current file whenever it was switched to. This has the disadvantage that any changes to the underlying file wouldn't be noticed until either the main window itself loses and then regains input focus, or the active file was changed to something else and then back. In practice, this was only an issue if there was a 3rd party changing the file behind the scenes. It also wouldn't notice background modifications to files that are never switched to.
> Sublime Text 3 by and large worked around the missed notification issue by subscribing to file system change notifications, so that it didn't need to poll. To work around file systems that don't publish change notifications, it still polls files when an application window goes from an unfocused to a focused state, but not when simply switching between files. 3101 will now poll the active file when the active file changes, to better handle file systems that don't send change notifications.

**Comment by equinusocio** [comment]
I have to figure out how add this new button. The default theme doesn't have this `panel_button_control ` class.

**Comment by jrappen** [comment]
@equinusocio comparing ctf0/Seti_ST3@26e08ed might help

**Comment by equinusocio** [comment]
Thanks @jrappen

**Comment by jrappen** [comment]
@equinusocio @mohamadnorouzi20 `على راسي` ("on my head" - ask an arabic friend what it **means**, word-by-word translations suck)

**Comment by equinusocio** [comment]
?

**Comment by jrappen** [comment]
nvm, was a reply to the `thanks`
