### ISSUE TITLE
Markdown list - first bullet is colored differently

### ISSUE THREAD

**Issue by flekschas** [equinusocio/material-theme#648]
I noticed that the first bullet point (Asterisk and hyphen) of a list is colored blue-ish while all other are colored white. Is the first bullet point colored differently on purpose?

![markdown list](https://cloud.githubusercontent.com/assets/932103/12888314/6d537bf8-ce47-11e5-9605-80022743ff11.png)

I am running Mac OS X 10.10.5, Sublime Text 3083, Material Theme v2.0.6 and MarkdownEditing v2.1.4.

**Comment by equinusocio** [comment]
I think there is a problem with your MD package. This is what i see with ST build 3102
![screen shot 2016-02-08 at 17 30 41](https://cloud.githubusercontent.com/assets/10454741/12891851/b5e38876-ce89-11e5-98d4-398e3e06cbea.png)

I use only Markdown Preview for the md preview and no other packages.

**Comment by flekschas** [comment]
I've tested it with Markdown Extended too and it looks the same as above. Am I missing something or do you have a special syntax highlighting set?

**Comment by equinusocio** [comment]
The only different is the ST build. From 3085 build ST introduce a new syntax highlight system that work much better. My theme is build for 3085+ build and use the new syntax system.

**Comment by flekschas** [comment]
I updated to build 3102 but unfortunately that doesn't change anything. Which syntax do you use? Afaik Sublime Text 3 isn't shipped with a syntax highlighter for markdown and Markdown Preview didn't add any either in my case. (Or is my installation messed up somehow?)

I am wondering if others run into the same issue as well since these two markdown packages (MarkdownEditing and Markdown Extended) seem to be quite popular.

**Comment by equinusocio** [comment]
I'm using Markdown Extendend and i have red bullets. Really i don't know how test it. Are you using Sublime Linter? Have you tried to reset the linter cache?

**Comment by flekschas** [comment]
Yeah I've reset the cache and it doesn't change anything.
