### ISSUE TITLE
Grey cursor

### ISSUE THREAD

**Issue by giltig** [equinusocio/material-theme#649]
Hi,
I would like to ask an option to configure the cursor (and the selectors of parentheses accordingly) to be grey.
It what was in oceanic next theme and its is much cleaner IMHO (configurable by setting of course).
BTW I use your theme and color scheme and its great

**Comment by equinusocio** [comment]
Do you mean the caret?

**Comment by giltig** [comment]
yes the caret and the small marks of the brackets that surrounds it

**Comment by equinusocio** [comment]
For the caret you have to customize your local theme installation. Search how do this among the closed issues. For the brackets mark you can't do anything
