### ISSUE TITLE
Issues with the HTML file-type icon

### ISSUE THREAD

**Issue by saadq** [equinusocio/material-theme#65]
When I first download the theme, the icon looks fine: 

![screen shot 2015-06-12 at 5 00 45 pm](https://cloud.githubusercontent.com/assets/5678694/8139829/a7e9198e-1124-11e5-8290-30cf3a0f879a.png)

If I close Sublime and reopen it, the icon changes to the default file-type icon for some reason:

![screen shot 2015-06-12 at 5 02 23 pm](https://cloud.githubusercontent.com/assets/5678694/8139847/d3824890-1124-11e5-9f48-f95e387c1467.png)

**Comment by equinusocio** [comment]
This is strange. I see the original red icon..

**Comment by saadq** [comment]
Hm, not sure what the issue was. I tried completely reinstalling ST, but the problem persisted. I guess I'll just leave file-type icons off for the time being.

**Comment by equinusocio** [comment]
You se the cog on all html files?

**Comment by saadq** [comment]
Yes, it was on all the HTML files.

I've managed to find the cause of the issue. Apparently, installing the [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter3) package makes it switch to the cog icon instead of the HTML5 icon. I'm not sure why this occurs. 

Before installing SublimeLinter: 

![screen shot 2015-06-15 at 5 40 49 pm](https://cloud.githubusercontent.com/assets/5678694/8171427/d0042a68-1385-11e5-9e52-fbbf26ce003e.png)

After installing SublimeLinter: 

![screen shot 2015-06-15 at 5 41 00 pm](https://cloud.githubusercontent.com/assets/5678694/8171439/db979b58-1385-11e5-8dc1-fe24cd18db70.png)
