### ISSUE TITLE
Wrong HTML color inside php files - ST 3 Build 3103 (public)

### ISSUE THREAD

**Issue by Disgeae** [equinusocio/material-theme#650]
Some syntax colors broke on the new build released last night.
Here an example of simple HTML divs:

<img width="268" alt="screen shot 2016-02-09 at 08 10 30 1" src="https://cloud.githubusercontent.com/assets/9702432/12909761/c81cbd20-cf04-11e5-88d1-f3cf29c821f1.png">

I'm using the standard theme and color scheme.

**Comment by deercreation** [comment]
Same issue.

**Comment by equinusocio** [comment]
I'm using 3dev and i have no issues with html. What HTML package are you using?

**Comment by Disgeae** [comment]
I checked and it's only when using HTML in PHP files. I don't use HTML packages.

**Comment by timonSchenzel** [comment]
Same issue here:

<img alt="color-issue" src="https://cloud.githubusercontent.com/assets/2272327/12913067/cba95fd0-cf1c-11e5-9d09-1355d987c7d9.png">

**Comment by juanpscotto** [comment]
Same problem to me. Some .ctp files from cake shows the code in white color

**Comment by jpcharrier** [comment]
Yes I'm also experiencing this! And we only work with PHP how do we fix this?! Can anyone point out the line number in color scheme??

**Comment by jpcharrier** [comment]
**WORKAROUND**
Depending which scheme you use the line number to alter this back to the way it was is :921 
Material Theme > Schemes > Material-Theme-Darker.tmTheme change line 921  from #DDDDDD to #ff5370 :)

I'm sure there are other places this was used and other things also affected, however to fix the display of html tags in php files the above works for me fine.

**Comment by marcushat** [comment]
Just upgraded, also having this issue.

**Comment by miguelolivares** [comment]
# Another Workaround

If you are using Gutter Color, go to Color Schemes of Gutter Color and check Material-Theme-Darker.gcfix

![screen shot 2016-02-10 at 11 42 39](https://cloud.githubusercontent.com/assets/4684028/12950336/775e6252-cfeb-11e5-87f4-92570857a2fd.png)

**Comment by marcushat** [comment]
I can confirm @jpcharrier workaround works. Changed the foreground color for "PHP: html tags" in OLD/Material-Theme-Darker.tmTheme and Material-Theme-Darker.tmTheme and it's back to how it was before.

Just search for "PHP: html tags" in the schemes because it's only on line 921 in Material-Theme-Darker.tmTheme

If you're going to update the package @equinusocio can you please include the OLD schemes too since it's such a simple fix. Thanks to both of you!

**Comment by equinusocio** [comment]
@marcushat yes i will do. But only this fix.

**Comment by marcushat** [comment]
Thanks. I'm willing to take on support for the old schemes if you don't want to though. I'll just make pull requests if they need need updates in the future.

**Comment by equinusocio** [comment]
I don't want to maintain a tons of color schemes. But PR  with fix are welcome.

**Comment by jpcharrier** [comment]
Hey I'd be happy to help out where I can, I'll fork and update the schemes and send you PR. Just so I'm clear, are the scheme in the /scheme folder - these are the old ones your referring to?

Regards,
JP Charrier

**Comment by equinusocio** [comment]
Yes `/schemes`directory

**Comment by ryanmortier** [comment]
I created a PR to get this fixed. #660
