### ISSUE TITLE
Strange artifact after ST 3103 upgrage

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#651]
As the new version of ST installed, I got an update of Material-Theme, which led to that unpleasant artifact (red yellow marker at the left).

<img width="359" alt="screenshot 2016-02-09 09 03 50" src="https://cloud.githubusercontent.com/assets/304929/12910856/71e9d6ea-cf0e-11e5-86b4-4456563741f7.png">

**Comment by equinusocio** [comment]
Try to remove and reinstall Material Theme.

**Comment by alexbeletsky** [comment]
@equinusocio helped, thx.

**Comment by equinusocio** [comment]
Np. This is a common issue with package control update/installing
