### ISSUE TITLE
Icon missing - overlay_bar_horizontal.png

### ISSUE THREAD

**Issue by pdanpdan** [equinusocio/material-theme#653]
I think this icon is missing, I get a 
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png
message in console

**Comment by equinusocio** [comment]
Same https://github.com/equinusocio/material-theme-appbar/issues/10

**Comment by pdanpdan** [comment]
I cleaned up everything and reinstalled, still the same issue:
Unable to decode Packages/Material Theme - Appbar/assets/commons/dirty_icon.png
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png
I checked and these icons are missing in the repository also

**Comment by callodacity** [comment]
+1, `Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png` in console on start up
