### ISSUE TITLE
Wrong icon being used in sidebar for .CSS files (shows .less file icon)

### ISSUE THREAD

**Issue by jpcharrier** [equinusocio/material-theme#654]
See screenshot below the wrong file icon is being used for .css files in the sidebar is the icon for .less files.
![screen shot 2016-02-10 at 3 19 13 pm](https://cloud.githubusercontent.com/assets/1574534/12937101/04425570-d00a-11e5-84da-5bc8aa1aa4bc.png)

**Comment by Revod** [comment]
:+1:

**Comment by equinusocio** [comment]
There is a problem with ST. The .css files provide `source.less`scope.

**Comment by equinusocio** [comment]
@jpcharrier Open a .css file, you can notice that ST assign less syntax to all .css files by default. Try to open a real css file, then go to ` View > Syntax > Open all with current extension as...` and then select CSS. Now reopen ST.

<img width="778" alt="screen shot 2016-02-14 at 19 17 29" src="https://cloud.githubusercontent.com/assets/10454741/13035413/d80b9aae-d34f-11e5-891d-df278e07ef01.png">

**Comment by jpcharrier** [comment]
@equinusocio Awesome thanks! Works perfectly now... :+1:
