### ISSUE TITLE
Option to remove tab navigator [Improvement]

### ISSUE THREAD

**Issue by hkraji** [equinusocio/material-theme#655]
First of all great job with a theme, one of the best for sure. 

It would be nice to have an option for disabling tab navigator ('< >' between sidebar and workspace). Personally, I use shortcuts and would like to remove this part of UI (a quite big part of UI actually).

**Comment by equinusocio** [comment]
... `"enable_tab_scrolling": false,`this is a simple ST preference that you should know ;) , isn't related to the theme.

**Comment by hkraji** [comment]
@equinusocio To be honest, did not notice it before your theme so I assumed it was theme driven.  Thank you for the help, all the best.
