### ISSUE TITLE
html and php syntax highlighting

### ISSUE THREAD

**Issue by worm2fed** [equinusocio/material-theme#661]
After updating sublime-text to sublime-text-dev-3.3103-1 (Archlinux: Linux tarvos 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux) there are no any more html syntax highlighting in .php file. Can u fix it?

Best regards, worm2fed.
![2016-02-12 17-59-41](https://cloud.githubusercontent.com/assets/6579275/13010258/fbd31bdc-d1b1-11e5-9037-8b5a91a60fa5.png)

**Comment by ryanmortier** [comment]
#660 fixed this.

**Comment by worm2fed** [comment]
Thanks
