### ISSUE TITLE
When renaming a file, can't see the file name that I am renaming

### ISSUE THREAD

**Issue by alexbet** [equinusocio/material-theme#662]
When I try to rename a file with the Sidebar Enhancements plugin (right click on file in sidebar and choose rename), I can't see the name of the file to rename. I can type the name and hit enter to rename it, but I cant see what I am doing at all, like doing it blind folded. I am not sure if this is an issue with the theme, but I think that it is.

On a side note, LOVE the theme, keep up the awesome work!

**Comment by alexbet** [comment]
When I try to rename a file with the Sidebar Enhancements plugin (right click on file in sidebar and choose rename), I can't see the name of the file to rename. I can type the name and hit enter to rename it, but I cant see what I am doing at all, like doing it blind folded. I am not sure if this is an issue with the theme, but I think that it is. 

On a side note, LOVE the theme, keep up the awesome work!

**Comment by Revod** [comment]
Read the known issues please, the fix are in the README

**Comment by alexbet** [comment]
Sorry, didn't notice that part of the read me. Resized and I can now see it. Thanks for the fast response!
