### ISSUE TITLE
appbar disappeared

### ISSUE THREAD

**Issue by sariattila** [equinusocio/material-theme#663]
![screenshot from 2016-02-15 10-42-37](https://cloud.githubusercontent.com/assets/5034149/13044900/e0268d6c-d3d0-11e5-843b-105abaf74465.png)

After the 2.0.7 update has been installed, appbar showing open files disappeared. sublime3, ubuntu 15.10.
Or maybe some default settings changed? Pls. help

**Comment by equinusocio** [comment]
Try to remove and reinstall appbar and/or material theme

**Comment by laminbarrow** [comment]
I had the same issue. Check your settings file and remove this line if it exists
	
`"theme": "Default.sublime-theme",`

and replace it with with any of the merial theme from this package

`  "theme": "Material-Theme.sublime-theme",
`

**Comment by sariattila** [comment]
None of above worked for me..

**Comment by equinusocio** [comment]
Paste here your preferences...

**Comment by sariattila** [comment]
`{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"font_options":
	[
		"gray_antialias"
	],
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_bold_tab": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme"
}`

**Comment by equinusocio** [comment]
There is no problem with your preferences. Have you tried to reinstall appbar package? Try and if you still have some problems please open a new issue to the relative appbar repository.
