### ISSUE TITLE
A version without langs - possibility

### ISSUE THREAD

**Issue by fatfisz** [equinusocio/material-theme#664]
First of all, great work :) I've been using this theme for over half a year now and I am really happy with it.

Some time ago I noticed that I couldn't use the `ctrl+/` shortcut for commenting out a line in `Gruntfile.js`. I found this quite strange and checked other JS files - they weren't affected. Only then did I notice that some other language syntax was used - "Gruntfile JS". It turned out that the file type in `tmLanguage` is so specific that I can't overwrite it using ST3 UI. I'm sure this syntax definition is at fault, because problems stopped after removing it.

Currrently I'm removing the `langs` directory from the installed package after each update so that I won't have any problems like that for a while. This, of course, has gotten a bit tiresome, so I'd like to ask if maybe there is some way to opt-out of `langs` here?

**Comment by equinusocio** [comment]
I have fixed the gulp file block comment with https://github.com/equinusocio/material-theme/commit/1133ce38512a18891e77bc2a5505f8a7e4815d19. You still can't use comment toggle?

**Comment by fatfisz** [comment]
I wrote about Gruntfile ;)

**Comment by equinusocio** [comment]
Oh, i'm sorry. If you want, you can try to apply and test the same fix above to the gruntfile pref and then make a PR! I will check in the next days.

**Comment by fatfisz** [comment]
Ok, will do that!

**Comment by equinusocio** [comment]
You can also check and test if all prefs are useless, if so we can totally remove prefs folder from the theme. :smile:

**Comment by fatfisz** [comment]
Could you help me out a bit? I'm completely green when it comes to developing ST packages.
My question is, what was the reason those files were put there in the first place?

**Comment by equinusocio** [comment]
`.tmlanguage` is a syntax-definition file ([read about it it](http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html?highlight=tmlanguage)). You can force ST to read some file with determinate extension and overwrite his default behavior, like the `license.tmlanguage`. These files was used for ST 2 and now i think some of they are outdated.

**Comment by fatfisz** [comment]
Thanks a lot!

**Comment by equinusocio** [comment]
Langs files will be removed form the next release.

**Comment by MiguelDebruyne** [comment]
A year and a half later the problem is still is there tho 

Since I'm here now I just want to say thank you for this theme! I've been using it for over a year now.

**Comment by equinusocio** [comment]
@MiguelDebruyne There is no problems with langs o.O
