### ISSUE TITLE
A little bit more contrast to the autocomplete would do a world of good

### ISSUE THREAD

**Issue by gj1118** [equinusocio/material-theme#665]
Hi, 
I am facing an issue with the autocomplete dropdown background color. Since its the same color with the color scheme background , the autocomplete items dont stand out . I hope its evident, from the snapshot below, that the autocomplete items do not stand out with the code , consecutively it becomes hard while cycling through the autocomplete items. One cannot easily infer whether  the code is an autocomplete menu item or the code iteslf. It also becomes somewhat hard because if I keep pressing the down arrow key and if i reach the last item, I am not taken to the first item , but rather the autocomplete box closes. 

I also know there is a Material Whitepanel plugin , but that stands a bit too much for me.  

I was wondering if the contrast mode option can be set to the autocomplete dropdown as well. A little bit of shadow (not sure if it would go with the standards) could bring out the autocomplete dropdown. 

![image](https://cloud.githubusercontent.com/assets/473101/13066370/1c7f84f0-d433-11e5-9eb8-536e3140b42d.png)

Please let me know what you think ?

**Comment by equinusocio** [comment]
@gj1118 you should see a drop shadow around the autocomplete popup.

**Comment by gj1118** [comment]
Hi @equinusocio , I am pretty sure that it will work for me, but the thing is , having this to port to many of the machines that I work on at work, where I have ST and Material theme is going to be a pain. If you can make this as an option, I would be obliged . 

Thanks
