### ISSUE TITLE
Theme doesn't work after last update to 3103

### ISSUE THREAD

**Issue by foria** [equinusocio/material-theme#667]
Do you know why it doesn't work with the new release?

**Comment by equinusocio** [comment]
the theme works perfectly with the last release. Please provide more details.

**Comment by carsonperrotti** [comment]
Does not work for me either. I have removed and re-installed the theme through package control. I have verified that the theme settings are in my user settings profile as well. The colour scheme for the text editor is working but the sidebar, tabs, etc. are all the default theme. 

<img width="1611" alt="screen shot 2016-02-16 at 1 28 17 pm" src="https://cloud.githubusercontent.com/assets/2063102/13086422/2819d81e-d4b1-11e5-9f6c-3ec6ba1000b4.png">

**Comment by carsonperrotti** [comment]
Never mind, I noticed that it added a line to set the default theme at the bottom after the update. I removed that line and was back in business. Perhaps this is your same issue too @foria, I didn't even notice that it added that line. 

Cheers!

**Comment by equinusocio** [comment]
Sometimes Package Control fail to reload the theme after update so you have to reactivate it.
