### ISSUE TITLE
New file Creating bottom tab issue!

### ISSUE THREAD

**Issue by arifhussain353** [equinusocio/material-theme#670]
Hi, 
Whenever i create file/folder by right click on sidebar then bottom input field shown which ask for me to type file/folder name.I have sidebar enhancement sublime as well.But after installing this theme bottom input field not showing properly.I can't see input field and text but when i type and press enter new file/folder created.Kindly tell me it's just with me ? or it's happen by installing theme ?.
For better explanation i take a screenshot before and after installing theme.
1:Before theme = http://prntscr.com/a4i5kd
2:After theme  =   http://prntscr.com/a4i6av
Thank you.

**Comment by Revod** [comment]
Read the README in known issues

**Comment by arifhussain353** [comment]
Oh ya.thank you. :)
