### ISSUE TITLE
Orange bar shows on the left

### ISSUE THREAD

**Issue by chrisjhoughton** [equinusocio/material-theme#674]
Hey guys! Huge fan. This only started happening a few days ago after Sublime prompted me to do an update:

<img width="335" alt="screen shot 2016-02-18 at 16 47 35" src="https://cloud.githubusercontent.com/assets/2671525/13150848/6ecb8f78-d65f-11e5-958e-f4b25ba77bb3.png">

Current sublime details:

<img width="336" alt="screen shot 2016-02-18 at 16 47 54" src="https://cloud.githubusercontent.com/assets/2671525/13150856/76b953b4-d65f-11e5-9ddb-27e1f1987f0e.png">

**Comment by equinusocio** [comment]
Try to completely remove and reinstall the theme

**Comment by chrisjhoughton** [comment]
Worked perfect thanks
