### ISSUE TITLE
Better Highlighting for Typescript Annotations and Decorators 

### ISSUE THREAD

**Issue by MohhamedRafi** [equinusocio/material-theme#675]
Currently I switched to using typescript for one of my projects and I notice that somethings like 
annotations and decorators are not highlighted. For example here: 

(Typescript)
![screenshot from 2016-02-18 15 33 03](https://cloud.githubusercontent.com/assets/7830796/13157275/ef081cde-d654-11e5-97ca-5ee90b4dcd48.png)

(Babel Selected)
![screenshot from 2016-02-18 15 31 04](https://cloud.githubusercontent.com/assets/7830796/13157241/bb471d1e-d654-11e5-9f4c-bc2a2cc64a1b.png)

It will be nice for it to be highlighted without switching to the other syntax because the typescript plugin add usage tools when dealing with typescript.

**Comment by equinusocio** [comment]
@MohhamedRafi Sorry but the typescrypt package doesn't provide rights scopes and i can support only official package. I suggest you associate Javascript (babel) syntax — through ST menu – to **.tsx** files so you don't have to do it each time.
