### ISSUE TITLE
Better contrast on Lighter Theme

### ISSUE THREAD

**Issue by lucasengel** [equinusocio/material-theme#676]
I believe the lighter theme has a really bad contrast. It looks quite nice with that fruity look though.

Take a look at a JSON file where the green almost fades into the white background:

<img width="423" alt="screen shot 2016-02-19 at 16 45 01" src="https://cloud.githubusercontent.com/assets/1020229/13185445/5251511a-d728-11e5-890d-23563f75bedf.png">

For testing purposes, I'm on rMBP.

**Comment by gj1118** [comment]
+1

**Comment by Arty2** [comment]
+1

**Comment by jlmakes** [comment]
With all due respect, I don’t think this has been addressed well enough.

I think there is a clear bias towards the darker themes, which look significantly better (and have better contrast) than the lighter theme. Even on my Apple display, the lighter theme is uncomfortable to use.

You’ve done great work, I want to emphasize that, but after using VS Code and some it’s lighter themes (particularly `Quiet Light`), I’ve come to realize how enjoyable they can be during the day to avoid seeing your reflection in the monitor on sunny days.

Anyway, here’s another **+1** to see this revisited.

**Comment by lucasengel** [comment]
I have to agree with @jlmakes. Although this issue was very punctual and **was fixed** the overall contrast is a bit low making this an issue apart. I usually have to make extra effort as the text seems to fade into the off-white background.

**Comment by equinusocio** [comment]
It should only review some colors. In the meantime, I am open to PR

**Comment by lucasengel** [comment]
I don't even know where to start when it comes to sublime theming but I can work on a CSS palette, does that help?

**Comment by equinusocio** [comment]
@lucasengel this is the json used by the theme compiler. Inside the `scheme.base` you can set a HEX palette used when the Lighter theme is compiled.

https://github.com/equinusocio/material-theme/blob/develop/src/settings/specific/Material-Theme-Lighter.json

**Comment by lucasengel** [comment]
I noticed from the latest theme update you've changed yellow to purple in some scopes. That already made a huge difference. Thanks, @equinusocio.
I'll take a look if I can improve somehow later today.

**Comment by jlmakes** [comment]
Awesome! @equinusocio, Is there a particular workflow you recommend for previewing changes while I work?

**Comment by lucasengel** [comment]
@jlmakes this helps: http://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai

**Comment by jlmakes** [comment]
@lucasengel @equinusocio I want to take a stab at revisiting the color scheme, but I don’t see a way to visualize my changes to the JSON file. The tmTheme editor is nice, but it doesn't appear to import/export JSON, let alone the format that `Material-Theme-Lighter.json` is in.

Should I be compiling the changes somehow?

**Comment by jlmakes** [comment]
@lucasengel @equinusocio tmTheme editor does not seem appropriate. It doesn‘t import JSON, nor would it let me preview changes to the Sublime interface theme.

@equinusocio Is there something I’m missing? Running `gulp` just seems to compile the theme. Am I supposed to make changes, compile and load the theme to review? There has got to be a better workflow, seeing as I might change a specific gray dozens of times to get it right… compiling and loading the theme every time can't be the only way.

**Comment by equinusocio** [comment]
@jlmakes You have to put a symlink of your local repo inside the `Packages` folder. Make sure you rename it `Material Theme`. Then you can run `gulp build` to launch the builder and after a seconds you will see the changes in your sublime text.

**Comment by lucasengel** [comment]
Guys, I've been trying to darken the colors as promised but nothing seems to fit. I've tried using the material palette but I that wasn't enough. In my tries I found yellow, amber, cyan and some lighter shades of gray (an any lighter shades of any color probably) will only get my eyes more tired.

I ended up with a less fruity-look using blue grays and browns, which seems to not resemble the original theme. =/

@jlmakes I've downloaded and uploaded the theme each time for testing in Sublime.

**Comment by jlmakes** [comment]
I’m still working on this but...

@lucasengel From what I understand of @equinusocio’s instructions, I believe the best way to go about it is to:
- Clone the repository (let’s say in `~/Desktop/material-theme`)
- Run `cd ~/Desktop/material-theme`
- Run `npm i` to install dependencies
- Go to your Sublime Text packages folder
- Run `ln -s ~/Desktop/material-theme 'Material Theme'` to create a symlink

You’ll now see a "shortcut" to your repository folder called Material Theme. From here, you should be able to enable the theme and color scheme normally—but when you run `gulp build` from within `~/Desktop/material-theme`, it will compile your changes and show up in Sublime Text.

This way you can edit the `Material-Theme-Lighter.json` instead of dealing with tmEditor.

**Comment by jlmakes** [comment]
Also @equinusocio @lucasengel 

I created a `.sketch` file to visualize what the current `Material-Theme-Lighter.json` palette looks like as 16x16 squares and 1x16 lines. I’ll double check it, but I believe this is accurate.

You can download it here: [material-theme-light.sketch](https://dl.dropboxusercontent.com/u/9257894/material-theme-light.sketch)

***

![theme](https://cloud.githubusercontent.com/assets/2044842/17262236/823c06f0-55da-11e6-965f-396ab58137e3.png)

![scheme](https://cloud.githubusercontent.com/assets/2044842/17262239/85305f00-55da-11e6-8ff7-dabdbe590243.png)

**Comment by equinusocio** [comment]
The new 3.1.0 release is coming. If there is a PR a will merge next time. I've made some little change on the color palette, so for now i will close this old issue until a PR.
