### ISSUE TITLE
Theme broken in Sublime Text 3 build 3103

### ISSUE THREAD

**Issue by andyforceno** [equinusocio/material-theme#677]
I updated Sublime Text (for Linux) a few days ago, and since then, the theme is broken. When I switch to different color schemes, the UI doesn't change (no more Material Theme tabs, for instance). Sometimes, when I switch to different color schemes, the color doesn't even change. I've tried removing the Material Theme package and re-installing, but it didn't change anything. 

Has anyone else experienced this? I'm so used to the Material Theme now, I find Sublime Text almost un-usable without it (I've been spoiled!). Here is what my Sublime Text looks like now (and you can see I have one of the schemes selected):
![screenshot from 2016-02-19 14 25 10](https://cloud.githubusercontent.com/assets/3803896/13186582/e0439e1a-d714-11e5-9af9-c65a444200e3.png)

**Comment by Revod** [comment]
Try uninstalling the theme and reinstalling again, I'm using the last build **3105** and work fine
![image](https://cloud.githubusercontent.com/assets/10109689/13188109/99bf54ae-d721-11e5-83da-018c246e77ba.png)
![image](https://cloud.githubusercontent.com/assets/10109689/13188127/ae9ad4d4-d721-11e5-8f27-dca45b27e8f4.png)

**Comment by andyforceno** [comment]
I have tried that several times already.

**Comment by andyforceno** [comment]
My Preferences.sublime-settings file lists my theme as:
`	"theme": "Default.sublime-theme"`

Should this be set to Material-theme or something other than the default?

**Comment by Revod** [comment]
@andyforceno yeah Andy, you need to put in theme, the material theme too example:
```json
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme-OceanicNext.tmTheme",
```
and done :smile:

**Comment by andyforceno** [comment]
That was the issue, as I'm seeing the right theme now. I'm not sure how it was reset.
