### ISSUE TITLE
Conditions words with differents colors as a text

### ISSUE THREAD

**Issue by JeremDsgn** [equinusocio/material-theme#678]
Hi!

It appears that some words use to create conditions, loops or whatever are displayed with differents colors when they are used in text context.

<img width="735" alt="capture d ecran 2016-02-20 a 11 11 17" src="https://cloud.githubusercontent.com/assets/937328/13196017/cf92ca1a-d7c2-11e5-92fa-91961f0211cb.png">

Configuration : JSX — React Native — Sublime Text 3103 — Material theme latest

**Comment by equinusocio** [comment]
@JeremDsgn this is what i see with Javascript (babel) package
![screen shot 2016-02-22 at 10 22 39](https://cloud.githubusercontent.com/assets/10454741/13214158/4154a9de-d94e-11e5-9800-9ab9cdd5575d.png)

**Comment by JeremDsgn** [comment]
I reproduce it with another mac.

[image: Images intégrées 1]

2016-02-22 10:23 GMT+01:00 Mattia Astorino <notifications@github.com>:

> @JeremDsgn <https://github.com/JeremDsgn> this is what i see with
> Javascript (babel) package
> [image: screen shot 2016-02-22 at 10 22 39]
> <https://cloud.githubusercontent.com/assets/10454741/13214158/4154a9de-d94e-11e5-9800-9ab9cdd5575d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equinusocio/material-theme/issues/678#issuecomment-187088224>
> .
>



-- 
*Cordialement,*
*Jérémy Barbet - Designer*

@JeremDsgn <https://twitter.com/JeremDsgn>
www.jeremybarbet.com
contact@jeremybarbet.com

**Comment by JeremDsgn** [comment]
I reproduce it with another mac wit same configuration.

<img width="670" alt="capture d ecran 2016-02-22 a 10 25 18" src="https://cloud.githubusercontent.com/assets/937328/13214291/09f147a8-d94f-11e5-86a5-655f8a0a5f86.png">

**Comment by equinusocio** [comment]
@JeremDsgn What package are you using for the react highlight?

**Comment by JeremDsgn** [comment]
I use this plugin : https://github.com/allanhortle/JSX. the issue came from this ? Because the problem is still remaining.

**Comment by equinusocio** [comment]
Can you try Javascript Babel package please?

**Comment by JeremDsgn** [comment]
Ok it works with the babel package. The problem came from JSX package. Thanks!
