### ISSUE TITLE
Can't see The Rename Option

### ISSUE THREAD

**Issue by Revod** [equinusocio/material-theme#68]
When I select the "Rename..." to a archive o a carpet, can't see this:
![Rename opcion](https://cloud.githubusercontent.com/assets/10109689/8142695/95f7c650-114f-11e5-9d1e-7cbacab0a956.png) 
This is in other theme, but in the material theme i click in "Rename..." but doesn't appear 
![sin titulo 2](https://cloud.githubusercontent.com/assets/10109689/8142713/8934eeec-1150-11e5-83ac-2e62cd29dd15.png)

**Comment by equinusocio** [comment]
sede #18 and restart twice sublime text
