### ISSUE TITLE
HTML tags in .phtml files

### ISSUE THREAD

**Issue by memomiliano** [equinusocio/material-theme#681]
![image](https://cloud.githubusercontent.com/assets/1069741/13226913/b0292d48-d972-11e5-891a-5b0266cbda38.png)

HTML tags in .phtml files (Zend Framework) are white, beacuse the file is marked like PHP.

I think that labels should be red, as in the HTML file.

Congrat's for the great work

**Comment by equinusocio** [comment]
If you change the syntax with the right you see the right colors?

**Comment by equinusocio** [comment]
This will be fixed in the next release. If you want now the fix you have to use the master package.
