### ISSUE TITLE
Please Remove File Extension Preferences

### ISSUE THREAD

**Issue by wbond** [equinusocio/material-theme#682]
The files at https://github.com/equinusocio/material-theme/tree/develop/prefs/Ext/ mess with the standard extension mapping.

It would be preferable to instead add a readme entry teaching people to use the *View > Syntax > Open all with current extension as…* menu.

**Comment by FichteFoll** [comment]
Or add these extensions to the syntax definition files directly via pull requests.

**Comment by cpruitt** [comment]
+1 for removing. This bit us by incorrectly mapping the .html.erb to vanilla HTML syntax (and it took us a while to track down the cause).

**Comment by Revod** [comment]
+1 for this
