### ISSUE TITLE
.bowerrc and .eslint being picked up by JSON syntax and not Material Theme

### ISSUE THREAD

**Issue by Sawtaytoes** [equinusocio/material-theme#683]
I'm on Windows using ST3 b3103.

I'm having a weird issue; might be another plugin. When opening .bowerrc and .eslintrc and any other .rc files, it's opening them up in Sublime Text as JSON format even if I force a change and remove them from the JSON syntax. Do you know what might be causing this?

Installed packages:

```json
"All Autocomplete",
"ApacheConf.tmLanguage",
"ApplySyntax",
"AutoHotkey",
"Babel",
"BBCode Syntax",
"Better CoffeeScript",
"Blade Snippets",
"BracketHighlighter",
"Ciapre Color Scheme",
"CJSX Syntax",
"Clouds Color Schemes",
"CMakeEditor",
"Codeivate",
"Colorcoder",
"ColorHelper",
"Compare Side-By-Side",
"Dotfiles Syntax Highlighting",
"EditorConfig",
"Emmet",
"Expand Tabs on Save",
"ExportHtml",
"File Rename",
"FileDiffs",
"Handlebars",
"Hosts",
"HostsEdit",
"HTML Underscore Syntax",
"HTML-CSS-JS Prettify",
"Inc-Dec-Value",
"Jade",
"Jade Snippets",
"jQuery",
"JS Snippets",
"Laravel Blade Highlighter",
"LESS",
"LiveScript",
"Lua Dev",
"Markdown Preview",
"MarkdownEditing",
"Material Theme",
"Material Theme - Appbar",
"Missing Palette Commands",
"Modific",
"nginx",
"Oceanic Next Color Scheme",
"Package Control",
"Placeholders",
"Predawn",
"Predawn Monokai",
"Predawn Twilight Theme",
"Razor",
"Red Planet Color Scheme",
"Smarty",
"Stylus",
"Sublime TFS",
"SublimeCodeIntel",
"SublimeLinter",
"SublimeLinter-coffee",
"SublimeLinter-contrib-eslint",
"SublimeLinter-contrib-sass-lint",
"SublimeLinter-csslint",
"SublimeLinter-json",
"SublimeLinter-lua",
"SublimeLinter-php",
"Syntax Highlighting for Sass",
"Tab Filter",
"Text Pastry",
"TOML",
"Tomorrow Color Schemes",
"VBDotNet",
"VDF",
"Xdebug Client",
"zenburn"
```

**Comment by equinusocio** [comment]
no not really... My `.rc` files open with the plain text syntax. You can try to set the default syntax for each file extension so you don't have to do it each time.

![screen shot 2016-02-24 at 10 17 30](https://cloud.githubusercontent.com/assets/10454741/13280707/d8637afc-dadf-11e5-9234-ed116aa9e49e.png)

**Comment by Sawtaytoes** [comment]
I did that already. It gets immediately reset upon closing and reopening the file.

**Comment by jeffijoe** [comment]
@Sawtaytoes What you just described is happening for me, too, with LESS files.

**Comment by equinusocio** [comment]
Are you using material theme 2.0.8?

**Comment by Sawtaytoes** [comment]
In `Material Theme.sublime-package/package.json`, I'm seeing:

```json
"version": "1.9.9"
```

But in package-metadata.json I see:

```json
"version": "2.0.7"
```

**Comment by Sawtaytoes** [comment]
Just forced an update from the package manager and got `👉 Version 2.0.8 👈`.

**Comment by equinusocio** [comment]
Wi 2.0.8 check if you still have the issue.

**Comment by Sawtaytoes** [comment]
Yes, still happening.

**Comment by equinusocio** [comment]
@Sawtaytoes what about 2.0.9?

**Comment by Sawtaytoes** [comment]
Still happening. I really think it's a plugin I have installed. @jeffijoe, is this fixed for you?

**Comment by jeffijoe** [comment]
@Sawtaytoes it's fixed on my end. :)

**Comment by equinusocio** [comment]
@Sawtaytoes you think we can close this issue?
