### ISSUE TITLE
Crash again and again in ST3

### ISSUE THREAD

**Issue by iamtechplayer** [equinusocio/material-theme#684]
Hi
I am using ST3, when installing material-theme its working good. After few days theme crashed. But don't found any reason.

After crashing its hard to install again every time.

**Comment by equinusocio** [comment]
Sorry but this isn't related to this theme. Remove and reinstall it through Package Control

**Comment by iamtechplayer** [comment]
@equinusocio isn't related to this theme. But i am facing this on this theme... i am using material-theme
 in ST3. And talking about this material-theme.?

I know that to reinstall the theme. but why i am reinstalling. why its crashed ???

**Comment by equinusocio** [comment]
The theme is disabled when Package Controlo update it. You have to wait until update finish.
