### ISSUE TITLE
CSS fileicon error

### ISSUE THREAD

**Issue by heby** [equinusocio/material-theme#685]
Sublime Text 3 3103 for mac
Material theme version is 2.0.8
![image](https://cloud.githubusercontent.com/assets/3339694/13276992/eefefbfe-daff-11e5-95a3-da27fe7a6752.png)

**Comment by Revod** [comment]
Fix:
Open the .css file, Go to _View > Open all with current extension as... > CSS_ and done

**Comment by heby** [comment]
OK,fixed. thanks
