### ISSUE TITLE
Missing text input box when rename file

### ISSUE THREAD

**Issue by daywong1119** [equinusocio/material-theme#687]
If i click rename on the side bar, there's no text input box shown, but when i type and press enter, it actually renamed.

Build 3103

**Comment by pooley182** [comment]
Experiencing the same issue when using the SideBarEnhancements plugin. When selecting 'New File' from the side bar it should present you with a  text bar at the bottom of the screen (activewindow.show_input_panel()) for typing in a filename. The space for the panel gets created but I can't see the panel, typing and pressing enter does name the new file.

**Comment by equinusocio** [comment]
Please check the Known Issue section in the readme file.
https://github.com/equinusocio/material-theme#known-issues
