### ISSUE TITLE
Stop updating all the time

### ISSUE THREAD

**Issue by enjikaka** [equinusocio/material-theme#688]
Seems like there is an update multiple times a week. When there is, Sublime breaks because my "active theme was updated". And I need to restart for the theme to apply correctly. Which is very annoying when I get to work in the morning and the first thing I have to do is start Sublime, close it, and start it again because of the theme updating too often.

**Comment by jbrooksuk** [comment]
From Dev Build 3106 this is no longer an issue. However, if you're not using the dev builds, don't install it from package control.

**Comment by equinusocio** [comment]
> From Dev Build 3106 this is no longer an issue. However, if you're not using the dev builds, don't install it from package control.

Or simply disable auto updates.

**Comment by kyle-emmerich** [comment]
@equinusocio Not a great solution, honestly. You shouldn't tell your users to disable auto-updating; otherwise, why bother updating it? You should just update less often with more meaningful updates. Don't push unstable versions.

**Comment by equinusocio** [comment]
Don't boring me with this issues. Please. Hotfix should be released immediately. And, i've released only 1 update for material theme.
