### ISSUE TITLE
Material Design Font suggest

### ISSUE THREAD

**Issue by B-iggy** [equinusocio/material-theme#69]
So this theme is really sexy and beautiful. Good job!
I'm just wondering why you don't go the full "google-material-design" road? ;)

The new Google Font "Roboto Mono" just fits perfect into this theme.

https://www.google.com/fonts/specimen/Roboto+Mono
After installing put in user-preference:
```"font_face": "Roboto Mono"```

**Comment by equinusocio** [comment]
Yeah thanks. I will try this font

**Comment by AAlakkad** [comment]
If anyone need direct link to download [Roboto Mono](https://github.com/google/fonts/tree/017bacd6542f9d9453267715ddafc9f71fb757bf/apache/robotomono).
