### ISSUE TITLE
Accent color per-project settings

### ISSUE THREAD

**Issue by jbrooksuk** [equinusocio/material-theme#690]
This may be related to build 3106.

Should it be possible to set the accent color on a per-project setting?

**Comment by equinusocio** [comment]
Similar to #614.

Inside your project file you can paste your sublime settings:

```
"folders": [...], 
"settings": {
		"rulers": [120],
		"tab_size": 2,
		"translate_tabs_to_spaces": true,
		"trim_trailing_white_space_on_save": false,
}
```

**Comment by jbrooksuk** [comment]
Yeah, I'm doing this but it's not working.

**Comment by jbrooksuk** [comment]
So I was wondering if this is a bug with Sublime or the theme _should_ be able to support it? Ping @wbond.

**Comment by equinusocio** [comment]
I think we can't add a custom settings inside project file. Currently only the default ones work.

**Comment by jbrooksuk** [comment]
I found a post on the forum that said that the theme preference can't be changed, it's "global". However the App Bar isn't a theme setting, and probably could be allowed as a non-global setting.

**Comment by equinusocio** [comment]
AppBar is a theme that override some of material theme rules. The accent definition preference is provided by Material Theme Package, so i think they are global.

**Comment by jbrooksuk** [comment]
Yeah, I spoke to @wbond, it's a global setting so it's unsupported.
