### ISSUE TITLE
sass syntax highlighting gone

### ISSUE THREAD

**Issue by zachleigh** [equinusocio/material-theme#691]
Updated to 2.0.8 just now and syntax highlighting for .sass files is no longer present.

**Comment by equinusocio** [comment]
Provide more details please.
- ST Build
- OS
- Sass/scss used package

**Comment by zachleigh** [comment]
Sublime Text Build 3083
Ubuntu 14.10
Sass 3.2.19 (Media Mark)

**Comment by zachleigh** [comment]
Just updated Sublime to build 3103 and still have the problem.

**Comment by zachleigh** [comment]
Its back. Forgot to close out sass files after the sublime upgrade. Closed everything up, checked again and its fine.  Sorry to waste your time!
