### ISSUE TITLE
Dynamic colour generation?

### ISSUE THREAD

**Issue by jbrooksuk** [equinusocio/material-theme#693]
How are you generating the accent colours? I figured from the gulp notice in the README that it was dynamic but it looks like that's not the case.

**Comment by equinusocio** [comment]
Gulp compiler grab this js partial.
https://github.com/equinusocio/material-theme/tree/develop/src/commons

**Comment by jbrooksuk** [comment]
I added a new colour and yet nothing was generated?

**Comment by equinusocio** [comment]
You have to run `gulp` command inside the project folder, and then edit the files inside `src/`. If there is no error you will se the system notification and the terminal message.
