### ISSUE TITLE
App bar coloring issue

### ISSUE THREAD

**Issue by stckcrsh** [equinusocio/material-theme#696]
![image](https://cloud.githubusercontent.com/assets/1430685/13301929/e3089aaa-db0c-11e5-9294-bf0eebf23ecb.png)

![image](https://cloud.githubusercontent.com/assets/1430685/13301957/00c5f01a-db0d-11e5-933f-2087cdc2e923.png)

Having issues where the color for the left and right tabs and the rest of the bar look weird.
I noticed that mine was different from another coworker's sublime with this same theme.

**Comment by equinusocio** [comment]
Just restart ST...

**Comment by Js-GitHub** [comment]
@stckcrsh 

I cannot get appbar colors to change when using:
"material_theme_accent_orange": true,
"material_theme_appbar_lime": true,
"material_theme_tree_headings": true,

Appbar colors track with changes in: "material_theme_accent..."
"material_theme_accent_orange": true,

Any advise or suggestions?

Maybe I need to uninstall and reinstall both material_theme and appbar?

I'll give it try later...
