### ISSUE TITLE
Rename file textbox is hidden

### ISSUE THREAD

**Issue by rahul-desai3** [equinusocio/material-theme#697]
After I right-click on a file in the sidebar and choose to rename it, I see a dark space at where the textbox should be, but there is not textbox.

Here's the snapshot:

<img width="1552" alt="screen shot 2016-02-25 at 12 41 21 am" src="https://cloud.githubusercontent.com/assets/2539881/13314176/8982e750-db58-11e5-9e89-c57d77648949.png">

If I just start typing at that point, it does go through. However, the UI is buggy.

I have the SideBarGit installed and it just doesn't show me the textbox for the commit message. Its just the dark space again. This doesn't happen with other themes that I have tried and no theme (obviously).

I love this theme and am very much used to it. However, this thing has been bugging me for a while now.

**Comment by equinusocio** [comment]
Please check the known issue section in the README file.
