### ISSUE TITLE
Theme Stopped Working

### ISSUE THREAD

**Issue by 4mohit** [equinusocio/material-theme#698]
Theme suddenly stopped working and change back to the default theme.I have been having this issue for a sometimes now. First I thought it maybe a problem with my installation so I removed the material theme and installed the SETI UI and It was working fine with it. Currently, I have no other theme installed beside material and no UI selector like(themr) and its still crashing .

**Comment by equinusocio** [comment]
- Try to remove and reinstall Material Theme
- When Package Control update the theme you have to wait until finish for reactivation.
