### ISSUE TITLE
Orange color glitch

### ISSUE THREAD

**Issue by virtous** [equinusocio/material-theme#699]
Today when I opened up Sublime I got this weird orange color glitch.

![bug](https://cloud.githubusercontent.com/assets/3582546/13337371/431a5334-dc1b-11e5-9a98-2b6fa818eb10.PNG)

Thought I'd report it here directly. Let me know if there's a fix for this.

Cheers.

**Comment by Revod** [comment]
Try uninstalling the theme and reinstall again

**Comment by virtous** [comment]
yepp, that fixed it. Thanks!

**Comment by cngu** [comment]
I'm running into this issue too. Tried uninstalling, restarting, re-installing, restarting and I still run into this issue ONLY for the indigo theme. It displays correctly for all the other colors.
