### ISSUE TITLE
comments jade

### ISSUE THREAD

**Issue by newyorktime** [equinusocio/material-theme#70]
Hi!! First of all, congratulations for this awesome theme.

I have a  very little issue. please take a look to the next screenshot, the comments in jade aren't in the same color.
![captura de pantalla 2015-06-13 a las 12 40 05](https://cloud.githubusercontent.com/assets/8522674/8144024/9b609a7a-11c9-11e5-88da-d137793df2c0.png)

Do you have think about to add the options of preap theme like the sidebar size an another options?

Thanks a lot

**Comment by equinusocio** [comment]
@newyorktime I will add some options in the next releases. For the comment issue i will check!
