### ISSUE TITLE
Is it possible to have the theme survive an update?

### ISSUE THREAD

**Issue by simonmurdock** [equinusocio/material-theme#702]
Hi, this theme is awesome

However every time sublime text updates it resets the theme to `"theme": "Material-Theme.sublime-theme"`, is it possible to configure my sublime so this doesn't happen?

I'm assuming it's something out of your control but I thought I'd ask.

Thanks

**Comment by equinusocio** [comment]
This is a Package Control behavior. When theme get updates Package Control Temporarily disable the theme. You have to wait until finish the update and it will be reactivated. If you are running a ST build before 3106 you have to restart Sublime Text after every theme update.

**Comment by simonmurdock** [comment]
ok thanks for replying @equinusocio :+1:
