### ISSUE TITLE
TODO: More accent colors.

### ISSUE THREAD

**Issue by ddagone** [equinusocio/material-theme#703]
This is just a comment, Could you add more **colors** please ?  

Thanks
Best regards

**Comment by equinusocio** [comment]
Any suggestion form the material palette?
https://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by ddagone** [comment]
Pink :
A400 #F50057

Blue :
A400 #297FF

Light Green :
500 #8BC34A

Yellow :
A400 #FFEA00

Amber :
900 #FF6F00

Thanks
Best regards

**Comment by equinusocio** [comment]
- [x] Pink : A400 #F50057
- [ ] Blue :  A400 #297FF
- [x] Light Green : 500 #8BC34A  (Already exist)
- [x] Yellow : A400 #FFEA00 (Already exist)
- [ ] Amber : 900 #FF6F00
