### ISSUE TITLE
Problems to render the Folders structure

### ISSUE THREAD

**Issue by HelikeLong** [equinusocio/material-theme#704]
I just instaled a Sublime Text 3 on my computer and installed the theme right way.
So I add a project and a folder to it, but, for some weird reason, it's not rendering it properly.
If I open a folder, it shows me animation, but don't actualy open it, so I have to resize the sidebar and, then, it updates and show me the folder open.
Sometimes it overlays to, so I have to close, resize, open and resize again, and then it fix.

Its really weird, I never had any problem like that on Ubuntu, it don't support Windows?

I have an Windows 8.1 Ultimate, Sublime Text build 3103, Material Theme and Material Theme AppBar.

**Comment by equinusocio** [comment]
Try to build a new project workspace and then restart ST

**Comment by HelikeLong** [comment]
Tried, and no luck :/
Starting to think, through, it's a problem in my Sublime itself

**Comment by HelikeLong** [comment]
Reinstalled my Sublime completly, now it's working.
