### ISSUE TITLE
Theme Install Directory in Cache

### ISSUE THREAD

**Issue by Jones-S** [equinusocio/material-theme#705]
Hi there

I just installed your theme via package control. After that I added it to my preferences and the look changed. So far so good, everything's working.
I now tried to make the font-size of the tabs smaller hoping to see more open tabs. I therefor looked for the sublime-theme file and realized that even after restarting my mac, the material theme folder was not here: 
`~/username/Library/Application\ Support/Sublime\ Text\ 3/Packages `
but instead here:
`~/username/Library/Application\ Support/Sublime\ Text\ 3/Cache/Material\ Theme `

Why is the theme in the cache folder? I don't understand that.
Thanks for a hint.

**Comment by christoga** [comment]
If you move the directory to Sublime Packages, will it work?

**Comment by Jones-S** [comment]
I have no idea but in the meantime the theme is where it's supposed to be. Maybe a restart of my mac did the thing? I have no idea but the issue is solved...
