### ISSUE TITLE
indent_guide_options "draw_active" colors all lines from left to active indentation with the same (activeGuide) color.

### ISSUE THREAD

**Issue by ThaJay** [equinusocio/material-theme#707]
SublimeText3 does not offer the option to not draw_stack while using draw_active in indent_guide_options, so I was wondering if you can make stackGuide more stealth, or give us an option to choose between highlight / normal guide / background (none) color for the stackGuide. That would be awesome as it would make the UI look even cleaner.
https://github.com/SublimeTextIssues/Core/issues/1125
https://github.com/SublimeTextIssues/Core/issues/1128
current look, the "draw_active" option uses activeGuide and stackGuide:
![indent_guide_options-draw_active](https://cloud.githubusercontent.com/assets/9341747/13426432/8f5d88e8-dfad-11e5-8fac-64d581d53724.png)
desired: option to hide stackGuide

**Comment by equinusocio** [comment]
This is what i see with `"indent_guide_options": [ "draw_normal", "draw_active" ],`:
<img width="329" alt="screen shot 2016-03-16 at 09 43 44" src="https://cloud.githubusercontent.com/assets/10454741/13806397/a9809300-eb5b-11e5-8c6c-6c640be3dd6d.png">
