### ISSUE TITLE
Color scheme not displayed when have more than fifteen levels of {}

### ISSUE THREAD

**Issue by fabriciosomini** [equinusocio/material-theme#709]
When the user uses more than 15 inner {} the color synthax will stop.
Verify the image for details.
![bug](https://cloud.githubusercontent.com/assets/15656090/13463548/7f5cea74-e06b-11e5-99f8-6dcbb97958e3.jpg)

Environment: Sublime 3
Language: Javascript
Theme: Material Theme (Material Theme-Oceanic Next)
Linter: JSHint

**Comment by equinusocio** [comment]
I don't make any fix/change on Oceanic Next scheme. Material theme use the original one, so you have to open the issue on his repository.
