### ISSUE TITLE
git icon wont show for git-related files

### ISSUE THREAD

**Issue by blomdahldaniel** [equinusocio/material-theme#71]
Hi, I love this theme, I think its really great, big thanks to your hard and fast work.

But I have stumbled upon an error that uninstall/install reboot wont fix.

I have the sweet laravel logo, php logo, js, json, yml icons but on my .gitignore file i only have a dark cogwheel. 

![sidebar](https://cloud.githubusercontent.com/assets/10044093/8144419/c2557bcc-11de-11e5-96b5-6b2494cac165.png)

Here is my config, don't know what could be causing this so i post my entire Settings - User file.
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_width": 2,
	"caret_style": "phase",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"copy_with_empty_selection": false,
	"drag_text": false,
	"draw_indent_guides": true,
	"draw_minimap_border": true,
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": false,
	"font_face": "Roboto Mono",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 14,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"match_brackets_content": false,
	"match_selection": false,
	"match_tags": false,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": false,
	"rulers":
	[
		80
	],
	"scroll_past_end": true,
	"scroll_speed": 5.0,
	"show_full_path": false,
	"sidebar_default": true,
	"tab_size": 4,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": true
}

```

Got any idea of how i can fix this?

**Comment by equinusocio** [comment]
I've tried all your preferences and i see the right icons... this is strange.
![schermata 2015-06-14 alle 12 04 28](https://cloud.githubusercontent.com/assets/10454741/8148148/ec49e72e-128d-11e5-9b2a-02b3e0008abc.png)

**Comment by blomdahldaniel** [comment]
Hm.. I am quite lost in all this. I am thinking uninstall/install of Sublime but it sucks to have to fix all the packages and all that.. Maybe I can try to update Sublime? I elswere have absolutely no clue where to look...?

**Comment by equinusocio** [comment]
What version of ST you use?

**Comment by llaraujo** [comment]
Hello @equinusocio , I just installed ST3 and I have this problem.

* ST 3 (Build 3083)
* Mac (10.10.3)

#### Installed Packages:
* EditorConfig
* Emmet
* Emmet Css Snippets
* JavaScript & NodeJS Snippets
* Pretty JSON
* SASS
* SideBarEnhancements

**Comment by blomdahldaniel** [comment]
Hi I have a lot of the same specs as @llaraujo 
* ST 3 is also build 3083.
* Mac 10.10.3

**Comment by B-iggy** [comment]
For me php and git also are missing.
It's from a project but even when I clean everything and reopen it - still missing.

Windows 8
ST3 3092
![addons](https://cloud.githubusercontent.com/assets/7815434/8154615/3342487a-133c-11e5-88c9-832ba98a2275.jpg)

I tried to uninstall SideBarEnhancements without success.

![icons](https://cloud.githubusercontent.com/assets/7815434/8154566/be06662c-133b-11e5-86e2-8618674798fb.PNG)

**Comment by gj1118** [comment]
For me , the license and the PHP icons are missing.  
Running ST3 3092  on a MAC Yosemite (10.10.3) 

This is what I have already done. 
1. Cleared the cache
2. Restarted Sublime Text 
3. Cleared the indexes
4. Restarted Sublime Text again.

but it seems nothing is working so far.

I tried this with Seti-UI , with it the license icons are appearing but not the PHP Icon.

![image](https://cloud.githubusercontent.com/assets/473101/8154873/9267e434-130c-11e5-8334-7eb07005a596.png)


![image](https://cloud.githubusercontent.com/assets/473101/8154758/5ab285c2-130b-11e5-80f5-2bdb8dac2fd8.png)


![image](https://cloud.githubusercontent.com/assets/473101/8154750/4673a596-130b-11e5-802c-e429b8ec9c35.png)

**Comment by B-iggy** [comment]
Well... after a complete reinstall of sublime. portable and installable I still don't have php and git :(

**Comment by gj1118** [comment]
@B-iggy have you tried it with the latest version of ST3 (Build 3092) ?  Is the PHP icon in place ?

**Comment by B-iggy** [comment]
So what I did the last hour:
deleted all portable and installed Sublime Versions. Run through regedit and deleted all registry paths related to sublime.
Restarted Windows.

Installed x64 st3 beta channel -> php icon there but no git
Installed x64 st3 dev channel -> both icons missing

Run x64 st3 beta channel portable -> php icon there but no git
Run x64 st3 dev channel portable -> both icons missing
(everything clean, no addons)

The git icon is in the right directory but somehow it doesn't get loaded.

**Comment by equinusocio** [comment]
UPDATE: The issue is caused by the Package SublimeLinter, and i don't know why (probably for the color scheme caching and path).

This not appear by using Sublimelint (not SublimeLinter)

**Comment by B-iggy** [comment]
I don't have sublimelinter or sublimelint installed?!

**Comment by equinusocio** [comment]
Yes i'm investigating.

**Comment by equinusocio** [comment]
@B-iggy show me your installed packages

**Comment by B-iggy** [comment]
Well as I mentioned four posts above: I did a complete fresh install. Like I never had sublime before.
Then I tried the portable and installable version of the two channels with different outcomes.

At the moment my packages are (+ SASS syntax):
![addons](https://cloud.githubusercontent.com/assets/7815434/8178685/ff9a227e-1410-11e5-886c-d81517290e97.jpg)

**Comment by KrisOlszewski** [comment]
Would it be caused by https://github.com/titoBouzout/SideBarEnhancements? I don't see Git icons and I am not able to create new files or folders. Right click > New folder doesn't trigger anything.

![screen shot 2015-06-16 at 11 26 28 am](https://cloud.githubusercontent.com/assets/2780894/8188298/92f4c232-141a-11e5-90e2-b563eec8cf5a.png)

**Comment by equinusocio** [comment]
No, i use SE too and in my sublime it work well. mm

**Comment by B-iggy** [comment]
Hm... what sublime version do you use on what machine (32/64 bit, windows, mac, linux) @equinusocio ?

**Comment by equinusocio** [comment]
![screen shot 2015-06-16 at 19 11 26](https://cloud.githubusercontent.com/assets/10454741/8189276/83082242-145b-11e5-9294-9751f0eecfa5.png)

OS X 10.10.3

**Comment by B-iggy** [comment]
seems so. Testing it later on Windows 10

**Comment by llaraujo** [comment]
@KrisOlszewski See #19  for the fix.

**Comment by KrisOlszewski** [comment]
@llaraujo thanks, I reinstalled ST3 from scratch and that fixed it.

**Comment by blomdahldaniel** [comment]
Closed because? 
The problem remains? 
Did you close because you are absolutely surtain that it is not because of the theme?

**Comment by equinusocio** [comment]
Yes, i've tried with a clean installation of ST 3, with only the SetiUI theme and this issue was happen when installing SublimeLinter. Someone has said that didn't install SulbimeLinter and the problem occurs the same. So i think it's related to ST. 

On my macbook this issue doesn't occur, instead is happen on my iMac. I don't know how debug this at the moment.

**Comment by blomdahldaniel** [comment]
@equinusocio okey, then I understand. Thanks for the awesome work you have done on this theme, i love every second when I am in Sublime (except for when i miss my git-icons... ;) )
Great job, and very active here with all the issues. :+1: 
Thanks!

**Comment by equinusocio** [comment]
thanks man :+1:

**Comment by ngocphamm** [comment]
Having this issue lately. The icon for PHP files doesn't show up (not sure about other file types).

I just installed fresh Sublime Text build 3092 (64-bit) on a new PC, add Package Control and then install the theme but it doesn't help. Guess it could be an internal problem of Sublime.

**Comment by ngocphamm** [comment]
I think I found the possible cause of the PHP file icon not showing up: https://github.com/ctf0/Seti_ST3/issues/149#issuecomment-111847053. It's likely that because of the recent changes in the syntax system.

According to the comment in the link, replacing `source.php` with `embedding.php` in the `icon_php.tmPreferences` will work.

I guess other file type icon missing will also due to similar syntax changes not reflected by the theme/syntax package yet.

**Comment by equinusocio** [comment]
I will check all icon preferences. Thanks @ngocphamm :)

**Comment by B-iggy** [comment]
After updating to latest version everything is great! Thank you! :)
![working](https://cloud.githubusercontent.com/assets/7815434/8396660/82994e28-1daf-11e5-82fe-01816db2eb2b.PNG)

**Comment by equinusocio** [comment]
Nice! :+1: But I did nothing :)

**Comment by NicolasParada** [comment]
I had this problem too. But it was solved with the last version :)
Keep the great work @equinusocio

**Comment by blomdahldaniel** [comment]
Woho! Yes the missing git icons has returned! :D Now I can fully enjoy your work @equinusocio

**Comment by equinusocio** [comment]
:+1:

**Comment by timbog80** [comment]
@equinusocio can you post or put your full preferences list on the read me or on here

**Comment by ngocphamm** [comment]
@equinusocio FYI https://github.com/sublimehq/Packages/issues/24

**Comment by equinusocio** [comment]
```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"close_windows_when_empty": false,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"drag_text": false,
	"draw_minimap_border": true,
	"file_exclude_patterns":
	[
		"*.pyc",
		"*.pyo",
		"*.exe",
		"*.dll",
		"*.obj",
		"*.o",
		"*.a",
		"*.lib",
		"*.so",
		"*.dylib",
		"*.ncb",
		"*.sdf",
		"*.suo",
		"*.pdb",
		"*.idb",
		".DS_Store",
		"*.class",
		"*.psd",
		"*.db",
		"*.sublime-workspace",
		"*.sublime-project"
	],
	"folder_exclude_patterns":
	[
		"node_modules",
		".svn",
		".git",
		".hg",
		"CVS"
	],
	"font_face": "FiraMono-Regular",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 19,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": false,
	"scroll_past_end": true,
	"scroll_speed": 5.0,
	"show_full_path": false,
	"sidebar_xlarge": true,
	"theme": "Material-Theme.sublime-theme",
	"trim_trailing_white_space_on_save": true
}

```

**Comment by equinusocio** [comment]
@ngocphamm this is already omplemented ;)

**Comment by ngocphamm** [comment]
@equinusocio He recommends using `source.php, embedding.php` for backward compatibility.

**Comment by equinusocio** [comment]
ok Thanks

**Comment by sasindumendis** [comment]
The latest update (v1.4.5) broke git icons for me again. :disappointed:

**Comment by blomdahldaniel** [comment]
Yes this is the same for me.. Gah.. 
.scss files have no icon as well.

Anybody know something?

How is it for the guys that had no problem before?
@equinusocio how is it for you?

**Comment by timbog80** [comment]
still getting this issue. why is it closed? has it been resolved? i did everything i dont have seti ui or any linters and the problem persists.

http://puu.sh/iPsZq/478872d411.png

**Comment by equinusocio** [comment]
Because i can't fix this. I've the same issue with Seti UI on my iMac  and not with Material Theme. Here, on my macbook i have the same issue with material theme instead.

**Comment by vluzrmos** [comment]
I'm having this issue too, I already reinstall the package...

![image](https://cloud.githubusercontent.com/assets/450848/8639052/863e6e6e-28a4-11e5-84be-9f7fd5f08650.png)

My installed packages are:

![image](https://cloud.githubusercontent.com/assets/450848/8639082/5fd3c7dc-28a5-11e5-8660-25430a9a6f33.png)
