### ISSUE TITLE
More readable line numbers and comments

### ISSUE THREAD

**Issue by michelecos** [equinusocio/material-theme#711]
Line numbers are a major resource when you deal with JavaScript errors. They are too hard to read.
Comments, also, are there to help. I do not subscribe to the notion that comments clutter code and are better removed.
I am asking an option to have line numbers and comments in a readable non obtrusive neutral light gray,
Thanks.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/254
https://github.com/equinusocio/material-theme/issues/393
https://github.com/equinusocio/material-theme/issues/439
https://github.com/equinusocio/material-theme/issues/290

**Comment by mixtecalex** [comment]
What is the file to custom the color line number? Where I can find it? Thanks

**Comment by equinusocio** [comment]
Your current active scheme file inside `./schemes`
