### ISSUE TITLE
Replace in Files is not showing

### ISSUE THREAD

**Issue by fbehrens** [equinusocio/material-theme#714]
How can I replace in files  ?

I guess it is not shown because of a problem with formatting.
The rename file or rename Directory is not shown as well.

I am Using DevChannel Sublime 3107 .

![image](https://cloud.githubusercontent.com/assets/13704/13564760/5fbe970a-e44c-11e5-8fa4-749e5f818efe.png)

With Normal Theme
![image](https://cloud.githubusercontent.com/assets/13704/13564729/12655fde-e44c-11e5-884c-2b324994b8c0.png)

**Comment by equinusocio** [comment]
Che the known issues in the readme file
