### ISSUE TITLE
Regex icon makes no sense

### ISSUE THREAD

**Issue by JustGoscha** [equinusocio/material-theme#715]
The regex icon doesn't male sense for me in the theme. I'm searching for it on a regular basis and only through hover I found out. It's a minor issue :) , but annoys me somehow, is there a way to change it myself?

**Comment by equinusocio** [comment]
Can you make a PR?

**Comment by michelecos** [comment]
I think that an asterisk would be easily recognizable as a marker for regexps and could also be drawn in such a way as to be visible as the other icons.

**Comment by equinusocio** [comment]
Try to pick the icon from here:
https://design.google.com/icons/

**Comment by andela-abankole** [comment]
How about this Icons:
[Code](https://design.google.com/icons/#ic_code)
[Explicit](https://design.google.com/icons/#ic_explicit)

I strongly suggest Explicit

**Comment by enkia** [comment]
If not explicit (good choice), there's also a ['period'](https://design.google.com/icons/#ic_fiber_manual_record)
