### ISSUE TITLE
Can't see `exit/close` button when press Ctrl+F

### ISSUE THREAD

**Issue by agusmakmun** [equinusocio/material-theme#716]
Hello there, we have a problem when i press `Ctrl+F` to find something, close button is doesn't exists.

![problem](https://cloud.githubusercontent.com/assets/7134451/13629167/dcd366ee-e609-11e5-9f6d-672cc91bc542.png)

**Comment by equinusocio** [comment]
Just press <kbd>ESC</kbd>. it's faster.
