### ISSUE TITLE
Use less padding to make better use of screen estate

### ISSUE THREAD

**Issue by fbehrens** [equinusocio/material-theme#717]
Hi, and sorry if this is not appropriate here, because it is just my optionion.
I like the theme very much, and I would like it even more,
if it has less padding everywhere:

* Project Drawer
* Tab Headers
* Command Bar
* Search Bar

This would be better for me on a small screen (Laptop).
the screenshots i stole from anotjer issue are just to illustrate, what I say.
I just fiddled a bit around in the theme, but i didn't came far.

Maybe you like the idea,
and may have some tips for customize

thanks, Frank

![](https://cloud.githubusercontent.com/assets/7134451/13629167/dcd366ee-e609-11e5-9f6d-672cc91bc542.png)

**Comment by equinusocio** [comment]
Just press esc.
