### ISSUE TITLE
Gulpfile JS.tmLanguage can't be opened

### ISSUE THREAD

**Issue by dylansteele8** [equinusocio/material-theme#719]
Getting this error when I open up Sublime now (updated to 2.0.9): `Error loading syntax file "Packages/Material Theme/langs/Gulpfile JS.tmLanguage": Unable to open Packages/Material Theme/langs/Gulpfile JS.tmLanguage`. Is there something I should do after upgrading to avoid this issue?

**Comment by dylansteele8** [comment]
Removed and installed the package. Not getting the error anymore.

**Comment by equinusocio** [comment]
#713

**Comment by FichteFoll** [comment]
The manual solution is to just reopen the files that use these syntaxes.

Uninstalling causes Package Control to remove the "invalid syntax references" that would be cause by removing the package.
