### ISSUE TITLE
New folder / Rename folder

### ISSUE THREAD

**Issue by Robertmw** [equinusocio/material-theme#721]
I just installed this theme (is awesome btw), and when I tried to create a new folder, right click on a folder - new folder, nothing happened.

After a few tries I observed that the action is triggered because the scrollbar from right side become smaller - that means the new folder input "container" is displayed, but no input visibile. But, the input renders after you resize that "container".

Same bug for rename, didn't tried to Search in folder. 

PS: After resize both actions work as expected.

**Comment by codekashmir** [comment]
Also encountered the same problem, but if you see closely at the bottom size of rename box is too small to see just hover your mouse pointer their and drag it to make larger.

**Comment by equinusocio** [comment]
Please read the readme file. There is a big "known issues" section.
