### ISSUE TITLE
No more "Packages/Material Theme"

### ISSUE THREAD

**Issue by unlucio** [equinusocio/material-theme#722]
Hello,
I just updated the theme as prompted by the package manager and starting getting the following error:
```
Error loading syntax file "Packages/Material Theme/langs/npm JSON.tmLanguage": Unable to open Packages/Material Theme/langs/npm JSON.tmLanguage
```
I checked in my `~/Library/Application Support/Sublime Text 3/Packages` and the `Material Theme` directory was gone.
I then proceed uninstalling and reinstalling the theme but now pretty much nothing work.
All I can see is the `~/Library/Application Support/Sublime Text 3/Cache/Material Theme` but  `~/Library/Application Support/Sublime Text 3/Packages/Material Theme` never came back.
Any suggestion?

**Comment by equinusocio** [comment]
Similar to #719. Also check #713 for more info.
