### ISSUE TITLE
Active tab

### ISSUE THREAD

**Issue by CXHub** [equinusocio/material-theme#723]
Hi,

First of all, this theme is awesome!

Is there an option that changes the **tab-highlight**? The active tab gets an underline, but i'm used to tabs that get an underline when there is an unsaved change. At this moment, the only thing changing is a small icon.

Thanks.

**Comment by equinusocio** [comment]
No at the moment. I will add this visual feedback by using the native sublime preference `"highlight_modified_tabs"`

**Comment by equinusocio** [comment]
I can only make italic the font inside a modified tab. But i will not remove the underline that's part of material design tab component.

**Comment by CXHub** [comment]
Then i'll just have to get used to it. Thanks anyway!
