### ISSUE TITLE
Theme accent colors not working...

### ISSUE THREAD

**Issue by c0ppo** [equinusocio/material-theme#724]
Used to work before. Not sure how long this option doesn't work, but when I set it to any other color then default, nothing changes at all. But a month ago everything worked like a charm. Latest sublime text 3 build, OS X 10.11.4

**Comment by equinusocio** [comment]
Paste your preferences please.

**Comment by gynekolog** [comment]
I have same problem. Only default scheme work correctly.
<img width="1019" alt="screen shot 2016-03-31 at 09 27 22" src="https://cloud.githubusercontent.com/assets/4593089/14168494/0988c894-f723-11e5-938b-1f73fe06c678.png">

**Comment by equinusocio** [comment]
Where is your accent setting...

**Comment by gynekolog** [comment]
I don't know which accent setting string you mean but reopen all tabs is solutions for me.

**Comment by equinusocio** [comment]
to set a different accent color you have to set ex. `"material_theme_accent_indigo": true` in your preference. The teal color is the default one, and in your screenshot works.

**Comment by gynekolog** [comment]
I am sorry, my fault. I had problem with applying other theme then default so I am at wrong issue.
