### ISSUE TITLE
"indent_guide_options" on Lighter Theme

### ISSUE THREAD

**Issue by lucasengel** [equinusocio/material-theme#726]
Indentation is invisible on lighter theme using: `"indent_guide_options": [ "draw_normal", "draw_active" ]`

<img width="237" alt="screen shot 2016-03-15 at 12 04 30" src="https://cloud.githubusercontent.com/assets/1020229/13782534/56daa060-eaa6-11e5-917a-319bdcfeec0a.png">
<img width="231" alt="screen shot 2016-03-15 at 12 04 57" src="https://cloud.githubusercontent.com/assets/1020229/13782535/57687688-eaa6-11e5-8bab-3de8442ba924.png">

**Comment by equinusocio** [comment]
I clearly see the intent guides in your screenshots. What's the problem?

**Comment by lucasengel** [comment]
Thanks for the fix @equinusocio, but now I can't see the line anymore.

<img width="64" alt="screen shot 2016-04-11 at 17 35 08" src="https://cloud.githubusercontent.com/assets/1020229/14441586/e135a91a-000b-11e6-910e-20d1e9a1e335.png">
