### ISSUE TITLE
Theme stopped working since 2.0.9

### ISSUE THREAD

**Issue by torrobinson** [equinusocio/material-theme#727]
Since restarting and obtaining 2.0.9, I get this on every startup (and nothing gets themed):
![image 2016-03-15 at 6 47 30 pm](https://cloud.githubusercontent.com/assets/4401999/13798724/b6e0c1be-eade-11e5-839d-780fe65abaab.png)

**Comment by jiachenlee** [comment]
+1

**Comment by equinusocio** [comment]
#713
