### ISSUE TITLE
Colour problem with closing php tag

### ISSUE THREAD

**Issue by impossibleform** [equinusocio/material-theme#728]
[Example](http://s22.postimg.org/qimkzmj35/Untitled.png)

**Comment by equinusocio** [comment]
Provide more details.

**Comment by Bazingi** [comment]
It's caused by Laravel Blade Highlighter...idk i if it's right to report there.

**Comment by equinusocio** [comment]
No, you have to report this issue on it's repository. There is a problem with the syntax provided
