### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by nicohvi** [equinusocio/material-theme#73]
Looks amazing, great job!

 Would love to see something like this for vim. :racehorse:

**Comment by avelino** [comment]
+1

**Comment by equinusocio** [comment]
If anyone can help with this.. :)

**Comment by jgallen23** [comment]
I wonder if it would be easiest to take the colors from this theme and create theme for [base16](https://github.com/chriskempson/base16) so we could use the [builder](https://github.com/chriskempson/base16-builder) to generate color schemes for vim/iterm/etc.

**Comment by arthurvr** [comment]
I, the be honest, have no idea how to write Vim themes but I'd looovvve to see this happening!

**Comment by muminoff** [comment]
+1

**Comment by jdkanani** [comment]
+1. Love to see in vim. If this ever happens, I will move from solarized for sure.

**Comment by nobe4** [comment]
In case anyone is interested : http://vimcasts.org/episodes/creating-colorschemes-for-vim/, I will try to work on it (also for the fun :+1: )

**Comment by slamflipstrom** [comment]
+1

**Comment by avelino** [comment]
Dracula theme initial for sublimetext support and extend to vim support

https://github.com/zenorocha/dracula-theme

**Comment by pacuna** [comment]
+1, love the theme but I don't use ST

**Comment by sunaku** [comment]
:pray: Vim support (especially for 256-color terminal Vim) would be heavenly. :angel:

**Comment by bitboxer** [comment]
can @equinusocio post the colors used? like in the readme here: https://github.com/altercation/solarized ? A separate repo for all other editors would be nice, too. Everyone could port and write PRs :+1:

**Comment by equinusocio** [comment]
@bitboxer done :+1: I've added the basic UI color palette of the Default Material Theme.

**Comment by bitboxer** [comment]
These are **all** colors in the scheme:

#263238
#37474F
#546E7A
#5C7E8C
#7986CB
#80CBC4
#82B1FF
#8BD649
#C3E88D
#CDD3DE
#EC5F67
#F1E655
#F77669
#F8E71C
#FAD430
#FFCF1B
#FFEB95
#FFFFFF

**Comment by davidhan527** [comment]
+1

**Comment by jdkanani** [comment]
Any update? Please add vim support :sob:  or I will be dead :skull: .

**Comment by nobe4** [comment]
Yeah the base16 support gave me no good result, for example, picking the colors in the @bitboxer order and giving them strait to base16 made my vim looks like : 

![screen shot 2015-06-23 at 16 54 46](https://cloud.githubusercontent.com/assets/2452791/8309050/8a828bd0-19c8-11e5-850c-8b2cab817f2a.png)

**Comment by bitboxer** [comment]
Yes, just putting them in the order I pasted them here does not make much sense :wink:

**Comment by jdkanani** [comment]
Here is my attempt with base16 builder. ![screen shot 2015-06-23 at 9 46 13 pm](https://cloud.githubusercontent.com/assets/1692593/8311073/6a9f84de-19f1-11e5-8ee9-6ddc519b58d0.png)

**Comment by arthurvr** [comment]
@jdkanani Looking good bro.

**Comment by jdkanani** [comment]
Base16 colors: (Not good :sob: )

scheme: "Material Theme"
author: "Mattia Astorino"
base00: "263238"
base01: "37474F"
base02: "546E7A"
base03: "5C7E8C"
base04: "80CBC4"
base05: "82B1FF"
base06: "CDD3DE"
base07: "C3E88D"
base08: "C792EA"
base09: "F77669"
base0A: "C792EA"
base0B: "C3E88D"
base0C: "8BD649"
base0D: "80CBC4"
base0E: "C792EA"
base0F: "80CBC4"

**Comment by arthurvr** [comment]
I honestly think the version by @jdkanani doesn't look bad. Doesn't exactly match the theme but not bad :p

**Comment by equinusocio** [comment]
Make it perfect :+1:

**Comment by jdkanani** [comment]
Done. First version for GVim. Check it out: https://github.com/jdkanani/material-theme
Please send some pull requests to make it better.

**Comment by jdkanani** [comment]
Here is the screenshot:

![screenshot](http://i.imgur.com/M2CF1m6.png)

**Comment by equinusocio** [comment]
Nice work! Remove the separators :D

**Comment by jdkanani** [comment]
@equinusocio [done](https://github.com/jdkanani/material-theme/commit/7d2167d5ee47eea2b2e9a71b911681a3a7e75645) :)

**Comment by equinusocio** [comment]
@jdkanani nice work. I suggest you to rename the repository to "vim-material-theme". When you do this i will link the theme in the official resources section of the README file. :+1:

**Comment by jdkanani** [comment]
@equinusocio okay done. Here it is: https://github.com/jdkanani/vim-material-theme

**Comment by montlebalm** [comment]
Great work @jdkanani. Now we just need to get an iTerm theme :)

**Comment by Dudemullet** [comment]
Thanks @jdkanani ! Great work

**Comment by kristijanhusak** [comment]
I created version that looks a bit like material theme, that is based on [w0ng/vim-hybrid](https://github.com/w0ng/vim-hybrid). Here's the screenshot:

![hybrid-material](https://cloud.githubusercontent.com/assets/1782860/8340203/483e81f2-1abd-11e5-8fc6-b1ca5c646404.png)


You can download it here https://github.com/kristijanhusak/vim-hybrid-material

**Comment by equinusocio** [comment]
@kristijanhusak Awesome work!

**Comment by Wutzara** [comment]
Droping my own attempt into the ring - basically i just used the same color-palette (mostly the 300 colors) to mimic the theme in some bits

![](https://raw.githubusercontent.com/Wutzara/vim-materialtheme/master/screenshot.png)

You can find it [here](https://github.com/Wutzara/vim-materialtheme)

**Comment by dikiaap** [comment]
I just create [Minimalist](https://github.com/dikiaap/minimalist) - Based on Material Theme Darker color scheme and Red accent.

![Minimalist material theme](http://i.imgur.com/laipfSy.png)

**Comment by dikiaap** [comment]
I just create [dikiaap/minimalist](https://github.com/dikiaap/minimalist) - Based on Material Theme Darker color scheme and Red accent.

![Minimalist material theme](http://i.imgur.com/laipfSy.png)
