### ISSUE TITLE
Renaming field hidden

### ISSUE THREAD

**Issue by berezuev** [equinusocio/material-theme#731]
## Environment
- Sublime Text 3 Build 3103
- Windows 7 Pro x64
- 1920x1080 px resolution

## Tips to reproduce the bug
- Open any folder with files.
- Right-click to file in Side Bar -> **Rename...**
- In the bottom of sublime window you'll see a solid-filled line (instead of file name field)
![image](https://cloud.githubusercontent.com/assets/695546/13876942/a6930ace-ed18-11e5-9671-c15d70e62ae1.png)

## Comments
Renaming function still works, but you can't see the field.

**Comment by equinusocio** [comment]
Check the fix inside the README file, under known issues.
