### ISSUE TITLE
Rename file or directory

### ISSUE THREAD

**Issue by antana013** [equinusocio/material-theme#733]
I just use sublime build 3103 and when I was installed your theme into my sublime then when I need to rename my file or directory input box fill new name is invisible.

thank you for good theme :)

**Comment by antana013** [comment]
It's has bug for when need to create new directory as well.

**Comment by saadq** [comment]
Check out the [Known Issues](https://github.com/equinusocio/material-theme#known-issues). The quick fix is just to grab the border of the input field and pull.

**Comment by antana013** [comment]
Thank you so much, and so sorry for did not look at it
