### ISSUE TITLE
AutoComplete Background Color

### ISSUE THREAD

**Issue by ikanyu** [equinusocio/material-theme#734]
Hi! I'm using the default theme but I dislike the autocomplete color as it is not very readable to me.

```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

![screen shot 2016-03-22 at 5 02 46 pm](https://cloud.githubusercontent.com/assets/8460219/13946544/30820b4c-f050-11e5-8bdd-411984be029a.png)

How can I do it if I still want the default color theme but with the lighter theme autocomplete color settings?

![screen shot 2016-03-22 at 5 03 48 pm](https://cloud.githubusercontent.com/assets/8460219/13946543/2d13fda8-f050-11e5-9b1d-1d2d5508368f.png)

**Comment by equinusocio** [comment]
Are you using White Panels Addon?

**Comment by ikanyu** [comment]
I am not very sure whether I activated it or not. But I did see it under the Package Control: Remove Package > Material Theme - White Panels

**Comment by ikanyu** [comment]
Updates:

I have decided to remove Sublime Text entirely from my Mac and reinstall it again. Apart from that I installed the Material Theme into my Sublime with the following code at my User Preference Settings
```
{
  "theme": "Material-Theme.sublime-theme",
  "color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"ignored_packages":
	[
	],
	"tab_size": 2,
}
```

Went to check for `Package Control: Remove Package > Material Theme - White Panels` and the Material Theme-White Panels is no longer there. Not sure how it is installed into my sublime at the first place. Previously I actually did try to `Package Control: Remove Package > Material Theme` but all the color went off.

Thanks anyway!

**Comment by equinusocio** [comment]
Try to install Material Theme White Panels addon to change the autocomplete and panels color to white.

**Comment by ikanyu** [comment]
How do I change the autocomplete color then? :)

**Comment by quantumproducer** [comment]
What is the key name for autocomplete?

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/blob/develop/sources/themes/darker/autocomplete.json
