### ISSUE TITLE
Color Scheme - Material-Theme-Darker missing @media coloring for SCSS

### ISSUE THREAD

**Issue by geebru** [equinusocio/material-theme#735]
![Screenshot](https://cloud.githubusercontent.com/assets/806033/13957681/a6442702-f023-11e5-96bb-67d8fb6c61ee.png)

Seems like the theme is missing `@media` coloring. Everything else seems to work for SCSS/Sass except for those calls.

I have not checked the other color schemes or themes.

**Comment by equinusocio** [comment]
I have no problem with .scss and sublime Sass package.
<img width="379" alt="screen shot 2016-03-29 at 09 38 44" src="https://cloud.githubusercontent.com/assets/10454741/14101046/10399782-f592-11e5-80a1-ab0c1f946fce.png">

**Comment by geebru** [comment]
I'm using the SCSS package as the Sass package (prior to installing Material) was giving me odd coloring issues. I'll give the Sass package a shot - perhaps your theme remedies the issues I was having with it before!

**Comment by geebru** [comment]
The Sass package does seem to remedy that issue although it shifts element, value, and a few other colors. Would this be an issue for the SCSS package creator then?
