### ISSUE TITLE
Rename file bar is hidden

### ISSUE THREAD

**Issue by connorbode** [equinusocio/material-theme#736]
I've attached a screenshot of the issue, and it is highlighted.  Note that I have a tonne of plugins installed, so this *could* be due to some other plugin. 

When I attempt to rename a file, the rename text input field is covered up by a bar at the bottom so I can't see what I am renaming it as. 

Let me know if you need any other info for repro

![screenshot 2016-03-23 17 42 04](https://cloud.githubusercontent.com/assets/1156049/14001908/e1199a64-f11e-11e5-9ad0-a68f076f5857.png)

**Comment by equinusocio** [comment]
Check the README file please, under known issues.
