### ISSUE TITLE
Do not see file "Rename" strip at the bottom of the screen

### ISSUE THREAD

**Issue by tadvi** [equinusocio/material-theme#737]
I do not see file "Rename" strip at the bottom of the screen.

Sublime Text 3 build 3103 on Windows.

To reproduce:
1. Click on the file in the SideBar.
2. Right click to get pop up menu with "Rename" option.
3. Select "Rename"
4. Looks like something is being displayed at the bottom. But there is no frame or controls in that bottom strip.

**Comment by equinusocio** [comment]
Check the readme file under known issue.
