### ISSUE TITLE
Bottom strip for Build

### ISSUE THREAD

**Issue by tadvi** [equinusocio/material-theme#738]
Bottom strip for Build has no distinction border or background color difference.

If Build takes long it is not obvious what is going on... like there is no indication that anything is happening because bottom strip for Build is not visible (it just dark shaded rectangle same as background).
Tiny frame line or some other indication of the Build running would help.
Thank you.

**Comment by equinusocio** [comment]
Have you tried with `"material_theme_panel_separator": true,` or `"material_theme_contrast_mode": true`?

**Comment by tadvi** [comment]
Sorry, I should have read README...

"material_theme_panel_separator": true
This works, but could be just slightly more visible.

Thank you.
