### ISSUE TITLE
Markdown Draw Centered

### ISSUE THREAD

**Issue by vluzrmos** [equinusocio/material-theme#74]
Hello,

Is there a way to define markdown "draw_centrered":false and that not be replaced after the package be updated?

**Comment by equinusocio** [comment]
Hi @Frozenfire92, yes, you can set this in your syntax file preference:

Open a .md file, then go in ```Preferences > Settings - More > Syntax Specific - User``` and paste this inside:
```json
{ "draw_centered": false }
```

**Comment by vluzrmos** [comment]
Thanks!

**Comment by prwhitehead** [comment]
Thanks!
