### ISSUE TITLE
Color Scheme Problem in php files

### ISSUE THREAD

**Issue by kokororin** [equinusocio/material-theme#740]
The problem occurred at ` self::$_LIB_ROOT = preg_replace('/comm[\/\\\]core$/is', '', dirname(__FILE__));`
There is a `\\\` in the preg pattern.
![image](https://cloud.githubusercontent.com/assets/10093992/14106844/8c096f32-f5e6-11e5-94c8-779bc4c69cde.png)
While The same code in phpstorm's material theme is well:
![32d7faa2-cfe8-4916-bef6-63ec794daf12_meitu_1](https://cloud.githubusercontent.com/assets/10093992/14106916/1b151d8e-f5e7-11e5-8a25-16069f7a9322.jpg)

**Comment by equinusocio** [comment]
What colorscheme are you using?

**Comment by kokororin** [comment]
Packages/Material Theme/schemes/Material-Theme.tmTheme

**Comment by equinusocio** [comment]
Can you paste this snippet?

**Comment by kokororin** [comment]
Here it is:
```php
<?php
function loadDefFavortie() {
        if (self::$_FAVORITE_FIX === null) {
            self::$_LIB_ROOT = preg_replace('/comm[\/\\\]core$/is', '', dirname(__FILE__));
            	
            require_once (self::$_LIB_ROOT . 'comm/config/core.php');
            if (is_array($_CORE_FAV_LIB)) {
                self::$_FAVORITE_FIX = $_CORE_FAV_LIB;
            } else {
                self::$_FAVORITE_FIX = array();
            }
        }
    }
```

**Comment by equinusocio** [comment]
There is a problem with the PHP built-in package. The package doesn't return the correct scopes after the '\\\'. If you remove one of the `\` the syntax works again. Se the screenshot, it return all the code as a single-quoted string:

<img width="810" alt="screen shot 2016-04-05 at 21 41 59" src="https://cloud.githubusercontent.com/assets/10454741/14295763/3f5b1924-fb77-11e5-92e7-80c913375a4f.png">

**Comment by kokororin** [comment]
Thanks a lot .
