### ISSUE TITLE
Invisible text in "file rename" input field

### ISSUE THREAD

**Issue by nilsnh** [equinusocio/material-theme#744]
Hi there,

When right-clicking a file in the side bar and selecting "rename" the text to rename is either missing or invisible from the bottom row where it usually would appear. Same thing happens when viewing a file, pressing ctrl+shift+p and selecting File:Rename.

Otherwise a great theme! :)

My versions/settings:

- Sublime 3 build 3103

```javascript
{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_face": "Fira Code",
	"font_size": 10,
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"overlay_scroll_bars": "enabled",
	"tab_size": 2,
	"theme": "Material-Theme.sublime-theme"
}
```

**Comment by equinusocio** [comment]
Please check the readme file.
