### ISSUE TITLE
hide extension in tab bar

### ISSUE THREAD

**Issue by Frogmouth** [equinusocio/material-theme#745]
Hello,
first, I love this theme. It's clear and usable, IT SHOULD BE A STANDARD FOR ALL DEVELOPER. :+1: 

I have a question:

**"Can i remove or hide the file extension in the Tab bar?"**

From:
<img width="692" alt="screen1" src="https://cloud.githubusercontent.com/assets/4380308/14346675/815eafec-fcb3-11e5-8987-debb6e5662bd.png">

to:
<img width="692" alt="screen2" src="https://cloud.githubusercontent.com/assets/4380308/14346542/fe35d7da-fcb2-11e5-8fcf-b92eeee11714.png">

Grazie / thx, 
Simone :)

**Comment by christoga** [comment]
I think it will be confusing if the user is coding a different language with the same name on the script

**Comment by equinusocio** [comment]
There is nothing to do. Sublime doesn't offer a way for hide the tabs file extension.

**Comment by Frogmouth** [comment]
@christoga - its depends to how you manage your workspace panel.
@equinusocio  - Ok, thanks.
