### ISSUE TITLE
Rename option does not show the characters

### ISSUE THREAD

**Issue by alannaidon** [equinusocio/material-theme#748]
Hello !
I was trying to rename a file (Right Click) and at first nothing happened... Then I stalled the **sidebar enhancements**, now I _can_  rename it, but the characters are not being displayed. You have to `Ctrl+A` then write the new name you want (without seeing the characters).

**Comment by equinusocio** [comment]
Check the README file
https://github.com/equinusocio/material-theme#known-issues
