### ISSUE TITLE
Visual spacer: console <> code

### ISSUE THREAD

**Issue by B-iggy** [equinusocio/material-theme#75]
I know flat design / material design is a synonym for "clean" but can you add a little visual spacer between the console and the code view? (see my screenshot)
When I want to resize the console it's really hard to find the edge.

Maybe the little dropshadow from the CTRL+P window?
![spacer](https://cloud.githubusercontent.com/assets/7815434/8145659/c1785cf6-1210-11e5-9859-a034bf8d714e.PNG)

thank you again for this nice work!

**Comment by equinusocio** [comment]
I can't add a separator only between console and code. I have to add it even in find/replace panel, and i want to make a fully flat "color layer".

You can live without this separator? You resize the console everytime? :smile:

**Comment by B-iggy** [comment]
Well when it's not possible it's ok. I get used to it :)
