### ISSUE TITLE
Hover on open folders remains green

### ISSUE THREAD

**Issue by oconnor0** [equinusocio/material-theme#751]
I set `"material_theme_accent_blue": true,` in my user config. When I hover over an open folder in the sidebar, the color is still the greenish default rather than blue. It appears this is the case with indigo as well. I haven't tried other colors.

**Comment by Blue-EyesWhiteDragon** [comment]
My "Preferences > Settings - User > Preferences.sublime-settings" is set up like so:

````JSON
{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "Material-Theme.sublime-theme",
	"material_theme_accent_blue": true
}
````

And it works fine for me, same with all the other colours.

Check for missing semi-colons, that's a common mistake when you paste something into a JSON file - I make it all the time.

**Comment by equinusocio** [comment]
Try to restart sublime text

**Comment by oconnor0** [comment]
I've restarted Sublime Text 3dev quite a few times. Here are the relevant portions of my `Preferences.sublime-settings`

```json
{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-OceanicNext.tmTheme",
	"material_theme_accent_blue": true,
	"material_theme_compact_sidebar": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_separator": true,
	"theme": "Material-Theme.sublime-theme",
}
```

@Blue-EyesWhiteDragon When I use your JSON, it works. As I investigate a little more, the issue appears to be

```json
    "material_theme_disable_folder_animation": true,
```

When that is true, I get the green folders on hover. When that is false, I get the blue animated folders on hover.
