### ISSUE TITLE
Every theme update results in a reindex

### ISSUE THREAD

**Issue by armanm** [equinusocio/material-theme#752]
I notice upon every update of this theme, Sublime has to reindex the entire project. This is probably fine for small projects but in large projects this really slows things down and makes my newish MacBook Pro run with all its fans going. Could this be improved?

**Comment by Blue-EyesWhiteDragon** [comment]
Sounds like something to do with Sublime Text, I don't think a theme can dig right into that part of the program.

**Comment by equinusocio** [comment]
> Sounds like something to do with Sublime Text, I don't think a theme can dig right into that part of the program.

**Comment by armanm** [comment]
@equinusocio  here is a screenshot of what I was describing. This happens immediately after every Material Theme update. I don't think this is a random event.

![screen shot 2016-05-03 at 10 02 57 am](https://cloud.githubusercontent.com/assets/1578748/14971522/5319a76e-1116-11e6-9151-4175b0945e74.png)

**Comment by equinusocio** [comment]
How do you think that a theme update can force reindex? This percentage show the update status.

**Comment by armanm** [comment]
It's simple. The CPU usage shots up. It takes about ten minutes for that
number to reach 100. Does this theme take ten minutes to update?
