### ISSUE TITLE
Sidebars Icons and file name bars not changing

### ISSUE THREAD

**Issue by alannaidon** [equinusocio/material-theme#754]
I just opened the `ST3 build 3103` and in a blink the whole theme, icons, everything was gone.  
I just removed the package and installed it again but still not working the sidebars and the file name bars.  

![ss](https://cloud.githubusercontent.com/assets/13774879/14500682/6390c318-0179-11e6-9635-0fe0777f1628.jpg)
 

The font colors and style are ok.

**Comment by equinusocio** [comment]
Duplicated of #753
