### ISSUE TITLE
background for open files at sidebar

### ISSUE THREAD

**Issue by romanfedyshyn** [equinusocio/material-theme#755]
hi. I'm try to find where I can change the color for open files background, but not realy can :)
hope you help me with that

**Comment by equinusocio** [comment]
You can't.

**Comment by romanfedyshyn** [comment]
no, I can ;)

**Comment by romanfedyshyn** [comment]
I'm just done with it )

**Comment by equinusocio** [comment]
You can't through the theme settings.

**Comment by romanfedyshyn** [comment]
http://grab.by/Ptmq how you can see I just set a black background for selected tree_row

**Comment by equinusocio** [comment]
> You can't through the theme settings, sure.
 
I know that you can customize the theme. But as said, you can't change this color thtough the theme preferences.

**Comment by romanfedyshyn** [comment]
yeah, I know ;) But I mean customize, I'm just give a incorrect question )
