### ISSUE TITLE
Inactive tabs have grey text

### ISSUE THREAD

**Issue by JTallis** [equinusocio/material-theme#757]
This is by far the best theme I've ever seen, along with the appbar.

The only issue that bothers me (other than issues with the padding), is that inactive tabs have grey text.

![](https://cloud.githubusercontent.com/assets/4530100/14547363/b01fd756-02a4-11e6-9859-edea3fed3144.png)

I'm not sure if this is related to a setting or not, I've played around and couldn't find anything that fixed it. Perhaps someone can shed some light on this?

**Comment by equinusocio** [comment]
Because on OS X the inactive tab have a transparent rgba white color that windows doesn't support.

**Comment by JTallis** [comment]
Oh, wow. How would you set the inactive text per accent? It's a real downer that Windows doesn't support this.

**Comment by equinusocio** [comment]
```json
  {
    "class": "tab_label",
    "fg": [84, 110, 122, 255],
    "shadow_color": [255, 255, 255, 0],
    "shadow_offset": [0, 0],
    "font.size": 11,
    "font.italic": false,
    "font.bold": false
  },

    // Tab selected label color

  {
    "class": "tab_label",
    "parents": [{"class": "tab_control", "attributes": ["selected"]}],
    "fg": [255, 255, 255, 255],
    "shadow_color": [255, 255, 255, 0],
    "shadow_offset": [0, 0]
  },
```
