### ISSUE TITLE
Missing text.cmdline and keyword.cmdline selectors

### ISSUE THREAD

**Issue by chrisgeo** [equinusocio/material-theme#758]
I'm not entirely familiar with SublimeText Development, but if anyone can point me to how I can update this, I'd gladly make a PR.

**Comment by equinusocio** [comment]
Can you paste some snippets?

**Comment by chrisgeo** [comment]
Sure, this is the bar: 
![image](https://cloud.githubusercontent.com/assets/216250/14743034/395484e0-0854-11e6-9fb2-0846c01eae95.png)

It's used in some plugins, like [Vintageous.](https://github.com/guillermooo/Vintageous/blob/master/VintageousEx%20Cmdline.tmLanguage)

The bar is there, it just need a background to standout with the selector: `text.cmdline keyword.cmdline`

**Comment by equinusocio** [comment]
@chrisgeo Can you try with the next release?

**Comment by chrisgeo** [comment]
@equinusocio It's showing the commandline now, the font-color is just missing:

![image](https://cloud.githubusercontent.com/assets/216250/14832101/585f8f36-0bad-11e6-930e-297490424080.png)

**Comment by equinusocio** [comment]
Have you tried to grab up the field bar? Check https://github.com/equinusocio/material-theme#known-issues

**Comment by chrisgeo** [comment]
Ah @equinusocio - that does it. I was used to other themes automatically showing it.

Thanks for your work and help!

**Comment by equinusocio** [comment]
@chrisgeo It's a Sublime Text bug that fail to recalculate the window bottom panel when you use a theme that drastically change space and padding.
