### ISSUE TITLE
The input box on the bottom left is invisible when creating a file/folder from the sidebar

### ISSUE THREAD

**Issue by Danappelxx** [equinusocio/material-theme#76]
It still works, but you can't see what you're typing (text is invisible, too).

**Comment by Revod** [comment]
see the [#18](https://github.com/equinusocio/material-theme/issues/18) , resize the rename panel once by dragging the top edge and then restart twice sublime text

**Comment by Danappelxx** [comment]
That fixed it, thanks! I would add it to the readme though (since it seems like I'm not the only one with this question).
