### ISSUE TITLE
not visible Remane input

### ISSUE THREAD

**Issue by retyui** [equinusocio/material-theme#760]
**I can not see the field to rename**

![step 1](https://pp.vk.me/c636217/v636217915/267c/xDe74MQ2S24.jpg)
![step 2](https://pp.vk.me/c636217/v636217915/2675/3SmxVe0Eyto.jpg)

**Comment by cspeer** [comment]
I got the same problem +1

**Comment by equinusocio** [comment]
👍 read the README file and search for a similiar issue. #731
