### ISSUE TITLE
Caret/cursor does not change colour with theme

### ISSUE THREAD

**Issue by JemarJones** [equinusocio/material-theme#763]
The caret/cursor does not seem to change colour with the theme. I for example have the following set:

```json
"material_theme_accent_blue": true
```
Yet my cursor remains a yellow/orange colour.

Is there a setting i have to set to change the colour to match the theme, or how would i accomplish this?

**Comment by equinusocio** [comment]
The caret color is defined inside the color schemes, and these files doesn't allow conditional settings. You have to change it manually by overwriting the theme rules.
