### ISSUE TITLE
Sublime Text Build 3111/3110/3103 issue (color-scheme won't show)

### ISSUE THREAD

**Issue by benfrain** [equinusocio/material-theme#764]
Unsure if this is a problem with Material theme or dev builds of Sublime Text.

I have the following settings: 

````
"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
"theme": "Material-Theme-Darker.sublime-theme"
````

But the color-scheme is not loading (Tabs and the theme itself seem fine). Here is the console output:

````
startup, version: 3103 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/benfrain/Library/Application Support/Sublime Text 3/Packages
state path: /Users/benfrain/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/benfrain/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Markdown", "SublimeLinter-jshint", "Vintage"]
generating syntax summary
generating meta info summary
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png
````

Would that asset (at the end of that output) be causing the issue?

BTW - thanks for the amazing theme :)

**Comment by equinusocio** [comment]
The theme should be active even with this error. You used Package Control?

**Comment by benfrain** [comment]
Yes. Also tried removing and re-installing via package control

**Comment by equinusocio** [comment]
Can you try to remove the theme and then manually reinstall from the repo? (Remember to rename the folder by removing the branch suffix)

**Comment by benfrain** [comment]
Sure. Will try in the morning and report back. Thanks.

**Comment by benfrain** [comment]
Success 👍 

I had a look in the existing folder before removing and it only had the 'schemes' folder with a Material-Theme-Darker.tmTheme file inside. Weird. No idea what had happened but I'm back up and running. Thanks for the help.

**Comment by SecureCloud-biz** [comment]
I get same error..
`Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png`

Just for the record, inside the: ( .sublime-package & this Repo)
`/Material Theme/assets/darker/`
there is no `overlay_bar_horizontal.png` file

**Comment by SecureCloud-biz** [comment]
also, I see this.. using Sublime Text 3 (3143) newest

`Errors parsing theme:`
**`icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility`**
`Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png`

**Comment by pdbits** [comment]
@SecureCloud-biz 

You can solve the opacity issue with the following fix. Just remember to do that for each and every theme file in the mentioned folder to ensure proper working.

[https://github.com/equinusocio/material-theme/issues/1183#issuecomment-329366290](url)
