### ISSUE TITLE
Support the TodoReview plugin for sublime

### ISSUE THREAD

**Issue by heavybeard** [equinusocio/material-theme#766]
referred to https://github.com/equinusocio/material-theme/issues/605

May I suggest to support the plugin TodoReview (here https://packagecontrol.io/packages/TodoReview)

Now the colors do not help reading.
![image](https://cloud.githubusercontent.com/assets/12038447/14736109/314f9e80-0875-11e6-843d-b05dc29b754b.png)

But with the Makefile Highlight color (with some fixes) should work
(I would prefer a Markdown color base solution)
![image](https://cloud.githubusercontent.com/assets/12038447/14736524/ea6f7226-0877-11e6-9da9-ff89fb845633.png)

Numerical order - path to file - the TODO line number - the TODO text

@equinusocio Do you think is possible to implement it?

**Comment by equinusocio** [comment]
Not at the moment, the only scope provided from this package is `text.todo-list entity.name.function`, is the line number and is the only element i can customize. Note that this package doesn't support Sublime Text 3.

**Comment by heavybeard** [comment]
Ok thank you!
