### ISSUE TITLE
Disable Italic style on code comments (v2.1.2)

### ISSUE THREAD

**Issue by pyk** [equinusocio/material-theme#769]
How to disable this behaviour on `v2.1.2` ?

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/710#issuecomment-192781012

**Comment by pyk** [comment]
Ok, thanks @equinusocio 👍

**Comment by JayBizzle** [comment]
I definitely need to switch this back 😒

**Comment by equinusocio** [comment]
@JayBizzle
![Just Do It](https://m.popkey.co/ca8f87/AoYjv_f-maxage-0.gif)

**Comment by JayBizzle** [comment]
😆

**Comment by rcrocombe** [comment]
Uuugh, I hate italic comments! Now I have to maintain my own version of `tmTheme`. Is there a way to just change the comment style and not copy the whole file into my override folder so I don't have to do it every time the "official" theme updates?

**Comment by equinusocio** [comment]
Make a `Material Theme` folder in the User packages, inside the packages directory. Put your files here with the same name and only the changed rules. Other files and rules will be pulled from the updates.

**Comment by rcrocombe** [comment]
Thanks for your help. I can't seem to put in single rules though, as it will corrupt the rest of the theme. Am it putting the file in the right place? `Packages/Material Theme`, or should it be `Packages/User/Material Theme`?

**Comment by kleinfreund** [comment]
> Thanks for your help. I can't seem to put in single rules though, as it will corrupt the rest of the theme. Am it putting the file in the right place? Packages/Material Theme, or should it be Packages/User/Material Theme?

@rcrocombe I experience the same. This is what I did:

1. In Sublime, go to *Preferences > Browse Packages...* (on Windows, this is the directory `C:\Program Files\Sublime Text 3\Packages`)
2. Create a directory `Material Theme`
3. In there, create a directory `schemes`
4. In there, create the file `Material-Theme[x].tmTheme` where `[x]` is either blank for the standard style or `-Lighter` or `-Darker` for the respective styles
5. Edit the file accordingly (With *PackageResourceViewer*, *Open Resource > Material Theme > schemes/ > Material-Theme[x].tmTheme* you can edit the file Sublime currently uses)

This however overrides the complete file, even if you only specify this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>author</key>
    <string>Mattia Astorino</string>
    <key>colorSpaceName</key>
    <string>sRGB</string>
    <key>name</key>
    <string>Material-Theme</string>
    <key>semanticClass</key>
    <string>material.theme.dark</string>
    <key>settings</key>
    <array>
        <dict>
            <key>name</key>
            <string>Comments</string>
            <key>scope</key>
            <string>comment, punctuation.definition.comment</string>
            <key>settings</key>
            <dict>
                <key>fontStyle</key>
                <string>normal</string>
                <key>foreground</key>
                <string>#546E7A</string>
            </dict>
        </dict>
    </array>
    <key>uuid</key>
    <string>133d1250-19c6-4565-bc93-b37fd36f7fc9</string>
</dict>
</plist>
```

Renaming the `Material Theme` directory I created results in the whole override not working anymore. What can we do to override only single settings like comment font styles, @equinusocio?
