### ISSUE TITLE
Red and green icon error

### ISSUE THREAD

**Issue by ThomasHoadley** [equinusocio/material-theme#771]
Hi there,

I'm loving the theme and look forward to using it but I was wondering if you had any idea how to fix the green/red icons as you can see in the screen shot?

https://www.dropbox.com/s/z0qt0ldcn6hj19f/Screenshot%202016-04-27%2012.18.38.png?dl=0

Very random!

**Comment by concept-core** [comment]
Did you make sure that you restarted sublime ?
I had the same issue due a update that just activated.

**Comment by ThomasHoadley** [comment]
I did indeed but unfortunately restarting didn't work for me!

**Comment by concept-core** [comment]
could you try to reset the user config again ?
Otherwise delete the theme and reinstall ?

**Comment by ThomasHoadley** [comment]
Still no luck unfortunately!

**Comment by equinusocio** [comment]
You have some error in you preferences. I think you missed something during installation.
- Paste you preference
- Sublime Text version and build
- Manual or Package Control installation?
