### ISSUE TITLE
Lost internet connection during an update; Theme corrupted

### ISSUE THREAD

**Issue by jcontonio** [equinusocio/material-theme#772]
I find the auto-updating of this package a bit annoying. Is there a way to disable that in my preferences? While working at a coffee shop with spotty internet yesterday, the theme was mid-update and then failed:

<img width="1552" alt="screen shot 2016-04-27 at 8 51 41 am" src="https://cloud.githubusercontent.com/assets/2809/14858584/7b1d0550-0c55-11e6-9435-67582deeb6af.png">

I am guessing I need to delete the files from the drive and re-install. I've tried switching themes, restarting Sublime, etc...but Material-theme is still corrupted.

**Comment by equinusocio** [comment]
After closing Sublime Text, go to the packages folder and manually delete the material theme folder from the Installed packages directory.

**Comment by jcontonio** [comment]
I just started over with a sublime install and everything is fine, but I'd say it still doesn't solve my issue...the issue being, I'd like this package to stop auto-updating as I am getting interrupted by it often while working, and usually have flakey internet.

**Comment by equinusocio** [comment]
I think you have some problem with package control. You can disable auto update through Package Control.

**Comment by jcontonio** [comment]
Woo thanks! Didn't even think about that...sorry.
