### ISSUE TITLE
Update Jade (now Pug) icon and file association

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/material-theme#773]
Jade will become Pug (more info [here](https://github.com/pugjs/pug/issues/2184)). We have to update the file icon and the file association (i think will be `.pug`).

Resources:

https://github.com/pugjs/pug-logo
https://github.com/pugjs/pug/issues/2189#issuecomment-205863725

**Comment by equinusocio** [comment]
In the meantime, here are the instructions to make sure your syntax highlighter continues to work with *.pug files:

Preferences » Browse Packages
Open User folder
Edit Jade.sublime-settings with the following contents:

{
  "extensions":
  [
    "pug"
  ]
}
Restart SublimeText

**Comment by JasinYip** [comment]
Maybe a new Pug icon is better? Because Pug is now using a pug as the logo, not rabbit anymore...

![](https://avatars2.githubusercontent.com/u/9338635?v=3&s=200)

**Comment by JasinYip** [comment]
![image](https://cloud.githubusercontent.com/assets/7105264/15491353/2576fb30-21a2-11e6-9434-bbf89f807e41.png)

It looks is still a rabbit? It's that the question I met only....?
