### ISSUE TITLE
No Italic in dark color schemes

### ISSUE THREAD

**Issue by valeryan** [equinusocio/material-theme#774]
The light themes are all showing italic font but the darker variants are not. Do you intend to also add the italic to comments in the Material-Theme-Darker and Material-Theme-Darker-OceanicNext schemes?

**Comment by aronstrandberg** [comment]
Is there a way to disable this? I very much do not want italic comments. @equinusocio

**Comment by valeryan** [comment]
@aronstrandberg you can download the color scheme you use and put it in your package folder , the remove the lines that reference font style italic. Maybe put it in the themes default folder. Then select your revised color scheme in preferences.

**Comment by equinusocio** [comment]
@aronstrandberg #769
https://github.com/equinusocio/material-theme/issues/769#issuecomment-214997944
