### ISSUE TITLE
Input text to rename a file doesn't appear

### ISSUE THREAD

**Issue by mapy69003** [equinusocio/material-theme#778]
Hello,

Sometime I need to rename a file. I click on rename, but the input text doesn't appear and I have to type blindly.

Is there a fix ?
Thank you for considering my issue.

Yoann

**Comment by mapy69003** [comment]
I just found how to resize it.

**Comment by jDeppen** [comment]
Same here. For anyone else with this issue, bring your cursor down near the bottom of the sidebar until you get the resize cursor, then click and drag up.

**Comment by equinusocio** [comment]
Or simply read the README file :)
