### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by iamhexcoder** [equinusocio/material-theme#780]
Love this theme, but the recent update has a whole lot of italics going on...scss classes, selectors, etc. Is there a way to disable this? It's quite a change from how things started.

**Comment by equinusocio** [comment]
Wait for the next release

**Comment by limenet** [comment]
@equinusocio I'm now using v2.1.3 and I still have comments and HTML attributes in italics. Is there any way to disable it?

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/769#issuecomment-214997944

**Comment by iamhexcoder** [comment]
Just got the update - thanks!!

👍
