### ISSUE TITLE
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png

### ISSUE THREAD

**Issue by incognitoms** [equinusocio/material-theme#781]
Console throws error: "Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png"

This "overlay_bar_horizontal.png" is missing from folder assets/darker here at github as well. The file is simply not there.

**Comment by equinusocio** [comment]
Are you on Windows?

**Comment by incognitoms** [comment]
No, OS X 10.11
