### ISSUE TITLE
Option to make find/replace bar smaller

### ISSUE THREAD

**Issue by evenfrost** [equinusocio/material-theme#784]
As for me, these custom paddings in bottom bar are way too big. There may be an option to reduce its size like [Predawn guys did](https://github.com/jamiewilson/predawn#find--replace-small-size). And probably it'll be a fix for nasty #67.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme#theme-options

**Comment by evenfrost** [comment]
@equinusocio There is no such option. And I double-checked it. And in case I missed anything I've just copypasted and saved all the options with values set to `true`, same result:
![image](http://i.imgur.com/1qCPOP2.png)
Predawn with `predawn_findreplace_small` set to `true`:
![image](https://camo.githubusercontent.com/ed1ad51084aaca4bd2d59c3f7cfbc77f94a58f6e/687474703a2f2f692e696d6775722e636f6d2f6e4d4d753541442e706e67)

**Comment by equinusocio** [comment]
You can use just this `"material_theme_compact_panel": true`.  If isn't enough you have to edit your copy of the theme.
