### ISSUE TITLE
Build Results and Console have no visual differentiation

### ISSUE THREAD

**Issue by nvenk** [equinusocio/material-theme#786]
This is such a great theme!! and I can't even look at sublime without it now.

I recently noticed that build results and console have no visual differentiation from the main window. It would be really helpful to have build results in a different color, or have a divider.

Cheers

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme#theme-options

`"material_theme_panel_separator"          : true , // show bottom panel separator`
