### ISSUE TITLE
Fix colors on mediaquery

### ISSUE THREAD

**Issue by heavybeard** [equinusocio/material-theme#787]
In mediaqueries started with a tag (not a class, not an id) the selectors colors have errors

![color-error](https://cloud.githubusercontent.com/assets/12038447/14977770/4b565ca6-1117-11e6-9ebd-5bf0f2fe165c.PNG)

![no-error](https://cloud.githubusercontent.com/assets/12038447/14977767/483e60ae-1117-11e6-8082-a8e31f7319ac.PNG)

**Comment by equinusocio** [comment]
Tried with CSS syntax and SASS Package ([SASS textmate-bundle](https://github.com/nathos/sass-textmate-bundle)). No errors.

<img width="318" alt="screen shot 2016-05-03 at 10 34 43" src="https://cloud.githubusercontent.com/assets/10454741/14978236/ae8f72b4-111a-11e6-9f99-61cd52505c29.png">
<img width="329" alt="screen shot 2016-05-03 at 10 34 48" src="https://cloud.githubusercontent.com/assets/10454741/14978237/ae94cf48-111a-11e6-8902-b57f4371cd4c.png">

**Comment by heavybeard** [comment]
The problem is with the CSS3 package https://github.com/y0ssar1an/CSS3

![image](https://cloud.githubusercontent.com/assets/12038447/14995182/bc2315a8-1173-11e6-8309-dffcfd183522.png)

**Comment by equinusocio** [comment]
@heavybeard i can't support a lot of third-party packages, and i think you don't need this package.
