### ISSUE TITLE
CSS showing as LESS

### ISSUE THREAD

**Issue by stevieg83** [equinusocio/material-theme#788]
CSS file icons are showing as LESS icons.

**Comment by equinusocio** [comment]
<img width="276" alt="screen shot 2016-05-03 at 15 08 48" src="https://cloud.githubusercontent.com/assets/10454741/14984038/f94dfb2e-1140-11e6-9143-01bc0439adc1.png">

What ST build are you using?

**Comment by ClementParis016** [comment]
I have the same issue as @stevieg83, using ST3 Build 3103 and the latest Material Theme update. CSS files got a LESS icon associated to them.

**Comment by equinusocio** [comment]
Try to remove and reinstall the LESS package.

**Comment by equinusocio** [comment]
#713 #654 #600

**Comment by ClementParis016** [comment]
Great, thanks for the fix ;)

**Comment by NauxChen** [comment]
thanks, resolve my problem;
Manual associate the css syntax to .css files
> View -> Syntax -> Open all with current extension as ...
