### ISSUE TITLE
Tab size

### ISSUE THREAD

**Issue by LucianKaltz** [equinusocio/material-theme#79]
It's really awesome!

However the tab size looks a little bit large on the screen. Would love to see if in settings tab size could be adjusted.

Thanks!

**Comment by nicholasxjy** [comment]
+1

**Comment by enygmatik** [comment]
+1

**Comment by octopitus** [comment]
+1

**Comment by llaraujo** [comment]
:+1:

**Comment by paulmist** [comment]
+1

**Comment by r3volution11** [comment]
:+1:
