### ISSUE TITLE
HTML / JSX attributes changed color in v2.1.3

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#791]
I received an update and noticed one change (intentional or not)

<img width="764" alt="screenshot 2016-05-04 11 36 39" src="https://cloud.githubusercontent.com/assets/304929/15010479/83abce44-11ec-11e6-90a3-0ceb5ff91bcd.png">

All attributes are light-blue now. Previously it was light yellow (that I personally liked much more :)

Regression?

**Comment by equinusocio** [comment]
@jeffijoe says that the html attributes inside jsx are white (and is also what i see). (See https://github.com/equinusocio/material-theme/issues/789) 

Check https://github.com/equinusocio/material-theme/commit/ab5fd7e75774b47bc3d3f795f4e8221cdd0208c7, jsx will look like this in the next 2.1.4 release:

<img width="943" alt="screen shot 2016-05-04 at 12 09 32" src="https://cloud.githubusercontent.com/assets/10454741/15011303/64e8cfb6-11f1-11e6-9525-6edc909a523a.png">

**Comment by alexbeletsky** [comment]
Thanks @equinusocio, 2.1.4 looks awesome, looking forward to a next release.

PS. What font do you use? it looks so cool :)

** Using Javascript Babel package (as well)

**Comment by equinusocio** [comment]
@alexbeletsky `Operator Mono`

**Comment by alexbeletsky** [comment]
What I see more, it's kind of inconsitent.. Sometimes JSX attributes are white, sometimes they are light blue (as in image above).

**Comment by equinusocio** [comment]
I think you have some problem with your package and/or Sublime Linter cache (if you use it)
