### ISSUE TITLE
Confusing coloring of the storage scope

### ISSUE THREAD

**Issue by lhecker** [equinusocio/material-theme#793]
Currently the `storage` scope has the same color as those of keywords. This leads to hard to read code in some languages (like Rust), like this: http://i.imgur.com/itr5HM0.png.

If you modify [this line](https://github.com/equinusocio/material-theme/blob/0acd954fcd2d2550e2d17f7ffe8cd97cf1390ec8/schemes/OLD/Material-Theme-Darker.tmTheme#L187) to something different it gets much better though: http://i.imgur.com/W6fZ1py.png (this uses `#82AAFF`).

Since I'm not a designer (and thus don't know which colors to use) I refrained from doing a PR right away and opened this issue instead.

**Comment by equinusocio** [comment]
Open a PR and choose a color that have a nice contrast with the dark themes (like the one you choose) and for the light scheme choose another color. 👍

**Comment by equinusocio** [comment]
@lhecker can you add your snippets for a test?

**Comment by lhecker** [comment]
Ah right I forgot about this issue - I'm sorry. I'm currently away and thus can't really develop anything right now except for the most basic stuff.

**Comment by equinusocio** [comment]
Check the latest update please
