### ISSUE TITLE
HTML tags containing a hyphen are coloured differently

### ISSUE THREAD

**Issue by fiznool** [equinusocio/material-theme#795]
For example:

![screenshot from 2016-05-05 21-29-14](https://cloud.githubusercontent.com/assets/820863/15056246/84559966-1308-11e6-9bad-a1144db38855.png)

I think I would expect `ion-view` to be all red, non-italicised.

**Comment by equinusocio** [comment]
Provide more details: 
- Sublime Text build
- syntax and Package used (in you screenshot)

**Comment by fiznool** [comment]
ST3, build 3103 (Ubuntu 15.10)

HTML syntax

How do I find out which version of this package I have installed? I installed it through Package Control.

**Comment by equinusocio** [comment]
<img width="679" alt="screen shot 2016-05-08 at 21 48 01" src="https://cloud.githubusercontent.com/assets/10454741/15100005/91395e1e-1566-11e6-93e1-1d0b3ce6c51c.png">

**Comment by fiznool** [comment]
Ok, I didn't know that, thanks, I'll try with a different syntax.

**Comment by fiznool** [comment]
I fixed this by using the [HTML Extended](https://github.com/orizens/html-extended) plugin, thanks for the pointer in the right direction.

**Comment by equinusocio** [comment]
Nice 👍🏻
