### ISSUE TITLE
Update Frequency

### ISSUE THREAD

**Issue by HendrikPetertje** [equinusocio/material-theme#796]
First of all, Your theme is just awesome man! seriously your material colors have been shining on my desktop for months now and I still love them!
But, small "luxury" problem here. 

You are making a lot of updates all the time. most of time I'm just working when your theme update kicks in and I need to restart all my work. Bit of a hassle. I know you do a lot of small fixes, but could you try to bundle them or use a version system where you merge changes back to a main branch? come with updates in say once per 2 days or even 5. 

Nice place to get started with a version management system is [Git Flow](http://danielkummer.github.io/git-flow-cheatsheet/). I'm not saying this is a defined standard among sublime plugins, but it's used a lot. 

Thanks again for your theme man, it rocks!

**Comment by dingo-d** [comment]
I think you can disable updates in the command panel.

**Comment by equinusocio** [comment]
Git-flow isn't related to the update frequency. If there is bugs i fix them asap (beyond the used versioning).

As told by @dingo-d you can disable auto updates through Package Control palette and run the update when you want.
