### ISSUE TITLE
Blade filetype icon not showing 

### ISSUE THREAD

**Issue by a1219062954** [equinusocio/material-theme#797]
For .blade.php files, only the PHP filetype icon is showing in the sidebar, not the Blade one. All other filetype icons appear to be working.

**Comment by equinusocio** [comment]
Just install [Laravel Blade Highlighter](https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter)
<img width="452" alt="screen shot 2016-05-08 at 21 52 31" src="https://cloud.githubusercontent.com/assets/10454741/15100035/365f7694-1567-11e6-9975-c0129d9f239a.png">

Or this:
https://github.com/Medalink/laravel-blade

**Comment by a1219062954** [comment]
Thanks ！I got it .
