### ISSUE TITLE
Italic Comments / html attributes not working

### ISSUE THREAD

**Issue by apertureless** [equinusocio/material-theme#798]
Hi, I saw in the 2.1.2 / 2.1.3 release notes, that italic styles are added to comments and html attributes, which is cool, because I recently switched to the operator font.

However, it seems not to be working for me. Code comments and html attributes are still regular style for me.

Sublime 3 / 3103 - mac osx

**Comment by apertureless** [comment]
Fixed it myself. Problem was a corrupt update. Reinstall fixed it

**Comment by santigarcor** [comment]
I'm tryin to use that operator font on ubuntu but the italic doesn't work do you know why?

**Comment by apertureless** [comment]
@santigarcor depends on the exact font familiy you are using.
There is operator and operator mono and the "ScreenSmart" types (Operator SSm, Operator Mono SSm)

Operator Mono is working for me. And Operator Mono SSm should be working, too.
Whats not working is Operator SSm. 

So check what exact family you have. And check if you have the complete family, with italics.

**Comment by luokuning** [comment]
@santigarcor Hello, this is my Operator font:
```
├── Operator-Black.otf
├── Operator-BlackItalic.otf
├── Operator-Bold.otf
├── Operator-BoldItalic.otf
├── Operator-Book.otf
├── Operator-BookItalic.otf
├── Operator-Light.otf
├── Operator-LightItalic.otf
├── Operator-Medium.otf
└── Operator-MediumItalic.otf
```
But comments and html attributes are not italic style, How can I fix that? Thanks

```
- Sublime Text:   3126
- Platform:   osx
- Arch:   x64
- Theme:   4.0.0
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8
```
