### ISSUE TITLE
Update has broken the theme?

### ISSUE THREAD

**Issue by mrwigster** [equinusocio/material-theme#799]
Getting this error message after latest theme update:
Error loading colour scheme Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme: Error parsing plist xml: expected = in file Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme on line: 311

**Comment by jbscarbrough** [comment]
Same here

**Comment by mattmurtaugh** [comment]
Same as well

**Comment by bloqhead** [comment]
I was JUST about to post this issue. +1. Happening to me on Linux Mint
![selection_006](https://cloud.githubusercontent.com/assets/349388/15117842/7c0608be-15d7-11e6-8caa-97e86068e7d9.png)
.

**Comment by jonhainstock** [comment]
Same here.

**Comment by ronghoward** [comment]
Same issue..

**Comment by bloqhead** [comment]
For those that want to get around this temporarily, you can select one of the "old" themes:
![menu_007](https://cloud.githubusercontent.com/assets/349388/15117917/d894a518-15d7-11e6-8b19-e3dec2cbcd9f.png)

**Comment by mrwigster** [comment]
As a temporary fix I've found you can use these as the theme settings in your user/Preferences.sublime-settings files

"theme": "Material-Theme-Darker.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/OLD/Material-Theme-Darker.tmTheme",

**Comment by Arty2** [comment]
Confirming, same line as the original post.

**Comment by bloqhead** [comment]
@mrwigster you are fast! Haha.

**Comment by nygdjs** [comment]
As I found, the issue is because there is a "false" merge in the `Material-Theme-Darker.tmTheme` file (at least, that was the active one for me) on line 311:
```
<<<<<<< HEAD
      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html</string>
=======
      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html, source.js meta.jsx.js entity.other.attribute-name.jsx</string>
>>>>>>> develop
```

**Comment by mrwigster** [comment]
@bloqhead I might be fast.. but apparently I'm 12 seconds slower than you ;)!

**Comment by bloqhead** [comment]
@mrwigster good point.

**Comment by Kzinglzy** [comment]
same here

**Comment by alexbet** [comment]
+1. The update rendered the theme completely unusable.

**Comment by hamstu** [comment]
@nygdjs Yup — that's the cause for me too. Thanks for the quick workaround @mrwigster!

**Comment by stefanledin** [comment]
Same here. Thanks for the workaround @mrwigster :)

**Comment by vdaluz** [comment]
+1. Thanks for the workaround

**Comment by agarzon** [comment]
I have the same issue.

**Comment by equinusocio** [comment]
Fix in 2.1.5

**Comment by agarzon** [comment]
@equinusocio 

```
Package Control

There are no packages ready for upgrade
```

I've tried also with uninstall/install, still getting 2.1.4

Ideas?

**Comment by DrewDouglass** [comment]
Looks like the packagecontrol.io repo was updated recently. Thank you, working now.
