### ISSUE TITLE
visual issues

### ISSUE THREAD

**Issue by chrisdrackett** [equinusocio/material-theme#8]
Not sure if I did something wrong, but after install I get a lot of strange visual artifacts:

http://cl.ly/image/3p14070N3m1L

**Comment by Revod** [comment]
you change the config in  Preferences > Settings - User with this?
```
{
    "theme": "Material-Theme.sublime-theme",
    "color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",
}
```

**Comment by superguigui** [comment]
Sometimes just restarting Sublime will do the trick.
Also to pinpoint the problem you can try opening the sublime text console.

**Comment by chrisdrackett** [comment]
@Revod those are the settings I'm using and I've tried restarting. I'll check out the console

**Comment by Revod** [comment]
@chrisdrackett I Used the config, restart Sublime and the theme are ready

**Comment by ojosdegris** [comment]
Restarting sublime did the trick. Absolutely LOVE the theme.

**Comment by ahmed-h** [comment]
Any idea why I'm getting this weird visual problem?

![screen shot 2015-06-03 at 11 47 39 pm](https://cloud.githubusercontent.com/assets/1876413/7968558/057aac56-0a4b-11e5-817f-1a8157d3a558.png)

**Comment by equinusocio** [comment]
@ahmed-h you've restarted Sublime Text?

**Comment by ahmed-h** [comment]
Ah that worked! Thank you!
