### ISSUE TITLE
Icons not working and color scheme wrong

### ISSUE THREAD

**Issue by Twisterking** [equinusocio/material-theme#80]
Hi there!

Thanks for this awesome theme! But unfortunaltey I am obviously doing something wrong.
I installed it via package control (also tried to copy it into the packages folder) but still ...
* the icons do not show up and
* the color scheme is wrong.

![bildschirmfoto 2015-06-14 um 11 24 52](https://cloud.githubusercontent.com/assets/4247268/8148034/2df01262-1288-11e5-8b33-b781c184cd2e.png)

my preferences:
```
{
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "Material-Theme.sublime-theme",
	//"theme": "Material-Theme-Darker.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"overlay_scroll_bars": "enabled",
	"line_padding_top": 3,
	"line_padding_bottom": 3,
	"font_options": [ "gray_antialias" ], // On retina Mac
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"font_face": "Fira Code"
}
```

Can you help?

Thanks, P

**Comment by equinusocio** [comment]
You use Sublime Text 3 build 3065+?

**Comment by Twisterking** [comment]
Oh thank you very much! Updated and works now! :+1: 
About the color scheme - thanks! Was confused because of the screenshots you provided. Might will edit it a bit - I think the colors are a bit too similar to provide real nice context/syntax highlighting - but that's just my 2 cents! :-)
