### ISSUE TITLE
Error loading colour scheme Material-Theme.tmTheme

### ISSUE THREAD

**Issue by artPlusPlus** [equinusocio/material-theme#800]
Opened sublime just now and got this error:

Error loading colour scheme Packages/Material Theme/schemes/Material-Theme.tmTheme: Error parsing plist xml: expected = in file Packages/Material Theme/schemes/Material-Theme.tmTheme on line: 299

This seemed to occur while updating. Usually, a changelog gets displayed, but that did not come up this time.

I tried closing/reopening sublime, same error.

I am using Sublime 3, Stable Channel, Build 3103 on Windows 7.

My user prefs:

```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"draw_minimap_border": true,
	"draw_white_space": "selection",
	"font_face": "Source Code Pro Medium",
	"font_size": 13,
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_orange": true,
	"overlay_scroll_bars": 3,
	"theme": "Default.sublime-theme",
	"trim_trailing_white_space_on_save": true,
	"word_wrap": false
}
```

**Comment by artPlusPlus** [comment]
Duplicate of #799

**Comment by equinusocio** [comment]
Use develop branch or wait for 2.1.5
