### ISSUE TITLE
There is a Conflict comitted.

### ISSUE THREAD

**Issue by sanjibperk** [equinusocio/material-theme#801]
Please check in master branch material-theme/schemes/Material-Theme.tmTheme

Line number 298

 HEAD
      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html</string>

      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html, source.js meta.jsx.js entity.other.attribute-name.jsx</string>

 develop

**Comment by matteo-webdev** [comment]
this is the same of this issue: https://github.com/equinusocio/material-theme/issues/799
take a look at that issue, there is also a temporary workaround

**Comment by sanjibperk** [comment]
Yup! Thanks! Actually what I tried was to download the develop branch and used it instead. It worked.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/commit/55875dff6937664a289882fb3019730aa155c4e4
