### ISSUE TITLE
update v2.1.4 color scheme seems to have an issue

### ISSUE THREAD

**Issue by mohamadnorouzi20** [equinusocio/material-theme#802]
![capture](https://cloud.githubusercontent.com/assets/8435784/15119043/2c3dc34c-1624-11e6-87c8-e3ea85f4ffc1.PNG)

**Comment by matteo-webdev** [comment]
this is the same of this issue: https://github.com/equinusocio/material-theme/issues/799
take a look at that issue, there is also a temporary workaround

**Comment by jBOKA** [comment]
+1
it seems to be a simple git merge conflict

**Comment by AddoSolutions** [comment]
:1

**Comment by equinusocio** [comment]
Fixed in 2.1.5
