### ISSUE TITLE
Latest update error

### ISSUE THREAD

**Issue by fitb-greg** [equinusocio/material-theme#804]
I am not sure what the problem is, but the theme updated and now sublime is saying this: https://dl.dropboxusercontent.com/s/tr7o48xke1xkl3e/2016-05-09%20at%2012.24%20PM.jpg and you can tell that the colors aren't loading in the code pane.

**Comment by elllias** [comment]
I've got the same issue.

**Comment by worm2fed** [comment]
Hey guys, there are an error in line 311 in file schemes/Material-Theme-Darker.tmTheme (for me)

U should edit this file (it located in ~/.config/sublime-text-3/Installed Packages/Material Theme.sublime-package. U have to remove HEAD or develop lines with simbols '<' and '='
```<<<<<<< HEAD
      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html</string>
=======
      <string>entity.other.attribute-name.html, entity.other.attribute-name.class.html, meta.tag.any.html entity.other.attribute-name.html, text.html.basic meta.tag.other.html entity.other.attribute-name.html, source.js meta.jsx.js entity.other.attribute-name.jsx</string>
>>>>>>> develop
```

**Comment by equinusocio** [comment]
2.1.5 is coming
