### ISSUE TITLE
Error parsing plist xml: expected = in file Packages/Material Theme/schemes/Material-Theme.tmTheme on line: 299

### ISSUE THREAD

**Issue by OscaRoa** [equinusocio/material-theme#805]
This morning when the package updated sublime text threw that error and I'm unable to load the color scheme.

Any ideas on how to fix this?

**Comment by christiannaths** [comment]
Looks like the package was deployed with merge conflicts committed 

https://github.com/equinusocio/material-theme/commit/55875dff6937664a289882fb3019730aa155c4e4

**Comment by elstratego** [comment]
Had the same issue so I switched to Prefs/Color Scheme/Material Theme/Schemes/OLD/Material Theme while it gets worked out.

**Comment by equinusocio** [comment]
2.1.5 is coming
