### ISSUE TITLE
block cursor color on Vintage mode

### ISSUE THREAD

**Issue by WDZThorn** [equinusocio/material-theme#807]
default color 
![647149cd-1c21-4b30-922c-7d28ff5b31f2](https://cloud.githubusercontent.com/assets/3402811/15137963/51fb7bf6-16bf-11e6-8341-f51fbe1829a0.png)
and i cant recognize it.
how to change it without modify theme file?

**Comment by equinusocio** [comment]
Try with this preferences:
```json
    // Valid values are "smooth", "phase", "blink" and "solid".
    "caret_style": "smooth",

    // These settings control the size of the caret
    "caret_extra_top": 0,
    "caret_extra_bottom": 0,
    "caret_extra_width": 0,
```

**Comment by emecell** [comment]
Just posting here for posterity in how to possibly get the whole caret the same yellow or to add more contrast to the blinking cursor. Using https://github.com/skuroda/PackageResourceViewer you can edit the material theme color scheme and looking for the selection color setting e.g.:
```
                <key>selection</key>
                <string>#FFCC00</string>
```
This is currently set to a slight grey but if you switch it to the caret color (`#FFCC00`), it will blink the whole cursor the same yellow. Unfortunately the speed in which the block and the caret blink are not the same so you see a little visual artifact. Ignoring that, I find it easier to set the selection color to something more contrasted which helps me find the block cursor faster. Hope this helps anyone else seeing this ticket!
