### ISSUE TITLE
Find in files overflow

### ISSUE THREAD

**Issue by johman10** [equinusocio/material-theme#81]
Wow! Thank you so much for this. Really love this theme.

Just one little bug I found was when searching in files (SHIFT+CMD+F). There is some overflow with the bottom bar which makes it impossible to read/change the last input.

![Example](https://cloud.githubusercontent.com/assets/5371454/8148231/8294224a-1292-11e5-94b7-e4b1c3da9478.png)

It would be awesome if you can fix that!

**Comment by equinusocio** [comment]
See #67
