### ISSUE TITLE
Deep-nested JavaScript syntax highlighting bug

### ISSUE THREAD

**Issue by sucrose** [equinusocio/material-theme#813]
![2016-05-11 14_03_34-o__webfoot_ecommerceplatform_devenvironment_vdir_jthomas_src_js_pages_checkout j](https://cloud.githubusercontent.com/assets/5590958/15191205/a5f0226c-1781-11e6-95dd-ebef4666e9b3.png)

**Comment by equinusocio** [comment]
Please provide more details:
-  Sublime Text build
-  Syntax highlight package
- This code snippet

**Comment by gioloi** [comment]
same happens with php in Sublime Text 3 build 3114 (OSX)
![2016-05-14_12-00-12](https://cloud.githubusercontent.com/assets/7725900/15267790/f2534e1c-19cb-11e6-97a9-2c2b17cf6d54.png)

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/813#issuecomment-218698196

**Comment by zdkroot** [comment]
I'm on Sublime 3 build 3114, OSX 10.11. Default php syntax highlighting.

```php
<?php

Route::group(['domain' => 'custom.url'], function() {
    Route::group(['namespace' => 'Namespace'], function() {
        Route::group(['before' => 'auth'], function() {
            Route::group(['prefix' => 'deep-nesting'], function() {
                // Everything in this block is colored the same
                Route::post('url', 'Controller@method');
                Route::post('url', 'Controller@method');
                Route::post('url', 'Controller@method');
                Route::post('url', 'Controller@method');
                Route::post('url', 'Controller@method');
                Route::group(['before' => 'another'], function() {
                    // Partially works?, Strings correct, comments are wrong
                    Route::get('url', 'AnotherController@anotherMethod');
                });
            });
        });
    }); // <--- blue ;
}); // <---- white ;
```

![screen shot 2016-05-19 at 11 47 25](https://cloud.githubusercontent.com/assets/638336/15399911/80c40e7c-1db7-11e6-925c-eeba509ca1e1.png)

Thanks for looking and awesome package. Keep up the good work.

**Comment by sucrose** [comment]
Sublime Text Build 3114 Stable

Settings - User
```
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme"
```

Code Snippet
`(function ($, window, document, undefined) {
    'use strict';
        $checkout.find('#promo').on('click', function (e) {
            $.post('/', function (data) {
                $checkout.find('#promo-code').val('');
                if (data.length) {
                    $orderList.fadeOut(function () {
                        $(this).empty().height(height).addClass('loading').fadeIn(function () {
                            $.get('/' + jt.antiCache(), function (response) {
                                $orderList.fadeOut(function () {
                                    $(this).removeClass('loading').html(response).height('auto').fadeIn();

                                    // Reload promo object
                                    promo = $checkout.find('#promo-data').data('json');

                                    // Promotions
                                    checkPromo();
                                });
                            });
                        });
                    });
                }
            });
        });
})(jQuery, window, document);`

**Comment by gioloi** [comment]
After playing a bit with default sublime text theme and color scheme, I can say that the problem is not related to Material Theme Package, but it is related to the latest build of sublime. This is confirmed by several comments on the support page of sublime. See [https://forum.sublimetext.com/t/build-3114-syntax-highlighting/20226](url)

**Comment by gioloi** [comment]
I confirm, the problem is in latest build of sublime (3114). I have downgraded to build 3103 and now all is working fine. You can find the links to previous version of sublime at this url [https://forum.sublimetext.com/t/how-to-downgrade-bulid-3114-to-build-3103/19972](url)

**Comment by equinusocio** [comment]
Thanks for the investigation

**Comment by Pablocgdev** [comment]
I can confirm this has nothing to do with the theme, just sublime build bug.

**Comment by diegonc** [comment]
No, it's doesn't seem to be Sublime.

With Material Theme

![wmt](http://i.imgur.com/BV9m7IK.png)

Just Sublime

![jst](http://i.imgur.com/eL2jgLc.png)

Code of the examples.
```
_(function () {
    a(function () {
        b(function () {
            c(function () {
                d(function () {
                    e(function () {
                        try {
                            //comment
                            var obj = {};
                            obj.a = "a";
                        } catch (ex) {
                            var str = 'alaal' + f('adljask');
                            return;
                        }
                    });
                });
            });
        });
    });
});
```

**Comment by diegonc** [comment]
BTW, Material Theme without its color scheme works.

![mtwcs](http://i.imgur.com/BuifMTI.png)

**Comment by equinusocio** [comment]
No it doesn't work. Also monokay change the color of the last function and should not be pink. 

My question is, why ST 3103 have no problems with the same material theme version? The only difference is the build.

**Comment by equinusocio** [comment]
Please check https://github.com/equinusocio/material-theme/issues/841
