### ISSUE TITLE
Question about "material_theme_tree_headings"

### ISSUE THREAD

**Issue by victorwpbastos** [equinusocio/material-theme#815]
What this option should do? It seems that it does nothing.

```json
"material_theme_tree_headings" : true
```

**Comment by equinusocio** [comment]
```
// If you use Material Theme - Appbar addon you can use additional settings:
"material_theme_tree_headings"            : true , // Show sidebar headings
```
This work only with Material Theme Appbar package enabled.
![2016-05-12 10 41 16](https://cloud.githubusercontent.com/assets/10454741/15208843/265857ce-182e-11e6-9c73-8adf90c4ad06.gif)

**Comment by victorwpbastos** [comment]
Ok. On Windows nothing happens.

**Comment by equinusocio** [comment]
I can't try this on Window machine, we just wait for a PR

**Comment by jrappen** [comment]
Cannot replicate issue, works fine for me:

* Sublime Text: Build 3113 dev portable on Win 10 Pro x64
* Material Theme: v2.1.6
* Material Theme - Appbar: v1.2.1

**Comment by equinusocio** [comment]
Thanks @jrappen. i think we can consider closed this issue.
