### ISSUE TITLE
Find is hidden by status bar

### ISSUE THREAD

**Issue by admench** [equinusocio/material-theme#817]
Screenshot:
![window_and_package_control_messages_ _dev_jlmmortgages](https://cloud.githubusercontent.com/assets/672916/15209269/1701c23e-1828-11e6-8e52-445517595aa9.gif)

**Comment by admench** [comment]
I see that this is a duplicate of https://github.com/equinusocio/material-theme/issues/67

**Comment by equinusocio** [comment]
And many other

**Comment by admench** [comment]
Apologies! Thanks for a great theme
