### ISSUE TITLE
JavaScript `const` keyword wrong color 2.1.5

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#818]
The regression issue with latest 2.1.3 version, `const` keyword is currently blue instead of purple, as it was before,

<img width="810" alt="screenshot 2016-05-12 14 37 40" src="https://cloud.githubusercontent.com/assets/304929/15214832/a43d8378-184f-11e6-95e3-9b32d3e0e349.png">

**Comment by equinusocio** [comment]
Try the 2.1.5

**Comment by equinusocio** [comment]
With babel JS, javascript, and material theme 2.1.5
<img width="177" alt="screen shot 2016-05-12 at 15 09 09" src="https://cloud.githubusercontent.com/assets/10454741/15215576/8cd013f0-1853-11e6-8a9c-55696ffe5bbd.png">

**Comment by alexbeletsky** [comment]
Same as #819 .. but I have ST3 3103.

**Comment by equinusocio** [comment]
same as #809 https://github.com/equinusocio/material-theme/issues/809#issuecomment-218693683
