### ISSUE TITLE
JavaScript `function` keyword wrong color 2.1.5

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#819]
Regression in 2.1.3, `function` keyword is blue instead of purple,

<img width="898" alt="screenshot 2016-05-12 14 43 32" src="https://cloud.githubusercontent.com/assets/304929/15214900/0bcbb104-1850-11e6-905c-d770a80c9b86.png">

**Comment by equinusocio** [comment]
With babel js and material theme 2.1.5
<img width="347" alt="screen shot 2016-05-12 at 15 07 55" src="https://cloud.githubusercontent.com/assets/10454741/15215528/54c86c50-1853-11e6-9409-2e7df727f74f.png">

**Comment by alexbeletsky** [comment]
Sorry, that's actually what I see with 2.1.3 (put the wrong version on headline)

**Comment by equinusocio** [comment]
Paste the snippet

**Comment by equinusocio** [comment]
same as #809 https://github.com/equinusocio/material-theme/issues/809#issuecomment-218693683

**Comment by n1ghtmare** [comment]
Just for the record I see the same thing (including the previous issue that you've linked).

I've updated to ST 3114 (stable), and I still see this.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/820#issuecomment-219198488
