### ISSUE TITLE
rename file visually bugged

### ISSUE THREAD

**Issue by yesh** [equinusocio/material-theme#82]
hi!
thank you for the beautiful theme, I have found two bugs in it:

rename files input doesn't show up.

hope it helps,
yeshe

**Comment by johman10** [comment]
Same bug as issue #81?

**Comment by yesh** [comment]
yeah, I was just writing at the same time as you.
I'll edit it removing the find in file issue.

**Comment by equinusocio** [comment]
Yes same bug. See #67 for fix
