### ISSUE TITLE
Syntax Colour Issue Updated

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme#820]
Hi equinusocio

Since you closed the previous issue, I just have to open a new one here...

- I just updated to stable channel 3114, but the issue remains.
- I disabled all packages and only left material theme and theme bar, the issue remains.
- I disabled theme bar and only left material theme, the issue remains
- I disabled material theme and switched back to default monokai, the issue was resolved.
- I re-enabled material theme, the issue returned.

Fortunately, I stumbled in the darker-theme in OLD folder, and it seems to fix the problems just for Python (with a different syntax colour). When I tried the snippet posted by other gentlemen, The issue still remains in JS.

Anyway, I'll take this as a temporary fix, but now I definitely think the problem is on material theme's side... Hope it can be fixed later. (Everything seems to be tested on Mac, have you tried any Windows machine?)

**Comment by verchielxy** [comment]
me too... updated 3114 just now

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/809#issuecomment-218975293

I can't resolve this problem because material theme make words highlight using the provided scope (provided by the syntax package). If the word have a different color than the one defined by material theme, so the problem is the provided scope from the syntax package. If the package tell material theme that the Method is a variable scope, material theme use the variable scope color, not the method one.

**Comment by pingshunhuangalex** [comment]
But how could switching back to darker theme in OLD folder fix some of the issue? and How could using the default theme doesn't appear to have any problems then?

**Comment by equinusocio** [comment]
Because the default monokai color scheme have less specific scopes, it use 4/5 colors for all the languages and, as you can see, it doesn't highlight every language specific word

**Comment by pingshunhuangalex** [comment]
So if there is nothing you can do to fix this, is there anything I can do to fix it except for switching to a Mac? Thanks.

**Comment by equinusocio** [comment]
For Python i use the built-in package and for js the Js Babel package. Both works well and i still have no problem also on Windows machine. My themes are only the darker, lighter and default one.

**Comment by pingshunhuangalex** [comment]
Well, that's good to know. Is your Windows machine on Win10?
And also as I said, the light theme and the default one works fine on syntax. Is there anything you did for these 2 themes but not for the darker one?
Default
![image](https://cloud.githubusercontent.com/assets/17170199/15246116/d7f25a32-194d-11e6-812e-f7ac97c7bfbe.png)
Lighter
![image](https://cloud.githubusercontent.com/assets/17170199/15246130/e924eb08-194d-11e6-98bf-02a643043f97.png)

**Comment by equinusocio** [comment]
You see a completely different colors.
<img width="422" alt="screen shot 2016-05-13 at 13 05 13" src="https://cloud.githubusercontent.com/assets/10454741/15246223/5cdf13cc-190b-11e6-9f6b-782f5e1985bf.png">

<img width="421" alt="screen shot 2016-05-13 at 13 05 34" src="https://cloud.githubusercontent.com/assets/10454741/15246233/6f42be4c-190b-11e6-942f-56ebbc6a4b1c.png">

**Comment by pingshunhuangalex** [comment]
@equinusocio 
Well at least they have 2 colors and darker theme only give me one...
So the take-home message is there is no way I can have the amazing thing you have here, right?
If the answer is positive, I'll leave you alone. Thanks.

**Comment by equinusocio** [comment]
The message is that the problem isn't related to the theme (as said here https://github.com/equinusocio/material-theme/issues/809#issuecomment-218975293). Again, are you using any SublimeLinter package?

**Comment by pingshunhuangalex** [comment]
No, just anaconda and anaconda plug-in. I disabled it this morning and it doesn't help...

**Comment by pingshunhuangalex** [comment]
For those of you who are still searching for a solution, I may find it at least in my case.

I used material theme since the beginning and always use the package control to update everything. I think somewhere during the development, there is a big change in this theme and it breaks the link there.

I went back to the package folder, I can find any material theme folder only app bar folder, but ST seems to read everything just fine (probably from the cache). I did a clean installation, and the issue remains. This morning I delete everything again and perform a manual installation using the latest version here, it finally solve everything. So now I can enjoy every bit of the material theme @equinusocio made. Thanks again for the amazing work. Can't really figure out how I ended up here, but people who have similar concerns, please feel free to have a go yourselves.

**Comment by equinusocio** [comment]
👍

**Comment by RegisBiron** [comment]
I'm still having syntax highlighting issues even after reinstalling ST 3, deleting all packages, reinstalling etc, clearing caches. My theme was perfect before I upgraded to stable 3114. 

These issues didn't exist in the previous stable build...

I've tried the above comments as well and nothing else seems to work.

I tried the Sublime SCSS package and it is still not like it used to be. My JSON highlighting is showing multiple colors depending on the nesting. 

## Settings
![screen shot 2016-05-19 at 3 00 29 pm](https://cloud.githubusercontent.com/assets/8062034/15406036/9ea7ac1c-1dd2-11e6-9b22-a8084af24172.png)

## SASS 
![screen shot 2016-05-19 at 3 00 45 pm](https://cloud.githubusercontent.com/assets/8062034/15406039/a94b0f24-1dd2-11e6-85bd-eebee9b5744c.png)

## PostCSS using syntax highlighting for PostCSS package
![screen shot 2016-05-19 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/8062034/15406128/1508256c-1dd3-11e6-8f04-13e47e255321.png)


## JSON
![screen shot 2016-05-19 at 3 02 33 pm](https://cloud.githubusercontent.com/assets/8062034/15406056/c2486e5e-1dd2-11e6-9fe1-515f06fd3edd.png)

### $ used in PHP and JS variables 
![screen shot 2016-05-19 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/8062034/15406081/e5823d6e-1dd2-11e6-883a-8a6b6a3621ce.png)

**Comment by equinusocio** [comment]
This isn't a material theme color scheme. If you use sublimelinter or color highlighter please clear the scheme cache

**Comment by RegisBiron** [comment]
Sorry I was confused since you list ""color_scheme": "Packages/Material Theme/schemes/Material-Theme-OceanicNext.tmTheme", in the README. Where is this color theme so I can post the issue? 

Whenever I paste that line into my settings it defaults to SublimeLinter.

**Comment by equinusocio** [comment]
Oceanic next is a third-party color scheme that is provided with material theme but i don't support or fix it. This issue is related to the material theme color schemes. ;)
