### ISSUE TITLE
method/function name color broken in new patch? (php)

### ISSUE THREAD

**Issue by impossibleform** [equinusocio/material-theme#821]
After updating Sublime to build 3114 method/function names lost their unique color. 

Color scheme: Default.

![ screenshot](https://cloud.githubusercontent.com/assets/5767281/15269812/f894f3f0-1a13-11e6-8a34-571c52f17db8.png)

**Comment by impossibleform** [comment]
Saw that same issue was reported 5 day ago and fixed it on my pc following your commit.

**Comment by equinusocio** [comment]
Same as #809 #820
