### ISSUE TITLE
Syntax Colour Improvement

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme#823]
Hi @equinusocio 
Here I am again. Just a small suggestion for your awesome theme here.

In Python, the <self> scope color is a bit too subtle, especially when it's next to a variable. Don't you think? Do you think you can change it to a clearer color without breaking the overall colour tone of the darker theme? Thanks.

![image](https://cloud.githubusercontent.com/assets/17170199/15282439/b3ac5822-1b86-11e6-9a13-961b3c59d7a2.png)

P.S. Everything is in their latest version.
P.S.S How did you manage to change the fonts just for the comments? (As seen in your screenshot above)

**Comment by equinusocio** [comment]
This color is shared between all color schemes, i have to make it clear on each one. I think i can increase the contrast, but maintaining the same color.

**Comment by equinusocio** [comment]
@pingshunhuangalex I can't change the global variable color. The current used scope `variable` is used for all languages. I can change the variable color only in `python` scope but you will have a color inconsistency.

**Comment by pingshunhuangalex** [comment]
Not sure if I understand. If the color is used for scope variable for all languages, then in other language there must also be situations where some colour looks subtle. Why can't we just change it for all the languages?

If due to whatever reasons it can't be changed, then just leave it as it is, no big deal. Thanks.

**Comment by equinusocio** [comment]
Because was a big issue. Check #459 #466 #610 #475 #818
