### ISSUE TITLE
SCSS has no .class color highlight

### ISSUE THREAD

**Issue by moofyme** [equinusocio/material-theme#825]
The Material Theme color scheme seems to have some issues with the `.class` selector:

![class issue](http://i.imgur.com/xMMtdP2.png)

Once I compile this into normal CSS it's all good.
Pretty much every other color scheme I have doesn't face this issue. I use the [SCSS Package](https://packagecontrol.io/packages/SCSS).

I have tried:
1. Restarting Sublime
2. Re-install packages
3. Tried other themes

**Comment by equinusocio** [comment]
Same as: #812 
Related: #820 #809
