### ISSUE TITLE
Styling `else:` in PHP

### ISSUE THREAD

**Issue by lukewhitehouse** [equinusocio/material-theme#827]
Seems that the `else:` conditional in an if/else statement in PHP isn't getting coloured as expected.

Try the following, which was embedded into a PHP file that also had some HTML throw in.

```
/**
 * Create address string
 */
if( $address ):
    $addr = false;
    $addr_count = count($address);

    foreach($address as $k => $i):
        if($k + 1 == $addr_count):
            $addr .= $i['line'];
        else:
            $addr .= $i['line'] . ', ';
        endif;
    endforeach;
endif;
```

**Comment by equinusocio** [comment]
Can you post a screenshot of what you see?

**Comment by lukewhitehouse** [comment]
@equinusocio of course! :)

![screen shot 2016-05-19 at 10 42 22](https://cloud.githubusercontent.com/assets/2808486/15389365/6759f2fc-1dae-11e6-9f60-eb7d81073330.png)

**Comment by lukewhitehouse** [comment]
Also: ST build 3114, latest version of Material Theme

**Comment by lukewhitehouse** [comment]
@equinusocio Awesome <3
