### ISSUE TITLE
Latest Sublime Text Build 3114 broken highlighting

### ISSUE THREAD

**Issue by RegisBiron** [equinusocio/material-theme#828]
Some of the highlighting seems to have become broken after updating to the latest Sublime Text Build 3114. `$` are now a different color in both PHP and JS. SASS and PostCSS highlighting is broken as well as comment styles. 

It seems like a bunch of highlighting was affected. I attached numerous examples. Please let me know if you need me to clarify!

I'm using Material-Theme-OceanicNext. 

SASS package and PostCSS syntax highlighting package. 

## SASS
![screen shot 2016-05-19 at 10 34 44 am](https://cloud.githubusercontent.com/assets/8062034/15397357/f0db9e8c-1dad-11e6-890d-e85490e72641.png)

## PostCSS
![screen shot 2016-05-19 at 10 36 10 am](https://cloud.githubusercontent.com/assets/8062034/15397361/f7c7c9a0-1dad-11e6-95ee-0b0162fd6d72.png)

## JS
![screen shot 2016-05-19 at 10 34 52 am](https://cloud.githubusercontent.com/assets/8062034/15397414/2e6dcb76-1dae-11e6-93dd-3672504b1e9b.png)

## PHP 
![screen shot 2016-05-19 at 10 35 36 am](https://cloud.githubusercontent.com/assets/8062034/15397456/45c35336-1dae-11e6-84a8-0671125dfb94.png)
 
## JSON
![screen shot 2016-05-19 at 10 36 54 am](https://cloud.githubusercontent.com/assets/8062034/15397427/340216a0-1dae-11e6-9d8f-180b47a33414.png)

## Markdown 
![screen shot 2016-05-19 at 10 42 20 am](https://cloud.githubusercontent.com/assets/8062034/15397487/678484fe-1dae-11e6-8576-4c52bb09ca3e.png)

**Comment by equinusocio** [comment]
You see a completely different color scheme. Please search for a similar issue before open a new one This is similar of #809 #818 #819 #820 #821
