### ISSUE TITLE
Last 24-hours: Update -> Tab-bar is always dark teal...?

### ISSUE THREAD

**Issue by PushkaCom** [equinusocio/material-theme#829]
Hi, I love this addon so much~

After the update, my settings file was changed and the material theme stopped working...
I had a backup of my settings file, so I restored it, and the theme came back, but now the top bar is always dark teal, no matter what theme/ color shcheme I use...

![croppercapture 2](https://cloud.githubusercontent.com/assets/985223/15413755/df0bb9de-1e76-11e6-9c5d-08792a8b3126.png)

**Comment by PushkaCom** [comment]
This is my settings file:



{
	"font_size": 16,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"word_wrap": true,
	"theme": "Material-Theme-Darker.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"overlay_scroll_bars"          : "enabled",
	"line_padding_top"             : 3,
	"always_show_minimap_viewport" : true,
	"bold_folder_labels"           : true,
	"indent_guide_options"         : [ "draw_normal", "draw_active" ],   // Highlight active indent
	"material_theme_accent_yellow"            : true , // set yellow accent color
	"material_theme_panel_separator"          : true , // show bottom panel separator
	"material_theme_tabs_autowidth"           : true , // Enable autowidth for tabs
	
}


![croppercapture 3](https://cloud.githubusercontent.com/assets/985223/15413788/2a37e612-1e77-11e6-81d4-b6c3507d46cd.png)

**Comment by equinusocio** [comment]
A don't see app bar  settings in your preferences...
