### ISSUE TITLE
the bottom bar needs to change background color

### ISSUE THREAD

**Issue by rasheedhamdawi** [equinusocio/material-theme#83]
if you make right click on sidebar to change file or folder name the bottom bar toggle but with the same background color so the text is invisible.
  
![preferences_sublime-settings_ _frontend](https://cloud.githubusercontent.com/assets/5089737/8149152/d46122ac-12b1-11e5-9866-c3d1e832dec9.png)

**Comment by equinusocio** [comment]
Pls see #67
