### ISSUE TITLE
Sublime update - Colours are more white than anything

### ISSUE THREAD

**Issue by rsands2801** [equinusocio/material-theme#831]
The past few updates are ruining this theme.  Why is so much white...$this-> is white the function is white, the parent:: is white as is the functon __construct

![untitled](https://cloud.githubusercontent.com/assets/5500424/15415194/6a271a1a-1e84-11e6-98ad-65b5dc7e0a99.png)

**Comment by rsands2801** [comment]
I am using build 3114

I removed everything completely, fresh install, manually downloaded 2.1.6 and put into packages folder.  No other packages installed

	"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"ignored_packages":
	[
		"Vintage"
	],
	"overlay_scroll_bars"          : "enabled",
"line_padding_top"             : 3,
"line_padding_bottom"          : 3,
"always_show_minimap_viewport" : true,
"bold_folder_labels"           : true,
"indent_guide_options"         : [ "draw_normal", "draw_active" ],   // Highlight active indent
"font_options"                 : [ "gray_antialias", "subpixel_antialias" ],    // On retina Mac & Windows

**Comment by rsands2801** [comment]
Also if i use Packages/Material Theme/schemes/Material-Theme-OceanicNext.tmTheme it shows proper function colours, it is only the material theme ones itself dont work after updating to build 3114

**Comment by AyushRaviRai** [comment]
Facing the same issue

everything is having similar color

+1
![everythingsamecolor](https://cloud.githubusercontent.com/assets/11500362/15455470/c792efd6-2072-11e6-8592-9fe30a07c62f.png)

**Comment by equinusocio** [comment]
Please check https://github.com/equinusocio/material-theme/issues/841
