### ISSUE TITLE
Theme keeps reverting to previous theme

### ISSUE THREAD

**Issue by hellopablo** [equinusocio/material-theme#832]
I'm using Material theme but find that often when I start Sublime in the morning it loads with the theme, but then reverts back to the default/previous theme after a few seconds. Once I set the preferences again it will stay, until the next day. I'm not 100% sure what the trigger is, or indeed how to reliably replicate, unfortunately.

I'm pretty sure this issue isn't specific to this theme, but I wonder if any of the theme developers/users have come across this odd behaviour before and know what might the problem be?

**Comment by equinusocio** [comment]
When Material Theme get update package control disable it for some seconds. You have to wait until finish and then you will see the theme active again. This is a Package Control behavior and not related to the theme. If you want to disable auto update you can do it through the command palette
