### ISSUE TITLE
Light Blue color variant

### ISSUE THREAD

**Issue by evenfrost** [equinusocio/material-theme#833]
Would be great if we had a light blue variant as current blue looks a bit harsh right now. I believe **Light Blue A400 #00B0FF** from Material colors would be just as awesome as current default Cyan color.
Thanks!

**Comment by equinusocio** [comment]
The default color is Teal not Cyan. You can choose Teal, Cyan o Blue accent color. Another blue color would be excessive.

**Comment by evenfrost** [comment]
I know it's far from being a trivial task, but as seen from your commits adding new accents, there is a lot of repetitive sections which could possibly be automated. Would be awesome if there was a gulp config which would automatically generate new accent based on template workflow (png images could be colored with some image manipulation lib). But again, it involves a lot of work to do and a subject of separate discussion. I think the issue can be closed now, thanks.

**Comment by equinusocio** [comment]
@evenfrost I'm open to collaborations ;)

**Comment by evenfrost** [comment]
@equinusocio I am surely to try it when have spare time. :)
