### ISSUE TITLE
Method Name color Changed

### ISSUE THREAD

**Issue by AyushRaviRai** [equinusocio/material-theme#834]
![functionnamecolorissue](https://cloud.githubusercontent.com/assets/11500362/15455269/d5e22404-206c-11e6-9134-37b08bb36f89.png)
Hi,

After the recent updgrade the color of function name has changed , it was blue before now its the same color as variable.

Not able to differentiate between variable and function :(

**Comment by equinusocio** [comment]
Old color schemes are not supported.

**Comment by AyushRaviRai** [comment]
@equinusocio  thanks for the super fast reply.

Tried the new theme but still same issue everything has same color
![functioncolor](https://cloud.githubusercontent.com/assets/11500362/15455352/2a5ec986-206f-11e6-908f-f584b61d6902.png)

**Comment by Disgeae** [comment]
#831 see this
