### ISSUE TITLE
 Do you have any plans on Rainbow brackets？

### ISSUE THREAD

**Issue by izhangzhihao** [equinusocio/material-theme#836]

**Comment by equinusocio** [comment]
wut?

**Comment by izhangzhihao** [comment]
![image](https://cloud.githubusercontent.com/assets/12044174/15469780/13f63502-211f-11e6-840c-c95a42f2eae2.png)
just like this

**Comment by izhangzhihao** [comment]
make brackets with diff colors

**Comment by dingo-d** [comment]
Why would they add that?? Just install [BracketHighlighter](https://github.com/facelessuser/BracketHighlighter) if you have troubles with keeping your brackets under control...

**Comment by equinusocio** [comment]
@izhangzhihao just follow the @dingo-d suggestion.

**Comment by izhangzhihao** [comment]
Do you have any other suggestions in intellij IDEA? @dingo-d

**Comment by equinusocio** [comment]
@izhangzhihao http://stackoverflow.com/questions/21259635/intellij-idea-braces-brackets-and-quotes-customize-color-highlighting

**Comment by izhangzhihao** [comment]
thanks @dingo-d

**Comment by dingo-d** [comment]
No problem, but it was equinusocio that suggested the link xD
