### ISSUE TITLE
Theme Settings in Preferences.sublime-settings (User) Are Reset After Each Update

### ISSUE THREAD

**Issue by hl2guide** [equinusocio/material-theme#837]
Theme Settings in Preferences.sublime-settings (User) are reset after each update within SublimeText 3.0. Is this fixable?

**Comment by hl2guide** [comment]
Theme Settings in Preferences.sublime-settings (User) are reset after each update within SublimeText 3.0. Is this fixable?

**Comment by equinusocio** [comment]
Please search for a similar issue before opening a new one. #387 #584 #283 and many others...
