### ISSUE TITLE
Error on Syntax Highlighting for HTML attributes with PHP tag

### ISSUE THREAD

**Issue by KaduAmaral** [equinusocio/material-theme#839]
### Theme Issue: Material Theme (default) Color Scheme

OS: **Windows 10 (64x)**
Sublime Text version: **Sublime Text 3 (64x)**
Materialize version: **last update**
Description of issue: **Error on Syntax Highlighting for HTML attributes, when put a PHP tag into a HTML tag.**

Steps to reproduce: **Put a PHP tag into HTML tag:**

```php
<a href="<?=$somelink?>" class="btn btn-link">Some Link</a>
```

Screenshot of issue:

![erro-syntax-hl](https://cloud.githubusercontent.com/assets/4316607/15473448/7f2d0cb8-20d6-11e6-9a94-8fe6ba2232de.png)

**Comment by equinusocio** [comment]
No problem here with the default theme. Please note that materialize is not material theme
<img width="507" alt="screen shot 2016-05-24 at 15 00 22" src="https://cloud.githubusercontent.com/assets/10454741/15504650/4bd0e246-21c0-11e6-98ff-dd87ee4d4b9f.png">

**Comment by KaduAmaral** [comment]
I'm using the Material Theme:

![my-sublime-settings](https://cloud.githubusercontent.com/assets/4316607/15505044/2d8666ee-2198-11e6-9797-228891022a1e.png)

**Comment by equinusocio** [comment]
- Try to purge SublimeLinter and ColorHighlighter cache
- Try to update ST
- Try fresh installation
