### ISSUE TITLE
Error on Syntax Highlighting on Javascript with PHP Block

### ISSUE THREAD

**Issue by KaduAmaral** [equinusocio/material-theme#840]
Javascript without syntax highlighting when between PHP condition:

![erro-js-syntax-hl](https://cloud.githubusercontent.com/assets/4316607/15478691/3d91c926-20f2-11e6-8f75-dafaba39270f.png)

### Some example code:

```php
<script type="text/javascript">
   jQuery(document).ready(function($) {
      <?php if (TRUE) { ?> 
      bootbox.alert('Hello World');
      <?php } ?>
   });
</script>
```
![erro-syntax-js](https://cloud.githubusercontent.com/assets/4316607/15504926/94db5c4c-2197-11e6-9f76-8a8a35fe4ae8.png)

### My Settings

![my-sublime-settings](https://cloud.githubusercontent.com/assets/4316607/15504925/94d56e04-2197-11e6-9947-8342eb5408e7.png)

**Comment by equinusocio** [comment]
paste the snippet please

**Comment by KaduAmaral** [comment]
I've updated the issue, with another example and my Sublime Settings.

**Comment by KaduAmaral** [comment]
I think this is a Sublime problem and not Theme, look, without any custom theme this happens too:

![erro-syntax-js-sem-tema](https://cloud.githubusercontent.com/assets/4316607/15539118/ee39c62e-2256-11e6-86d5-7c7493d29919.png)

**Comment by equinusocio** [comment]
I think the php pakage have some syntax issue and doesn't provide the correct scope
