### ISSUE TITLE
Issues when installing Material Theme manually

### ISSUE THREAD

**Issue by lolsokje** [equinusocio/material-theme#852]
I tried installing the theme via Package Control, but I couldn't find it. I tried to manually install it, by downloading the latest version, renaming the folder to Material Theme, and pasting the two lines to activate the theme in my User Preferences file. It works, but there are two issues that are apparent straight away:
1. Tabs that aren't active have a white background
![image](https://cloud.githubusercontent.com/assets/12721617/15627031/fbab86ee-24d6-11e6-89fe-04c05df01cfa.png)
2. Icons for file-types don't appear in the sidebar
![image](https://cloud.githubusercontent.com/assets/12721617/15627037/38d0b2ba-24d7-11e6-9abf-14bf7e21dea9.png)

Any idea how I can fix this?

**Comment by equinusocio** [comment]
What sublime text version are you using?

**Comment by lolsokje** [comment]
Build 3047.

**Comment by equinusocio** [comment]
I'm sorry but material theme support only Sublime Text 3 build 3103+
