### ISSUE TITLE
No reaction on CTRL + ALT + LeftClick

### ISSUE THREAD

**Issue by rafalpetryka** [equinusocio/material-theme#853]
When I press CTRL + ALT and click to folder my project doesn't collapse. Icon animation works only. I'm using SublimeText 3 Build 3114

**Comment by equinusocio** [comment]
This is not related with the theme. Anyway on OS X the shortcut is <kbd>alt</kbd> + <kbd>click</kbd> (not cmd+alt+click) and works fine.
![2016-05-30 09 39 01](https://cloud.githubusercontent.com/assets/10454741/15642879/6ba11daa-264a-11e6-9bc2-c6fcfa0e56e9.gif)
