### ISSUE TITLE
Some visual issues–

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme#854]
1) There is a weird padding at the bottom of the input field. But only if there is one line?

2) Can the background of the search options etc. be in contrast mode also? 

<img width="393" alt="e69d516f-2717-4b5a-af77-510ade3ef20e" src="https://cloud.githubusercontent.com/assets/1983382/15645430/97da47b2-2658-11e6-8db9-df4c6e537e3e.png">

3) Can the padding of the list items be reduced? Atleast vertically? 
4) How can I change the height of the list so more items fit in, maybe responsively regarding on the number of items?

<img width="519" alt="6b6d6fbd-1fdf-41f4-800d-8ea256911bb7" src="https://cloud.githubusercontent.com/assets/1983382/15645494/1b4e95b2-2659-11e6-98ec-fa98a6eff6e4.png">

**Comment by equinusocio** [comment]
Please move this issue on the white panel addon repository
