### ISSUE TITLE
Sidebar highlight opened file when expanding folder

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme#855]
Let's say, I have "home.php" fully opened (double clicked) – it is highlighted in the sidebar as opened. When you close the folder and expand it again, the file is not highlighted anymore.

Expanded folder:
<img width="746" alt="be4663aa-f29d-4b47-90ad-832851d22699" src="https://cloud.githubusercontent.com/assets/1983382/15646487/2cb18760-265e-11e6-8380-cc5e431b12bb.png">

Closed and expanded again:
<img width="745" alt="ad7f2670-2f3d-4e73-aa99-eac9cb92544d" src="https://cloud.githubusercontent.com/assets/1983382/15646500/3bd0d570-265e-11e6-9595-232b942b304c.png">

**Comment by equinusocio** [comment]
This isn't a bug because Sublime Text remove the focus when you click any other elements (included folders) in the sidebar panel.
