### ISSUE TITLE
Bottom bar obscured

### ISSUE THREAD

**Issue by PhilippeGauthier** [equinusocio/material-theme#857]
When doing a Find / Replace the Replace section is obscured. You can pull it up by adjusting height of the pane. Same thing if creating a new file via the sidebar, the input area is obscured. The problem fixes itself if I use a different theme.

![screen shot 2016-06-01 at 3 34 12 pm](https://cloud.githubusercontent.com/assets/4649619/15728030/f924db9c-280e-11e6-91b9-2340701cc542.png)

**Comment by equinusocio** [comment]
Check the known issue in the readme file
