### ISSUE TITLE
Selector highlighting too subtle for SCSS (Darker theme)

### ISSUE THREAD

**Issue by clintonbloodworth** [equinusocio/material-theme#858]
Selector highlighting is too subtle when syntax is set to SCSS. This is the case when using either [Sass Syntax Highlighting](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass) or [SCSS](https://packagecontrol.io/packages/SCSS). Upon setting syntax to Sass or keeping the syntax as SCSS and switching to another theme, selector highlighting is improved.

SCSS
<img width="875" alt="scss" src="https://cloud.githubusercontent.com/assets/10171306/15729302/8d65d77a-2828-11e6-922d-920840e740a1.png">

Sass
<img width="875" alt="sass" src="https://cloud.githubusercontent.com/assets/10171306/15729304/9158a6e6-2828-11e6-997a-b7b03066fe05.png">

**Comment by equinusocio** [comment]
Please search for a similar issue. Both packages are unuspported. Please use sass tmbundle instead.
