### ISSUE TITLE
Highlighting for FIXMEs results in poor readability

### ISSUE THREAD

**Issue by oddysee** [equinusocio/material-theme#859]
As you can see from the screenshot below, reading a FIXME that is highlighted using SublimeLinter's annotations extension can literally make one's eyes water.

<img width="492" alt="screen shot 2016-06-02 at 12 05 40 pm" src="https://cloud.githubusercontent.com/assets/899902/15731727/93673302-28ba-11e6-819b-1702d04419b1.png">

Is there a way to have a different set of colours for these?

**Comment by equinusocio** [comment]
MMM My sublimeLinter doesn't highlight the `FIXME:` key. I will try to fix it in the next major 3.0.0 release.
