### ISSUE TITLE
Syntax Highlighting breaks in Fullscreen

### ISSUE THREAD

**Issue by alexblunck** [equinusocio/material-theme#86]
When going fullscreen syntax highlighting seems to break on my machine.

Here are the preferences I'm using
```json
{
    "color_scheme": "Packages/User/SublimeLinter/Material-Theme (SL).tmTheme",
    "theme": "Material-Theme-Darker.sublime-theme"
}
```

And a screenshot
![screen shot](https://cloud.githubusercontent.com/assets/614291/8150464/94ba92a2-12eb-11e5-8893-4b6102e0311e.png)

Thanks for making this theme!

**Comment by gj1118** [comment]
@alexblunck have you tried clearing your cache and then restarting sublime text ?

**Comment by equinusocio** [comment]
The problem is ``` "color_scheme": "Packages/User/SublimeLinter/Material-Theme (SL).tmTheme"`
Try to disable the linter and clearing the cache.

**Comment by alexblunck** [comment]
@equinusocio Sorry for taking so long to respond. I don't think it's related to sublimelinter, I removed the package and problem still persists.

Command Palette text also looks weird (only in fullscreen):

![screen shot 2015-06-17 at 15 54 57](https://cloud.githubusercontent.com/assets/614291/8208813/d26f4b04-1509-11e5-9dc2-cd7d7260c67c.png)

**Comment by equinusocio** [comment]
Try to purge Sublime Text 3, reinstall the theme and install your packages one by one
