### ISSUE TITLE
Line number and selection highlighting too subtle on Darker theme

### ISSUE THREAD

**Issue by neokio** [equinusocio/material-theme#860]
I've spent the day with this theme, and have never been as happy with any theme for anything, ever.
So this one hiccup in its usefulness is like an imperfect stitch in an otherwise flawless tapestry, one I would gladly live with were it not interfering with my workflow.

I can't easily see where my cursor is. Every time I look away from Sublime Text, then look back, I literally spend 2 seconds tracking it down.

Here's what I see now:
![material-theme-dark](https://cloud.githubusercontent.com/assets/146623/15748059/b0a6b08c-28dd-11e6-92a3-7720a9c667fa.png)

Here's what I think would work better:
![material-theme-dark-suggestion](https://cloud.githubusercontent.com/assets/146623/15748108/d2dbe6e0-28dd-11e6-81cb-09f476deb55e.png)

Difference 1: The highlight around the line number ("22" in the image above) matches the lighter grey of the highlight over the minimap. It feels more consistent having them the same brighter grey, and lets me find my cursor position instantly.

Difference 2: The box around selected text "dataType" (and its outline) is lighter. These selections are very difficult to spot, defeating Sublime Text's most impressive function. Making them just a bit brighter lets me actually see what I've selected.

If my suggestion makes you say "Oh hell no", I'd be most grateful if you could tell me how to make these changes myself (especially the line number highlighting).

Thank you!!

**Comment by impossibleform** [comment]
Hi, Neokio! I want to say i really liked the idea! You can change the line highlight color using [this plugin](https://github.com/skuroda/PackageResourceViewer) and navigate into Material Theme>Schemes>Material-Theme-Darker.tmTheme. It should be on line 47 with key name lineHighlight.

**Comment by neokio** [comment]
Thank you for that!
The values I ended up using were:

```XML
        <key>lineHighlight</key>
        <string>#ffffff10</string>
        <!-- was 00000030 -->
        <key>selection</key>
        <string>#004d40</string>
        <!-- was 61616150 -->
        <key>selectionBorder</key>
        <string>#26a69a</string>
        <!-- was 4F4F4F -->
```

I can't even believe how awesome this is!
I'd say `lineHighlight` is the only necessary change.
The other two changes add teal highlighting from the [Material Design](https://www.google.com/design/spec/style/color.html#color-color-palette) spec:
![screen shot 2016-06-05 at 3 37 16 am](https://cloud.githubusercontent.com/assets/146623/15803134/e0ea646c-2ace-11e6-9fe3-0836b5ff2643.png)

Gonna try that out for a bit and see if it's not too much :)
So cool!

**Comment by equinusocio** [comment]
Unfortunately i can't made this brutal change to the selection becouse it's a personal choice and you can do this by yourself like @impossibleform said.

For the current active line are you using this sublime setting `"highlight_line": true,`? From the major release the current line will be more dark for the darker scheme

**Comment by neokio** [comment]
I really am entirely unable to use the dark theme without setting `lineHighlight` to `#ffffff10`.
But I'd love to benefit from your other updates!
Is there a way to allow "User" settings that override the defaults (which get overwritten with each update), or do I have to use PackageResourceViewer to extract and modify after each update?
