### ISSUE TITLE
Theme preventing auto_complete window from displaying

### ISSUE THREAD

**Issue by MarketHubb** [equinusocio/material-theme#862]
Excellent work (I love the theme) but when I install my auto_complete window no longer appears.

Am I missing something obvious here?

**Comment by equinusocio** [comment]
Do you mean the bottom (find/replace/rename ecc..) panel?

**Comment by MarketHubb** [comment]
No - I realize that the find replace can get lost at the bottom and need to be pulled up.

I completely removed (including cache) and reinstalled Sublime last night. Things appear to be working now.
