### ISSUE TITLE
why the fields become white?

### ISSUE THREAD

**Issue by wegorich** [equinusocio/material-theme#865]
http://take.ms/6bVCh

	"theme": "Material-Theme-Darker.sublime-theme",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",

Come on, why the update broke the best theme :?

**Comment by equinusocio** [comment]
Clear the scheme cache and restart sublime.

**Comment by wegorich** [comment]
It's works after sublime fully restart
