### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by brooksrelyt** [equinusocio/material-theme#870]
After the new update I get this message each time i save and close a document:

![image](https://cloud.githubusercontent.com/assets/5075282/16014733/83691714-3160-11e6-994e-7e6c9bd7d3f2.png)

**Comment by SonnyCrockett** [comment]
^ this

**Comment by equinusocio** [comment]
Just clean the color schemes cache, set default theme and restart ST. Then enable material theme again

**Comment by albychen5** [comment]
how do you clean the color schemes cache?

**Comment by SonnyCrockett** [comment]
i've deleted `Library/Application Support/Sublime Text 3/Cache/Material`
removed calls to Material theme and color scheme from user profile doc
quit / re-opened ST3
re-added calls for Material theme and color scheme to user profile doc
still got the warning about widgets
quit / re-opened ST3
still get the warning about widgets

**Comment by dougmacklin** [comment]
@SonnyCrockett I ended up closing all of the tabs I had open and reopening them and the issue was fixed

**Comment by SonnyCrockett** [comment]
@dougmacklin i wish that worked for me. sadly, nope.

**Comment by christopherburton** [comment]
Having the same issue.

**Comment by brooksrelyt** [comment]
@dougmacklin After the update I was receiving two error messages. After closing each of my open tabs and messing with my user settings the first error message disappeared. The message above still shows

**Comment by christopherburton** [comment]
Material Theme folder was missing from my packages directory. I had to re-download the zip file and add it there. This fixed the error messages.

**Comment by SonnyCrockett** [comment]
error seems to be fixed after deleting `Library/Application Support/Sublime Text 3/Packages/material-theme-2.1.4`

**Comment by equinusocio** [comment]
Why do you have 2.1.4 installed?

**Comment by SonnyCrockett** [comment]
¯\_(ツ)_/¯ beats me, but it's gone now. 
figured the auto-updates were taking care of business.

maybe it was a manual install at some point?
