### ISSUE TITLE
JSX 'let' highlight

### ISSUE THREAD

**Issue by theWaR13** [equinusocio/material-theme#871]
Hello. There is a problem appeared with the last update. When i use JSX syntax, keyword 'let' has a white color, same as variables. It's very frustrating. Could you fix it please? Thanks.

**Comment by equinusocio** [comment]
<img width="206" alt="screen shot 2016-06-14 at 11 32 28" src="https://cloud.githubusercontent.com/assets/10454741/16038072/b5e9ceb8-3223-11e6-804a-0f3bec813117.png">

This is the color by using Javascript Babel, React JSX, and the build-in javascript packages. And there no bug. If you see the white color please update to Material Theme 3, clear the color scheme cache and restart ST. Also check the update note:
https://github.com/equinusocio/material-theme/releases
