### ISSUE TITLE
Indent Guides pollution

### ISSUE THREAD

**Issue by lucasengel** [equinusocio/material-theme#872]
`"indent_guide_options": ["draw_active"]` is drawing all preceding columns since last update. Is this really supposed to happen? Is there a way to draw only the last indentation?
<img width="132" alt="screen shot 2016-06-14 at 10 41 37" src="https://cloud.githubusercontent.com/assets/1020229/16044978/f1c9f630-321c-11e6-8a5d-d4aee1f99178.png">

**Comment by equinusocio** [comment]
This is the correct behavior because you are inside a nested rules. 👍
