### ISSUE TITLE
After most recent update, sass variables are now long colored

### ISSUE THREAD

**Issue by tylerfowle** [equinusocio/material-theme#874]
After my theme updated, the syntax has been messed up. most notably the sass variables are white, previously they were a salmon/crimson color.
![screen shot 2016-06-16 at 9 51 06 am](https://cloud.githubusercontent.com/assets/7574003/16121469/04d96bec-33a9-11e6-8c96-a4088b2902a5.png)

**Comment by equinusocio** [comment]
This is the new scheme. Please check the full 3.0.0 release note.
https://github.com/equinusocio/material-theme/releases/tag/v3.0.0

**Comment by tylerfowle** [comment]
Where is the documentation for the "theme builder" and "scheme bulder"?

**Comment by equinusocio** [comment]
Doesn't exist
