### ISSUE TITLE
Wrong syntax highlight with JS

### ISSUE THREAD

**Issue by paul321** [equinusocio/material-theme#875]
I attached a screenshot with the highlight erros
![syntax](https://cloud.githubusercontent.com/assets/555502/16122311/4574f4fa-33ef-11e6-9b5f-a25edf0e5b5a.png)

**Comment by equinusocio** [comment]
mmm paste the snippets please.

**Comment by paul321** [comment]
Here it is:
`define(['a'], function(A) {
    return Worker.extend({}, {
        c: {
            a: '',
            b: ''
        },
        test: function() {
            var self = this;
            return new Promise(function(resolve, reject) {
                Db.getSalesCount(self.agency.id).then(function(count) {
                    if (!count || self.agency.attr('rebuild')) {
                        self.latestSaleDate = 0;
                    }
                    page = page || 1;
                    self.get(self.urls.sales).then(function(html) {
                        var trs = $(html).find(self.selectors.sales);
                        async.eachSeries(trs, function(tr, next) {
                            tr = $(tr);

                            var url = tr.find(self.selectors.sale.url).attr('href');
                            var date = tr.find(self.selectors.sale.date).text();
                            var price = tr.find(self.selectors.sale.price).text();
                            var smallThumb = tr.find(self.selectors.sale.smallThumb).attr('_src');
                            var identifier = tr.find(self.selectors.sale.identifier).text();

                            //skip refund sales
                            if (date && price && !price.contains('-') && smallThumb && url) {
                                Db.getMediaByIdentifier(identifier, id).then(function(media) {
                                    media = media ? media : new Media();
                                });
                            }
                        }, function() {
                            resolve();
                        });
                    });
                });
            });
        }
    });
});
`

**Comment by equinusocio** [comment]
Ok thanks. There is some issue with the built-in javascript package see #813. Consider to use [BabelJSPackage](https://github.com/babel/babel-sublime) package and assign all `.js` files with this highlight.
