### ISSUE TITLE
Issue with input fields on larger screens

### ISSUE THREAD

**Issue by zaynv** [equinusocio/material-theme#879]
Let me preface this by saying that I have already seen the Known Issues in the README. That does fix the issue, but if I use the input field again, the problem happens once again. This only seems to happen when I'm on an external monitor. If I just use my laptop, the problem gets fixed by dragging the panels. 

Example input field (on external monitor):

![screen shot 2016-06-20 at 1 11 01 pm](https://cloud.githubusercontent.com/assets/8627403/16208741/75f74f78-36e8-11e6-9815-f4733acb549f.png)

It gets fixed once I move my mouse to the bottom of the screen:

![screen shot 2016-06-20 at 1 11 33 pm](https://cloud.githubusercontent.com/assets/8627403/16208757/85996092-36e8-11e6-86e8-4aca32ec344f.png)

But if I run the command again, I get the same issue:

![screen shot 2016-06-20 at 1 11 59 pm](https://cloud.githubusercontent.com/assets/8627403/16208770/95f4edee-36e8-11e6-9e74-097899a90786.png)

And moving the mouse to the bottom of the screen fixes it again. 

![screen shot 2016-06-20 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/8627403/16208805/c5e76504-36e8-11e6-882c-46f8020f1fea.png)

Is there a reason this happens when using an external monitor? Here are my specs if they can help at all:

Laptop: 15" Macbook Pro Retina 2015
External Monitor: Dell 24"

**Comment by zaynv** [comment]
So it turns out this is happening with other themes as well, not just yours. I just assumed that it was a Material Theme issue because of the known issues thing you had mentioned, but this happens with every theme I use. Do you think I should open this issue somewhere else?

**Comment by equinusocio** [comment]
This is similiar to a lot of other issue. And there is the opened issue https://github.com/SublimeTextIssues/Core/issues/939 👍
