### ISSUE TITLE
Rename file broken

### ISSUE THREAD

**Issue by anneria** [equinusocio/material-theme#883]
Hi @equinusocio,

Right-click on a file/folder to rename it seems to be broken. There is a blank space at the bottom where it normally allows you to edit. 
![screen shot 2016-06-23 at 10 41 08 am](https://cloud.githubusercontent.com/assets/14565252/16297030/3752a5f8-392f-11e6-9ada-54b0571bc5e1.png)

**Comment by equinusocio** [comment]
Please check the known issue section in the readme file

**Comment by anneria** [comment]
Thank you :)

*ANNéRIA DU PLESSIS*
triptoann@gmail.com | +27837079514
