### ISSUE TITLE
Not an issue: Congrats with 3.0.0

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#885]
I would like to say congrats for 3.0.0 release. Finally, it looks very consistent and no annoying issues. Even if I'm not super happy with white color used for code/text (think light grey works a bit better), it could be just a matter of time. 

Great job and thanks a lot, @equinusocio - amazing effort!

PS. It could be immediately closed, once read :)

**Comment by equinusocio** [comment]
Thank you guy! 👍
