### ISSUE TITLE
Darker scheme - indent guides not visible

### ISSUE THREAD

**Issue by ClementParis016** [equinusocio/material-theme#888]
Using Material Dark Darker scheme, I can't see the indent guides:
![image](https://cloud.githubusercontent.com/assets/5601687/16375573/55ba0696-3c5c-11e6-8e7c-72da61cee27f.png)

But if I switch to the default Material Dark scheme, it works:
![image](https://cloud.githubusercontent.com/assets/5601687/16376259/a24e1dd2-3c5f-11e6-9c74-711e461503cc.png)

Is this something we could fix?

System info:
- Sublime Text 3 Build 3114
- Mac OS X 10.11.5
- Latest Material Theme update

**Comment by equinusocio** [comment]
Just customize your local installation. Search through the issues
