### ISSUE TITLE
White Search Boxes w/ Uneven Text (After Latest Update)

### ISSUE THREAD

**Issue by jrodl3r** [equinusocio/material-theme#889]
Search boxes used to match the theme, and the text inside them used to be vertically centered.

<img width="485" alt="" src="https://cloud.githubusercontent.com/assets/869411/16417888/818d1d12-3cfc-11e6-87be-0d0bbfa9514a.png">

Did something break? Is there something I need to do manually to get back the nice search panels (like the website and sample images show it...)

Thx

**Comment by equinusocio** [comment]
Try to reinstall the theme and restart sublime text

**Comment by jrodl3r** [comment]
Thx!
