### ISSUE TITLE
git file icons not showing

### ISSUE THREAD

**Issue by christopherburton** [equinusocio/material-theme#890]
I realize this may be a duplicated issue but the solutions posted have not worked. Git file icons continue to be ignored. I've tried all known solutions including reinstalling ST3 and disabling all third-party packages without success.

**Stable Channel, Build 3114**

<img width="199" alt="screen shot 2016-06-28 at 8 47 08 pm" src="https://cloud.githubusercontent.com/assets/1005485/16437073/9e429480-3d71-11e6-80a1-cec394e8905a.png">

**User Settings:**

````json
{
	"auto_complete": true,
	"auto_indent": true,
	"auto_upgrade": false,
	"bold_folder_labels": true,
	"caret_style": "phase",
	"color_scheme": "Packages/Jeffrey Way Theme/schemes/Facebook.tmTheme",
	"default_encoding": "UTF-8",
	"detect_indentation": true,
	"draw_indent_guides": true,
	"draw_white_space": true,
	"enable_tab_scrolling": false,
	"font_face": "Input",
	"font_size": 13,
	"gutter": true,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_subsequent_lines": true,
	"line_numbers": false,
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"margin": 4,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": false,
	"smart_indent": true,
	"tab_completion": true,
	"tab_size": 4,
	"theme": "Material-Theme.sublime-theme",
	"trim_automatic_white_space": true,
	"word_wrap": true,
	"wrap_width": 0
}
````

**Comment by SebJansen** [comment]
Thanks for the effort!

**Comment by oivva** [comment]
Now you can use [File Icons Extended](https://packagecontrol.io/packages/File%20Icons%20Extended) that supports Material Theme.

**Comment by christopherburton** [comment]
@oivva Works! Thank you.
