### ISSUE TITLE
Interface doesn't work SOMETIMES when using this theme, menus work though. 

### ISSUE THREAD

**Issue by hemantcompiler** [equinusocio/material-theme#891]
When I open sublime text nothing works except the menus and I can only see the Tabs opened but not the contents of the files. Clicking anywhere doesn't work except for the menus. It happens randomly. Most of the times it hangs and sometimes it works. But when I switch back to the default theme it works flawlessly.

How can I debug this?

* Ubuntu 16.04
*Sublime Text Build 3114

**Comment by equinusocio** [comment]
Please open a new issue and follow the issue template.
