### ISSUE TITLE
Indent Guidelines Not Displayed for Material-Theme-Darker

### ISSUE THREAD

**Issue by jeffdeville** [equinusocio/material-theme#892]
### Summary

Indent Guidelines Not Displayed for Material-Theme-Darker, but if I change to just Material-Theme, they show up

### Expected behavior

If I set:
```
"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
```
then the guidelines should be displayed

### Actual behavior

They're not

### Steps to reproduce

1. Set:
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",

2. Save
3. Be just a little sad

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3118

**Comment by raedlime** [comment]
Same here! :-/

**Comment by faergeek** [comment]
I think it worth to point out that only active guidelines are not shown (at least in my case).

**Comment by jeffdeville** [comment]
Ah, good clarification. My apologies for missing that initially.
