### ISSUE TITLE
Style "else" in PHP still not working

### ISSUE THREAD

**Issue by encodia** [equinusocio/material-theme#894]
It seems also last version (3.0.1) miss to style "else" branch, in PHP code.

For example:

`if( !is_singular() && !is_category() ) :
				echo '</h1>'; 
			else :
				echo '</h2>'; 
			endif;
`
<img width="598" alt="schermata 2016-07-02 alle 09 56 20" src="https://cloud.githubusercontent.com/assets/7887270/16539181/5397e800-403b-11e6-9461-9f32ff507d3d.png">

**Comment by equinusocio** [comment]
Put the operator on one line.
