### ISSUE TITLE
Can't create folder by double click folder icon on left side with "New Folder" menu

### ISSUE THREAD

**Issue by chengzheng007** [equinusocio/material-theme#895]
Hi, very thanks for providing such a useful and beautiful theme, Could I give a little suggestion? After I use this I found that, when I double click the folder, It pop up menu such as "New File", "Rename", "New Folder" etc. But I can't create a new folder by click the "New Folder" menu, And When I use the default theme---Monokai, it can work. 
    By the way, I use Mac and Sublime Text.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme#known-issues 👍
