### ISSUE TITLE
no shell script icon if the ".sh" extension is not present

### ISSUE THREAD

**Issue by maximd** [equinusocio/material-theme#897]
### Summary

No shell script icon appears if the "`.sh`" extension is not present

### Expected behavior

Shell script icon should be present for shell scripts without a `.sh` extension

FYI, those shell scripts without a `.sh` extension are already detected as "Shell Script (Bash)" by sublime text because there is a shebang "`#!/usr/bin/env bash`" at the beginning of the file

### Actual behavior

The default asterisk icon "`*`" appears for shell scripts without a "`.sh`"

### Steps to reproduce

* Create a shell script named "`test_script`" which content includes a shebang:

```bash
#!/usr/bin/env bash
echo foo
```
* Create a shell script named "`test_script.sh`" which content *does not* include a shebang:

```bash
echo foo
```

### Environment
* Material theme version 3.0.1
* Tested on:
 * Mac OS X
  * Linux Centos
* Sublime Text:
  * Build 3114

**Comment by equinusocio** [comment]
Unfortunately i can't do anything. Sublime text doen't show the icon even if the scope provided is correct. I think to show the file icon he need the `.*` extension.

**Comment by oivva** [comment]
Currently I suggest users to remove other custom UI themes when they have problems with the file icons. I hope we will fix such issues in the near future.
