### ISSUE TITLE
Problem with package update

### ISSUE THREAD

**Issue by alannaidon** [equinusocio/material-theme#899]
When submitting a bug report, please follow the following template:

---

### Summary
Everytime I initialize the ST3, I get a warning about matherial theme update and it tells me to restart ST3. When I do, the topBar is gone... How may I restore it without having to Uninstall /Reinstall the package? 
Also: All my files preset types are set to _plain text_
...

### Expected behavior
No need to uninstall/reinstall the package everytime an update shows up
...

### Actual behavior
Need to reinstall the package to have the top bars back again.
...

### Steps to reproduce

1. First step: wait for an update warning;
2. Second step: Restart the Sublime as recommended;
3. Third step: BIRL!

### Environment

* Operating system and version:
  * [ X ] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3103

**Comment by equinusocio** [comment]
This type of issue is not related to the theme. You have some problem when Package Contro try to update this package. Try to unistall it through Package Control, and then check if any `Material-Theme` exist inside your "Packages/Installed packages directory" (Sublime Text → Browse packages). When you're sure that Material Theme is completely removed try to reinstall it with Package Control

You still have the same issue repeat the unistall but then install the theme by downloading the repo https://github.com/equinusocio/material-theme#manual-installation
