### ISSUE TITLE
Light version

### ISSUE THREAD

**Issue by chrisdrackett** [equinusocio/material-theme#9]
If I get this up and running I would be happy to help out with a light version!

**Comment by equinusocio** [comment]
Yes! but i want to have a stable version before make portings and variants

**Comment by equinusocio** [comment]
@chrisdrackett the default version (and darker) are almost finished.

**Comment by m19** [comment]
Just wanted to thank you for this theme! Really love it. Eager to see the light theme for when I'm working outside.

Keep it up :)

**Comment by leky** [comment]
It's awesome! can you add support for small tabs size?

**Comment by jaimeeee** [comment]
It would be nice too to have some colores, not only green. I will see what can I do!

**Comment by equinusocio** [comment]
@jaimeeee  This is a theme base on the Material Design guidelines and colors palette. I don't want to add some distracting and extra-palette colors. :)

@leky I will add some settings in the next releases :)

**Comment by kaumac** [comment]
I really wish there was a color darker than 263238 for Blue Grey :disappointed:, other than that, I really think the colors are looking great, congrats and thanks for the theme :wink:

**Comment by wldcordeiro** [comment]
I'm interested in helping out with this @equinusocio could you point to a list of the colors in the theme?

**Comment by equinusocio** [comment]
In the light version, only the accent color can be the same: #80CBC4. Other color must be edited.

**Comment by wldcordeiro** [comment]
@equinusocio I was thinking you could use the command panel background color for the main background and vice verse.

**Comment by equinusocio** [comment]
@wldcordeiro no, unfortunately it's not so easy, the light version needs a more accurate color palette to avoid the stress of eyes

**Comment by juristr** [comment]
:+1: for a light version. For dev I use the dark version, but usually when you have to demo something on bad beamers, light versions are much more suitable.

**Comment by xen** [comment]
I wish to try light version. Dark looks gorgeous, but I can't work with dark themes.

**Comment by jczimm** [comment]
+1 for light version

**Comment by equinusocio** [comment]
The darker version will become more darker with a neutral charcoal palette. For the lighter version you have to wait a bit.

**Comment by assimovt** [comment]
:+1:

**Comment by equinusocio** [comment]
I'm working hard. Please be patient :)

**Comment by xen** [comment]
Thank you for your effort.

**Comment by Danappelxx** [comment]
I love this theme, but to be honest I really don't like the new dark theme. Could you add an option to go back to the old one? Maybe something like Material-Theme-Darker-old? Right now I went back to the standard theme but I don't really like the white in the panels.

**Comment by equinusocio** [comment]
In the next release i will remove the white panels and input from default theme.

**Comment by raffw7912** [comment]
+999 for light theme, I would really like to use during sunny days when I'm struggling to see my code :+1:

**Comment by myurtsev** [comment]
Is there a possibility to change the background color of the command palette to white again? I kinda prefered it that way.

**Comment by equinusocio** [comment]
@myurtsev  Isn't yet official but you can install the addon Material Theme - White Panels through Package Control then restart ST

**Comment by rahmatawaludin** [comment]
:+1:

**Comment by timbog80** [comment]
Why does everyone want  a light version? it strains your eyes.

**Comment by chrisdrackett** [comment]
your eyes maybe ;)

**Comment by Danappelxx** [comment]
Some people are just used to light themes I guess. These are the people that I assume began their programming careers with themes like Xcode, eclipse, np++, etc. hard to shake off old habits I suppose.

**Comment by timbog80** [comment]
try sticking with a dark theme you will see that you will be able to stare at the editor for a lot longer. light themes strain your eyes alot, its really not good for you

**Comment by m19** [comment]
Not just that. I just moved to a tropical country and like to work outside. That's just not possible with a dark theme. Currently I just the solarized light color scheme when I'm outside.

**Comment by equinusocio** [comment]
![screen shot 2015-06-27 at 12 43 00](https://cloud.githubusercontent.com/assets/10454741/8391639/13def5c2-1cca-11e5-8b95-0a061d0a19d2.png)

**Comment by Danappelxx** [comment]
That actually looks way better than I thought it would be. 10/10 👍

**Comment by m19** [comment]
Looks amazing! Keep it up!

**Comment by Far0s** [comment]
Wow, it does look fabulous ! :D

**Comment by m19** [comment]
If you have a bitcoin address I'd be happy to send you some bits to support you :)

**Comment by equinusocio** [comment]
@m19 at the moment i have paypal for donations :)

**Comment by m19** [comment]
@equinusocio 
Not really related to this issue. But I've noticed you've added Bitcoin donations. As promised I've sent you 0.02 BTC. https://blockchain.info/tx/7586cb7c32f2404680822e52a60a5ed9672be6a376f61602c94e38419e96f17c

Good luck with the development!

**Comment by kennysmoothx** [comment]
This looks HOT! Can't wait to give this light theme a spin..

+1

**Comment by timbog80** [comment]
+1

**Comment by NicolasParada** [comment]
Very cool :+1:

**Comment by equinusocio** [comment]
The lighter version (and v2.0.0) is almost "finished":

![Material Theme Lighter](https://transfer.sh/oo2kV/screen-shot-2015-07-11-at-13.34.44.png)

![Material Theme Lighter](https://transfer.sh/r93wu/screen-shot-2015-07-11-at-13.34.31.png)
