### ISSUE TITLE
Support for Sublime Text 2

### ISSUE THREAD

**Issue by vlafiser** [equinusocio/material-theme#90]
Hey man,

the theme is awesome! But, do you plan release version for ST2?

Thanks and I hope will possible install this cool theme on the older version soon! :)

**Comment by Revod** [comment]
The Problem with Material Design Theme for ST2 is that the icons will not be displayed

**Comment by vlafiser** [comment]
I have broken more things if I'm trying figure out on ST2.

**Comment by B-iggy** [comment]
For me I call ST3 stable. ;)
Give it a try.

**Comment by equinusocio** [comment]
Actually you can manual install the package on ST2 (but you can't see the file icons). I will not provide support for version 2 of Sublime Text
