### ISSUE TITLE
After last update *.coffee files has no icon in sidebar

### ISSUE THREAD

**Issue by alexanderbelko** [equinusocio/material-theme#900]
### Summary
After last update *.coffee files has no icon in sidebar

### Expected behavior
*.coffee files has icon in sidebar

### Actual behavior
*.coffee files has no icon in sidebar

### Steps to reproduce

1. Open ST3
2. Add *.coffee files to project
3. There are no icon for *.coffee files in sidebar

### Environment

* Operating system and version:
  * [x] Mac OS ...
* Sublime Text:
  * Build 3114

**Comment by equinusocio** [comment]
There is a problem with some file_type recognition after latest ST update, also gulp/grunt file doesn't have icons.

**Comment by alexanderbelko** [comment]
@equinusocio Thanks!
