### ISSUE TITLE
Rename Field

### ISSUE THREAD

**Issue by shavonn** [equinusocio/material-theme#902]
### Summary

Can't see the rename file/folder field.

### Expected behavior

The field should show at the bottom.

### Actual behavior

I can't see the field anywhere. I can only basically just type blindly and hope for the best when I hit Enter.

### Steps to reproduce

1. Right-click on file or folder and click rename.
2. Type and see that it does not appear anywhere.
3. Hit enter and name updates to whatever you typed.

### Environment

* Operating system and version:
  * Mac OSX El Capitain
* Sublime Text:
  * Build 3114

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme#known-issues
