### ISSUE TITLE
The .json icon is missing

### ISSUE THREAD

**Issue by ThomasPof** [equinusocio/material-theme#903]
### Summary

The .json icon is missing

### Expected behavior

It was working until the last release (07/07)

### Actual behavior

Nothing is displayed
<img width="172" alt="capture d ecran 2016-07-11 a 21 57 24" src="https://cloud.githubusercontent.com/assets/11079771/16752867/fa99256e-47b2-11e6-9ada-7e47b5a8f11f.png">

### Environment

* Operating system and version:
  * [ ] Mac OS 10.11.5
* Sublime Text:
  * Build 3114

**Comment by oivva** [comment]
Remove other custom themes. More details [here](https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134/4)
