### ISSUE TITLE
Problem with vintageous

### ISSUE THREAD

**Issue by hezt** [equinusocio/material-theme#904]
### Problem
I use both material theme and vintageous, but when I type / and : to enter Last line mode, I can not find my command.
### Example
In vim normal mode, I type :wq, I cannot see my command on the bottom of sublime text 3. Without material theme, I can see the last line mode's bar.

### Environment

* Operating system and version:
  * Mac OS 10.11.3
* Sublime Text:
  * Build 3...

Thanks.

**Comment by equinusocio** [comment]
You can paste a screenshot with/without material theme? Check also the known issue in the readme file.

**Comment by geohuz** [comment]
I'm attaching the screenshots, first one is without material-ui theme,

![withoutmaterial](https://cloud.githubusercontent.com/assets/730770/17290805/e67df710-5812-11e6-965d-ca34e3194cee.png)


and this one with material-ui theme,

![withmaterial](https://cloud.githubusercontent.com/assets/730770/17291683/fac31ec6-5817-11e6-978b-8f70716d3a64.png)

**Comment by equinusocio** [comment]
Check the known issue in the readme file.
