### ISSUE TITLE
Feature Request: Provide a Bracket Highlighter matching color scheme

### ISSUE THREAD

**Issue by txemaleon** [equinusocio/material-theme#905]
I've started using [Bracket Higlighter](http://facelessuser.github.io/BracketHighlighter/) which provides better bracket matching visuals for Sublime Text.

This plugin is [often referred as one of essentials sublime text plugins for web developers](https://www.google.es/search?client=safari&rls=en&q=essentials+sublime+text+plugins+for+web+developers&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=qlOKV9DPH5DY8gfSzYGYCQ#q=sublime+text+plugins+for+web+developers+brackethighlighter) and has [over 1M installs in Package Control](https://packagecontrol.io/packages/BracketHighlighter).

Right now all bracket types are painted in white. It would be really nice to pack Material Theme with colors for this package.

Looks like it can be done this way inside the theme:

```xml
<!-- BEGIN Bracket Highlighter plugin color modifications -->

<dict>
    <key>name</key>
    <string>Unmatched</string>
    <key>scope</key>
    <string>brackethighlighter.unmatched</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#FD971F</string>
    </dict>
</dict>

<dict>
    <key>name</key>
    <string>Bracket Curly</string>
    <key>scope</key>
    <string>brackethighlighter.curly</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#FF0000</string>
    </dict>
</dict>

<dict>
    <key>name</key>
    <string>Bracket Round</string>
    <key>scope</key>
    <string>brackethighlighter.round</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#0000FF</string>
    </dict>
</dict>
```

And in [Brackets Highlighter](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L575) preferences it defines the following ids:

* brackethighlighter.default
* brackethighlighter.unmatched
* brackethighlighter.curly
* brackethighlighter.round
* brackethighlighter.square
* brackethighlighter.angle
* brackethighlighter.tag
* brackethighlighter.c_define
* brackethighlighter.quote

**Comment by equinusocio** [comment]
I will add only `brackethighlighter.default` = paleblue and the `brackethighlighter.unmatched` = red. So the default brackets color is the paleblue and not a set of different color
