### ISSUE TITLE
File icons for CoffeeScript?

### ISSUE THREAD

**Issue by dcusan** [equinusocio/material-theme#906]
Hello,

firstly congrats on the theme, it is by far the best theme for ST3 I know!

I don't know if this is a bug or just a little feature request, but all my files in the sidebar have a little file icon except for the `.coffee` files. I don't really know if there is supposed to be an icon or not, but I thought I mention it.

![image](https://cloud.githubusercontent.com/assets/5691039/16970819/3ea1bf56-4e51-11e6-99df-0df7b6d3d3b0.png)

Thanks anyways!

**Comment by rcrocombe** [comment]
I'm also missing CoffeeScript icons. They used to be there before a few weeks ago.

**Comment by equinusocio** [comment]
Check and try #903

**Comment by rcrocombe** [comment]
So try removing other themes? I only have Material Theme installed and some plugins. I tried removing Better Coffeescript and I get `*` asterisk icons instead of blank spaces.

**Comment by josuemontano** [comment]
Same here, I'm using ST Build 3119, there are no other themes installed besides the default.

**Comment by equinusocio** [comment]
@dcusan please check the latest 3.0.3 release

**Comment by rcrocombe** [comment]
@equinusocio That fixed it, thanks!
