### ISSUE TITLE
Tab bar not themed correctly after last update

### ISSUE THREAD

**Issue by kommen** [equinusocio/material-theme#908]
### Summary

After the theme was updated today, the tab bar is no longer themed as expected.

### Expected behavior

Tab bar as seen in the screenshots here: https://camo.githubusercontent.com/972bd5d93779fdaf95e02cf0326b429be93adcba/687474703a2f2f692e696d6775722e636f6d2f395079784a4d4e2e676966

### Actual behavior

<img width="650" alt="screen shot 2016-07-22 at 10 21 31" src="https://cloud.githubusercontent.com/assets/258/17051021/78bc8698-4ff6-11e6-9fb3-356171100596.png">

### Steps to reproduce

Open multiple files in tabs to see the tab bar

### Environment

* Operating system and version:
  * [x] Mac OS 10.11.6 (15G31)
* Sublime Text:
  * Build 3118

**Comment by equinusocio** [comment]
What version of Material Theme do you have? because no update was released form days. You should have the v3.0.2 (https://github.com/equinusocio/material-theme/releases/latest). And everything works fine. 

Just try to close all files inside all workspaces and then restart ST

**Comment by kommen** [comment]
I have 3.0.2, apparently it was updated by Package Control today from 3.0.1.

**Comment by equinusocio** [comment]
MMm It's strange. Can you try to purge the theme (Remove it through Package Control, delete al material theme folders) and then reinstall it? I suggest you to reapply material theme settings step by step.

**Comment by kommen** [comment]
Thanks, reinstalling, deleting the cache and reapplying all settings fixed the issue!

**Comment by equinusocio** [comment]
👍 This kind of issue is always related to the package control update process, that sometimes break the package.
