### ISSUE TITLE
The rename dialog box do not apear

### ISSUE THREAD

**Issue by gcc32** [equinusocio/material-theme#909]
The rename dialog do not apear at the bottom of the program like Find dialog box. Its occurs on Windows and Mac on SB3

**Comment by Stormiix** [comment]
Just resize the it , and it will show up

**Comment by gcc32** [comment]
Ok it works! But its an issue!

**Comment by equinusocio** [comment]
@gcc32 please next time use the issue template and search for a similar one. Also check the known issue of the readme file. I will close any similar issues.
