### ISSUE TITLE
Material Theme Preferences "User" override settings thingy?

### ISSUE THREAD

**Issue by neokio** [equinusocio/material-theme#913]
Greetings,

I find the dark theme unworkable with the default darker lineHighlight (as mentioned in #860). So after each update, I take 10 minutes using PackageResourceViewer to extract, and then set that value to #ffffff15 (along with a few other minor tweaks).

Would you consider adding a persistent "User" settings that override the defaults (which get overwritten with each update)? I don't even know if this is possible, much less something you'd want to implement. But I see many other, much less configurable Sublime Text packages with user override settings, so I thought there'd be no harm in asking.

After two months of using your dark theme, there's no going back. I'm crazy about it. I dream in this colorspace. So if your answer is "Yeah, no. In fact, I'm going to make it harder for you from now on", I'd be like, "Excellent!".

**Comment by equinusocio** [comment]
1. Close Sublime Text.
2. Make a folder called `Material Theme` inside your `Packages` directory.
3. Inside this folder make another folder called `schemes` and put inside a blank file with the name `Material-Theme-Darker.tmTheme` (*You must have only this files inside the Material Theme folder*)
4. Inside this file paste this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>author</key>
	<string>Mattia Astorino</string>
	<key>colorSpaceName</key>
	<string>sRGB</string>
	<key>name</key>
	<string>Material-Theme-Darker</string>
	<key>semanticClass</key>
	<string>material.theme.dark</string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>lineHighlight</key>
				<string>#ffffff15 /string>
			</dict>
		</dict>
       </array>
</dict>
</plist>
```

Reopen Sublime Text. You should have your custom line highlighter color and you will get updates without lose your customization.

**Comment by neokio** [comment]
Thank you for taking the time!
Doing the above seems to reset the entire style to default (white background, black text), with ONLY the `lineHighlight` in effect. I made sure to remove the `Material Theme` folder, leaving only this file, and tried removing and re-installing the theme just to be sure, it still has this effect. As per your setup instructions, User Settings (preferences) reference this exact file ...

```
"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
```

... so it makes sense in a way. Anyways don't give this another thought, users like me can just tweak your settings each time. Thanks again!

**Comment by equinusocio** [comment]
Just extract the original darker tmtheme file and paste it inside your tmtheme file (above steps). Edit the line highlight color in your copy. You will get all theme updates but not the darker scheme. I think it's good enought.
