### ISSUE TITLE
Error loading widget color scheme

### ISSUE THREAD

**Issue by corneliusio** [equinusocio/material-theme#914]
### Summary
For the last few weeks, there seems to be an issue with the directory structure of the theme. 

After any update to the Material Theme package, I start getting this error. 

![screen shot 2016-07-27 at 9 58 26 am](https://cloud.githubusercontent.com/assets/4140885/17180405/fb9b5fdc-53e1-11e6-82c9-1b75da3cf828.png)

The only way I can get it to work (this error pops up constantly while using Sublime) is to extract the package with [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) and change the directory structure under `/Material Theme/widgets`.

From what I can see, the install places all the widget color scheme files in the root of the `widgets` directory.
![screen shot 2016-07-27 at 9 59 21 am](https://cloud.githubusercontent.com/assets/4140885/17180540/75b14430-53e2-11e6-8d7a-1180740a5c81.png)

But it seems that the package is looking for them under subdirectories (`darker`, `lighter`, `default` respectively). So the only way for me to fix it is to move the files like so. 
![screen shot 2016-07-27 at 10 04 31 am](https://cloud.githubusercontent.com/assets/4140885/17180656/c2a5fbd2-53e2-11e6-9bf2-a964f8b5cec7.png)

At first I figured this would be resolved quickly since it seems relatively straight forward it appears to simply happen with any fresh install of the package. But now I'm starting to wonder if this is somehow a more isolated incident. I did find these two closed issues, #870 and #118. But neither seem to actually land on a resolution.

Though I have tried:
1. Deleting Material Theme from Sublime Text's cache directory.
2. Closing all tabs before closing and reopened.
3. Completely uninstalling and reinstalling Material Theme.

### Environment
I'm running OS X 10.11.6
Sublime Text Build 3114
Currently on v3.0.3 of the Material Theme installed with Package Control.

**Comment by equinusocio** [comment]
Completely remove the theme and reinstall it

**Comment by corneliusio** [comment]
Yeah, I figured that might possibly fix it. Have tried it numerous times in the past (and again just now to make sure). No dice.

**Comment by corneliusio** [comment]
And after this last round of uninstalling and reinstalling, I am now seeing these graphical glitches (in addition to the original error). And no matter how much I uninstall/reinstall, clear caches, restart Sublime, or restart my machine; I don't seem to be able to get rid of them. 😕 

![screen shot 2016-07-27 at 12 04 53 pm](https://cloud.githubusercontent.com/assets/4140885/17184969/9461e828-53f4-11e6-9ecf-6f7e7f8c3f3e.png)

**Comment by equinusocio** [comment]
You have other themes installed? try to remove all the themes, then re-purge the material theme and reinstall it through Package Control. If you still have any issue try to install it by manually.

**Comment by corneliusio** [comment]
I did not have any other themes before installing the one mentioned above, and I also removed it right after I got the graphical glitches resolved in Material Theme.

Installing manually does seem to have taken care of the error. So the problem seems to be with the way that it get's installed via Package Control.

**Comment by equinusocio** [comment]
Yes, package control sometimes have issues when updating/installing a package.

I really can't help you. This type of issues are related to the Package Control plugin and i can't help about that. If you still get the issue I can suggest to search for a similar closed issue and completely purge/reinstall the theme, both through Package Control and manually.
