### ISSUE TITLE
Feature request: Add option to force @2x.png icons.

### ISSUE THREAD

**Issue by samuelbodin** [equinusocio/material-theme#915]
I'm currently on my Surface Pro 4 which has a very high screen resolution. As a result, all the icons in the theme look blurry. I always end up changing all the paths to match the @2x.png files. This works fine until a new theme update comes, then it changes back to the original state and I have to do the path change again. It would be nice if there was an option to force the theme to use the @2x.png icons all the time.

Some screenshots:

Normal .png
![Image ](http://i63.tinypic.com/2qkibo8.jpg)

@2x.png 
![Image](http://i64.tinypic.com/246rtah.jpg)

Thanks.

**Comment by equinusocio** [comment]
The theme can't handle this core behavior. All the assets provided with this package are @2x and @3x density. Sublime use the correct assets on a retina display so i think that ST have a problem to detect your device screen density. You should open this issue on the ST issues repository.

**Comment by samuelbodin** [comment]
Ok thanks, I will do that!
