### ISSUE TITLE
Add monochrome filetype icons

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/material-theme#917]
Add an alternative monochome icons set (filetype)

**Comment by ctf0** [comment]
use this 
```js
{
        "class": "icon_file_type",
        "settings": ["chrome_icons"],
        "layer0.tint": [0,0,0]
    },
```

**Comment by equinusocio** [comment]
Oh thanks. 👍

**Comment by equinusocio** [comment]
With this code i can't get a blueish icon..

**Comment by equinusocio** [comment]
The point is that i can't use different files for icons. ST, as you know, automatically pick the relative png file. So i can't add both colored and white (for monochrome) icons because i can't set the path to use with a theme setting.

**Comment by ctf0** [comment]
okay as ST read the icons from folder only called `icons` a solution would be including 2 separate folders for icons with different name `colored` & `chrome`, and the user according to which version he wants he just need to change the folder name to `icons`
