### ISSUE TITLE
Not displaying icons

### ISSUE THREAD

**Issue by dumitru05** [equinusocio/material-theme#918]
### Summary
Not displaying icons files

### Actual behavior

https://www.dropbox.com/s/mtvnn6jmruwvb3a/img-2016-07-29-20-22-10.png

### Environment

* Operating system and version:
  * Mac OS El Capitan 10.11.6
* Sublime Text:
  * Build 3114

**Comment by equinusocio** [comment]
Material Theme version? This is strange i can suggest to try to remove other themes and restart ST

**Comment by dumitru05** [comment]
last version, 3.0.4

**Comment by equinusocio** [comment]
Follow the purge steps and make sure that you don't have the `material_theme_disable_fileicons` settings

**Comment by dumitru05** [comment]
it works) thank you very much!
