### ISSUE TITLE
Can't see the filename when typing

### ISSUE THREAD

**Issue by Nisthar** [equinusocio/material-theme#919]
I use material theme for my sublime text all the time. Anyway, The only two problems i am facing is that i can't see the text i type into the box for creating new files, renaming files, etc. I am using the sidebar plugin too.

Also, the other problem (i am not sure if its my sublime's error) is that when i reopens my sublime text it changes the theme back to the normal theme.

Short:
1. Can't see the text i type for the filename when creating new files, renaming files, etc
2. Constantly revert back to normal theme when i close and reopens sublime (may be because of upgrading.)

**Comment by equinusocio** [comment]
1. See the known issue in the readme file to fix the input box

2. Try to remove it and delete all material theme folders inside your Packages. Then reinstall it. This issue is related to Package Control and i can't help.
