### ISSUE TITLE
Problems with package Material Theme + package SideBarEnhancements

### ISSUE THREAD

**Issue by llaraujo** [equinusocio/material-theme#92]
Hi,

the options of SideBarEnhancements (New File... , Duplicate..., etc...) are not showing up with this theme. It is visible that's working because size of sidebar increases, but does not have the necessary styles to full working.

Please, you check?

The Package is: https://github.com/titoBouzout/SideBarEnhancements

**Comment by gj1118** [comment]
@llaraujo Does  #18  help ?

**Comment by equinusocio** [comment]
See #67 for the fix

**Comment by llaraujo** [comment]
Sorry, my apologies.

Thanks!
