### ISSUE TITLE
Huge Padding in popupCss Affects Phantoms

### ISSUE THREAD

**Issue by wbond** [equinusocio/material-theme#920]
### Summary

Color schemes add way too much padding to phantoms.

### Expected behavior

Not to add so much padding to phantoms.

### Actual behavior

Adds too much padding to phantoms.

### Steps to reproduce

1. Look at https://forum.sublimetext.com/t/colorhelper-2-0-0/21762/25

### Environment

* Operating system and version:
  * Windows ...
  * Mac OS ...
  * Linux ...
* Sublime Text:
  * Build 3118+

### Resolution

There are two settings that should be controlled by color schemes, `popupCss` and `phantomCss`. One is used for the Show Definitions and scope name popups. The other is used for inline build results, and things like Color Helper. If there is no `phantomCss`, then `popupCss` is used instead for phantoms.

Adding 16px of padding to the `html` element seems like you are trying to affect the popups and give them more breathing room. My initial recommendation is that you probably add a `phantomCss` which is similar to `popupCss`, but does not really add any padding.

Also note that the built-in popups and phantoms provided by Sublime Text have an `id` attribute on the `<body>` tag so that you can target them if you are trying to adjust specific layout issues. You can use https://packagecontrol.io/packages/PackageResourceViewer to inspect the Default package and look at `symbol.py`, `show_scope_name.py` and `exec.py`.

**Comment by equinusocio** [comment]
This is what i see with ColorHelper 2.0.4 and Material Theme 3.0.3 without `phantomCss`
<img width="313" alt="screen shot 2016-07-30 at 16 08 21" src="https://cloud.githubusercontent.com/assets/10454741/17270993/d9aeb906-566f-11e6-9452-c4384c7e2acb.png">

By adding 
```xml
<key>phantomCss</key>
<string><![CDATA[ html { padding: 20px; border-radius: 10px; } ]]></string>
```
nothing change and no padding  around the phantom color preview...

**Comment by equinusocio** [comment]
The author of the plugin force to ignore any css rules assigned to the html selector. Anyway i will fix this by adding the phantomCss key.
