### ISSUE TITLE
Package Control: An error occurred while trying to parse the dependencies.json for Material Theme

### ISSUE THREAD

**Issue by fiznool** [equinusocio/material-theme#925]
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

When submitting a bug report, please follow the following template:

---

### Summary

When installing Material Theme through Package Control, the following message appears in the console window:

```
Package Control: An error occurred while trying to parse the dependencies.json for Material Theme
```

The theme is not installed.
...

### Expected behavior

Theme should be installed
...

### Actual behavior

Theme is not installed
...

### Steps to reproduce

1. Open ST console window
2. Use Package Control to install Material theme

### Environment

* Operating system and version:
  * Ubuntu 16.04
* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.0

**Comment by equinusocio** [comment]
Update to Sublime Text 3118 and retry the installation.

**Comment by joshmadewell** [comment]
@equinusocio Version 3118 is a dev build which is only available to registered users. Is that the only solution to this?

**Comment by equinusocio** [comment]
I've pushed the hotfix (3.1.1). You can try with the manual installation? Because Package Control will parse the new release in 20 mins

**Comment by equinusocio** [comment]
I hope that by setting `>=3118` inside the `dependencies` file will fix that issue. I think that if the sublime build isn't >= 3118 it doesn't search for that dependencies. I don't know very well how dependencies works here.

**Comment by fiznool** [comment]
When installing manually I get:

```
reloading plugin Material Theme.material_theme
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/fiznool/.config/sublime-text-3/Packages/Material Theme/material_theme.py", line 5, in <module>
    import mdpopups
ImportError: No module named 'mdpopups'
```

**Comment by joshmadewell** [comment]
The manual installation worked for me :D thanks!

**Comment by equinusocio** [comment]
@fiznool you downloaded the 3.1.1 release?

**Comment by fiznool** [comment]
yep

**Comment by equinusocio** [comment]
You can try to remove the theme (from Package Control and manually from "Packages/") and the reinstall it manually?

**Comment by equinusocio** [comment]
@joshmadewell remember that manual installation doesn't get new updates. So remember to install it through Package Control in 1 hr

**Comment by joshmadewell** [comment]
@equinusocio Good point. I'll be sure to do that. Thanks for the quick response on this and great work on the theme :D

**Comment by fiznool** [comment]
@equinusocio sorry still the same issue.

Should all [these comments](https://github.com/equinusocio/material-theme/blob/develop/dependencies.json) be in the JSON file? Maybe `dependencies.json` isn't being parsed correctly?

**Comment by equinusocio** [comment]
@fiznool Inside the command palette launch `Cackage Control: Satisfy Dependencies` and restart sublime

**Comment by austenc** [comment]
I think what @fiznool is saying is that comments are not valid within JSON. Getting rid of those should fix the issue.

**Comment by equinusocio** [comment]
@fiznool Try also, in your local material theme folder, to open `dependencies.json` file and remove the comments. Then restart sublime text.

**Comment by rahul-ramadas** [comment]
I'm on build 3120, and I see this issue as well.

**Comment by equinusocio** [comment]
3.1.2 released. I'm sorry for this issue. @rahul-ramadas check the manual installation (3.1.2) if it works.

**Comment by rahul-ramadas** [comment]
Manual install fixed that issue and the theme now loads. However, there seem to be a few more problems. It complains about being unable to satisfy a dependency (`webbrowser`), and `mdpopups` seems to be trying to import `markdown` which is not available.

```
reloading plugin Material Theme.material_theme
Traceback (most recent call last):
  File "E:\Sublime\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "E:\Sublime\Data\Packages\Material Theme\material_theme.py", line 5, in <module>
    import mdpopups
  File "E:\Sublime\Data\Packages\mdpopups\st3\mdpopups\__init__.py", line 12, in <module>
    import markdown
ImportError: No module named 'markdown'
reloading plugin Material Theme.urls
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, webbrowser, is not available
Package Control: Skipping automatic upgrade, last run at 2016-08-01 08:08:18, next run at 2016-08-01 09:08:18 or after
Package Control: The dependency webbrowser is not currently installed; installing
Package Control: The dependency specified, webbrowser, is not available
Package Control: The dependency webbrowser could not be installed or updated
Package Control: The dependency webbrowser has successfully been installed or updated
error: Package Control

One or more dependencies could not be installed or updated.

Please check the console for details.
```

**Comment by equinusocio** [comment]
@rahul-ramadas you launched `Package Control: Satisfy Dependencies`?

**Comment by edlahoz** [comment]
I tried removing the package and then reinstalling it. Doesn't seem to be installing it again, as it's not showing up when I list the installed packages.

**Comment by equinusocio** [comment]
@edlahoz browse the `Packages` folder and search/remove all material theme (folder and files) reference. Then restart sublime and try to reinstall.

**Comment by rahul-ramadas** [comment]
@equinusocio Yes, the dependency error you see above is from when I manually tried to satisfy dependencies.

**Comment by equinusocio** [comment]
I get the same errors. webbrowser is a python module and should be installed without problem. I noticed this message from the console:
```
Package Control: The dependency webbrowser could not be installed or updated
Package Control: The dependency webbrowser has successfully been installed or updated
```

So at the end webbrowser it's installed.

**Comment by kedarv** [comment]
Ever since the update, I cannot properly apply the color theme (the package folder for the theme does not exist). Is this related?

**Comment by equinusocio** [comment]
@kedarv i think yes, unfortunately this update break everithing. Just wait 15 mins and try to remove/reinstall it

**Comment by saurabh-gohil** [comment]
Having same issue on Windows as well on build 3120

**Comment by fiznool** [comment]
@equinusocio I'm still seeing the same issue with v3.1.2. After copy/pasting the plugin folder to my `Packages` dir, I ran the `Package Control - Satisfy Dependencies` and it said that all dependencies were satisfied.

```
reloading plugin Material Theme.material_theme
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/fiznool/.config/sublime-text-3/Packages/Material Theme/material_theme.py", line 5, in <module>
    import mdpopups
ImportError: No module named 'mdpopups'
reloading plugin Material Theme.urls
generating meta info summary
Package Control: All dependencies have been satisfied
```

**Comment by fiznool** [comment]
Right, so I changed the version number in `dependencies.json` to `>=3114` (my ST version number, then ran `Satisfy Dependencies` and restarted ST3. Then I get the below message (which is consistent with the comment from @rahul-ramadas)

**Comment by rahul-ramadas** [comment]
I removed the manually installed packaged and tried installing from Package Control and got the 3.1.2 version. However, the theme is still not loading properly. It is complaining about not being able to find the `webbrowser` dependency.

That dependency is not listed in the [default repository](https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json), so it is unclear to me where it could come from. Is it possible that it is working for you because you have a private repository from where it is getting satisfied?

**Comment by rahul-ramadas** [comment]
I think the dependency that you really need is [python-markdown](https://github.com/facelessuser/sublime-markdown).

**Comment by fiznool** [comment]
I can confirm the fix in the PR from @rahul-ramadas with the dependency range set to >=3114 fixes my environment. Thanks for the PR!

**Comment by equinusocio** [comment]
Thanks to all, guys. 👍 🙂

**Comment by kedarv** [comment]
I am still having issues getting the theme to work (`markupsafe` dependency is causing issues). What is the solution?

**Comment by fiznool** [comment]
@kedarv probably best to open a new issue with your reproduction steps, environment and st3 version described to see if it's the same problem as reported here.

**Comment by equinusocio** [comment]
@kedarv open a new issue please.
