### ISSUE TITLE
Error loading colour scheme Material-Theme.tmTheme

### ISSUE THREAD

**Issue by oroszlanyzsolt** [equinusocio/material-theme#927]
---

### Summary

Error loading colour scheme, unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme.

### Expected behavior

Theme applied to Sublime Text 3 editor

### Actual behavior

Unable to open Packages/Material Theme/schemes/Material-Theme.tmTheme

### Steps to reproduce

1. First step
    Install Material Theme through package installer
2. Second step
    update Preferences.sublime-settings to
"theme": "Material-Theme.sublime-theme",
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",

### Environment

* Operating system and version:
  * [x] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.1

**Comment by equinusocio** [comment]
Just purge and reinstall it. Next time search for a similar issue. 👍

**Comment by oroszlanyzsolt** [comment]
Still no luck. I'have reinstalled Sublme Text 3 and removed all temporary files in:

- C:\Users\<user_name>\AppData\Roaming\Sublime Text 3
- C:\Users\<user_name>\AppData\Local\Sublime Text 3
- c:\Program Files\Sublime Text 3
- Deleted temporary files: C:\Users\Oroszlány Zsolt\AppData\Local\Temp
