### ISSUE TITLE
I have been using this theme for a few weeks now and I love it. However, this morning August 1, 2016 I opened Sublime and it no longer loads the Material theme. I have quit sublime and restarted it. changed to the different themes available and uninstalled the package entirely. Now I can't get the package to re-install. My theme says that it is using the Material Darker but it's actually showing the default sublime theme. 

### ISSUE THREAD

**Issue by donna-affinityps** [equinusocio/material-theme#928]
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

When submitting a bug report, please follow the following template:

---

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3...
* Material Theme release:
  * v3...

**Comment by edlahoz** [comment]
Having same issue

**Comment by equinusocio** [comment]
Please rename and provide informations in the correct way or i will close.

**Comment by donna-affinityps** [comment]
@equinusocio Please close and I will redo it on my personal github account.
