### ISSUE TITLE
Theme not loading at all in Sublime Text 3

### ISSUE THREAD

**Issue by dholmes87** [equinusocio/material-theme#929]
### Summary

I have been using the Material theme for a few weeks now and I love it. However, on August 1, 2016 I opened Sublime and the theme is no longer loading. I waited to see if the package needed to reload and nothing. I closed Sublime and restarted and still nothing. I uninstalled the package using package control and now when I try to re-install using package control it doesn't do anything at all. I have tried to install and activate the package manually but that doesn't seem to work either. 

### Expected behavior

I expect to see the theme load and my file menu and tabs show with the theme coloring a shown in your readme file.

### Actual behavior

The default Sublime theme is loading no matter what I have tried. 

### Steps to reproduce

1. Open Sublime
2. Load a project to see that the theme isn't working 
3. Restart Sublime
4. Uninstall Material theme through package control
5. Try to re-install and notice that it is not working. 
6. Manually install and change settings in user settings save and restart sublime but notice that the theme still isn't working. 

### Environment

* Operating system and version:
  * [x] Mac OS X El Capitan Version 10.11.16
* Sublime Text:
  * Build 3114 
* Material Theme release:
  * Not sure as I have uninstalled it and now can't re-install it. When I tried to install manually I was using the latest github build for download.

**Comment by XerWandeRer** [comment]
I have the same issue. It says in console:

```console
Package Control: An error occurred while trying to parse the dependencies.json for Material Theme.
```

**Comment by jackzh8** [comment]
I got the same problem.
`Package Control: An error occurred while trying to parse the dependencies.json for Material Theme.`

**Comment by equinusocio** [comment]
Whait the 3.1.2 release in minutes or just install it manually.
