### ISSUE TITLE
Latest Update

### ISSUE THREAD

**Issue by Takaya213** [equinusocio/material-theme#934]
Hi, after the latest update, my theme has stopped working completely. I have tried uninstalling it an reinstalling it, closing and opening Sublime in-between, and it still doesn't work, just shows me the default theme, no matter which one I try and use.

**Comment by equinusocio** [comment]
please read #925 #926 #927 #929 #930 #931

**Comment by adiachenko** [comment]
@equinusocio 7 releases in the last 7 days lol. I am happy you work on this package and enjoy using it very much. But i wish you would roll out updates less frequently. It almost feels like every time I open Sublime I need to wait for MT update and then more often then not I even need to restore my settings after update. This is too tedious.

**Comment by equinusocio** [comment]
@adiachenko I'm sorry but there was a s**t of bug that has blocked everyone on ST 3114. Now it's fixed and no more frequently updates
