### ISSUE TITLE
Provide instructions on how to change app icon

### ISSUE THREAD

**Issue by faergeek** [equinusocio/material-theme#935]
First, thanks for the best theme for sublime ever! 👍 

But it would also be cool to provide instructions in readme on how to change default app icon with the one provided (https://github.com/equinusocio/material-theme#other-resources).

**Comment by equinusocio** [comment]
Atm you can change the app icon only on OS X platform. At the moment i can't update the readme but i'm open to PR. 

To change the app icon just go into your `Applications` folder, select Sublime Text and press <kbd>Alt</kbd>+<kbd>Cmd</kbd>+<kbd>i</kbd> then drag the `.icns` file over the app icon in the info window. You have to remove/add ST to your dock to see the new icon.

**Comment by faergeek** [comment]
The problem is that there's no `.icns` file in provided archive, there's only single `.png`. And when I do it with png then sublime icon turns into standard os x icon for png files.

**Comment by RichieAHB** [comment]
@faergeek you have to copy and paste the icon from preview rather than drag the file type on it - that worked for me.  Although it not being an icns with relevant sizings, the icon looks very squashed at small sizes.

**Comment by equinusocio** [comment]
I'm sorry. This is the right package. I will update the readme file very soon.
[Material-Theme-Icon.zip](https://github.com/equinusocio/material-theme/files/396220/Material-Theme-Icon.zip)

**Comment by faergeek** [comment]
Great, it works, thanks! 👍

**Comment by equinusocio** [comment]
@faergeek you have to change the icon again every ST update.

**Comment by faergeek** [comment]
@equinusocio Thanks, it's ok for me :-)
