### ISSUE TITLE
Disable removing class importing on save if don't exist on the code.

### ISSUE THREAD

**Issue by giwrgos88** [equinusocio/material-theme#936]
I have created a class which binds dynamically interfaces and classes from an array. Instead of adding the class namespace in the array I want to add it as use on the top of the file. When I'm saving the file because I haven't mentioned the class in my code it removes it from top. How I can disable this feature?
When submitting a feature?

**Comment by equinusocio** [comment]
What you talking about?

**Comment by giwrgos88** [comment]
I'm talking about this 
<img width="418" alt="screen shot 2016-08-04 at 10 23 44" src="https://cloud.githubusercontent.com/assets/3164113/17393631/9bcb4f02-5a2d-11e6-8469-7f3d1b2d36cf.png">

If I have the following use Test\Model\Test; and don't use the Test model inside my code, on save the editor removes if from the file

**Comment by equinusocio** [comment]
And how you can think that this theme is the cause of this issue?

**Comment by giwrgos88** [comment]
Because It happened after I changed template to this one

**Comment by equinusocio** [comment]
Disable it and test eith other themes. Material Theme can't access to the code. I think you should investigate on other plugin
