### ISSUE TITLE
Search bar has lost it's styling in recent update

### ISSUE THREAD

**Issue by rorysmorris** [equinusocio/material-theme#937]
The sublime search bar has lost it's styling in recent update

Screenshot attached:

![screen shot 2016-08-04 at 10 41 27](https://cloud.githubusercontent.com/assets/15087652/17397447/0929a0ba-5a30-11e6-9d4b-4b74ec183700.png)

**Comment by equinusocio** [comment]
Just restart ST. Next time search for a similar issue and use the issue template.
