### ISSUE TITLE
Updates are too frequent

### ISSUE THREAD

**Issue by shah-newaz** [equinusocio/material-theme#938]
It's kind of annoying to get updates almost every other day. Can't updates be more cumulative ?

**Comment by equinusocio** [comment]
No if there are hofixes to do. Anyway you can disable auto update through Package Control palette and run update when you want.

**Comment by shah-newaz** [comment]
Thanks @equinusocio . I totally understand and appreciate your passion on this BEST EVER sublime text theme. Just the fact that I had to open an issue for such silly thing explains how annoying it can get haha! Maybe it's the way sublime text behaves when updating a theme.

I thought a more restrictive Git Flow can be beneficial here.
Understand hotfixes and stuff. Kudos again!
