### ISSUE TITLE
Material Theme should not define anchors as block

### ISSUE THREAD

**Issue by facelessuser** [equinusocio/material-theme#939]
### Summary

Currently Material Theme is defining links as `display: block`.  This should not be done.  As a default, this doesn't make sense.  Anchor tags are inline and should be treated as such.  This is breaking popups for people where images are wrapped in links.  See: https://github.com/facelessuser/ColorHelper/issues/52.  I could override this, but I shouldn't have to.

### Steps to reproduce

1. Install ColorHelper via Package Control and restart.
2. Initiate the `ColorHelper:  Show Color Picker` command from the palette.  All links are now blocks and images disappear if they are wrapped in blocks. 

### Environment

* Operating system and version:
  * All
* Sublime Text:
  * 3120
* Material Theme release:
  * Current

**Comment by equinusocio** [comment]
I think the generated image should be inline-block to fix this. Anyway i can only use inline-block, not inline

**Comment by facelessuser** [comment]
Oh, FYI, inline-block is not supported by Sublime's minihtml.

**Comment by equinusocio** [comment]
Because display block or inline block allows paddings and margins and i useful to avoid containers. I will investigate, thanks.
