### ISSUE TITLE
Updating too often

### ISSUE THREAD

**Issue by sunscreem** [equinusocio/material-theme#942]
Hi, 

Any chance of updating less often - its a real pain when I have to wait nearly a minute to start using sublime most days.

I love the theme and genuinely appreciate the work you do - but its becoming a pain :(

**Comment by equinusocio** [comment]
Really you can't wait 1 min for an update? Anyway, you can disable auto update through package control.

**Comment by sunscreem** [comment]
Sorry - I hope I didn't cause offence. I'll explain the problem more constructively:

I often find I need to open sublime just to do a very quick typo fix or edit a .ini file on my machine.

Its is frustrating when you open sublime and it just doesn't seem to work properly and there's no feedback as to why its going slow and not opening things. After about 30-40 seconds the theme goes white and then the "your theme has been updated dialog" appears over the top. I see a change log appear. I then have to close and re-open sublime to get rid of the white theme. Then, finally, I can get to work.

Maybe you don't see this as an issue because you're not experiencing this delay yourself? I can see from the close issues its been brought to you before.

I don't want to turn off the auto-update as I'll forget to update manually. So I have a suggestion - I'm wondering if you could maybe have a beta channel where those who want the very latest version can get the daily updates?

**Comment by ozanhazer** [comment]
I'm also unhappy with this. I mean I appreciate the hard work but it's really a concentration killer when some tab opens automatically and the theme goes back to original and then back to theme, some warning pops out telling that I might need to restart the editor etc.

And also sublime text resets itself occasionally back to default theme and I have to come back here to copy paste the exact name of the theme to the config...

Yes we can live with it, and we are, but it's just annoying. I'd agree with the beta channel or at least limit the updates to once per month or I don't know two weeks or so unless there's smt. critical...

**Comment by equinusocio** [comment]
You can reactivate the theme through the activator command panel

**Comment by ozanhazer** [comment]
nice tip thanks...
