### ISSUE TITLE
New color accents issues on open folder hover and tooltips

### ISSUE THREAD

**Issue by StromRick** [equinusocio/material-theme#943]
### Summary

If you select one of the new accent color added (sky, bright-teal, acid-lime, brba, tomato) the hover color keeps to stay teal (see screenshot), also the tooltip font color stays white and gives legibility issues

<img width="143" alt="schermata 2016-08-08 alle 15 57 52" src="https://cloud.githubusercontent.com/assets/20906966/17482217/feba1bba-5d80-11e6-820e-47f491125367.png">
![schermata 2016-08-08 alle 15 55 55](https://cloud.githubusercontent.com/assets/20906966/17482218/febbe152-5d80-11e6-9018-0a66d2ef12b1.png)
![schermata 2016-08-08 alle 15 55 34](https://cloud.githubusercontent.com/assets/20906966/17482216/feb9561c-5d80-11e6-883e-e4b751d356bc.png)

### Expected behavior

The folder color is expected to be the same as the accent color (as all others folders and old color accents do)

### Actual behavior

the hover on the open folder keeps being teal

### Steps to reproduce

1. Change accent color
2. hover on an open folder

### Environment

* Operating system and version:

  * Mac OS El Capitan 10.11.5

* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.6

**Comment by equinusocio** [comment]
You use `material_theme_disable_folder_animation: true`?

**Comment by StromRick** [comment]
yes i do, that's my configuration:

`"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_sky": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"overlay_scroll_bars": "enabled"`

**Comment by equinusocio** [comment]
mmm wait, in your screenshot you're not using the sky accent, you are using the `acid-lime` accent.

**Comment by StromRick** [comment]
sorry, i forgot to say that i changed color few minutes ago (the differences in the hover colors are less prominent), but the issue is the same
