### ISSUE TITLE
Theme reset to default after automatic update

### ISSUE THREAD

**Issue by graphem** [equinusocio/material-theme#945]
Not sure if anyone is experiencing this, but my user settings are reset to the default theme and color_scheme whenever this package is updated, this is annoying as I need to go in and add again the theme and color_scheme. I am using sublime 3. Thanks.

**Comment by maketroli** [comment]
It's happening the same to me. Sometimes happens when I close Sublime and open it again.

**Comment by graphem** [comment]
Seems my colleague was having the same and he stop using the theme for this reason

**Comment by yPangXie** [comment]
The same to me.

**Comment by dingo-d** [comment]
Same happened to me yesterday. Luckily I keep a backup of my settings on the desktop so I just copy paste the whole thing back. I had to remove and install Material Theme 3 times yesterday to got it working. Now I've just disabled the automatic update for it. I'll update every month or so, just to be up to date, but this really gets annoying...

**Comment by equinusocio** [comment]
#837, #702, #387, #327, #258, #234 and many more... this is a Package Control issue. Just wait until theme update and it will be reactivated. If doesn't try from (#234):

> Hey guys and girls. Here one solution that works for sure and I will share to all. Linux OS works but I wan't to hear others from other OS to confirm that works. And if all OS works then @equinusocio you can close all this and put solution in readme. Find that file Preferences.sublime-settings (~/.config/sublime-text-3/Packages/User for Linux users) and just take away write permission that is it. Be honest you are not changing that file every day so giving just read permission and take away write permission will not harm you. When you want to make changes you will give temporary write permission till you done and you are done. Next time theme update you will be asked to restart you will restart and that is it, life goes on. No more re adjustment in user configuration file on each update. @equinusocio keep good work! Thanks for the awesome theme and that you keeping up to date.
