### ISSUE TITLE
Material theme not working

### ISSUE THREAD

**Issue by sweettimes** [equinusocio/material-theme#946]
I can not active material theme, please view this image

![screen shot 2016-08-10 at 8 27 16 pm](https://cloud.githubusercontent.com/assets/566289/17555281/301406e4-5f39-11e6-9b65-c9bab14a090e.png)

• ST ver.:   3103
• Platform:   osx
• Arch:   x64
• Theme:   3.1.4
• Install via PC:   True
• mdpopups:   Version could not be acquired!
• markdown:   Version could not be acquired!
• pygments:   2.1.3
• jinja2:   Version could not be acquired!

### Environment

* Operating system and version:
  * [x] Mac OS 10.11.6
* Sublime Text:
  * Build 3103
* Material Theme release:
  * v3.1.4

**Comment by equinusocio** [comment]
Run "Satisfy Dependencies"

**Comment by sweettimes** [comment]
Oh thank you, I updated this package and it working well (my country network is very slow so it can not auto update the package).
