### ISSUE TITLE
Yellow accent isn't very yellow

### ISSUE THREAD

**Issue by anhuynh** [equinusocio/material-theme#947]
### Summary

The yellow accent looks more orange than yellow.

### Expected behavior

![yellow1](https://cloud.githubusercontent.com/assets/12944605/17572841/ab9f5382-5f24-11e6-9a36-be80ddd08ef4.jpg)

This is using yellow A400 (#FFEA00) from Google's material colour palette.

### Actual behavior

![yellow2](https://cloud.githubusercontent.com/assets/12944605/17572863/cad871fc-5f24-11e6-95b7-cc9ec7cd1b41.jpg)

### Steps to reproduce

1. Choose yellow accent colour

### Environment

* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.7

@equinusocio I could change the yellow and make a pull request but I was wondering what your process is in changing the asset icon colours. Is there a fast way to do it?

**Comment by equinusocio** [comment]
It's taken from the material design yellow color palette
https://material.google.com/style/color.html#color-color-palette
