### ISSUE TITLE
Theme sometimes reverts back to default

### ISSUE THREAD

**Issue by Orbyt** [equinusocio/material-theme#949]
### Summary

Every once in awhile, i'll open up sublime text and it will be back on the default theme. To fix the issue, I simply go to Preferences->Settings-User and reactivate the theme with:

```json
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
"theme": "Material-Theme.sublime-theme",
```

### Steps to reproduce
The bug seems to be random, and I haven't been able to reproduce on command.

### Environment

* Operating system and version:
  * [x] Windows 10 64 bit
* Sublime Text:
  * Build 3114
* Material Theme release:
  * Whatever the latest is

**Comment by Stormiix** [comment]
I believe this happens when the theme get's updated by package control , from my experience , it would usually fix itself after minutes.. or sometimes in only few seconds.
So this isn't really an issue with the theme.

**Comment by Orbyt** [comment]
@Stormiix Usually with an update I'll get a file open listing the new changes to the theme. That doesn't happen when this issue occurs.

**Comment by farizsofyan** [comment]
I also having this problem for few times when i restarted the Sublime and it updated something (PyV8 perhaps).

**Comment by anhuynh** [comment]
@Orbyt You should research other issues like this before opening a new one. Two issues exactly like this were opened in the past day and were closed because it has been raised so many times before. See @equinusocio's last comment in #945.

**Comment by Orbyt** [comment]
@anhuynh Yes, but the issue here was that this seemed to be happening without an update.

I'll have to look a little closer next time it happens to be sure.

**Comment by matteocontrini** [comment]
This is annoying even when it's an update issue... releases are a bit too much frequent with a new update causing this issue every other day. I'd suggest reducing the pace of public releases...

**Comment by Orbyt** [comment]
Why was this closed? This is a legitimate problem that occurs almost every other time I open ST, and only occurs with this theme.
