### ISSUE TITLE
Sublime Text 3 not responding after installing the theme

### ISSUE THREAD

**Issue by setzer17** [equinusocio/material-theme#953]
I installed Material theme for the first time yesterday, and it was working perfectly. Today, when I opened sublime , it was not responding. The only thing that was  responding was the Menu area. I restarted the OS, but the problem still persists.
The way I fixed it was by simply resizing the window. It was maximized, after I resized it by clicking on the window button, sublime started working normally.

Sublime build: 3114
OS: Ubuntu Mate 16.04.1 on a VM
Material theme: 3.1.9

**Comment by equinusocio** [comment]
Try to close all workspaces and make a new project workspace

**Comment by setzer17** [comment]
I will try that the next time it freezes cause now it's working fine. I will let you know when it happens again.

**Comment by setzer17** [comment]
It just happened again. I closed all files and opened the code folder again and it worked fine.
But why is it happening?

**Comment by equinusocio** [comment]
Try also to build a new project workspace under the Project menu. This is a sublime issue that crash when it has to handle opened files and a theme/scheme change occurs.

**Comment by brtknr** [comment]
+1 this issue. The  issue is temporarily resolved when I close the project and restart Sublime but it reoccurs after some usage. I have now removed Material these and Sublime text is stable again.

**Comment by equinusocio** [comment]
Try to build a new workspace not close/reopen a project. Go to `Project > New Workspace for Project`.

**Comment by brtknr** [comment]
Ok I will try again and let you know on Monday! It works fine on my personal Macintosh OSX install.
