### ISSUE TITLE
Find & Replace: results displayed in place of search box

### ISSUE THREAD

**Issue by yumyo** [equinusocio/material-theme#955]
### Summary

When using the `Find & Replace` function in a sidebar folder, the behaviour has always been to display the found results in a file window (like any other file). However, since the last (or second to last) theme update, search results are displayed in place of the `Find & Replace` panel. 

How to switch it back to normal?

### Expected behavior

**Find & Replace** results displayed as usual, in file window like any other file. 

### Actual behavior

**Find & Replace** results displayed in place of the **Find & Replace** panel

### Steps to reproduce

1. Click on folder in sidebar
2. Select **Find & Replace...**
3. Results are displayed inside the **Find & Replace** panel  instead of the file window. 

### Environment

* Operating system and version:
  * Mac OS 10.11.6 (15G31)
* Sublime Text:
  * Build 3114
* Material Theme release:   
  • 3.1.4   
  • Install via PC:   True   
  • mdpopups:   1.9.3   
  • markdown:   2.6.6   
  • pygments:   2.1a0   
  • jinja2:   2.8

**Comment by yumyo** [comment]
For some reason I can't get 3.1.9 from package manager. I am updating manually

![01](https://cloud.githubusercontent.com/assets/959034/17695734/e8e8161c-63a1-11e6-97fb-a5258db2232f.jpg)
![02](https://cloud.githubusercontent.com/assets/959034/17695736/e8ea1746-63a1-11e6-8489-67ad239808aa.jpg)
![03](https://cloud.githubusercontent.com/assets/959034/17695735/e8ea0c88-63a1-11e6-8808-f22e62ab7617.jpg)
![04](https://cloud.githubusercontent.com/assets/959034/17695737/e8ea914e-63a1-11e6-9754-a4ee942c084d.jpg)

**Comment by yumyo** [comment]
well, removing material theme didn't solved it, so I'll definitely exclude they are directly related

**Comment by oivva** [comment]
@yumyo It's not theme related & not the bug. Just click `Use Buffer`:

![image](https://cloud.githubusercontent.com/assets/9801624/17695953/db93e0ba-63b3-11e6-9d8f-64c76a7ebf6d.png)

**Comment by equinusocio** [comment]
Thanks @oivva  👍 :)
