### ISSUE TITLE
Suggestion: Reduce frequency of official releases.

### ISSUE THREAD

**Issue by cpruitt** [equinusocio/material-theme#956]
I'd like to offer a little bit of feedback and hopefully submitting it as a GitHub issue isn't too off base. The release schedule for Material Theme seems like it might be a little "overly enthusiastic". On one hand i *very much* appreciate the amount of development time spent on the theme and the attention to bug fixes and improvements. On the other hand, it's become a bit of a recurring point of humor among our development team that it is impossible to launch ST3 without being told that Material Theme has updated and that we should relaunch the editor to prevent display issues. If it were not for the constant need to relaunch ST3 it wouldn't be much of an issue and, to be fair, it's just something that occurs on editor launch. That being said, it happens enough to be something that each member of our team independently identified as a point of frustration before it came up in group conversation.

So all that to suggest maybe limiting public Material Theme updates (other than critical fixes) to a more regular schedule, whatever that may be, and do more pre-release builds in between actual releases. It would certainly remove a point of friction we experience and, though I may very well be the minority, perhaps improve the experience for some other users as well.

Thanks for listening!

**Comment by equinusocio** [comment]
All sudden updates that are released are always hotfix . And since the cause of sublime text inactivity , you better have some update rather than a blocked editor .

You and your team can turn off automatic updates from the Package Control and update material theme manually when you are most comfortable .

**Comment by cpruitt** [comment]
Certianly you want to take the approach that's best for both you and for most of Material theme's users. I'm just trying to share one point of view that may (or may not) be shared by a wider user base than just myself. I guess my thought was mainly that it seems like there are a lot of "hotfix" releases that might not be all that critical in nature. There was another release today, and I think the last release was just a few days ago. If those fixes are really things that needed to be pushed out as quickly as humanly possible because many users have widespread issues, then I'm all for the update, but in this case there are changes logged like "improve markdown highlighting" and "R file type icon". Those don't really seem too "hotfixy" in terms of critical issues and seem like things that could be rolled up into larger releases that are pushed with less frequency.

Package control does not support beta channels, but I think (goodness knows I am NOT an expert here) that it does support the `install_prereleases` setting which I believe allows package authors to release frequent updates with a `-prerelease` version suffix which users can opt into, and lets most users just pull the combined regular releases with less frequency.

Again, please don't think I'm cranky or picking a fight over this or anything. It's not the end of the world and I think I can disable auto-updates for material theme using `auto_upgrade_ignore`. I just wanted to pass on our opinion because as the author pushing out the releases, you might not be aware of the apparent frequency of them for those of us on the receiving end.

Either way, thanks for the theme. Best I've encountered.

**Comment by HendrikPetertje** [comment]
I opened an issue a few months ago on the same topic. 
Here in the office it has become kind of a joke to see if a developer had time to actually write code during a day. An other colleague simply opens sublime text. if there's a sublime update for the material theme then.. we have a good laugh.

But in all seriousness, if all my small style fixes would mean a hotfix then the Apple Appstore + Google would have a hard time keeping up with my proposed updates all the time. not to mention the annoyance of update notifications on my users phones all the time :). having to turn off auto update while having other plugins running to that do things with SSL and stuff sound like a very unsafe idea, sorry. 

I absolutely love your theme, it's amazing really! (having at least 10 peeps in the office using your theme no matter the updates does tell something about the quality of your theme ;))

for your release schedule you could look into "git flow". Sublime does allow the option to install pre-releases, simply name your develop branch to be the source for those packages while master follows the bigger releases.
