### ISSUE TITLE
Separators between columns/panes are very hard to see.

### ISSUE THREAD

**Issue by chanpory** [equinusocio/material-theme#957]
How do I change the color of the separator between columns? They're impossible to see and I have a hard time adjusting my columns because of it. Is there a setting for this?

Also, is there a setting to make the separator between tabs darker as well.

I'm old and need a little a bit more contrast, but I like the theme overall.

**Comment by equinusocio** [comment]
Related to #254, #393, #439, #290. You can customize your local theme installation.

https://github.com/equinusocio/material-theme/issues/305#issuecomment-120479395

**Comment by chanpory** [comment]
@equinusocio thanks! i created a Material-Theme.sublime-theme to customize. I was able to change the column dividers, but I cannot figure out how to change the separators or spacing between tabs. Do you know which properties?

**Comment by equinusocio** [comment]
The tab separator is an Image. So you have to replicate the assets directory and put the new Image inside

**Comment by chanpory** [comment]
I'm having trouble overriding the asset. I've created a `Material-Theme.sublime-theme` to override styles and replicated the `assets` directory from your Github repo into my `User` directory, but still cannot override the assets. Here is the structure of my `User` folder

```
User
- Material-Theme.sublime-theme
-- Material Theme
---Assets
----commons
-----tab_separator.png

```

Is there another way I should be setting up the structure?
