### ISSUE TITLE
Folder icons are not pixel-fitted

### ISSUE THREAD

**Issue by chanpory** [equinusocio/material-theme#958]
On a non-retina external monitor, the folder icons are slightly blurry and not pixel-fitted to be sharp.

**Comment by equinusocio** [comment]
Only these icons are blurry? Anyway i can't handle this behavior because Sublime Text detect the assets resolution to use. So on a retina display it will use @2x images and on a non-retina display it will use the default @1x images. Both resolutions are available and probably ST fail to use both @1x and @2x when you use an external monitor with a different pixel density. I'm sorry, maybe you can report this issue on the official ST forum.

**Comment by chanpory** [comment]
@equinusocio I mean that the assets themselves are not aligned to the pixel-grid, so this isn't an issue with ST itself. Here is an example or a blurry asset: 

https://github.com/equinusocio/material-theme/blob/develop/assets/accent-blue/folder_opened--hover.png

This might a result of the tool you're using to rasterize the icons. The lines are landing at half pixels causing some blurriness. This occurs on your Retina assets as well, but it's less apparent because of the higher-res. Are you using Sketch, Illustrator, or Photoshop to create the assets?

Here's a bit of info on pixel grids: https://www.smashingmagazine.com/2014/10/create-assets-for-multiple-scale-factors/

Everything else about this theme is sharp, except for the icons.

**Comment by equinusocio** [comment]
You're right. I will fix these icons.

**Comment by enkia** [comment]
@equinusocio I've pixel fitted the icons in Sketch but it seems to me that when doing so, it changes the original design of the 'opened folder' material icon. The border is thinner on Retina screens than I'd like.  

Thoughts? You can test accent-blue using [these icons.](https://github.com/enkia/misc/tree/master/accent-blue)

**Comment by equinusocio** [comment]
@enkia You have to multiply. So if on a normal display the folder icon have 2px on a retina display the border should be 4px, not 1px. Thanks for the help.

**Comment by enkia** [comment]
I tried true 2x borders at first but it was *too* thick in my estimation. For my own version of your theme, I settled on 1px in the end.

**Comment by equinusocio** [comment]
Ok.. so you're working on your own theme version? Ook.

**Comment by enkia** [comment]
Yeah, I mentioned it awhile back. :) [It's up!](https://packagecontrol.io/packages/Enki%20Theme)
