### ISSUE TITLE
Please return old icons for Python. (in last update you 've changed it to new style icons)

### ISSUE THREAD

**Issue by ArtemBernatskyy** [equinusocio/material-theme#961]
[Screenshot](https://vk.com/doc344585549_437781892?hash=5b35f3dd2b78dbb7e7&dl=38e826be5146479761).
In previous update this icons were all yellow like.  
P.S. Leaving star for great work:)

**Comment by equinusocio** [comment]
... You're not using materiale theme. I think You're using Boxy theme that doesn't have anything to do with materiale theme.

**Comment by oivva** [comment]
@ArtemBernatskyy Yes, that's Boxy. See: https://github.com/oivva/boxy/issues/111

**Comment by ArtemBernatskyy** [comment]
Yes, i wrote in the wrong place.
