### ISSUE TITLE
Anyway to adjust the color darkness with a parameter?

### ISSUE THREAD

**Issue by eromoe** [equinusocio/material-theme#963]
I turn my monitor very dark(brightness 0), because the browser's white background would hurt my eye.
Normal theme is look good if I use brightness 40, but if lower than 40 , it become more hard to see comment  and  tag names.

So, I want to turn material-theme a a little light, but I don't know how to do. such as a config parameter like "darkness": "0.8".

PS: I can't use the light theme, too bright for me .

**Comment by equinusocio** [comment]
You have to overwrite and customize the theme. Search through closed issues.

**Comment by eromoe** [comment]
`Advanced configuration` is grey out.
I don't find some issues relate to mine. All they says are color not correct ....

**Comment by yllexie** [comment]
My advanced configuration is grey out too.Still looking for solution...

**Comment by equinusocio** [comment]
The advanced configurazione isn't related to this issue. If you want to edit configurazione through the code jus open sublime preferences.
