### ISSUE TITLE
Tab hover fade out animation

### ISSUE THREAD

**Issue by iGombar** [equinusocio/material-theme#964]
Probably a silly thing, but my OCD isn't giving me any rest. 

When you hover over tabs the bar at the bottom smooths in, but when you move the pointer away from the tab it just disappears abruptly. Is there a way to make it fade out? Literally what it does already but the opposite way would be fine.

**Comment by equinusocio** [comment]
ATM isn't possible. The fade animation is a sort of trick that cause visual glitches if used on "tab-blur"
