### ISSUE TITLE
B

### ISSUE THREAD

**Issue by jpstone** [equinusocio/material-theme#968]
The background for the text inside of open tabs has suddenly turned black after an upgrade. I have tried restarting sublime text 3 to no avail. I have also copied my user package settings to a different computer and the issue transfers between computers.

Info for my material theme installation:

- Sublime Text:   3114
- Platform:   osx
- Arch:   x64
- Theme:   3.1.10
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

Screenshot of issue:

![image](https://cloud.githubusercontent.com/assets/5823372/17937294/990790ce-69ef-11e6-9c00-77b3e9904b37.png)

My user preferences:

```{
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_size": 11,
	"ignored_packages":
	[],
	"material_theme_small_tab": true,
	"material_theme_tabs_separator": true,
	"rulers":
	[
		80
	],
	"tab_size": 2,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true
}```

Any help is appreciated.

Thanks!

**Comment by anhuynh** [comment]
That looks like you are using the Monokai color scheme even though your preferences say Material Theme. Have you tried switching the color scheme to something else and then back to Material?

**Comment by jpstone** [comment]
That did the trick, thanks!
