### ISSUE TITLE
Advanced new file not displaying the input correctyle.

### ISSUE THREAD

**Issue by OctoD** [equinusocio/material-theme#97]
![schermata del 2015-06-15 12 41 52](https://cloud.githubusercontent.com/assets/2328211/8158265/edfa1ea8-135b-11e5-804e-98428511e9a2.png)

As you can see, the prompt for ANF is not properly showing. This happens only while using MaterialTheme (awesome theme, btw).

Cheers &  ciao Mattia :)

**Comment by equinusocio** [comment]
Pls see #67 for the fix
