### ISSUE TITLE
Italic issues: pipe symbol now a forward slash 

### ISSUE THREAD

**Issue by SamPotts** [equinusocio/material-theme#970]
### Summary
Pipe symbols seem to be italic now making them look like forward slashes. I'm not sure if we need `if`, `function` etc in italic but it seems the change has broken more than it's improved. Also things like `!==` in an if stratement is now in italic too. 
...

### Expected behavior
```javascript
var x = x || {};
```
...

### Actual behavior

```javascript
var x = x // {};
```
...

### Steps to reproduce

1. Write `||`
2. Be confused whether you wrote `||` or `//`

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS 10.12
  * [ ] Linux ...
* Sublime Text:
  * 3120
* Material Theme release:
  * 3.1.11

**Comment by SamPotts** [comment]
Perhaps this was introduced as part of #960

**Comment by jayflo** [comment]
For me I get italics on `||`, `var`, `if`, `return`, `function`.  I can't tell but maybe `=` also.

**Comment by equinusocio** [comment]
<img width="304" alt="screen shot 2016-08-31 at 18 52 02" src="https://cloud.githubusercontent.com/assets/10454741/18138225/061b1638-6fac-11e6-9676-1fb666571326.png">

Now only `storage.type` and `keyword.control` will be italic.

**Comment by Revod** [comment]
@equinusocio how you make the Operator Mono italic work  completely in sublime? Here how look mine:
![image](https://cloud.githubusercontent.com/assets/10109689/18144782/5b6f6c30-6f96-11e6-8da2-f43d45470de9.png)

This is my setting
```json
"font_face": "Operator Mono Medium",
	"font_options":
	[
		"subpixel_antialias",
		"gray_antialias"
	],
	"font_size": 10,
	"highlight_line": true,
`

I'm on Windows 10 Anniversary Update (Build 14393.82)

**Comment by SamPotts** [comment]
Thanks @equinusocio - that looks good to me. I'll give it a go 👍

**Comment by equinusocio** [comment]
@Revod 
```json
	"font_face": "Operator Mono",
	"font_size": 14,
	"font_options": ["gray_antialias"],
```
