### ISSUE TITLE
Remove "Material Theme" from the right click menu 

### ISSUE THREAD

**Issue by oconnor0** [equinusocio/material-theme#971]
I dislike the recent addition of "Material Theme" to the right click menu. I don't like the clutter. I would like to either see it removed - or if that isn't viable - to see an option to disable it.

**Comment by equinusocio** [comment]
You can use the command palette if you don't want to use the context menu.

**Comment by mrhyde** [comment]
Why force people to dislike something that was made well in past? Why not make things optional?
I personally dislike the style of new menu. I think it's ugly, out of place and not user-friendly

**Comment by equinusocio** [comment]
@mrhyde what style of new menu? o.O 

> Why not make things optional?
Because it can't be optional.

**Comment by mrhyde** [comment]
> what style of new menu? o.O

this one
![](http://i.imgur.com/oUGaoOY.png)

**Comment by equinusocio** [comment]
lol.. it's a bug. Should looks like:
<img width="340" alt="screen shot 2016-09-09 at 12 01 48" src="https://cloud.githubusercontent.com/assets/10454741/18383322/3f51a428-7685-11e6-84b4-458354f22fed.png">


Please try to run "Satisfy Dependencies."

**Comment by mrhyde** [comment]
Tried that many many times (and just now) - it was always like this.

OS: Windows 10, Build 14915
Sublime Text 3, Build 3114

**Comment by equinusocio** [comment]
@mrhyde You have to wait 3119 release.

**Comment by mrhyde** [comment]
after updating to 3120 it became better but still have font issues
![](http://i.imgur.com/GYOunrs.png)

**Comment by equinusocio** [comment]
@mrhyde can you paste here ad arrow simbol that you see on windows?

You see one of these?
← ❮ 〈

**Comment by mrhyde** [comment]
In both Chrome and Firefox I can see, copy and paste this symbols `← ❮ 〈`
But when I copy them to Sublime Text I get this ![](http://i.imgur.com/8Hw64wY.png)

**Comment by kennith** [comment]
@oconnor0 You can disable the right context menu by adding an empty Context.sublime-menu file in the Packages\Material Theme\Context.sublime-menu

**Comment by oconnor0** [comment]
@kennith Wonderful, thank you. :)

**Comment by equinusocio** [comment]
@mrhyde Back arrow (will be ←) updated in the next release.
