### ISSUE TITLE
Pipe looks like Slash

### ISSUE THREAD

**Issue by hrantly** [equinusocio/material-theme#972]
### Summary
Pipe looks like slash
...

### Expected behavior
Pipe to look like pipe :smile: 
...

### Actual behavior
Pipe looks like slash
...

### Steps to reproduce

1. Open sublime text 3 
2. Open php file
3. in IF statement see how || looks like.

### Environment

* Operating system and version:
  * [x] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3...
* Material Theme release:
  * v3...

**Comment by equinusocio** [comment]
#970
