### ISSUE TITLE
Line Number color is too similar with background, making line numbers hard to read

### ISSUE THREAD

**Issue by icecold21** [equinusocio/material-theme#973]
### Summary

Line Number color is too similar with background, making line numbers hard to read

### Expected behavior

Brighter color to make it easier to read

### Actual behavior

very close to background color

### Steps to reproduce

simply open a file with content through sublime editor

### Environment

* Operating system and version:
  * [V] Windows ...
  * [V] Mac OS ...
  * [V] Linux ...
* Sublime Text:
  * Build 3114
* Material Theme release:
  * 3.1.11

**Comment by equinusocio** [comment]
Search for a similar issue.
