### ISSUE TITLE
The new color scheme hides characters in Markdown

### ISSUE THREAD

**Issue by rock3r** [equinusocio/material-theme#974]
### Summary

The new Material Theme color scheme, when writing Markdown, makes some characters invisible, such as backticks and blockquote `>`s:

![image](https://cloud.githubusercontent.com/assets/153802/18210031/865aa7d6-712e-11e6-9798-972c01cca274.png)

(no, there is no text selected in this screenshot)

### Expected behavior

All characters should be readable, such as with the old scheme:

![image](https://cloud.githubusercontent.com/assets/153802/18210165/224b5d48-712f-11e6-99e4-43d8fa8732b5.png)

### Steps to reproduce

1. Create markdown document
2. Use backticks to highlight `code` or `>`s for blockquotes
3. Observe results

### Environment

* Operating system and version: Mac OS El Capitan
* Sublime Text: Build 3114
* Material Theme release: v3.1.11

**Comment by rock3r** [comment]
Grazie @equinusocio!

**Comment by equinusocio** [comment]
<img width="272" alt="screen shot 2016-09-02 at 19 21 57" src="https://cloud.githubusercontent.com/assets/10454741/18212301/b7f3b31e-7142-11e6-9a73-9fa446187b7b.png">
