### ISSUE TITLE
Latest Release (3.1.11) Set italic for storage.type scopes

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/material-theme#976]
Why not make italic optional? If it possible. Otherwise how can I disable it myself (preferably without switching to a old version `OLD -> Material Theme`)?

**Comment by equinusocio** [comment]
This can't be a preference because ST doesn't allow preferences for color schemes but UI only

**Comment by oivva** [comment]
@Zx-EvM You can disable italics per syntax or at all via:

```js
    // Valid options are "no_bold", "no_italic", "no_antialias", "gray_antialias",
    // "subpixel_antialias", "no_round" (OS X only), "gdi" (Windows only) and
    // "directwrite" (Windows only)
    "font_options": ["no_italic"],
```

**Comment by equinusocio** [comment]
@Zx-EvM @oivva This will disable all italic style from ST/syntax, not only in Material Theme or any other packages.

**Comment by oivva** [comment]
@equinusocio I know, but as option. For example I don't like italics at all, except `Markdown` syntax.

**Comment by equinusocio** [comment]
Yes i know that you know :)
