### ISSUE TITLE
Italic for || , === etc

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#977]
With a latest update, logical and comparison operators are in italic form. I think it's a terrible idea, take a look on this code,

<img width="565" alt="screenshot 2016-09-06 16 49 35" src="https://cloud.githubusercontent.com/assets/304929/18278465/856b9a70-7452-11e6-970c-04cae59e8333.png">

`||` OR operator, looks like a comment `//`.. it's really confusing. The same I can say about `===`, `!==`,  etc.

What was the reason to do that?

**Comment by equinusocio** [comment]
#970

**Comment by wuron** [comment]
So is it fixed?
`||` is still in italics for me.
I’m using material-theme v3.1.11 and sublime-text 3 v3114 on Ubuntu.

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/releases/tag/v3.1.12 is the latest release but seems that PC doesn't update the package.
