### ISSUE TITLE
pipes look like slashes

### ISSUE THREAD

**Issue by felixhageloh** [equinusocio/material-theme#978]
Since the latest update certain symbols are rendered italic (I guess when they are recognized as a keyword/operator). 

The issue is that for some fonts - I think the ones that have full italic support - the pipe symbol become almost indistinguishable from a slash. So 

`||` and `//` look virtually the same. 

I've tested this with [Ubuntu Mono](http://font.ubuntu.com) and [Source Code Pro](https://github.com/adobe-fonts/source-code-pro/releases) and with both I get this issue. Menlo on the other hand doesn't. 

Is there a chance to revert this or is there a way I can configure the italics?

**Comment by equinusocio** [comment]
#970

**Comment by felixhageloh** [comment]
thanks for pointing me to the existing issue. So has it been fixed in the latest release? I don't have an update coming in yet

**Comment by felixhageloh** [comment]
ah I see it in the release notes - Package Control still uses an older release I guess. I'll wait till updates trickle through (or update manually). Thanks!

**Comment by felixhageloh** [comment]
Ok i did verify that I have the latest version, but I still have this issue

**Comment by felixhageloh** [comment]
- Sublime Text:   3114
- Platform:   osx
- Arch:   x64
- Theme:   3.1.11
- Install via PC:   False
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by equinusocio** [comment]
The Fox isn't yet released
