### ISSUE TITLE
Better delimitation of sections

### ISSUE THREAD

**Issue by redgluten** [equinusocio/material-theme#98]
I like the overall look of the theme a lot but the lack of delimitation for the different parts of the UI is not a good idea for practical usage. Form should follow function, etc. Could there be an option to add contrast like the [the one in Mac OS X Yosemite](http://osxdaily.com/2014/10/22/increase-contrast-mac-os-x-yosemite/)?

**Comment by equinusocio** [comment]
Not at the moment sorry.
