### ISSUE TITLE
Feedback: The new italics style for keywords is distracting

### ISSUE THREAD

**Issue by kommen** [equinusocio/material-theme#981]
Hi @equinusocio,

first thanks a lot for your awesome work. I like the dark theme and color scheme a lot!

Just one feedback to the recent change https://github.com/equinusocio/material-theme/commit/e9534c404ddab8c4bb596f218b5b16f4bae352fd for making keywords italic: 
I can see a use case for some languages, however, I find it very distracting.

For example, in ClojureScript the `@` symbol is now italic, which bothers me most. Example: http://imgur.com/zf9TVNB

For now, I just copied the theme and reverted the change, as there doesn't seem to be an option to just override that. Would it be possible to make that an option somehow?

Thanks again!

**Comment by equinusocio** [comment]
You can disable italics with the sublime setting `font_option`. You can disable It globally or pee-syntax.

**Comment by kommen** [comment]
Ah, I didn't know that, thank you!

**Comment by equinusocio** [comment]
As always: "Know your tools" ;)
