### ISSUE TITLE
Material Theme freezes ST on startup

### ISSUE THREAD

**Issue by huyvohcmc** [equinusocio/material-theme#983]
### Summary

Sometimes when I open Sublime Text with Material Theme activated, it just freezes. I cannot use any keyboard shortcut, I cannot click on anything on the sidebar. The only way to get rid of it is to close the windows and open it up again. I tried to remove Material Theme and everything works fine. I notice that the problem only appear when Material Theme is installed and activated.

### Expected behavior

ST works normally when started with Material Theme.

### Actual behavior

It freezes like this:

![issues](https://cloud.githubusercontent.com/assets/17645203/18474163/ee36422e-79ea-11e6-9457-d6b5a89f6f44.png)

### Steps to reproduce

1. Open up ST with some existing projects.

### Environment

* Operating system and version:
  * [ ] Linux: Ubuntu 16.04.
* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.12

**Comment by equinusocio** [comment]
#953 Build build a new project workspace
