### ISSUE TITLE
the theme ui don't use my set default font

### ISSUE THREAD

**Issue by unixc3t** [equinusocio/material-theme#984]
### Summary
I install the theme and reset idea . the theme activate ,but the theme ui font is changed, it doesn't use my default  font
the error font is activated when i change the ui and restart idea

### Expected behavior
 I change the theme 
 the Appearance > default font  is Comic Sans Ms
I want the new ui font is Comic Sans Ms

### Actual behavior
1 I change the theme 
2 the Appearance > default font  is Comic Sans Ms
3  but  the new ui  font actual is other font  
4 I change the font is Comic Sans Ms and restart idea
5 I open the idea ,it's can't apply my Comic Sans Ms ,I have to set the default font again
![_001](https://cloud.githubusercontent.com/assets/4446148/18514084/b1676dfe-7ac2-11e6-9720-db3afeb33ca0.png)

### Environment

ubuntu 16.04 64bit

###Tools
Idea community 2016.2.4 

* Material Theme release:
  1.4.4

sorry ,I am english is weak

**Comment by equinusocio** [comment]
Report this issue on https://github.com/ChrisRM/material-theme-jetbrains 👍
