### ISSUE TITLE
Beautify the context menu!

### ISSUE THREAD

**Issue by phiterf** [equinusocio/material-theme#987]
I'm using [SideBar Enhancements plugin](https://github.com/titoBouzout/SideBarEnhancements) and I don't think the context-menu matches the current layout of the theme.

![image](https://cloud.githubusercontent.com/assets/12252332/18747937/44488ec6-80a6-11e6-97e8-7d46bf98a26f.png)

Now, if you could make it dark, and add some icons it would be really cool (if possible).

Take as an example the PHP Storm context menu, it fits the theme.

Also, the arrow icon by the side of the folders would look nice as well, but I guess it's not that necessary, since you have a different icon for open folders.

![image](https://cloud.githubusercontent.com/assets/12252332/18748032/dce93c3e-80a6-11e6-8b97-6624430a053e.png)

**Comment by equinusocio** [comment]
Sublime Text use the system context menu...
