### ISSUE TITLE
Syntax color for the latest darker theme

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme#988]
Hi @equinusocio 

I'm setting up my portable ST3, and when I installed theme, the color highlights seems to be quite different from what I have now (I later found out the OLD darker theme actually looks the same as the one I'm using).

New One:
![image](https://cloud.githubusercontent.com/assets/17170199/18901898/32ece9a6-8592-11e6-96a9-50c08190915f.png)

Old One:
![image](https://cloud.githubusercontent.com/assets/17170199/18901952/86c7a656-8592-11e6-8f8b-773b989eda2a.png)

Could you please post a syntax screenshot here for the latest darker color theme? (A dummy class in python would do the job) Thanks.

**Comment by equinusocio** [comment]
<img width="954" alt="screen shot 2016-09-28 at 09 48 41" src="https://cloud.githubusercontent.com/assets/10454741/18904914/c1765496-8560-11e6-9785-f41447c46bc7.png">

**Comment by pingshunhuangalex** [comment]
Thanks for the screenshot. Just wonder what's wrong with the old colour theme?

Also, is it possible to make the white text pale gray just like what u did in the old theme? I think it goes easier on the eye this way. Don't u think?

**Comment by equinusocio** [comment]
@pingshunhuangalex The new refactored schemes use a dynamic color system and compilator that allow easy maintenance and customization. You can use the old schemes but no updates will be released.
