### ISSUE TITLE
Tab Separator Option Stop Functioning

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme#989]
Hi @equinusocio 

It's me again. Continuing tuning my ST3, I found that the ``` "material_theme_tabs_separator": true, ``` stops functioning. Setting it to ```true``` won't suppress the hover animation, and there is no visual difference, i.e. no separator can be seen. Thanks.

**Comment by equinusocio** [comment]
<img width="369" alt="screen shot 2016-09-28 at 11 26 55" src="https://cloud.githubusercontent.com/assets/10454741/18908067/74e85da0-856e-11e6-8adc-f97fe0101786.png">

**Comment by pingshunhuangalex** [comment]
Well, I know I'm probably being annoying here, but I don't see how a screenshot of yours can help solving my problem, except for knowing it works pretty well on your computer...

I did a clean installation, and all cache wiped. My settings are listed below. Tried many times, no luck.

```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"dictionary": "Packages/Language - English/en_GB.dic",
	"dpi_scale": 1,
	"draw_minimap_border": true,
	"font_face": "Tsentsiu Mono HG",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_appbar_charcoal": true,
	"material_theme_bold_tab": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	**"material_theme_tabs_separator": true,**
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"show_encoding": true,
	"tab_size": 4,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true
}

```

**Comment by equinusocio** [comment]
>`Setting it to true won't suppress the hover animation`.

`material_theme_tabs_separator ` doesn't remove the hover animation (?) but add a vertical separator between tabs, as you can see in the screenshot. Maybe on your monitor you can't see the separators and i can only suggest to set a correct luminosity and a correct color calibration.

The issue remain closed because this setting works and there is not a real issue with the theme.

This is the darker screenshot.
<img width="377" alt="screen shot 2016-09-28 at 12 57 41" src="https://cloud.githubusercontent.com/assets/10454741/18911062/2a66fafe-857b-11e6-9342-32ace86ce7bc.png">

**Comment by pingshunhuangalex** [comment]
Here is the screenshot of my tabs when the option is set to ```true```.
![image](https://cloud.githubusercontent.com/assets/17170199/18911186/ef463612-85be-11e6-8089-9f55d88194cb.png)
I know what this option does, because I used it before, and there was a distinctive difference just like what's displayed in your screenshot.

Putting that aside, let's say it's my computer or monitor's issue whatever. Here is a screenshot directly from your Github page:
![image](https://cloud.githubusercontent.com/assets/17170199/18911265/6cbce65e-85bf-11e6-86a6-e34d3ec7d478.png)
If the option no longer disables hover animation, I suggest you update the text there. Thanks.

**Comment by equinusocio** [comment]
1. `material_theme_tabs_separator ` disable hover animation.
2. `material_theme_tabs_separator ` doesn't remove the current tab underline...
3. The font compatibility issue is in progress
4. I have no problems on my windows 8/10 virtual machine with a clean ST installation, even with your preferences, so i can't reproduce this issue.

**Comment by pksunkara** [comment]
I have the same issue on Mac. I just installed material-theme for the first time.

**Comment by equinusocio** [comment]
@pksunkara paste a screenshot and preferences.
