### ISSUE TITLE
Remove rounded corner for pop overs/drop downs

### ISSUE THREAD

**Issue by sharedmit** [equinusocio/material-theme#99]
How can I remove the rounded corner on the pop overs/drop downs ?

**Comment by equinusocio** [comment]
You cant, sorry.

**Comment by sharedmit** [comment]
Oh .... I just thought I saw sth like that on a Laracasts video.

**Comment by equinusocio** [comment]
This is a theme related style. You have to edit the theme.

**Comment by sharedmit** [comment]
Awesome! Googling how to edit sublime themes :)
