### ISSUE TITLE
Can't install on elementaryOS (Ubuntu 16.04)

### ISSUE THREAD

**Issue by tiiger** [equinusocio/material-theme#990]
### Summary
Can't install Material Theme on elementaryOS (Linux based on Ubuntu).
...

### Expected behavior
Using the package manager the theme should install automatically.
...

### Actual behavior
It doesn't.
In the console the following messages appear:

Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' is not available
Package Control: The dependency 'markupsafe' could not be installed or updated
...

### Environment

* Operating system and version:
  * elementary OS 0.4 Loki based on Ubuntu 16.04 LTS
* Sublime Text:
  * Build 3126
* Material Theme release:
  * The latest version available to the package manager.

**Comment by tiiger** [comment]
Actually that was quite hasty, because it was simple enough to just run
sudo apt install python-markupsafe 

:laughing: 

Sorry.

**Comment by equinusocio** [comment]
You can also run, i think, PackageControl: Satisfy Dependecies

**Comment by Armangh** [comment]
I have the same problem and even after installing markupsafe the problem is not solved.
- OS:
    * Ubuntu 16.04
- Sublime Text:
     * Build 3126
- Material Theme:
   * The latest version available in Package Control
