### ISSUE TITLE
Dark Theme sidebar Title issue

### ISSUE THREAD

**Issue by jCrip** [equinusocio/material-theme#991]
Hi, i think there is a problem with the last version of the theme. The standard and dark mode of the theme has a problem with the sidebar title, the light version is showing everything fine.
<img width="480" alt="captura de pantalla 2016-10-03 a las 10 52 01" src="https://cloud.githubusercontent.com/assets/871257/19039951/4f422a7a-8958-11e6-8482-e63766490703.png">
<img width="500" alt="captura de pantalla 2016-10-03 a las 10 52 15" src="https://cloud.githubusercontent.com/assets/871257/19039952/4f72e174-8958-11e6-96ca-4a0ef379206a.png">

### Environment

* Operating system and version:
  * Mac OS ...
* Sublime Text:
  * Build 3125
* Material Theme release:
  * v3.2.0

**Comment by sweettimes** [comment]
Mine:
- Sublime Text:   3126
- Platform:   osx
- Arch:   x64
- Theme:   3.2.1
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

![screen shot 2016-10-04 at 8 42 09 am](https://cloud.githubusercontent.com/assets/566289/19060485/de848498-8a12-11e6-8c2f-1ccf16a41120.png)

**Comment by equinusocio** [comment]
I will check this. Probably is a Material Theme regression when you don't use Appbar.

**Comment by equinusocio** [comment]
I'm working on it, is a `sidebar_container` class issue when `contrast_mode` is active.

**Comment by sweettimes** [comment]
yeah, thats right (Y)

**Comment by equinusocio** [comment]
Material Theme and Material Theme Appbar updated. Wait the Package Control update.

**Comment by equinusocio** [comment]
For a reference, this issue is fixed with`Material Theme`(3.2.2) and `Material Theme Appbar` (1.2.4)
