### ISSUE TITLE
Sidebar file_type_icon size option

### ISSUE THREAD

**Issue by diazgilberto** [equinusocio/material-theme#997]
# Changing sidebar icon's size:

More than an issue this is a question. Great job with the theme by the way!!!

### Summary

1. I was exploring the file structure for the project and I notice that .png's in the icon folder come in 3 sizes.
1. It is possible to apply settings in the user's file or in the master settings file to change the icon's size?

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OSX | El Capitan 10.11.6
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v3.2.2

**Comment by equinusocio** [comment]
At the moment isn't possible. Sublime Text automatically load `file_type_**.png` icons inside the `icons` directory. Themes can only provide png's to load and not handle this behavior (
except hide). The mulitple density png's that you see are loaded by ST based upon your screen screen density.

**Comment by diazgilberto** [comment]
Understand!
It is not a necessity. However, it is a nice-to-have thing. I use the highest resolution and the icons become too small, but not a big deal.

**Comment by equinusocio** [comment]
I will add this setting `material_theme_big_fileicon`

**Comment by diazgilberto** [comment]
ST updates the theme automatically right?

**Comment by equinusocio** [comment]
If you've installed it through Package Control yes. Package Control bot grab the latest release every 1hrs. Maybe i will work on this tonight :D

**Comment by diazgilberto** [comment]
That is quick!! You don't need to rush for this. Great job, the theme stands out by far from the rest.

**Comment by diazgilberto** [comment]
How often package control updates packages?

**Comment by equinusocio** [comment]
Hourly. But the update has not been released yet.
