### ISSUE TITLE
Support for PlainNotes and PlainTasks

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme#999]
When submitting a feature or enhancement request:

1. PlainNotes is a very useful plugin for taking notes inside SublimeText; it's color schemes don't match. Unfortunately PlainNotes uses color schemes with a few additions. Mainly markdown stuff when I got it all right.

Would be great if Material could support them
https://github.com/aziz/PlainNotes/issues/47

**Comment by equinusocio** [comment]
mmm I have no idea how to support this package, there is no docs.

**Comment by oivva** [comment]
@equinusocio see [this](https://github.com/oivva/st-boxy/commit/66d4d7952be0fdaa0b1157f3e73af3e272aeb355) and [this](https://github.com/oivva/st-boxy/commit/58f2847edb3734a7b660687054ab7940a7c67f95) :wink:

**Comment by equinusocio** [comment]
I think that the package developer should be add support for themes, not vice-versa. It should use the current scheme background.

**Comment by equinusocio** [comment]
@oivva I've tried Boxy and the PlainNotes schemes doesn't works.

**Comment by equinusocio** [comment]
PlainNotes support is not scheduled now.
